### ISSUE TITLE
[aes] shadow reg storage and update error status question

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#8460] opened 2021-09-30 21:04 UTC
Hi Pirmin,

I would like to confirm the AES status register behavior as below:
1). Write two shadow registers with different value to trigger an update error
2). Check status register -> ALERT_RECOV_CTRL_UPDATE_ERR is set to 1.
3). Probe design to make a storage error in shadow reg's committed val
4). Check status register -> ALERT_FATAL_FAULT is set to 1, but ALERT_RECOV_CTRL_UPDATE_ERR is reset to 0.
Is that intended to reset `ALERT_RECOV_CTRL_UPDATE_ERR` field back to 0?
I can align on DV side, but just want to double check and see if you want to make this field persistent.

![image](https://user-images.githubusercontent.com/11466553/135529951-3ad16cbb-3cdb-497b-859e-d70160338b1f.png)

Thanks,
Cindy

**Comment by tjaychen** [comment] 2021-09-30 23:15
should we try to make this behavior standard? ie if an update error
happens, we don't clear it unless software does it?

**Comment by cindychip** [comment] 2021-09-30 23:18
It would be ideal to standardize it (if not too much trouble on design side). Also aes status fields are all "RO" instead of "RW1C", that means SW cannot clear it.

**Comment by vogelpi** [comment] 2021-10-01 12:43
Hey @cindychip ,
yes I can confirm that this is intended behavior. The idea is that whenever a fatal alert is occurring (no matter whether it's a storage error in the shadow register or some other fault inside the design), all status bits are cleared to 0.

The motivation for this behavior is that we don't want to give away potentially useful information to an adversary to refine an attack. For example, if a fault is injected while the cipher core is idle and the module locks up with the idle bit high, the adversary knows that the timing was wrong and needs to change that.

As for the clearing: The update error is cleared whenever the shadow register is written.

**Comment by tjaychen** [comment] 2021-10-01 20:30
hmmmm Pirmin since you have multiple fault error possibilities inside AES,
does that mean there's no way to dis-ambiguate which fault caused the error?
I think this is something we should discuss in upcoming silicon / security
meetings. I'm still not convinced that we need to "hide" software error
readbacks.

I still maintain that if an attacker has the ability to control arbitrary
software reads to see how the system was attacked, far greater damage can
already be made.
If however we do decide that errors need to be hidden, we need to apply
this concept to the entire design, because right now blocks like kmac /
otp_ctrl / flash / keymgr expose in quite a fine granularity the actual
error.

**Comment by vogelpi** [comment] 2021-10-04 14:35
> hmmmm Pirmin since you have multiple fault error possibilities inside AES, does that mean there's no way to dis-ambiguate which fault caused the error?

Yes, that is correct. But in AES, all error sources except one indicate that an FI attack is ongoing. They are all fatal. The only one error/alert that can be triggered by software is the shadow register update error. 

> I think this is something we should discuss in upcoming silicon / security meetings. I'm still not convinced that we need to "hide" software error readbacks.
> I still maintain that if an attacker has the ability to control arbitrary software reads to see how the system was attacked, far greater damage can already be made.

I tend to agree with you but to be honest, I don't have the system-level picture required to really judge this. In my view, even if the attacker has control over software it doesn't mean that he has access to sideload keys. But through FI attacks on AES,  he could try to make the module output intermediate state and then use that to guess the sideload key.  

> If however we do decide that errors need to be hidden, we need to apply this concept to the entire design, because right now blocks like kmac / otp_ctrl / flash / keymgr expose in quite a fine granularity the actual error.

I think every single one of these blocks are far more complicated in terms of software interaction than AES (doesn't even have interrupts). So, I would say having fine granularity is very useful for software development/bring up etc. But maybe some of these registers should be gated by LC?

**Comment by moidx** [comment] 2021-11-10 22:40
Added this issue for further discussion in the Security/Software WG meetings.

**Comment by m-temp** [comment] 2022-01-21 08:49
As there was no time in the Security WG meeting:
KMAC behaves similar (does not clear the status, but also does not tell what happened). I favor this behavior, as I see no point to tell an attacker what was going on. However this is in contrast with the "Implementation Guidance"
> If a particular alert sender has multiple error sources within the IP, the IP shall expose an associated error register to indicate the cause.

If this is crucial for debugging, we should disable it in the prod-phase.
Or at least for faults that cannot be triggered by software (e.g. invalid sparse encoding of an FSM).
Anyway it's worth a discussion.

**Comment by tjaychen** [comment] 2022-01-21 17:07
yeah i think there are opposing views on the project on this point right now.
I tend to fall into the camp that if we are worried about an attacker being able to read a status, then it implies that software is already compromised to some extent (since an attacker is able to control arbitrary reads).  If we go with that perspective, we are already in a world of trouble. 

So for this version, I tend to favor exposing debugging information (with some software ability to lock it out).  Since most of our debugging will actually be done in PROD state, and if PROD state exposes nothing, we effectively have no avenues of information.

**Comment by vogelpi** [comment] 2022-01-27 11:37
Hey @cindychip ,
@rasmus-madsen and I noted that AES currently has some CSR tests failing. Investigating the failures it seems that the environment expects the recoverable alert bit (shadow register update error) to remain set until the corresponding status bit is read.

However, if another write to the shadow register happens, this actually resolves the condition for the recoverable alert. So in our view, it makes less sense to keep the status bit high. What is your view on this? Do you think it would be possible to adapt the tests accordingly?

**Comment by rasmus-madsen** [comment] 2022-01-31 11:47
@vogelpi @cindychip 
we need to resolve this fairly quickly as it is holding back PRs due to CI failures
I am inclined to just exclude the registers

**Comment by moidx** [comment] 2022-01-31 17:57
I agree with @tjaychen. It is possible for software bugs to trigger recoverable errors, inclusive when operations are interrupted due to unexpected context switching.  An attacker with access to the software interface will presumably know how to trigger this error by looking at the RTL, so I think hiding this information is has a lower security value in our implementation.

I prefer to prioritize debuggability in this case considering that the crypto library is part of the TCB, and other debug interfaces are disabled in PROD mode.

**Comment by vogelpi** [comment] 2022-02-03 18:09
We have been discussing this issue in the Security meeting and concluded the following:

1. In the case of fatal alerts, we prefer debug-ability over hiding information. This holds not just for software that can cause fatal alert conditions (in many modules such as AES, KMAC this isn't even possible) but also for physical chip-level effects that may trigger some FI countermeasures, e.g., power distribution issues. Not clearing the status register in this case can provide useful information for debugging the chip. For this reason, I will change the AES implementation to not clear the status register upon a fatal fault. I can make the behavior parametrizable to change it back easily if it's considered useful at a later point.
2. For recoverable alerts, we have concluded that they should no longer be visible in the status register once the condition triggering the alert has been resolved. In the case of AES, this means if a new message is started by writing the control register, we should clear the recoverable alert bit in the status register. We will have to adjust DV accordingly.

**Comment by cindychip** [comment] 2022-02-03 18:47
Thank you Pirmin, that sounds great. I will align the DV common test accordingly for 2).
@eunchan, could you see if we want to align Kmac for 1). Currently in hmac storage fatal alert, it will clear the update recoverable alert bit to 0.

**Comment by vogelpi** [comment] 2022-02-04 07:55
Thanks @cindychip that would be appreciated if you could take care of the DV adjustment. If you have any questions, don't hesitate.

**Comment by cindychip** [comment] 2022-02-08 07:30
My pleasure. @vogelpi could you tag me on the PR that reflects the change on item (1) once it is ready?

**Comment by cindychip** [comment] 2022-02-10 00:52
Thanks Pirmin for the PR, one last question - for item 2), do we plan to standardize it across the IPs or just AES only?

**Comment by vogelpi** [comment] 2022-02-21 11:24
Hey @cindychip ,

sorry for keeping you waiting. I've added my responses inline below.

> One last question - for item 2),
> 
> a). do we plan to standardize it across the IPs or just AES only?
> 
Yes, I think eventually we should standardize on that behavior. However, I don't consider it super important for ES. People are probably very busy with other, more critical stuff at the moment. So, I recommend to just do it for AES right now.

> b). the condition to clear update error status is register based? For example, if I have update error on `ctrl_shadowed` register, then I write twice with the same value to `ctrl_aux_shadowed`. This won't clear the shadow reg update error, am I understand it correctly?

This is not fully correct. To clear the update error status bit, the AES operation needs to be restarted by re-writing the main control register (`ctrl_shadowed`) twice. This is what the spec says. Writing `ctrl_aux_shadowed` twice doesn't clear the status bit even if the alert was triggered by that register.

**Comment by moidx** [comment] 2022-08-19 15:34
Hi @cindychip is this still an issue? Who should it be assigned to?

**Comment by vogelpi** [comment] 2022-10-21 13:33
When moving some shadow register bits around for #15641 I came again across this issue. I went through it again. The corresponding tests are passing, and the behavior of DV and RTL is documented (with links to this issue and lowRISC/OpenTitan#10617). I am now closing this issue.

Please feel free to re-open if you don't agree.

**Closed by vogelpi** 2022-10-21 13:33 UTC
Labels: Component:DV, Type:Question
