### ISSUE TITLE
[test-triage] //sw/device/tests:uart_smoketest_signed_sim_verilator is broken

### ISSUE THREAD

**Issue by hcindyl** [lowRISC/opentitan#17813] opened 2023-04-04 18:00 UTC
### Hierarchy of regression failure

Block level

### Failure Description

Error log
```
Starting interactive console
[CTRL+C] to exit.

[2023-04-04T17:33:11Z INFO  opentitanlib::io::uart] set_flow_control to false
�BFV:0142500d

Exiting interactive console.
[2023-04-04T17:58:41Z INFO  opentitantool::command::console] ExitFailure("BFV:0142500d")
[2023-04-04T17:58:41Z INFO  opentitantool] Command result: Matched exit_failure expression
    
    Stack backtrace:
       0: anyhow::error::<impl anyhow::Error>::msg
       1: anyhow::__private::format_err
       2: <opentitantool::command::console::Console as opentitanlib::app::command::CommandDispatch>::run
       3: opentitantool::_::<impl opentitanlib::app::command::CommandDispatch for opentitantool::RootCommandHierarchy>::run
       4: opentitantool::main
       5: core::ops::function::FnOnce::call_once
       6: std::sys_common::backtrace::__rust_begin_short_backtrace
       7: std::rt::lang_start::{{closure}}
       8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/ops/function.rs:287:13
       9: std::panicking::try::do_call
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:483:40
      10: std::panicking::try
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:447:19
      11: std::panic::catch_unwind
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panic.rs:140:14
      12: std::rt::lang_start_internal::{{closure}}
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/rt.rs:148:48
      13: std::panicking::try::do_call
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:483:40
      14: std::panicking::try
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:447:19
      15: std::panic::catch_unwind
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panic.rs:140:14
      16: std::rt::lang_start_internal
                 at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/rt.rs:148:20
      17: std::rt::lang_start
      18: main
      19: __libc_start_call_main
                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
      20: __libc_start_main_impl
                 at ./csu/../csu/libc-start.c:381:3
      21: _start
Error: Matched exit_failure expression

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: <opentitantool::command::console::Console as opentitanlib::app::command::CommandDispatch>::run
   3: opentitantool::_::<impl opentitanlib::app::command::CommandDispatch for opentitantool::RootCommandHierarchy>::run
   4: opentitantool::main
   5: core::ops::function::FnOnce::call_once
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/ops/function.rs:287:13
   9: std::panicking::try::do_call
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:483:40
  10: std::panicking::try
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:447:19
  11: std::panic::catch_unwind
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panic.rs:140:14
  12: std::rt::lang_start_internal::{{closure}}
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/rt.rs:148:48
  13: std::panicking::try::do_call
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:483:40
  14: std::panicking::try
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:447:19
  15: std::panic::catch_unwind
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panic.rs:140:14
  16: std::rt::lang_start_internal
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/rt.rs:148:20
  17: std::rt::lang_start
  18: main
  19: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  20: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:381:3
  21: _start
```

### Steps to Reproduce

- GitHub Revision: 09ebf5660
- bazel test --test_output=errors //sw/device/tests:uart_smoketest_signed_sim_verilator

**Comment by a-will** [comment] 2023-06-13 17:14
At first glance, it seems to be failing signature verification. We get to shutdown_finalize() after rom_try_boot(). The trace shows it jumps from this line to shutdown_finalize():

https://github.com/lowRISC/opentitan/blob/5d7311def1201cb7b3cece0634a8ed21d41ea3b0/sw/device/silicon_creator/rom/rom.c#L549

after returning from sigverify_encoded_message_check().

**Comment by moidx** [comment] 2024-06-07 02:20
This test has not been deleted as is a duplicate of `rom_e2e_smoke`.

**Closed by moidx** 2024-06-07 02:20 UTC
Labels: Priority:P2, Component:ChipLevelTest, Component:TestTriage, Earlgrey-PROD Candidate
