### ISSUE TITLE
[edn] V2S Signoff

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22468] opened 2024-04-08 14:04 UTC
For reference, these are previous signoff issues:
- [EDN D2S #20982](https://github.com/lowRISC/opentitan/issues/20982)
- [EDN V1 #21017](https://github.com/lowRISC/opentitan/issues/21017)

**Comment by vogelpi** [comment] 2024-06-07 13:36
## Commits since Earlgrey-PROD.M2
For Commits since Earlgrey-ES tapeout, see https://github.com/lowRISC/opentitan/issues/20982#issuecomment-2027775836

`git rev-parse --short HEAD` 57f1155f7b

`git log 9ddf276..HEAD --oneline hw/ip/edn`
32895089c6 [edn/dv] Add transition to reject entropy state to alert test
-> Close FSM coverage holes, see #22352.
975eadb688 [edn/rtl] Fix bugs for SW and HW cmd status interface
-> RTL bug fixes flagged by DV commit above
7c92d49f77 [edn/rtl] Fix Verilator lint errors and warnings
0c9867927c [edn/dv] Fix FSM coverage holes
-> Close FSM coverage holes, see #22352.
53868edd8e [edn/rtl] Make Error main SM state terminal again
-> RTL bug fix
bfed776382 [edn/dv] Fix some edge cases for edn_disable_auto_req_mode_vseq
6450330a54 [edn/dv] This commit fixes the deadlock in edn_disable_auto_req_mode
-> Fix edn_disable_auto_req_mode sequence, see #20818
7f84f7cdb8 [csrng/rtl] Add reseed interval status error
-> Add new error response to EDN
6e8108c51b [edn/doc] Switch back to EDN's registers.md
1d12ff7a6c [csrng/rtl] Remove zeroize state after uni error from ctr drbg cmd
-> Removing an error condition inside CSRNG which was impossible to reach, aligning error response to EDN
dcaf19e3fe [edn/dv] Correct prediction of sw_cmd_reg_rdy for auto mode Instantiate
903b319171 [csrng/rtl] Add command out of sequence cmd_sts error
-> Add new error response to EDN
375c7bda00 [edn/dv] fix broken private CI tests
b389e286ab [edn/dv] Remove leftover of removed output FIFO in edn_err test
00fc69d288 [edn] Harden FIFO instantiations
-> Use hardened prim_sync_fifo instantiations inside EDN, this standardized countermeasures is verified via auto generated `edn_sec_cm` test
9a6b4491a1 [edn,rtl] Fix assertions
042e0b9158 [csrng/rtl] Change and assign cmd_sts signal
-> Alignment of error response to EDN
8295903d7e [bazel,autogen_hjson] Split C and rust header generation
30d7e787c7 (tag: Earlgrey-PROD-M2-RC5, tag: Earlgrey-PROD-M2) Add the project name to the copyright header
f4c2bb9030 Remove trailing whitespaces
73c4e33aa9 [edn] Increase version number, revert verification stage to V1

## Issues closed since Earlgrey-PROD.M2
For issues closed since Earlgrey-ES tapeout, see https://github.com/lowRISC/opentitan/issues/20982#issuecomment-2027775836

- #8120
- #16516
- #16563
- #17772
- #19293
- #19568
- #20818
- #20953
- #20976
- #20982
- #21155
- #22121
- #22209
- #22352
- #22385
- #22524
- #22732
- #22753
- #22819
- #22997
- #23131

## Currently open issues

- #7667
- #7798
- #8458
- #10738
- #11172
- #14364
- #15427
- #16269
- #16572
- #16593
- #16902
- #17109
- #17785
- #19027
- #19028
- #19031
- #19045
- #19361
- #19444
- #19789
- #19797
- #19846
- #20194
- #21216
- #21222
- #21706
- #22241
- #22293
- #22366
- #22465
- #22468
- #22634
- #22667
- #22705
- #22833
- #22850
- #22856
- #22869
- #23191
- #23526
- #23542

## Coverage report from 2024-06-06

## Summary

**Comment by moidx** [comment] 2024-06-11 21:20
Discussed moving as P1 to M5 due to RTL risk analysis performed during last issue triage.

**Comment by vogelpi** [comment] 2024-06-13 09:36
Update: I've now updated the signoff issue to reflect that the RTL issue found in the last minute (#23526 ) has also been fixed.

**Comment by h-filali** [comment] 2024-06-13 12:28
I double checked for all my PR's if there are some open issues and couldn't find any. I also double checked all the issues I've been working on and they are all mentioned here.

I also double checked the last nightly regression and can confirm that everything is above 90%.
The nightly that ran on [2024.06.10_06.28.44](https://reports.opentitan.org/hw/ip/edn/dv/2024.06.10_06.28.44/report.html) had ~82% progress for V2 but the errors that went away in the most recent nightly align exactly with the changes made by @vogelpi described in #23526.

I double checked if I could find any commits for EDN that are missing but I couldn't find any.

One of the open issues in the list above is now closed (#19789).

To me this looks good. Nicely done @vogelpi ^^

**Comment by vogelpi** [comment] 2024-06-17 07:18
Thanks for your feedback @h-filali . I've now filed the PR (#23700) to close this issue and move EDN v.2.0.0 to V2S.

**Closed** 2024-06-20 14:06 UTC
Labels: Component:DV, IP:edn, Type:Signoff
