### ISSUE TITLE
[dv] V2 function coverage criteria

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13849] opened 2022-07-26 17:17 UTC
@GregAC pointed out this criteria isn't consistent in our doc
1. in development_stages [doc](https://docs.opentitan.org/doc/project/development_stages/) , it says: 100% functional coverpoints covered and 75% crosses covered

2. in the V2 [checklist](https://docs.opentitan.org/doc/project/checklist/#v2), it shows: Functional coverage has reached 70%.

I think we follow the first one (100% coverpoint, 75% cross) to sign off the V2.

As brought up in the Si meeting, our coverage dashboard only shows a number for the overall functional coverage. It's not easy to calculate the number of all cross coverage. We may look into all the covergroup and get that cross coverage number before signing off the block, but design/TB may be updated and the coverage number could be changed after V2. We probably won't look into all the covergroup again and it's hard to know if this criteria is still met.

To make the review easier, we may change this criteria to "100% for coverpoint, 90% for overall functional coverage"

Or even further simplify it to "90% for overall functional coverage". 

cc: @matutem @cindychip @jdonjdon @martin-lueker @rasmus-madsen @sha-ron @johngt

**Comment by sriyerg** [comment] 2022-07-26 18:47
90% overall fcov for V2 SGTM.

**Comment by GregAC** [comment] 2022-07-27 14:22
Happy with 90% overall fcov also

**Comment by martin-lueker** [comment] 2022-07-27 14:46
I'm concerned that we are now raising the bar for V2.  70% overall fcov (from the checklist) is now changing to 90%.   The 100% coverpoint + 75% cross, seems reasonable.
However this is only equivalent to 90% if you have only a few crosses (<40% of the total)   Our team has been making our effort estimates for V2 based on the 70% overall standard.  If we change this, we are going to have a resource crunch, and in our case this is not easy to resolve.  

Also we should revisit all the blocks currently at V2 would have to be reverted based on their current coverage.

We also need to assess whether we will have to change our regression methodology. 
My understanding is that these metrics are applied to single-night 50 run regressions, and that we don't have running database accumulating coverage over time.  If this simulation is not reaching the cover metrics in one night (just because of limited sampling), what do we do?

**Comment by martin-lueker** [comment] 2022-07-27 15:01
> We also need to assess whether we will have to change our regression methodology. My understanding is that these metrics are applied to single-night 50 run regressions, and that we don't have a running database accumulating coverage over time. If this simulation is not reaching the cover metrics in one night (just because of limited sampling), what do we do?

After thinking about this more I realized that this last item is not such a challenge, if there are sampling issues we can just propose longer slightly longer regressions.

I still think however, that if we are going to change the official threshold, we should review the other V2s and make sure they still qualify, or would have to be rolled back.

**Comment by sriyerg** [comment] 2022-07-27 17:47
I did look at all existing blocks that are at V2/V2S and they all had 90%+ overall fcov coverage, and concluded that it may be ok to set this threshold. We have not seen the need so far to merge coverage with previous invocations, but dvsim supports it if there is a need to turn it on. Also, the number of seeds can be adjusted per test, and DV engineers can modify randomization constraints to steer the coverage as needed, so mandating 90% overall fcov at V2 to me seems reasonable.

**Comment by weicaiyang** [comment] 2022-07-27 18:04
I think 90% overall fcov is easier than 100% coverpoint + 75% cross.
If it's below 90%, most likely coverpoint is not 100%. I kind of feel we actually lower the bar.

But with 100% coverpoint + 75% cross requirement, when it's around 85%, we may think it passes the criteria as it may take a while to open all the covergroup to check if it really meets the criteria.

The criteria (90% overall fcov) is much easier to review, and it's also aligned with the coverage result in dashboard.

**Comment by rasmus-madsen** [comment] 2022-07-28 07:42
>  DV engineers can modify randomization constraints to steer the coverage as needed,
@sriyerg  I think this is only sort of true!
if we don't have cumulative coverage modifying the constraints, would in this case typically mean opening up the randomization space, which would most like require more runs.

I am all for cumulative coverage collection.

anyway on the main topic. at some point we need to reach 90%+ coverage so the question is where to we set the checkpoint.
for me it is more a V3 item

**Comment by weicaiyang** [comment] 2022-07-28 19:02
> I am all for cumulative coverage collection.
anyway on the main topic. at some point we need to reach 90%+ coverage so the question is where to we set the checkpoint.
for me it is more a V3 item

We want everything to 100% for V3. what percentage do you think it makes sense for V2?
I personally feel it's not so hard to get to 90% fcov. Since we have a bunch of built-in covergroup in base lib, those covergroups are covered by automatic tests and make the cumulative number very high already, even if there are many uncovered in the block specific covergroups.

**Comment by msfschaffner** [comment] 2022-07-28 22:46
I agree with Weicai that at V3 everything should be at 100% (with waivers applied).

@martin-lueker, Do you plan to add more covergroups, or are most of them already reflected in the code?
Because looking at the nightlies from yesterday, AES, EDN and CSRNG seem to be pretty close to 90% or even above. Only ES is still at 35%. 

Hence, 90% seems within reach for most of these blocks...

**Comment by martin-lueker** [comment] 2022-07-29 12:28
Thanks @msfschaffner and @weicaiyang.  I agree about the V3 metric (100% to within some small epsilon)

Thanks also for checking the most recent nightlies. I'd thought we were farther from that based on my conversations with @senelson7 and @rasmus-madsen.  This is good.   It looks like the only one that at marginal is CSRNG at 89%+.  So maybe that's not so bad?  (However I do have a concern that CSRNG has been floating at this level for some time now, so I would leave it to @senelson7 to opine on what it would take to push this over the top.

On the topic of ES:

There are a few remaining CPs left to be added, but these are the simplest ones.  My emphasis has been on getting all the CP's implemented before coming back to closing coverage on all of them.   I'm not personally worried about the CP's.   I suspect ES will be in pretty good shape with those by this time next week.

The crosses, on the other hand are another story. Based on the conversation above, I suspect that ES is a bit different than the rest of the IP's as it has over 450 crosses (far more than the number of cover points.)  So that is why I've been having trouble equating 100% cp + 75% cr =~ 90% total.   These come about for a couple of the CGs that check for every possible combination of configurations (even in cases where some parameters are not thought to play a role), crossing as many as six parameters.     This is also why I was skeptical about getting to 90% with just 50 sims: there is at least one cross with 270 buckets one for each DUT configuration.   The most recent changes to the `entropy_src_rng` test add the possibility of hitting several DUT configurations at once, and so it could possibly hit all those in 50 runs, particularly if we set them to run longer, but it's still a lot of combinations, so I'm not sure.

Alternatively, I've been contemplating reducing the number of crosses, to just make a complete set of two parameter crosses, to cover all possible combinational _pairs_, if not all possible combinations.   This would reduce the cross point count quite a bit.  What do others think?

**Comment by weicaiyang** [comment] 2022-07-29 18:37
@martin-lueker
IMO, the criteria may not need to be suitable for all blocks. (it needs to work for most of the block). We can always make an exception if there is a good reason. e.g. we have a good coverage for all combinational pairs, but coverage number is lower than V2 criteria due to cross coverage of all 6 parameters, which is low risk

If I understand the coverage scoring correctly, each coverpoint including cross is weighted equally. e.g. we have 6 CP and 1 CR with all 6 CP. If all 6 CPs are 100%, and CR is 30%, the overall coverage is 6.3/7=90%. 
```
covergroup
  cp1: // 100%
  cp2: // 100%
   ...
  cp6: // 100%
  cross: cp1, cp2, cp3, cp4, cp5, cp6; // 30%
```

We could add 2 parameters crosses too, as they are easier to debug. If we add those crosses and they're over 90%, we will have even higher coverage number. 
```
covergroup
  cp1: // 100%
  cp2: // 100%
   ...
  cp6: // 100%
  cross: cp1, cp2;
  cross: cp1, cp3;
  ... // all other 2 parameters cross
  cross: cp1, cp2, cp3, cp4, cp5, cp6; // 30%
```

**Comment by rasmus-madsen** [comment] 2022-08-03 15:43
Im ok with this

**Comment by weicaiyang** [comment] 2022-08-03 16:54
> Im ok with this

Thanks @rasmus-madsen. If no objection, I will make a PR to update the criteria to 90% overall fcov later today

**Comment by sriyerg** [comment] 2022-08-03 16:56
Thanks @weicaiyang for addressing this!

**Comment by martin-lueker** [comment] 2022-08-03 17:28
Thanks for working this out Weicai.   Given that we are so close on most of these blocks (and the one block where we are not is my own responsibility) I'm happy to agree to this as well, (especially if people are willing to be reasonable about the large goofy crosses, when the CP's are 100%).  Thanks.

**Comment by cindychip** [comment] 2022-08-03 18:43
The proposal sounds great.

**Comment by GregAC** [comment] 2022-08-03 19:28
This sounds good to me, if I've understood @weicaiyang correctly where you have large crosses that are hard to hit it can be acceptable to add smaller crosses that are a subset of the big cross to bring the numbers up for V2 (subject to review of course, e.g. demonstrating the new smaller crosses are dealing with the most important/most used behaviours where the larger cross is checking all possible combinations).?

**Comment by weicaiyang** [comment] 2022-08-03 19:42
> This sounds good to me, if I've understood @weicaiyang correctly where you have large crosses that are hard to hit it can be acceptable to add smaller crosses that are a subset of the big cross to bring the numbers up for V2 (subject to review of course, e.g. demonstrating the new smaller crosses are dealing with the most important/most used behaviours where the larger cross is checking all possible combinations).?

yes, I think it's ok to add small crosses (subset of big cross), which helps coverage review too.

**Comment by msfschaffner** [comment] 2022-08-03 20:17
Cool, thanks for driving this @weicaiyang. The proposal SGTM.

**Comment by martin-lueker** [comment] 2022-08-03 21:22
> > This sounds good to me, if I've understood @weicaiyang correctly where you have large crosses that are hard to hit it can be acceptable to add smaller crosses that are a subset of the big cross to bring the numbers up for V2 (subject to review of course, e.g. demonstrating the new smaller crosses are dealing with the most important/most used behaviours where the larger cross is checking all possible combinations).?
> 
> yes, I think it's ok to add small crosses (subset of big cross), which helps coverage review too.

Ah interesting.  I like this actually, I hadn't thought of having both big and small crosses, though I can see how they are both valueable.

**Closed** 2022-08-04 17:09 UTC
Labels: Component:Doc, Component:DV, Priority:P1
