### ISSUE TITLE
[test-triage] e2e_chip_specific_startup_test_unlocked0_fpga_cw310_rom

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#18035] opened 2023-04-18 14:41 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

The tests has been failing consistently with the following log message.
<details>
<sumary>Log</sumary>

```
2023-04-18T07:59:13.2746688Z [2023-04-18T07:58:55Z INFO  opentitanlib::util::usb] Could not open device at bus=1 address=7: No such device (it may have been disconnected)
2023-04-18T07:59:13.2747906Z [2023-04-18T07:58:55Z INFO  opentitanlib::util::usb] Could not open device at bus=1 address=40: No such device (it may have been disconnected)
2023-04-18T07:59:13.2748940Z [2023-04-18T07:58:55Z INFO  opentitanlib::util::usb] Could not open device at bus=1 address=69: No such device (it may have been disconnected)
2023-04-18T07:59:13.2749939Z [2023-04-18T07:58:55Z INFO  opentitanlib::util::usb] Could not open device at bus=1 address=25: No such device (it may have been disconnected)
2023-04-18T07:59:13.2750576Z [2023-04-18T07:58:55Z INFO  opentitanlib::io::uart] set_flow_control to false
2023-04-18T07:59:13.2751355Z [2023-04-18T07:58:55Z INFO  opentitanlib::test_utils::load_bitstream] Loading bitstream: "sw/device/silicon_creator/rom/e2e/bitstream_chip_specific_startup_test_unlocked0.bit"
2023-04-18T07:59:13.2752101Z [2023-04-18T07:58:55Z INFO  opentitanlib::util::usr_access] Bitstream file USR_ACCESS value: 0xd15f078e
2023-04-18T07:59:13.2752748Z [2023-04-18T07:58:55Z INFO  opentitanlib::util::rom_detect] Current bitstream: "ROM:d4b97739\r"
2023-04-18T07:59:13.2753226Z [2023-04-18T07:58:55Z INFO  opentitanlib::transport::cw310] Programming the FPGA bitstream.
2023-04-18T07:59:13.2753514Z [2023-04-18T07:59:09Z INFO  opentitanlib::test_utils::init] load_bitstream: success.
2023-04-18T07:59:13.2753701Z "load_bitstream": true
2023-04-18T07:59:13.2753955Z [2023-04-18T07:59:09Z INFO  opentitanlib::bootstrap] Asserting bootstrap pins...
2023-04-18T07:59:13.2754217Z [2023-04-18T07:59:09Z INFO  opentitanlib::app] Asserting the reset signal
2023-04-18T07:59:13.2754502Z [2023-04-18T07:59:09Z INFO  opentitanlib::app] Deasserting the reset signal
2023-04-18T07:59:13.2754790Z [2023-04-18T07:59:09Z INFO  opentitanlib::bootstrap] Performing bootstrap...
2023-04-18T07:59:13.2755063Z [2023-04-18T07:59:12Z INFO  opentitanlib::bootstrap] Releasing bootstrap pins...
2023-04-18T07:59:13.2755323Z [2023-04-18T07:59:12Z INFO  opentitanlib::app] Asserting the reset signal
2023-04-18T07:59:13.2755591Z [2023-04-18T07:59:12Z INFO  opentitanlib::app] Deasserting the reset signal
2023-04-18T07:59:13.2755869Z [2023-04-18T07:59:12Z INFO  opentitanlib::test_utils::init] bootstrap: success.
2023-04-18T07:59:13.2756029Z "bootstrap": true
2023-04-18T07:59:13.2756171Z 343:Starting test test_chip_specific_startup...
2023-04-18T07:59:13.2756310Z ROM:d15f078e
2023-04-18T07:59:13.2756423Z bootstrap:1
2023-04-18T07:59:13.2759762Z ROM:d15f078e
2023-04-18T07:59:13.2761075Z I00000 ottf_main.c:110] Running [2023-04-18T07:59:13Z INFO  opentitanlib::test_utils::rpc] Sending: "ChipStartup"
2023-04-18T07:59:13.2761698Z sw/device/silicon_creator/rom/e2e/chip_specific_startup.c
2023-04-18T07:59:13.2762000Z I00001 chip_specific_startup.c:84] Initializing DIFs
2023-04-18T07:59:13.2762308Z I00002 chip_specific_startup.c:95] Querying hardware
2023-04-18T07:59:13.2763132Z RESP_OK:{"otp":{"creator_sw_cfg_ast_init_en":6,"creator_sw_cfg_jitter_en":9},"lc_state":1,"mstatus":128,"jitter":false,"entropy":{"entropy_src":9474201,"csrng":1638,"edn":39270},"epmp":{"cfg":[10063104,39309,2332033024,2609946368],"addr":[8192,13733,12287,134219968,134224620,134348799,0,0,0,0,268435456,335544320,0,16895,67137536,67125247],"mseccfg":6},"ast_init_done":true,"sram":{"scr_key_valid":true,"scr_key_seed_valid":true,"init_done":true}}
2023-04-18T07:59:13.2764092Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] chip_startup_t {
2023-04-18T07:59:13.2764325Z         otp: rom_otp_config_t {
2023-04-18T07:59:13.2764497Z             creator_sw_cfg_ast_init_en: 0x6,
2023-04-18T07:59:13.2764685Z             creator_sw_cfg_jitter_en: 0x9,
2023-04-18T07:59:13.2764834Z         },
2023-04-18T07:59:13.2764977Z         lc_state: 0x1,
2023-04-18T07:59:13.2765130Z         mstatus: 0x80,
2023-04-18T07:59:13.2765272Z         jitter: false,
2023-04-18T07:59:13.2765438Z         entropy: rom_entropy_config_t {
2023-04-18T07:59:13.2765611Z             entropy_src: 0x909099,
2023-04-18T07:59:13.2765763Z             csrng: 0x666,
2023-04-18T07:59:13.2766124Z             edn: 0x9966,
2023-04-18T07:59:13.2766259Z         },
2023-04-18T07:59:13.2766411Z         epmp: rom_epmp_config_t {
2023-04-18T07:59:13.2766565Z             cfg: [
2023-04-18T07:59:13.2766700Z                 0x998d00,
2023-04-18T07:59:13.2766843Z                 0x998d,
2023-04-18T07:59:13.2766990Z                 0x8b000000,
2023-04-18T07:59:13.2767132Z                 0x9b909f00,
2023-04-18T07:59:13.2767384Z             ],
2023-04-18T07:59:13.2767514Z             addr: [
2023-04-18T07:59:13.2767655Z                 0x2000,
2023-04-18T07:59:13.2767797Z                 0x35a5,
2023-04-18T07:59:13.2767929Z                 0x2fff,
2023-04-18T07:59:13.2768072Z                 0x80008c0,
2023-04-18T07:59:13.2768219Z                 0x8001aec,
2023-04-18T07:59:13.2768356Z                 0x801ffff,
2023-04-18T07:59:13.2768500Z                 0x0,
2023-04-18T07:59:13.2768630Z                 0x0,
2023-04-18T07:59:13.2768766Z                 0x0,
2023-04-18T07:59:13.2768906Z                 0x0,
2023-04-18T07:59:13.2769039Z                 0x10000000,
2023-04-18T07:59:13.2769187Z                 0x14000000,
2023-04-18T07:59:13.2769328Z                 0x0,
2023-04-18T07:59:13.2769470Z                 0x41ff,
2023-04-18T07:59:13.2769604Z                 0x4007000,
2023-04-18T07:59:13.2769752Z                 0x4003fff,
2023-04-18T07:59:13.2769884Z             ],
2023-04-18T07:59:13.2770024Z             mseccfg: 0x6,
2023-04-18T07:59:13.2770166Z         },
2023-04-18T07:59:13.2770312Z         ast_init_done: true,
2023-04-18T07:59:13.2770474Z         sram: sram_init_t {
2023-04-18T07:59:13.2770631Z             scr_key_valid: true,
2023-04-18T07:59:13.2770800Z             scr_key_seed_valid: true,
2023-04-18T07:59:13.2771083Z             init_done: true,
2023-04-18T07:59:13.2771284Z         },
2023-04-18T07:59:13.2771493Z     }
2023-04-18T07:59:13.2771839Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] CREATOR_SW_CFG_AST_INIT_EN = True
2023-04-18T07:59:13.2772209Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] CREATOR_SW_CFG_JITTER_EN = False
2023-04-18T07:59:13.2772571Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] lc_state = TestUnlocked0
2023-04-18T07:59:13.2772895Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] epmp = Epmp {
2023-04-18T07:59:13.2773090Z         entry: [
2023-04-18T07:59:13.2773235Z             EpmpEntry {
2023-04-18T07:59:13.2773379Z                 cfg: 0x0,
2023-04-18T07:59:13.2773529Z                 kind: Off,
2023-04-18T07:59:13.2773688Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2773840Z                     0x0,
2023-04-18T07:59:13.2773974Z                     0x0,
2023-04-18T07:59:13.2774109Z                 ),
2023-04-18T07:59:13.2774242Z             },
2023-04-18T07:59:13.2774379Z             EpmpEntry {
2023-04-18T07:59:13.2774519Z                 cfg: 0x85,
2023-04-18T07:59:13.2774663Z                 kind: Tor,
2023-04-18T07:59:13.2774815Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2774972Z                     0x8000,
2023-04-18T07:59:13.2775114Z                     0xd694,
2023-04-18T07:59:13.2775252Z                 ),
2023-04-18T07:59:13.2775383Z             },
2023-04-18T07:59:13.2775521Z             EpmpEntry {
2023-04-18T07:59:13.2775665Z                 cfg: 0x81,
2023-04-18T07:59:13.2775810Z                 kind: Napot,
2023-04-18T07:59:13.2775966Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2776122Z                     0x8000,
2023-04-18T07:59:13.2776266Z                     0x10000,
2023-04-18T07:59:13.2776405Z                 ),
2023-04-18T07:59:13.2776537Z             },
2023-04-18T07:59:13.2776676Z             EpmpEntry {
2023-04-18T07:59:13.2776815Z                 cfg: 0x0,
2023-04-18T07:59:13.2776957Z                 kind: Off,
2023-04-18T07:59:13.2777111Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2777264Z                     0x0,
2023-04-18T07:59:13.2777401Z                     0x0,
2023-04-18T07:59:13.2777536Z                 ),
2023-04-18T07:59:13.2777769Z             },
2023-04-18T07:59:13.2777906Z             EpmpEntry {
2023-04-18T07:59:13.2778050Z                 cfg: 0x85,
2023-04-18T07:59:13.2778192Z                 kind: Tor,
2023-04-18T07:59:13.2778351Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2778506Z                     0x20002300,
2023-04-18T07:59:13.2778655Z                     0x20006bb0,
2023-04-18T07:59:13.2778796Z                 ),
2023-04-18T07:59:13.2779002Z             },
2023-04-18T07:59:13.2779139Z             EpmpEntry {
2023-04-18T07:59:13.2779282Z                 cfg: 0x81,
2023-04-18T07:59:13.2779427Z                 kind: Napot,
2023-04-18T07:59:13.2779584Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2779741Z                     0x20000000,
2023-04-18T07:59:13.2779885Z                     0x20100000,
2023-04-18T07:59:13.2780024Z                 ),
2023-04-18T07:59:13.2780154Z             },
2023-04-18T07:59:13.2780291Z             EpmpEntry {
2023-04-18T07:59:13.2780434Z                 cfg: 0x0,
2023-04-18T07:59:13.2780578Z                 kind: Off,
2023-04-18T07:59:13.2780730Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2780878Z                     0x0,
2023-04-18T07:59:13.2781014Z                     0x0,
2023-04-18T07:59:13.2781149Z                 ),
2023-04-18T07:59:13.2781277Z             },
2023-04-18T07:59:13.2781420Z             EpmpEntry {
2023-04-18T07:59:13.2781622Z                 cfg: 0x0,
2023-04-18T07:59:13.2781775Z                 kind: Off,
2023-04-18T07:59:13.2781924Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2782077Z                     0x0,
2023-04-18T07:59:13.2782216Z                     0x0,
2023-04-18T07:59:13.2782343Z                 ),
2023-04-18T07:59:13.2782480Z             },
2023-04-18T07:59:13.2782611Z             EpmpEntry {
2023-04-18T07:59:13.2782755Z                 cfg: 0x0,
2023-04-18T07:59:13.2782894Z                 kind: Off,
2023-04-18T07:59:13.2783063Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2783212Z                     0x0,
2023-04-18T07:59:13.2783348Z                     0x0,
2023-04-18T07:59:13.2783477Z                 ),
2023-04-18T07:59:13.2783618Z             },
2023-04-18T07:59:13.2783753Z             EpmpEntry {
2023-04-18T07:59:13.2783899Z                 cfg: 0x0,
2023-04-18T07:59:13.2784042Z                 kind: Off,
2023-04-18T07:59:13.2784190Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2784342Z                     0x0,
2023-04-18T07:59:13.2784481Z                     0x0,
2023-04-18T07:59:13.2784607Z                 ),
2023-04-18T07:59:13.2784738Z             },
2023-04-18T07:59:13.2784868Z             EpmpEntry {
2023-04-18T07:59:13.2785011Z                 cfg: 0x0,
2023-04-18T07:59:13.2785149Z                 kind: Off,
2023-04-18T07:59:13.2785306Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2785457Z                     0x0,
2023-04-18T07:59:13.2785592Z                     0x0,
2023-04-18T07:59:13.2785724Z                 ),
2023-04-18T07:59:13.2785851Z             },
2023-04-18T07:59:13.2786001Z             EpmpEntry {
2023-04-18T07:59:13.2786138Z                 cfg: 0x83,
2023-04-18T07:59:13.2786281Z                 kind: Tor,
2023-04-18T07:59:13.2786428Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2786586Z                     0x40000000,
2023-04-18T07:59:13.2786734Z                     0x50000000,
2023-04-18T07:59:13.2786864Z                 ),
2023-04-18T07:59:13.2787000Z             },
2023-04-18T07:59:13.2787130Z             EpmpEntry {
2023-04-18T07:59:13.2787273Z                 cfg: 0x0,
2023-04-18T07:59:13.2787418Z                 kind: Off,
2023-04-18T07:59:13.2787566Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2787719Z                     0x0,
2023-04-18T07:59:13.2787852Z                     0x0,
2023-04-18T07:59:13.2787989Z                 ),
2023-04-18T07:59:13.2788115Z             },
2023-04-18T07:59:13.2788253Z             EpmpEntry {
2023-04-18T07:59:13.2788398Z                 cfg: 0x87,
2023-04-18T07:59:13.2788611Z                 kind: Napot,
2023-04-18T07:59:13.2788770Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2788918Z                     0x10000,
2023-04-18T07:59:13.2789063Z                     0x11000,
2023-04-18T07:59:13.2789199Z                 ),
2023-04-18T07:59:13.2789326Z             },
2023-04-18T07:59:13.2789462Z             EpmpEntry {
2023-04-18T07:59:13.2789606Z                 cfg: 0x80,
2023-04-18T07:59:13.2789801Z                 kind: Na4,
2023-04-18T07:59:13.2789957Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2790107Z                     0x1001c000,
2023-04-18T07:59:13.2790255Z                     0x1001c004,
2023-04-18T07:59:13.2790395Z                 ),
2023-04-18T07:59:13.2790519Z             },
2023-04-18T07:59:13.2790656Z             EpmpEntry {
2023-04-18T07:59:13.2790803Z                 cfg: 0x83,
2023-04-18T07:59:13.2790943Z                 kind: Napot,
2023-04-18T07:59:13.2791100Z                 range: EpmpAddressRange(
2023-04-18T07:59:13.2791255Z                     0x10000000,
2023-04-18T07:59:13.2791405Z                     0x10020000,
2023-04-18T07:59:13.2791546Z                 ),
2023-04-18T07:59:13.2791670Z             },
2023-04-18T07:59:13.2791801Z         ],
2023-04-18T07:59:13.2791929Z     }
2023-04-18T07:59:13.2792287Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] Checking that the debug memory region is enabled in state TestUnlocked0
2023-04-18T07:59:13.2792669Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] lc_state = TestUnlocked0
2023-04-18T07:59:13.2793090Z [2023-04-18T07:59:13Z INFO  e2e_chip_specific_startup] Checking that the SRAM scrambling key seed is not valid in LC state TestUnlocked0
2023-04-18T07:59:13.2793545Z thread 'main' panicked at 'assertion failed: !cs.sram.scr_key_seed_valid', sw/host/tests/rom/e2e_chip_specific_startup/src/main.rs:311:13
```
</details>

### Steps to Reproduce

- GitHub Revision: master
```sh
bazel test --define DISABLE_VERILATOR_BUILD=true --define bitstream=gcp_splice \
--test_tag_filters=-verilator,-dv,-broken --build_tests_only \
//sw/device/silicon_creator/rom/e2e:e2e_chip_specific_startup_test
```

### Tests with similar or related failures

- [ ] e2e_chip_specific_startup_test_unlocked0_fpga_cw310_rom

**Comment by engdoreis** [comment] 2023-04-18 14:41
@johngt for visibility

**Comment by johngt** [comment] 2023-04-25 09:48
Assigning to @alphan but also tagging @luismarques for visibility.

**Comment by moidx** [comment] 2023-05-05 03:47
There have been a couple of changes that could have fixed this. I am unable to reproduce now.

**Comment by moidx** [comment] 2023-06-19 10:59
Closing now. Please re-open if able to reproduce.

**Closed by moidx** 2023-06-19 10:59 UTC
Labels: Component:TestTriage
