### ISSUE TITLE
[DV] Regression runs firing tb.dut.top_earlgrey.tl_adapter_ram_main.TlOutKnown_A

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1736] opened 2020-03-12 13:38 UTC
Private CI is failing due to an assert firing.

<hr/>

**TEST:** chip_sanity, **SEED:** 3726260937<br>
**LOG:** $scratch_path/0.chip_sanity/out/run.log<br>
```
UVM_ERROR @ 8568613506 ps: (prim_assert.sv:18) [ASSERT FAILED] [tb.dut.top_earlgrey.tl_adapter_ram_main.TlOutKnown_A] TlOutKnown_A: !$isunknown(tl_o) (../src/lowrisc_tlul_adapter_sram_0.1/rtl/tlul_adapter_sram.sv:279)
```

<hr/>

A solution is most likely being worked on as part of https://github.com/lowRISC/opentitan/pull/1729.

CI [failed first](https://dev.azure.com/lowrisc/opentitan-private/_build?definitionId=8&_a=summary&repositoryFilter=7&branchFilter=2063) for https://github.com/lowRISC/opentitan/pull/1616, which is unrelated and had clean CI. I've filed https://github.com/lowRISC/opentitan/issues/1735 to hopefully address the underlying reason for the flaky test.

**Comment by eunchan** [comment] 2020-03-12 15:58
What I understand is that the unknown error occurs (and CI failed) as the host request partial read from SRAM? And the partial read happens as the host writes partially prior to that event. Am I understanding correctly @sriyerg ?

Then, I think the host would be better to make sure to initialize SRAM or change the Unknown Assertion to only check the partial data not revising the RTL. 

CC: @msfschaffner @tjaychen

**Comment by sriyerg** [comment] 2020-03-12 17:19
A fix for this has already been pushed in #1732.

**Comment by sriyerg** [comment] 2020-03-12 17:29
BTW, this is not a 'flaky' error - its a real issue flagged (likely) by the changes in #1616, which was possibly merged without a rebase (which was when the fix in dvsim to exit with error was pushed). This resulted in subsequent PRs to fail with the error. 

#1616 possibly resulted in a change which caused a partial write to the RAM followed by partial read, which returned full data instead of masked data that ended up propagating the Xs from the uninitialized parts of the RAM.  

The flakiness is more due to the regression not completing within 15 minutes - on rare occasions, it exceeds the 15 min limit failing the private CI. I'd very much prefer to adhere to the 15 min limit (which will be admittedly be harder to meet as more tests get added to the regression).

**Comment by imphil** [comment] 2020-03-12 17:55
@sriyerg could you explain more what you mean?

That's how the CI runs looked:

![image](https://user-images.githubusercontent.com/1467123/76549370-34a85b80-6488-11ea-81e9-77a7f867357e.png)

- None of the tests got close to the 15 min limit
- There are 5 green runs after the "exit with errors" change and the runs that go red.
- All shown runs are on master, i.e. after all rebasing.

Given that, I see two possible explanations: either the test is flaky (but in a weirdly consistent way, given it consistently fails now), or the software change that was committed actually had the side effect of triggering failing chip-level DV runs (I don't know enough about what is being tested to make that judgement call by looking at the diff in #1616)

**Comment by sriyerg** [comment] 2020-03-12 18:19
If a test is consistently failing with the exactly the same error message, it is by definition not flaky :)

#1616 was last updated 2 days ago and it was merged 22 hours ago. It likely did no undergo a rebase, so it did not have the dvsim updates from #1697 which was also merged just 2 days ago. This resulted in #1616 to continue to false-pass in the CI and get merged. See the false-passing [CI check results](https://dev.azure.com/lowrisc/opentitan-private/_build/results?buildId=8938&view=logs&j=89b1484e-e59b-56b8-bef8-ec534b74be7c&t=5028a3c4-0542-585a-b10c-81f6b79fff87) that allowed it to be merged. 

Once it got merged along with the updates in #1697, it started failing in the CI runs in the master branch (which I believe is what we are seeing here).

SW updates in #1616 likely changed the way writes and reads were issued from Ibex. I am guessing it did not issue partial writes and reads before #1616 so this issue was never seen before. The change uncovered a bug in the SRAM adapter that was not masking the partial read, which ended up propagating Xs on rdata and being flagged as assertion error.

**Comment by sriyerg** [comment] 2020-03-12 18:23
To clarify further, See:

#1616 CI failing in [20200310.3](https://dev.azure.com/lowrisc/opentitan-private/_build/results?buildId=8938&view=logs&j=89b1484e-e59b-56b8-bef8-ec534b74be7c&t=5028a3c4-0542-585a-b10c-81f6b79fff87) run (before getting merged)

#1616 CI failing in [20200311.18](https://dev.azure.com/lowrisc/opentitan-private/_build/results?buildId=9012&view=logs&j=89b1484e-e59b-56b8-bef8-ec534b74be7c) run (after getting merged into the master branch)

Also see my [comment](https://github.com/lowRISC/opentitan/pull/1726#issuecomment-597955716) in #1726 which failed the first time the CI ran on it with a 15-min timeout error.

**Closed** 2020-03-13 11:13 UTC
Labels: Component:DV, Priority:P1
