### ISSUE TITLE
[aes] Create waivers for not creating fatal alerts

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15709] opened 2022-10-25 13:11 UTC
Related to two fatal alerts not being created:

1. Forcing main FSM signals does not result in a fatal alert ([#13572](https://github.com/lowRISC/opentitan/issues/13572))
2. Forcing cipher core FSM signals does not result in fatal alert ([#13646](https://github.com/lowRISC/opentitan/issues/13646))

- Could potentially be waived for V2S because RTL is correct but test does not know when to expect an alert and when not.
- Remaining effort: suggest to waive this as we have passing seeds for all these tests which is sufficient for V2S

If creating the waivers will need to announce to @moidx and @msfschaffner for inclusion in the next Chairs meeting where waivers will be reviewed.

>estimate 8

**Comment by johngt** [comment] 2022-10-25 13:13
If going down waiver route, change priority to P3.

**Comment by vogelpi** [comment] 2022-10-28 15:59
The two issues are boiling down to the same thing: the test forces a signal and expects an alert which sometimes isn't happening within a certain time frame as the RTL doesn't evaluate the forced signal at that point. Thus the fault is ineffective. The RTL behavior is correct.

Currently about 1 out of 10 FI tests fails because of this.

**Comment by msfschaffner** [comment] 2022-10-28 20:15
Looping in @sriyerg and @weicaiyang. For V2(S) purposes, I believe we require that 90% of the nightly regression tests are passing (see [here](https://docs.opentitan.org/doc/project/checklist/#sim_nightly_regression_v2)). So if that is fulfilled, I believe we can make this a V3 coverage closure issue and defer into M3 without needing a chairs / TC approved waiver.

**Comment by weicaiyang** [comment] 2022-10-28 21:01
SGTM, we can change this issue to M3 and address it after V2S.

**Comment by vogelpi** [comment] 2022-11-07 08:46
I am closing this issue as we don't need to waive anything. To meet the coverage target for V2S we had to make some changes to these FI tests which caused the problematic behavior to become more significant. As a result, the pass rate of these tests dropped below the threshold. We thus files #16001 to fix this and solve the underlying issue.

**Closed by vogelpi** 2022-11-07 08:46 UTC
Labels: Component:DV, IP:aes
