### ISSUE TITLE
[otbn, dv] Assertion of predec_error_o is not causing a fatal alert

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#13847] opened 2022-07-26 13:13 UTC
@GregAC, @vogelpi, in this testcase, I'm trying to test CTRL.REDUN countermeasure for otbn. I'm trying to inject a fault by asserting tb.dut.u_otbn_core.u_otbn_mac_bignum.predec_error_o . However, there is no fatal alert and the status of otbn is not going to locked state. Please find screenshot attached. 
![Screenshot from 2022-07-26 14-13-01](https://user-images.githubusercontent.com/91126414/181014370-ac137e21-8f0b-4c53-9c7d-ec9f7ac92a4e.png)

**Comment by vogelpi** [comment] 2022-07-26 15:41
Hi @prajwalaputtappa ,
thanks for opening this issue. Can you maybe provide the command to reproduce this? Then Greg or I can have a look at the waves. There are multiple versions of `predec_error_o` (reg files, MAC, ALU etc.) and some of them are only taken into account if OTBN is actually seeing a valid instruction, i.e., it is running.

**Comment by prajwalaputtappa** [comment] 2022-07-26 18:01
Hi @vogelpi,
I've made a temp commit to reproduce the issue. The commit id is 857c7495a8d914ba09f010422010848f257b9523. Please use the following command to reproduce the error:
util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson  -i otbn_ctrl_redun --fixed-seed 2054388998 -w --tool=xcelium 
I hope this helps. Let me know if you've any questions.

**Comment by vogelpi** [comment] 2022-07-26 19:20
Thanks @prajwalaputtappa , the command will be useful.

I can't see the commit. What I would need is a branch name and you need to make sure that you actually pushed this branch to your OpenTitan fork. Then, I can checkout the branch and knowing the commit ID I can ensure that I am at the right place. But AFAIK, I cannot just checkout your commit using the provided ID.

If you can provide me the branch name, I can take a look on THU.

**Comment by prajwalaputtappa** [comment] 2022-07-27 10:43
Pirmin, I've created a temporary PR here - https://github.com/lowRISC/opentitan/pull/13867

**Comment by vogelpi** [comment] 2022-07-29 09:19
Thanks @prajwalaputtappa . I now had a look at this. As suspected, OTBN happens to be idle when the mac_en signal is forced for this test and seed. As you can see in the waves below, the predecode error is triggered inside the MAC unit but it doesn't propagate inside the core as OTBN is halted, i.e., not seeing valid instructions (see also the code snippet below).

![otbn_debug](https://user-images.githubusercontent.com/20307557/181726986-329bfa8d-84eb-4747-9199-61c22a163563.png)

From `otbn_core.sv`
```sv
  assign predec_error =
    ((alu_bignum_predec_error | mac_bignum_predec_error | controller_predec_error) & insn_valid) |
     rf_bignum_predec_error                                                                      |
     ispr_predec_error                                                                           |
     rd_predec_error;
```

This is not a bug, but instead I think the test needs to be made aware of this. Do you think it would be feasible to define that some of the target signals for the force are only expected to trigger an error if OTBN isn't idle? Or in other words, to formulate a condition for each target signal under which a force must be detected?

**Comment by johngt** [comment] 2022-08-02 13:04
Closing issue - as this is not a bug.

**Closed by johngt** 2022-08-02 13:04 UTC
Labels: Type:Enhancement, IP:otbn, Milestone:V2S
