### ISSUE TITLE
[spi_host,dv] Revisit default pull-up in block-level TB

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#16205] opened 2022-11-10 11:56 UTC
[We think](https://github.com/lowRISC/opentitan/pull/16015#discussion_r1014570884) this pull-up in the `spi_host` block-level TB
https://github.com/lowRISC/opentitan/blob/d856706cac88b04486775c74887408c9cc7ca186/hw/ip/spi_host/dv/tb.sv#L100-L102
is not required, but tests currently fail without it. We should investigate this.

**Comment by abdullahvarici** [comment] 2022-11-17 08:30
I have reviewed following lines: https://github.com/lowRISC/opentitan/commit/3ca6113491c8bb2317ff55cd5b9d288c0b8daf02/hw/ip/spi_host/dv/tb.sv#L100-L104 
After removing Line 100 and 101, the spi_host_speed test is running succesfully. (`so_pulldown` in Line 101 was not being used in anywhere anyway.) After removing Line 103, a few assertions in `prim_fifo_sync.sv` and `spi_host.sv` were failing and because of that the test was failing.

**Comment by andreaskurth** [comment] 2022-11-17 09:02
Thanks for investigating this @abdullahvarici. I think:

- Removing L101 is uncontroversial since `so_pulldown` is not used anywhere. When you remove it, please don't forget to also remove the signal declaration.
- Before removing L100, we should run each test of `spi_host` with at least 10 seeds to make sure we're not violating an obvious assumption in the other tests.
- To judge L103, which assertions were failing?

**Comment by abdullahvarici** [comment] 2022-11-17 09:07
> Removing L101 is uncontroversial since so_pulldown is not used anywhere. When you remove it, please don't forget to also remove the signal declaration.
Yeah, sure.
> Before removing L100, we should run each test of spi_host with at least 10 seeds to make sure we're not violating an obvious assumption in the other tests.
How about a full regression test?
> To judge L103, which assertions are failing when you remove that line?
The followings: `(prim_fifo_sync.sv:193) [ASSERT FAILED] DataKnown_A` and `(spi_host.sv:612) [ASSERT FAILED] CioSdKnownO_A`

**Comment by andreaskurth** [comment] 2022-11-17 09:12
> How about a full regression test?

You can run it if you have time (that's why I wrote "at least" :slightly_smiling_face: ) -- I currently don't.

> The followings: (prim_fifo_sync.sv:193) [ASSERT FAILED] DataKnown_A and (spi_host.sv:612) [ASSERT FAILED] CioSdKnownO_A

Could you assess whether those assertions are meaningful or overzealous in this scenario? That is, do the assertions fail because an assumption on which `prim_fifo_sync` or `spi_host` is built is violated? Or do they fail because they are written too narrowly?

**Comment by abdullahvarici** [comment] 2022-11-18 12:49
After removing L100, I've run each test of `spi_host` with 10 seeds without any failure.

I made following change in `spi_host.sv`:
```
- `ASSERT_KNOWN_IF(CioSdKnownO_A, cio_sd_o, !passthrough_i.passthrough_en |
-    (passthrough_i.passthrough_en && passthrough_i.csb_en && !passthrough_i.csb))
+ for (genvar i = 0; i < 4; i++) begin : gen_assert_ciosdknown
+    `ASSERT_KNOWN_IF(CioSdKnownO_A_0, cio_sd_o[i], cio_sd_en_o[i] & (!passthrough_i.passthrough_en |
+      (passthrough_i.passthrough_en && passthrough_i.csb_en && !passthrough_i.csb)))
+  end
```
This was necessary and it prevents following assertion failure: `(spi_host.sv:612) [ASSERT FAILED] CioSdKnownO_A` when I remove L103.

However, if I didn't misunderstood, `cio_sd_i` is sampled by the spi_host whenever `sck` is active. When cio_sd_i is not driven by spi_agent (i.e. when only spi_host sending data), this value is sampled as unknown (maybe it is not used and got rid off) and causes following assertions failure:
- (prim_fifo_sync.sv:193) [ASSERT FAILED] DataKnown_A
- (tlul_assert.sv:310) [ASSERT FAILED] dKnown_A
I think those assertions are meaningful and we should not remove L103 or we should change the design for unknown data is not being sampled and stored in fifos.

**Comment by andreaskurth** [comment] 2022-11-21 07:15
> This was necessary and it prevents following assertion failure: (spi_host.sv:612) [ASSERT FAILED] CioSdKnownO_A when I remove L103.

IIUC, your change means `cio_sd_o[i]` must be known *only if `cio_sd_en_o[i]` is high. I think this makes sense.

> I think those assertions are meaningful and we should not remove L103 or we should change the design for unknown data is not being sampled and stored in fifos.

I agree. I don't think it's possible for `spi_host` to know if `cio_sd_i` is valid, since there is no enable, chip-select, or valid input associated with it. If you agree, let's keep the current design and assertions.

**Comment by abdullahvarici** [comment] 2022-11-21 10:45
Yes Andreas, I agree with you. I am closing the issue then.

**Closed by abdullahvarici** 2022-11-21 10:45 UTC
Labels: Component:DV, Priority:P3, IP:spi_host
