### ISSUE TITLE
[test-triage] chip_sw_alert_handler_escalation

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14205] opened 2022-08-10 22:47 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

UVM_ERROR @ 3935.230296 us: (chip_base_vseq.sv:159) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_alert_handler_escalation_vseq] lc_escalate_en_o: 0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx00000005 mismatched

### Steps to Reproduce

- GH revision: [9c0b24ddb](https://github.com/lowrisc/opentitan/tree/9c0b24ddbeb5616bd8db661ec1395f2d4f326bc4)
- util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_alert_handler_escalation_vseq --build-seed 2483310614 --fixed-seed 3231918301

**Comment by johngt** [comment] 2022-08-17 16:13
Adding tests with similar or related failures
- [ ] chip_sw_alert_handler_escalations
- [ ] chip_sw_lc_ctrl_alert_handler_escalation

**Comment by tjaychen** [comment] 2022-08-19 16:46
hmm? can i ask why this was assigned to me? 
Has there been any more triage on the failure reason?

**Comment by engdoreis** [comment] 2022-08-19 20:32
I quickly tried to debug this test, but I could not find any easy solution. So I assigned it to you because the `sw/device/tests/sim_dv/alert_handler_escalation.c` was committed by you. 
But maybe I misunderstood the regression on call process.

**Comment by tjaychen** [comment] 2022-08-19 20:33
okay sounds good, if you could just leave a few notes and what you were able to see during the triage process (what was tried etc), or if anything seemed peculiar, that would be great. 

I can have a look.

**Comment by tjaychen** [comment] 2022-08-24 15:45
unassigning for now as test is not under triage

**Comment by tjaychen** [comment] 2022-08-24 20:23
assign to @tjaychen for triage.

**Closed** 2022-08-25 21:13 UTC
Labels: Component:TestTriage
