### ISSUE TITLE
[rv_dm,dv] Verify that the JTAG DMI register space cannot be accessed if lc_hw_debug_en is a non strict true value (`jtag_dmi_debug_disabled` BLT)

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15667] opened 2022-10-23 18:14 UTC
This issue tracks the implementation of the `jtag_dmi_debug_disabled` block-level test, which is specified in the testplan for `rv_dm`.

>estimate 8

**Comment by andreaskurth** [comment] 2023-02-23 08:30
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP3 because this is an open V2 test but we already have a TLT covering it.

**Comment by rswarbrick** [comment] 2024-01-18 17:07
I see that @Shahid-Mehmood-S implemented an `rv_dm_jtag_dmi_debug_disabled_vseq` last November. Does that vseq implement what's needed to close this issue?

**Comment by rswarbrick** [comment] 2024-01-18 17:33
Oh. No it can't. @Shahid-Mehmood-S, how did you actually test this at your end?

Trying to run locally with 
```
  util/dvsim/dvsim.py hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson -i rv_dm_jtag_dmi_debug_disabled --fixed-seed 123
```
fails with a compilation error.

The problem is that there's a basic syntax error in line 24 of the vseq file. So the work is definitely not done, nor is there any evidence that the existing work has been tested.

**Comment by rswarbrick** [comment] 2024-01-18 17:38
Aargh, sorry. I was looking at a local checkout, which had the contents of PR #20739. I asked a couple of questions about whether the change I could see locally would fix stuff (not yet!).

I'll delete the questions above.

**Closed** 2024-01-22 13:41 UTC
Labels: Component:DV, Priority:P3, IP:rv_dm, Milestone:V2, Earlgrey-PROD Candidate
