### ISSUE TITLE
[test-triage] chip_sw_data_integrity_escalation 

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18489] opened 2023-05-10 11:36 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
Test chip_sw_data_integrity_escalation has 2 failures.
0.chip_sw_data_integrity_escalation.233406972
Line 1101, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_data_integrity_escalation/latest/run.log

  UVM_ERROR @ 2657.512088 us: (sw_logger_if.sv:523) [data_integrity_escalation_reset_test_prog_sim_dv(sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c:362)] CHECK-STATUS-fail: %r
  UVM_INFO @ 2657.512088 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

### Steps to Reproduce

- GitHub Revision: [bc163b70f](https://github.com/lowrisc/opentitan/tree/bc163b70f077a821f16aeeaafa721f1c10a919bc)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_data_integrity_escalation --build-seed 488598207 --fixed-seed 233406972 --waves fsdb

### Tests with similar or related failures

- [ ] chip_sw_data_integrity
- [ ] chip_sw_instruction_integrity
- [ ] chip_sw_sram_lc_escalation

**Comment by johngt** [comment] 2023-05-10 11:38
Tests failing since May 5th
|    | Tests                             |   2023-05-09 19:59:10 |   2023-05-09 07:05:17 |   2023-05-08 22:12:41 |   2023-05-08 07:09:02 |   2023-05-07 07:02:50 |   2023-05-05 07:02:25 |   2023-05-04 07:05:40 |   2023-05-03 07:07:45 |   2023-05-02 07:05:10 | Suite                                                                             |
|---:|:----------------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:----------------------------------------------------------------------------------|
| 63 | chip_sw_data_integrity_escalation |                 66.67 |                 83.33 |                    50 |                 66.67 |                 66.67 |                 66.67 |                   100 |                   100 |                   100 | chip_sw_data_integrity, chip_sw_instruction_integrity, chip_sw_sram_lc_escalation |

**Comment by moidx** [comment] 2023-05-10 18:33
The failure points to the following section in the test:

**Comment by moidx** [comment] 2023-05-10 23:28
This test probably needs to be refactored. All ISRs initiate flash_write transactions, and there is a NMI that also triggers a flash transaction.  When the NMI overrides an ISR in progress, the test fails due to a dif check referenced below.


```
UVM_INFO @ 2566.742088 us: (sw_logger_if.sv:521) [data_integrity_escalation_reset_test_prog_sim_dv(sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c:325)] At instr access fault handler
UVM_INFO @ 2610.442088 us: (sw_logger_if.sv:521) [data_integrity_escalation_reset_test_prog_sim_dv(sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c:353)] At NMI handler
UVM_ERROR @ 2657.512088 us: (sw_logger_if.sv:523) [data_integrity_escalation_reset_test_prog_sim_dv(sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c:362)] CHECK-STATUS-fail: 0x85861a2e
```

https://github.com/lowRISC/opentitan/blob/bbebcaff907f3b02206742f6b3b18d0c4a2a40c3/sw/device/lib/dif/dif_flash_ctrl.c#L419-L421

**Comment by moidx** [comment] 2023-05-10 23:36
Hi @msfschaffner, I am moving this to M2.5.2 as it will take some effort to remove the flakiness from the test, and it has been root caused to a software issue. Please feel free to move back to M2.5.1 if needed.

**Comment by msfschaffner** [comment] 2023-05-11 00:49
That sounds good to me!

**Comment by johngt** [comment] 2023-05-17 09:30
Note that there is a new error but also related to this test.

```
  UVM_ERROR @ 2905.855920 us: (sw_logger_if.sv:523) [data_integrity_escalation_reset_test_prog_sim_dv(sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c:363)] CHECK-STATUS-fail: FLA:209 = Unavailable
  UVM_INFO @ 2905.855920 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
```

**Comment by moidx** [comment] 2023-05-17 12:49
Hi @johngt, this is the same error. The difference is that I updated the logging to print the `status_t` message. This will hopefully make similar issues easier to debug in the future.

**Comment by johngt** [comment] 2023-06-30 10:55
We have seen this issue in more recent runs - leaving for @moidx and @msfschaffner to decide whether to close or to put in the backlog as a V3 item. My suggestion would be the latter.

**Comment by msfschaffner** [comment] 2023-07-06 13:30
Making this a V3 item sounds good to me!

**Comment by matutem** [comment] 2023-07-21 18:28
I think the best way to handle this is to increment nmi_count only once, since that test only cares if the nmi was run at least once. This means only the first NMIs will perform a flash write, so subsequent NMIs won't find the flash to be busy.

**Closed** 2023-07-25 18:11 UTC
Labels: Component:DV, Priority:P2, Milestone:V3, Component:ChipLevelTest, Component:TestTriage
