### ISSUE TITLE
[csrng,doc] CSRNG documentation questions

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#16203] opened 2022-11-10 10:25 UTC
These are some questions I had when I was writing the test plan and could not find in the documentation:

1. When do the interrupt flags in `intr_state` clear? Do they clear when the CSRNG receives the next command? **Update:** Clarified in: https://github.com/lowRISC/opentitan/pull/16116
1. In the documentation the cmd type is 4 bits, but it is only 3 bits in the implementation. Values (`0x0`,`0x6-0xF`) are marked as reserved, should I change this in the documentation to only allowing values up to `0x7`?
1. In the documentation glen is defined as a 13 bit value with the most significant 7 bits of the command marked as reserved. In the RTL, these reserved bits are included in glen. Should we change the RTL to match the documentation on this one?
1. Do we use a derivation function when instantiating and reseeding? It is mentioned once in the documentation but couldn't find it in the RTL. **Update:** Clarified in: https://github.com/lowRISC/opentitan/pull/16313

**Comment by vogelpi** [comment] 2022-11-10 10:58
Hi @marnovandermaas ,
thanks for factoring this out into a seperate issue. I am don't know about the first question, maybe @mwbranstad can help with this one. For the other ones:

2. My understanding is that this is why they're marked as "reserved" in the documentation already. If someone drives non-zero values to these bits, undefined behavior may result.
3. Also here I think this is the meaning of "reserved". But since they're defined as "unused" it would probably be better to change the RTL here. I am against RTL modification at this stage but it would be a minor one.
4. To my knowledge, our CSRNG implements CTR_DRBG without derivation function. So there the documentation should be corrected. This can happen after M2.

**Comment by martin-lueker** [comment] 2022-11-10 17:12
We do not use a derivation function for thi block..   The specification for the derivation function is a major pain to implement in HW.  We instead insist that the output of the `entropy_src` is "full-entropy" to satisfy SP 800-90A.

**Comment by vogelpi** [comment] 2022-11-10 17:16
Thanks for your inputs @mwbranstad and @martin-lueker . All clear then, this is useful for the DV work we're doing. I think we can make any documentation changes related to this after M2.

**Comment by marnovandermaas** [comment] 2022-11-11 16:12
> No - all 4 bits are claimed and defined. Only 3 bits may be used today, but future use may use more.
Forgive my ignorance, but it looks like it is 3 bits from the `csrng_core.sv`:
> A: this seems incorrect. the glen field is actually 13 bits to support a 4096 value, as defined by bits 24-12. The upper 7 bits of the 32 bit command are reserved. The RTL supports this. Not seeing any issue here.
I can't exactly find where the glen field is written from the bus, but I agree that glen should be 13 bits, which I've found in the RTL here: https://github.com/lowRISC/opentitan/blob/21b703db5740e68b64e7bfd4700ea24786479858/hw/ip/csrng/rtl/csrng_cmd_stage.sv#L52

**Comment by marnovandermaas** [comment] 2022-11-14 12:56
Added updates to question 1 and 4 in the main description

**Comment by vogelpi** [comment] 2022-11-25 13:26
Thanks for filing the PR @marnovandermaas .

Regarding No. 2:
> > No - all 4 bits are claimed and defined. Only 3 bits may be used today, but future use may use more.
> 
> Forgive my ignorance, but it looks like it is 3 bits from the `csrng_core.sv`:
> 
> https://github.com/lowRISC/opentitan/blob/21b703db5740e68b64e7bfd4700ea24786479858/hw/ip/csrng/rtl/csrng_core.sv#L1037
> 

I think this is exactly what Mark meant: Only 3 bits may actually be used today. But 4 bits are claimed/reserved by the specification. Bit No. 4 is ignored at the moment but future versions may use it. In the current version, behavior is undefined if Bit No. 4 is set. We've agreed that no no further action is required for this one.

> > A: this seems incorrect. the glen field is actually 13 bits to support a 4096 value, as defined by bits 24-12. The upper 7 bits of the 32 bit command are reserved. The RTL supports this. Not seeing any issue here.
> 
> I can't exactly find where the glen field is written from the bus, but I agree that glen should be 13 bits, which I've found in the RTL here:
> 
> https://github.com/lowRISC/opentitan/blob/21b703db5740e68b64e7bfd4700ea24786479858/hw/ip/csrng/rtl/csrng_cmd_stage.sv#L52

I just looked up the RTL and I think everything is fine here. The RTL only uses the 13 bits as Mark confirmed:
https://github.com/lowRISC/opentitan/blob/21b703db5740e68b64e7bfd4700ea24786479858/hw/ip/csrng/rtl/csrng_cmd_stage.sv#L181-L197

and
https://github.com/lowRISC/opentitan/blob/21b703db5740e68b64e7bfd4700ea24786479858/hw/ip/csrng/rtl/csrng_cmd_stage.sv#L290

So also that seems fine. I am thus closing this issue.

**Closed by vogelpi** 2022-11-25 13:26 UTC
Labels: Component:Doc, Type:Question, IP:csrng
