### ISSUE TITLE
[chip-test] - chip_sw_rv_core_ibex_double_fault

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13219] opened 2022-06-15 11:00 UTC
### Test point name

[chip_sw_rv_core_ibex_double_fault](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_rv_core_ibex_double_fault)

### Host side component

TBD

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

gac

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

## Test description

 Verify the functionality of the ibex double fault dump.

- Purposely create an ibex double exception during execution, by performing an unmapped read and in the exception handler perform another unmapped read.
- Ensure the rstmgr fault dump correctly captures both dumps correctly and indicates the previous dump is valid.

**Comment by tjaychen** [comment] 2022-08-22 21:21
can we double check if this test is a duplicate of this one [here](https://github.com/lowRISC/opentitan/blob/83f86fa8959de62cc344e90cb4eba604c93417e2/hw/top_earlgrey/data/chip_testplan.hjson#L1150-L1161)?

Or whether the test could be enhanced to satisfy the requirements of both?

**Comment by engdoreis** [comment] 2022-08-23 08:01
I beleive it is dublicated. I discussed with @HU90m and we beleive there's room for improvement in the existing `chip_sw_rstmgr_cpu_info`, thats why this issue is still opened.

**Comment by tjaychen** [comment] 2022-08-23 14:46
sounds great!

**Comment by HU90m** [comment] 2022-10-24 12:16
Passed three nightly regressions.

**Closed by HU90m** 2022-10-24 12:16 UTC
Labels: Type:Task, IP:rv_core_ibex, Component:ChipLevelTest
