### ISSUE TITLE
[regression] GDB debugger shows all instructions as unimp

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#1802] opened 2020-03-20 20:51 UTC
I usually attach GDB to OpenTitan running on the Nexys FPGA.

I would do this by running OpenOCD

```shell
$ openocd -s util/openocd -f board/lowrisc-earlgrey-nexysvideo.cfg
```

and then connecting GDB to it by running this in riscv32 GDB

```shell
        target extended-remote :3333
        monitor reset halt
```

Since commit:

```diff
commit 39faf3879f251b6d77a2f5b241d2cf054718df58
Author: Michael Schaffner <msf@opentitan.org>
Date:   Wed Mar 11 22:20:06 2020 -0700

    [tlul_adapter_sram] Fix to avoid X on invalid read data
    
    Signed-off-by: Michael Schaffner <msf@opentitan.org>

 hw/ip/tlul/rtl/tlul_adapter_sram.sv | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)
```

this doesn't work.

OpenOCD correctly connects and GDB connects to OpenOCD but every instruction is read as:

```
? unimp
```

GDB can't get any assembly information. On top of that it appears that execution doesn't work correctly it looks like the loaded binary doesn't run. Although I haven't confirmed the binary not running is from the same commit.

**Comment by tjaychen** [comment] 2020-03-23 07:00
Sorry you're seeing this Alistair... I don't actually have access to an
fpga right now (and might not for some time...) So I can't reproduce what
you're seeing...

Could you confirm whether this also breaks on verilator? It sounds like the
more basic problem is that the binary just won't run? Do you at least see
some of the ROM printouts ? Or does it die before then?

**Comment by asb** [comment] 2020-03-24 10:29
CC @msfschaffner.

**Comment by msfschaffner** [comment] 2020-03-30 20:34
Sorry for my late response I have been focusing on a different project last week. Let me give this a closer look...

**Comment by alistair23** [comment] 2020-03-30 22:35
No worries. I've been too busy to try and reproduce this with Verilator as well. If you have problems reproducing this (on Verilator or FPGA) let me know and I'll reproduce it again.

**Comment by GregAC** [comment] 2020-03-31 15:33
Did you get anywhere on this @msfschaffner ?

I am taking a look now, you can reproduce under verilator. Looks like GDB issues a memory read to OpenOCD which then returns all 0s. I've succesfully captured a vcd of this happening.

Either the debug module has lost access to the iside memory for some reason or there's something broken with addresses and it's reading from the wrong place. I'm going to keep looking at it and will let you know what I've found out by the end of the (UK) day.

**Comment by GregAC** [comment] 2020-03-31 17:20
I've found the root cause, the adapter in the debug module that converts its memory access requests to TL has some issues with the mask generation. This results in the DM reads to flash not actually getting any bytes back. See issue https://github.com/lowRISC/opentitan/issues/1860 which I'll fix tomorrow (due to tilelink requirements it's a little fiddly).

**Comment by msfschaffner** [comment] 2020-03-31 21:34
Thanks @GregAC for looking into this. The TL mask generation of the DM was also under my suspicion, since the particular commit that was referred to above basically just changed the way the byte mask is used for data read from SRAM (we now make sure that unrequested bytes are masked out to 0). 

Can you CC me on the PR?

**Comment by GregAC** [comment] 2020-04-01 11:06
@alistair23 do you want/need a fix for this soon? It's opened a bit of a can of worms around how we adapt the Ibex/Debug Module protocols to Tilelink that may take a few days to discuss (https://github.com/lowRISC/ibex/issues/757 and https://github.com/lowRISC/opentitan/issues/1867). In the meantime I could do a quick fix to make it work if you have need of such a thing

**Comment by alistair23** [comment] 2020-04-01 17:07
I'm just using an old build, so no rush on my side.

**Comment by GregAC** [comment] 2020-04-09 11:25
This has been fixed by #1879

**Closed by GregAC** 2020-04-09 11:25 UTC
