### ISSUE TITLE
[otbn] Is latch inferred intentionally for insn_subset_reg?

### ISSUE THREAD

**Issue by rmbhagwat** [lowRISC/opentitan#3773] opened 2020-10-10 04:04 UTC
Dear OTBN decoder designer,

Is the following latch inferred intentionally?

  /////////////
  // Decoder //
  /////////////

  always_comb begin
    rf_wdata_sel          = RfWdSelEx;
    rf_we                 = 1'b0;
    rf_ren_a              = 1'b0;
    rf_ren_b              = 1'b0;

    illegal_insn          = 1'b0;
    ecall_insn            = 1'b0;
    ld_insn               = 1'b0;
    st_insn               = 1'b0;
    branch_insn           = 1'b0;
    jump_insn             = 1'b0;
    ispr_rw_insn          = 1'b0;
    ispr_rs_insn          = 1'b0;

    opcode                = insn_opcode_e'(insn[6:0]);

    unique case (opcode)
      //////////////
      // Base ALU //
      //////////////

      InsnOpcodeBaseLui: begin  // Load Upper Immediate
        **insn_subset      = InsnSubsetBase;**
        rf_we            = 1'b1;
      end

      InsnOpcodeBaseOpImm: begin // Register-Immediate ALU Operations
        **insn_subset      = InsnSubsetBase;**

WARNING: [Synth 8-327] inferring latch for variable 'insn_subset_reg' [/home/rbhagwat/project/rot/20201008_opentitan/build/lowrisc_systems_top_earlgrey/src/lowrisc_ip_otbn_0.1/rtl/otbn_decoder.sv:165]

**Comment by GregAC** [comment] 2020-10-12 08:59
Thanks for the report @rmbhagwat. This was not intentional and will be fixed when https://github.com/lowRISC/opentitan/pull/3710 gets merged.

**Comment by rmbhagwat** [comment] 2020-10-13 07:45
Thank you @GregAC !!!

**Comment by GregAC** [comment] 2020-10-13 10:11
#3710 has been merged so this is fixed.

**Comment by rmbhagwat** [comment] 2020-10-21 09:15
[Synth 8-327] inferring latch for variable 'increment_out_reg' ["/home/project/rot/20201018/build/lowrisc_systems_top_earlgrey_TEBA0841_0.1/src/lowrisc_ip_otbn_0.1/rtl/otbn_controller.sv":228]

**Comment by imphil** [comment] 2020-10-21 09:20
@rmbhagwat Thanks for your report.

I'm assuming this is a new latch? (Not unlikely, since all of that code is under heavy development at the moment). 

* If you know how to fix it (it's probably just a missing default statement), we'd very much appreciate if you can open a pull request. That's the fastest and easiest way to get such things fixed. Let me know if you need any help on doing so, we are happy to guide you through the process.
* If you report a new problem (even though it's similar), please file a new issue. This help us to keep track of what has been resolved, and where more action is needed.

**Comment by rmbhagwat** [comment] 2020-10-21 10:03
Sure, I'll raise the pull request. I didn't know that I could contribute.

**Comment by vogelpi** [comment] 2020-10-21 13:08
I think this is a duplicate of #3646.

**Comment by vogelpi** [comment] 2020-11-02 17:01
The last remaining auto-inferred latch has been removed by #3997. Now that also #3988 is merged, it should be impossible to introduce new auto-inferred latches. I am closing this issue.

**Closed by vogelpi** 2020-11-02 17:01 UTC
