### ISSUE TITLE
[rv_dm, jtag, mfg] Workarounds 

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18441] opened 2023-05-08 16:42 UTC
### Description

Discussed in triage meeting.

Potential workarounds if root-cause of issues is not found;

1) set bootstrap pins to get ROM into bootstrap mode; The WD will have a timeout of 1s to allow JTAG to connect.
2) Need to create a test_unlocked0 OTP image  with ROM_EXEC disabled. This can be done as an additional overlay for the specific test in question.
3) Load a properly signed image that doesn’t do anything: while(1). idle_test.c

**Comment by johngt** [comment] 2023-05-08 16:42
@moidx / @msfschaffner for visibility.

**Comment by johngt** [comment] 2023-05-08 21:08
Thanks for the updates @pamaury - flagging to @moidx / @msfschaffner - given the importance.

**Comment by msfschaffner** [comment] 2023-05-12 20:41
@moidx do we still want to keep this open, given that the RV_DM issue has been root caused?

**Comment by moidx** [comment] 2023-05-12 22:44
Sounds good. Closing for now, we can use this issue for reference later.

**Closed** 2023-05-12 22:44 UTC
Labels: Component:DV, Priority:P1, IP:rv_dm, Submilestone:M2.5.1
