### ISSUE TITLE
[hmac, rtl] Expose `Idle` status of HMAC

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#22916] opened 2024-05-01 14:08 UTC
### Description

Related to https://github.com/lowRISC/opentitan/issues/22731.

I am working on HMAC driver, and I realized that SW does not have a good visibility on what is going on in HMAC IP. In particular, I was not able to figure out:

- how to check if HMAC is still active,
- when active, if there is a way to discard the ongoing operation.

At the driver level, we usually have a function to check the availability of the IP before continuing with the operation (just to be safe). For instance, we have the following function, which is supposed to discard whatever is going on in HWIP, so that we can run HMAC with the current request:

https://github.com/lowRISC/opentitan/blob/e9925bdf1464e9cec8ab8931c108cee4acb2709b/sw/device/lib/crypto/drivers/hmac.c#L18-L40

Would it be possible to have `Idle` bit in `STATUS` register, as we have in [KMAC](https://opentitan.org/book/hw/ip/kmac/doc/registers.html#status--sha3_idle)? Also, what is the correct way to flush the ongoing operation in HMAC? As far as I see, deasserting `sha_en` as above does not work because CFG register is gated with internal FSM signals.

Not having visibility is a bit of problem, because with streaming, we are potentially looking at two HMAC calls that interleave each other, and we need to know if HMAC is occupied.

cc: @gdessouky @andreaskurth @martin-velay @jadephilipoom

**Comment by martin-velay** [comment] 2024-05-01 14:51
Hi Fatih,

What you are looking for might be the [hmac_done](https://opentitan.org/book/hw/ip/hmac/doc/registers.html#intr_state--hmac_done) interrupt. I have checked with a simulation and in the RTL: [hmac_core.sv](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/hmac/rtl/hmac_core.sv;l=426-431)
Is that enough for your application?

The Idle is also transmitted as an output signal of the HMAC, I think for power gating purpose but I don't really know if this is made visible to the SW at any other stage as such.

BR,
Martin

**Comment by ballifatih** [comment] 2024-05-02 09:51
Hi @martin-velay. Yes I am aware of `hmac_done` interrupt. Although this is useful, it does not quite address what I need.

Upon entering driver functions (i.e. hmac_init, hmac_update, hmac_final), the first thing to check is to ensure that HMAC IP is in ready state. `Idle` bit would indicate whether HMAC is in clean/ready state, otherwise the driver function can decide to wait or clear HMAC IP. In this context, `hmac_done` cannot be used, because it will not be raised in erroneous states or when HMAC is waiting for further message bytes to be written in MSG_FIFO. Driver functions are stateless, so they are not keeping track of HMAC HW status.

One could argue that these driver functions can always make sure to leave HMAC in ready state and clean after themselves before returning to their caller. That would guarantee that upon entry to driver functions, HMAC is in clean/ready state. This is already the current idea. But relying on only this assumption makes the driver very fragile.

**Comment by gdessouky** [comment] 2024-05-02 12:27
I think the current assumption, up until now, has been that the driver functions leave HMAC in a ready (idle) state (after `hmac_done` or another error is raised), but this was also an easier assumption to maintain since there was no context switching supported.  Is the purpose here to check for state to decide whether to wait or already call `hmac_halt`?

In any case, this did occur to me when adding the RTL for signalling invalid configuration errors, because then there will be no `hmac_done`, only an error to SW and HMAC stays idle. So it can only be useful for the SW to expose the Idle status. Does anyone see reason not to? 

Dasserting `sha_en` is the intended way to clear/flush the ongoing operation and bring the HMAC back to ready (idle) state - why do you think this wouldn't work as intended?

**Comment by gdessouky** [comment] 2024-05-02 17:04
> I think CFG register is gated with `cfg_block` signal in the top level of HMAC, which means that if HMAC is in a state where it is waiting for SW to write more bytes to MSG_FIFO, then setting `sha_en` to 0 will be ignored. So we do not have a reliable way of forcing HMAC to discard and become ready. If we know the state of HMAC, then we could at least trigger stop or process accordingly.
> 

Yes, my bad. Deasserting `sha_en` clears the SHA-2 engine but it is blocked at the HMAC top-level until `cfg_block` is deasserted. But this is reliable, because what prevents SW thread B from disabling the IP at any point in time and flushing the computation for SW thread A and denying it service? Things get tricky with the context switching...

We need `Idle` exposed to SW, then at least status can be checked indeed. But what happens if the IP is not idle and SW thread B wants to use the IP? It should actually not be allowed to trigger stop/process to the IP when it is computing for thread A. Do we rely on a timeout?

**Comment by cdgori** [comment] 2024-05-02 17:50
Agreed that `Idle` should be exposed.  But, I think we need some kind of semaphore/mutex to handle access to the HMAC across multiple threads now that save/restore is possible.

**Comment by andreaskurth** [comment] 2024-05-14 18:37
Exposing Idle to SW SGTM. A semaphore/mutex for HMAC access arbitration between different SW threads is definitely a problem to be solved in SW, though ;-)

Adding flush functionality is out of scope at this point (we're long past the M2 deadline).

**Comment by andreaskurth** [comment] 2024-05-22 06:26
After the `idle_o` output during save & restore is fixed (#23233), we should be able to expose it in a CSR status bit to resolve this issue

**Comment by martin-velay** [comment] 2024-05-27 15:54
Hi,
I think there is still a bug. The idle_o is not moving into "true" in the case exposed in the screenshot below as it should.
![image](https://github.com/lowRISC/opentitan/assets/165653139/73133714-414f-4d6c-9308-ba5f92c89ec1)

I have a fix to propose for that: PR #23336

**Comment by martin-velay** [comment] 2024-06-03 06:54
RTL change has been done #23242  and fixed #23432 

This issue could be closed, but note that **this register will be tested later** as mentioned #23380

**Closed by martin-velay** 2024-06-03 06:54 UTC
Labels: IP:hmac, SW:cryptolib, prodc-integration
