### ISSUE TITLE
[test-triage] rom_keymgr_functest timeout

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16353] opened 2022-11-15 11:48 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out has 3 failures:

Test rom_keymgr_functest has 3 failures.
0.rom_keymgr_functest.1782056684
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.rom_keymgr_functest/latest/run.log

  Job ID: smart:8f62bf14-6e2a-4179-a688-4273fc0e7596
1.rom_keymgr_functest.812360938
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.rom_keymgr_functest/latest/run.log

  Job ID: smart:fe94bd45-cd1c-4ec7-a057-d29485e4b5c8
... and 1 more failures.
```

### Steps to Reproduce

- GitHub Revision: [47d4bfa34](https://github.com/lowrisc/opentitan/tree/47d4bfa34b424d29fcaf2d13e2a64ce1bd815ec7)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i rom_keymgr_functest --build-seed 4006484429 --fixed-seed 1782056684 --waves fsdb

### Tests with similar or related failures

- [ ] chip_sw_rom_functests

**Comment by johngt** [comment] 2022-11-15 11:50
This test is failing consistently with timeouts.
Would suggest increasing the timeout and seeing if this then passes once that has been increased.

|     | Tests               |   2022-11-14 08:10:42 |   2022-11-13 08:12:54 |   2022-11-12 08:04:45 |   2022-11-11 08:07:48 |   2022-11-10 08:10:06 |   2022-11-09 08:04:06 |   2022-11-08 08:03:42 |   2022-11-07 08:08:10 |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 | Suite                 |
|----:|:--------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:----------------------|
| 231 | rom_keymgr_functest |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 | chip_sw_rom_functests |

@weicaiyang / @cindychip - tagging on-call triage

**Comment by ballifatih** [comment] 2022-11-15 11:57
Correct me if I'm wrong, but I think that this is fixed by #16340. I think since we just merged it yesterday, it hasn't passed through the nightly yet.

**Comment by ballifatih** [comment] 2022-11-15 12:15
Also linked to ##16060 (for visibility).

**Comment by johngt** [comment] 2022-11-15 12:38
Thanks @ballifatih ! Let's leave this issue open for 3 regression runs and hope that the fixes resolve the issues

**Comment by ballifatih** [comment] 2022-11-18 20:16
It seems like this passed the last 4 regression runs, so I'm closing the issue.

**Closed by ballifatih** 2022-11-18 20:16 UTC
Labels: Component:TestTriage
