### ISSUE TITLE
[spi_device] Assertion DataFlow_A from prim_arbiter firing when issuing byte by byte in TXRX test

### ISSUE THREAD

**Issue by kosta-kojdic** [lowRISC/opentitan#9119] opened 2021-11-09 16:30 UTC
We have encountered these errors repeating in spi_device test:

xmsim: *E,ASRTST (/scratch/google/goo_opentitan/kostak/master/spi_device-sim-xcelium/default/src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_ppc.sv,167): (time 676807289 PS) Assertion tb.dut.u_fwmode.u_fwmode_arb.gen_arb_ppc.u_reqarb.gen_data_port_assertion.DataFlow_A has failed
                UVM_ERROR @ 676807289 ps: (prim_arbiter_ppc.sv:167) [ASSERT FAILED] DataFlow_A
                xmsim: *E,ASRTST (/scratch/google/goo_opentitan/kostak/master/spi_device-sim-xcelium/default/src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_ppc.sv,167): (time 688047289 PS) Assertion tb.dut.u_fwmode.u_fwmode_arb.gen_arb_ppc.u_reqarb.gen_data_port_assertion.DataFlow_A has failed
                UVM_ERROR @ 688047289 ps: (prim_arbiter_ppc.sv:167) [ASSERT FAILED] DataFlow_A

This happens when I run txrx test with the only modification being in task process_spi_xfer: spi_host_xfer_bytes is called with only 1 byte always, not randomized number of bytes as in txrx test.

**Comment by eunchan** [comment] 2021-11-09 16:41
in the dumped waveform, I can see the assertion failure due to the unknown values:

![image](https://user-images.githubusercontent.com/1192814/140965744-af2ac730-199d-4ae1-9ef5-8df10cc58088.png)

The unknown value comes from DPSRAM as `spi_fwm_rxf_ctrl` does read-modify-write for partial write (in this case 1 byte).

https://github.com/lowRISC/opentitan/blob/master/hw/ip/spi_device/rtl/spi_fwm_rxf_ctrl.sv#L163

As DPSRAM is not initialized, this seems to be understandable scenario. In this case we could choose either three fixes:

1. Revise the assertion to ignore unknown.
2. Revise FW Mode RXF CTRL to support Byte Enable on DPSRAM interface. The Byte Enable has been added after FWMode was designed.
3. Add DPSRAM initialization (write 0) to DV init code.

CC: @tjaychen @weicaiyang

**Comment by tjaychen** [comment] 2021-11-09 17:45
i feel like either 1 / 2 is more desirable.
Mostly because I worry that 3 could mask issues by making the memory all
0's (which is probably not a realistic value anyways).

Would 2 be difficult to do Eunchan? I know the tlul_adapter_sram stuff for
example use the read mask to 0 out bytes the source doesn't care about, but
I guess this is hardware direct access and not through tlul?

**Comment by eunchan** [comment] 2021-11-09 17:57
> i feel like either 1 / 2 is more desirable. Mostly because I worry that 3 could mask issues by making the memory all 0's (which is probably not a realistic value anyways). Would 2 be difficult to do Eunchan? I know the tlul_adapter_sram stuff for example use the read mask to 0 out bytes the source doesn't care about, but I guess this is hardware direct access and not through tlul?
>
Thanks for the comment Tim.

I think for long term, as we remove the restriction of the word write to DPSRAM, option 2 is best in terms of efficiency. It removes the timer feature on SPI Generic mode and Read-modify-write operation too. But I think it is not worth to change the design and re-spin the DV testbench. 

So, Let me dig the assertion how to waive the unknown value.

**Comment by weicaiyang** [comment] 2021-11-09 19:10
option 1 and 2 look good to me too.
For option2, we haven't done too much on testing byte granularity transfer. It's fine if you want to make the design change.
For option3, not sure whether it's a concern if we initialize DPSRAM to random values

**Comment by tjaychen** [comment] 2021-11-09 19:49
sounds good! Thanks Eunchan.

**Comment by eunchan** [comment] 2021-11-10 18:34
The issue has been resolved in #9130. Let me close this

**Closed by eunchan** 2021-11-10 18:34 UTC
Labels: Component:RTL
