### ISSUE TITLE
[rom_ext,csrng] Fix rom_ext for pending csrng interrupt

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#20747] opened 2024-01-02 22:31 UTC
### Description

The test //sw/device/tests/autogen:plic_all_irqs_test_0 fails for both fpga_cw310_sival_rom_ext and silicon_owner_sival_rom_ext. 

The failure is for peripheral 19 (kTopEarlgreyPlicPeripheralAdcCtrlAon): rather than 19 the test gets peripheral 27 (kTopEarlgreyPlicPeripheralCsrng), and interrupt 174 (kTopEarlgreyPlicIrqIdCsrngCsEntropyReq).

Apparently the interrupt happens right after peripherals_irqs_enable https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/autogen/plic_all_irqs_test.c;drc=e5b074b89ee185a45a1008415cc6839a14a033ad;l=2111 , since a call to LOG_INFO after that and before peripheral_irqs_trigger is not run. It seems there is a pending interrupt from csrng upon test entry, so I suspect the rom_ext leaves it pending.

ADC is the first peripheral in the test, so it makes sense it would be the one to fail, and the fact that both fpga_cw310 and silicon running with rom_ext fail the same way suggests it is a rom_ext issue.

**Comment by pamaury** [comment] 2024-04-12 22:06
Can you check if #22525 fixes this issue? I am not entirely sure it's related but it's worth a try.

**Comment by vogelpi** [comment] 2024-05-01 11:26
The root cause for this bug is most likely #22877 (similar as for #22819).

**Comment by vogelpi** [comment] 2024-05-09 13:08
I just re-ran the test on the FPGA `//sw/device/tests/autogen:plic_all_irqs_test_0_fpga_cw310_sival_rom_ext`. It's working both on `master` (622018b25190bc6129f6495edc98dec642b6c037) and `earlgrey_es_sival` (7f1ef1c112fbdb0e5b3dab8030044a4c21d2c946). It seems that the keymgr related fixes linked in the previous post indeed solve this issue.

I am closing this issue.

**Closed by vogelpi** 2024-05-09 13:08 UTC
Labels: Priority:P1, Type:Bug, SW:ROM_EXT, Component:SiliconValidation

**Comment by vogelpi** [comment] 2024-05-09 14:29
FYI: @nasahlpa also check the test on silicon where it's working now as well :-)
