### ISSUE TITLE
[csrng] SW instance instantiate command hangs after entropy complex initialization

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#19568] opened 2023-08-31 21:54 UTC
### Description

In https://github.com/lowRISC/opentitan/pull/19548 we observed a hang when trying to run the `csrng` instantiate command right after initializing the entropy complex in continuous mode. 

The current workaround is to check for the `MAIN_SM_STATE` register to report `MainSmIdle` state before issuing any commands to the `csrng` interface. Checking the [`SW_CMD_STS`](https://opentitan.org/book/hw/ip/csrng/doc/registers.html#sw_cmd_sts) `CMD_RDY` flag does not seem to help. 

During debugging we noticed that the main FSM gets stuck in `MainSmParseCmd` when the instantiate command is sent before the FSM is in `MainSmIdle` state. We'll have to reproduce the test in simulation to be able to debug further.

**Comment by moidx** [comment] 2024-02-10 02:22
CC @vogelpi

**Comment by vogelpi** [comment] 2024-02-12 09:44
Thanks @moidx for pinging me. @h-filali recently reworked the SW_CMD_STS register for EDN to fix issues similar to that in EDN and I think for PROD will want to do the same for CSRNG, too. For now, I am assigning the two of us.

**Comment by vogelpi** [comment] 2024-03-04 10:06
This is to be investigated after taking care of #16516 . Ideally, software then has the necessary information and the workaround in the cryptolib can be removed.

**Comment by h-filali** [comment] 2024-03-26 14:23
I think the issue was due to the cmd_rdy signal being high when the CSRNG wasn't turned on yet. I already fixed this in #21981 because this looked a bit off.
I created [#22263](https://github.com/lowRISC/opentitan/pull/22263) to remove the added line for the workaround from the entropy.c file.
@pamaury would you mind checking again once #22263 is merged?

**Closed** 2024-04-22 21:44 UTC
Labels: Component:DV, Type:Bug, Type:Enhancement, Component:RTL, Subsystem:Entropy, IP:csrng

**Comment by vogelpi** [comment] 2024-04-23 12:21
FYI @pamaury , @h-filali  and I tested:
- `//sw/device/tests/crypto:drbg_functest_fpga_cw310_rom_with_fake_keys` and
- `bazel test --test_output=streamed //sw/device/tests/crypto:drbg_functest_fpga_cw310_sival_rom_ext`

with the latest hardware and after removing the workaround (what resolved this issue). The tests are still passing. So, the issue is indeed resolved now.
