### ISSUE TITLE
[i2c] V2(S) Signoff

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22108] opened 2024-03-19 14:24 UTC
Ensure V2(S) signoff criteria are fulfilled.

This issue tracks V2(S) signoff for the M5-scoped components of the I2C hwip. As such, this is not a full signoff, but a signoff with qualifiers. The qualifying conditions can be seen in the following [linked thread comment](https://github.com/lowRISC/opentitan/issues/22108#issuecomment-2225759494). (And are also linked in the `i2c.hjson` file 'revisions' section under 'Notes'). The lightweight signoff template has also been completed in the [following comment](https://github.com/lowRISC/opentitan/issues/22108#issuecomment-2152850795) for the scoped features.

---

Signoff Meeting Notes (OpentitanACL)
- [Meeting Notes 06/06/24](https://docs.google.com/document/d/1559GiZe9Ada32IDraXT2mtv5NJawHpdcBVRh80zxBqQ/edit) 
- [Meeting Notes 05/07/24](https://docs.google.com/document/d/17qnLpGPr_dJs0denJ8p-iY8bJmJ2MpVAYv9e1tkxWhQ/edit#heading=h.4pl5f3fnl2sb)

---

Depends on items captured in the following issues to close:
- [x] #23077 

Effort tracked here is just for further signoff admin.

**Comment by rswarbrick** [comment] 2024-03-21 12:55
I've set up "pretend meeting review notes" [here](https://docs.google.com/document/d/1VXJUi7edxKygUOZwDiCh_1APMHRiICAMIhcKGdBj6Sk/edit), which is hopefully the leg-work needed for signing off the block as v1.

I believe the main work item remaining is to tweak the testplan to reflect design changes that have come in since the ES tapeout. This task is tracked as #22168.

**Comment by moidx** [comment] 2024-06-11 21:22
Discussed moving as P1 to M5 due to RTL risk analysis performed during last issue triage.

**Comment by hcallahan-lowrisc** [comment] 2024-07-12 14:51
The [above V2(S) review comment](https://github.com/lowRISC/opentitan/issues/22108#issuecomment-2152850795) follows the [lightweight signoff process](https://docs.google.com/document/d/1ZaM2SpZjsBO5Aaj0Lai7LE5wR5osp6StDQAEUQJPfDE/edit#heading=h.ee574932an4y) for a V2(S) level signoff, but as agreed and discussed, this signoff does not meet the full signoff critera due to the addition of new RTL features at a late point in the overall development timeline. 

**Importantly**, the following qualifying critera apply:
> This V2(S) signoff only targets the features categorized for the M4 milestone, which includes testplan updates up to https://github.com/lowRISC/opentitan/pull/22337. Changes subsequent to this are considered out of scope for this issue, and will be addressed in a future signoff without any qualifying statements.

### Features out-of-scope for this signoff

#### - Testpoints applicable to the following new RTL features
 - #22345
 - #22459
 - #22460
 - #22551
 - #22864
 - #22865
 - #22872
- Testpoints for these features were added in the following changes : https://github.com/lowRISC/opentitan/pull/23073
  - target_mode_n_byte_ack_control
  - target_mode_bus_timeout
  - controller_mode_bus_timeout
  - controller_mode_bus_idle_delay
  - loopback_test _(Controller-Mode and Target-Modes active simultaneously, with external loopback)_
  - multi_controller_clock_synchronization
  - multi_controller_arbitration_lost_interference
  - multi_controller_arbitration_lost
  - target_mode_arbitration_lost_interference
  - target_mode_arbitration_lost
#### - Functional Coverage applicable to the new testpoints
#### - Code Coverage of RTL directly contributory to the new features only

### Confidence-level based on this qualified signoff

By definition, this signoff cannot opine about the verification confidence in the new RTL features.
However, we can draw conclusions about the state of the base-set functionality. This boils down to a few specific questions:
  - Does the presence of new functionality affect the base-set functionality in any way?
  - Has the behaviour of the base-set functionality regressed due to the addition of these new features?

The following evidence supports the assertion that we are sufficiently confident to signoff to this qualified level.:

1. _New features since ES to the base-set I2C features have been verified, as scoped in the [testplan update PR](https://github.com/lowRISC/opentitan/pull/22337)._
    - This functionality has been exercised in DV, with all testpoints implemented.
    - This has entailed some changes to the programming model, which has been updated across DIFs, software tests and documentation.

2. _Existing testpoints are still covered, with regressions passing to V2(S) thresholds, and ccov/fcov also meeting the requisite thresholds._
    - Note. sans-merge of #23987
    - Note. Some ccov related to RTL changes for new features is missing. This is to be expected, but has been checked in a signoff review context (see notes linked above).

3. _Top-level tests, integration tests (e.g. Breakout-Board tests against real I2C devices) have not shown any regressions against ES-behaviour._

4. _New functionality has been added behind enables and feature flags that leave them disabled, unused or maskable._
    - n_byte_ack control mode -> Enabled by !!CTRL.ACK_CTRL_EN
    - {controller,target}_mode_bus_timeout -> Enabled by configuring !!TIMEOUT_CTRL.MODE to the non-default value 'BUS_TIMEOUT'
    - controller_mode_bus_idle_delay -> Enabled by !!CTRL.MULTI_CONTROLLER_MONITOR_EN
    - multi_controller_{clock_synchronization,arbitration_lost} -> Stimulated by multi-controller bus environment
    - target_mode_arbitration_lost -> Stimulated by multi-controller bus environment

**Comment by rswarbrick** [comment] 2024-07-12 16:14
Thanks for the careful write-up. I'm convinced and happy that it's correct. I propose you send a PR updating the development stage in the hjson, with a note in the checklist about the limited scope ("we have only verified XYZ").

**Comment by hcallahan-lowrisc** [comment] 2024-07-13 22:31
I've updated the signoff checklist comment above, based on the merger of #23987 and #24010. This includes updating the note. about low FSM coverage based on a review of the local 10-seed All-Once regression I ran to support #23987, and the review discussion where it was agreed this was acceptable.
I've also ticked the boxes for ccov/fcov based on the results of the regression in #23987, as I am confident once we run a full 50-seed nightly regression these numbers will creep up above the thresholds. Based on a manual review of the coverage report, I did not see anything to cause me concern.

As such, I think this is ready to signoff by merging #24011. Though if we wished to wait for a nightly regression to confirm the coverage metrics, that would also be acceptable.

**Closed** 2024-07-14 08:26 UTC
Labels: Component:DV, IP:i2c, Type:Signoff
