### ISSUE TITLE
[test-triage] `flash_ctrl_derr_detect`

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#23941] opened 2024-07-05 15:13 UTC
### Hierarchy of regression failure

Block level

### Failure Description

`  UVM_ERROR @ 38893.8 ns: (flash_ctrl_scoreboard.sv:863) [uvm_test_top.env.scoreboard] Check failed item.d_error == 1 (0 [0x0] vs 1 [0x1]) On interface flash_ctrl_eflash_reg_block, TL item: req: (cip_tl_seq_item@154455) { a_addr: 'ha8a4  a_data: 'h0  a_mask: 'hf  a_size: 'h2  a_param: 'h0  a_source: 'h5  a_opcode: 'h4  a_user: 'h24c2a  d_param: 'h0  d_source: 'h5  d_data: 'h29e6002b  d_size: 'h2  d_opcode: 'h1  d_error: 'h0  d_sink: 'h0  d_user: 'hd43  a_source_is_overridden: 'h0  a_valid_delay: 'h0  d_valid_delay: 'h0  a_valid_len: 'h0  d_valid_len: 'h0  req_abort_after_a_valid_len: 'h0  rsp_abort_after_d_valid_len: 'h0  req_completed: 'h0  rsp_completed: 'h0  tl_intg_err_type: TlIntgErrNone  max_ecc_errors: 'h3  }
  , ecc_err:1 in_err:0
  UVM_INFO @ 38893.8 ns: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---`

### Steps to Reproduce

- GitHub Revision: [3e678c112b](https://github.com/lowrisc/opentitan/tree/3e678c112b9a2035585c34800ca4d85fcf4152b6)
- Build seed: 94940390549829454688103081328166376218078465228811124044523808815554354133843

**Comment by vogelpi** [comment] 2024-07-05 15:45
This seems to be related to #23871. Since this PR was merged, this test has a pass rate of 0%. The last regression before this PR has a pass rate of 100% for this test. @matutem are you able to look into this once you're back, please?

**Closed** 2024-07-26 04:21 UTC
Labels: Component:TestTriage
