### ISSUE TITLE
[spi_device] When and how should SW read cmdfifo, addrfifo, and payload buffer for correct data?

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#11871] opened 2022-04-04 13:20 UTC
* spi_device should have a bit that indicates the completion of a SPI transaction and the FIFOs & the payload buffer are ready to be read from.
  * It looks like `cmdfifo_notempty` and `addrfifo_notempty` are updated independently during a SPI transaction.
  * According to the spec, `upload_payload_not_empty` in `INTR_STATE` register is updated after the transaction ends but it's not useful for commands without payloads.
  * `csb` in the `STATUS` register can possibly be used to check if a SPI transaction is complete but it is not clear whether sw can read from the FIFOs and the payload buffer right away.

* spi_device should ensure that values read from cmdfifo, addrfifo and payload are consistent with each other, e.g. they should always reflect the last transaction.
  * The address read from the address FIFO could belong to any command in the command FIFO (some commands don't have address fields), and similarly for the payload.
  * Please see [this thread](https://github.com/lowRISC/opentitan/pull/11884#discussion_r842004669).

cc @cfrantz @a-will

**Comment by a-will** [comment] 2022-04-04 15:13
> csb in the STATUS register can possibly be used to check if a SPI transaction is complete but it is not clear whether sw can read from the FIFOs and the payload buffer right away.

That will lead to race conditions, since `csb` may be asserted most of the time to check the BUSY bit. I wouldn't recommend that option. :)

For a hardware solution that may not have the nicest tracking, we could take the sys_clk-sampled csb and `cmdfifo_notempty` and use them to create "command upload done" signal. So, something like...

```systemverilog

always_comb begin
  command_upload_done_d = command_upload_done_q;
  if (!sys_cmdfifo_notempty_o) begin
    command_upload_done_d = 1'b0;
  end else if (sys_csb_deasserted_pulse_i && sys_cmdfifo_notempty_o) begin
    command_upload_done_d = 1'b1;
  end
end

always_ff (posedge sys_clk or negedge sys_rst_ni) begin
  if (!sys_rst_ni) begin
    command_upload_done_q <= 1'b0;
  end else begin
    command_upload_done_q <= command_upload_done_d;
  end
end
```

So the "done" status gets cleared as soon as the command FIFO is emptied. This assumes that `sys_csb_deasserted_pulse_i` asserts no sooner than `sys_cmdfifo_notempty_o` (a critical timing requirement to catch the event). Otherwise, we'd want to delay that pulse until the requirement is met.

**Comment by eunchan** [comment] 2022-05-11 22:34
I think the most viable solution is to generate interrupt at every SPI transaction, until the FIFO becomes empty. If the HW wants to generate a one time pulse interrupt when FIFO is not empty.

**Comment by eunchan** [comment] 2022-05-11 22:38
Is this (getting interrupt at every transaction until FIFO becomes empty) OK to SW? Then I can revise design in this way.

**Comment by alphan** [comment] 2022-05-16 14:40
Discussed this offline with @eunchan. I believe hw changes in #12614 and sw changes in #12672 should resolve this but couldn't verify this yet due to CI issues. I'll close this issue once I do that.

**Comment by alphan** [comment] 2022-05-16 15:48
@eunchan I've just tried to print the spi flash command opcode using both changes and this is what I observed:
* For chip_erase (`0xc7`) and sector_erase (`0x20`), I first get a `0x00` followed by the expected cmd opcode. It feels like IRQ bit is set twice?
* For page_program (opcode: 0x02), I get `0x00` or `0x20`. I'm not sure where the wrong value comes from, may be some stale data in a buffer somewhere.

I'll keep looking but wanted to ask if these were expected HW issues.

**Comment by eunchan** [comment] 2022-05-16 15:53
> @eunchan I've just tried to print the spi flash command opcode using both changes and this is what I observed:
> 
> * For chip_erase (`0xc7`) and sector_erase (`0x20`), I first get a `0x00` followed by the expected cmd opcode. It feels like IRQ bit is set twice?
> * For page_program (opcode: 0x02), I get `0x00` or `0x20`. I'm not sure where the wrong value comes from, may be some stale data in a buffer somewhere.
> 
> I'll keep looking but wanted to ask if these were expected HW issues.

Definitely not expected. I will revise the sim to test the scenario. Thanks for the tests!

**Comment by alphan** [comment] 2022-05-16 15:58
> FYI, the logic that uploads the command opcode to the FIFO was not changed nor the FIFO pointers itself. If interrupt occurs twice, (yes possible if SW didn't fetch CMDFIFO but clears interrupt) the first entry should be the expected OPCODE and the next one is empty (`0x00`).

Ah, sw currently clears the interrupt before reading the fifo because I didn't expect that it would matter. I'll move the clear to the end of the function after everything is read and try again. Thanks!

**Comment by eunchan** [comment] 2022-05-16 16:13
> > FYI, the logic that uploads the command opcode to the FIFO was not changed nor the FIFO pointers itself. If interrupt occurs twice, (yes possible if SW didn't fetch CMDFIFO but clears interrupt) the first entry should be the expected OPCODE and the next one is empty (`0x00`).
> 
> Ah, sw currently clears the interrupt before reading the fifo because I didn't expect that it would matter. I'll move the clear to the end of the function after everything is read and try again. Thanks!

Yep.. That is unfortunate side-effect of this change. To delay, the logic cannot use the SYS_CLK fifo empty. Hum, Maybe I can find a way to raise interrupt just once. Let me think about it.

**Comment by eunchan** [comment] 2022-05-16 16:27
> > > FYI, the logic that uploads the command opcode to the FIFO was not changed nor the FIFO pointers itself. If interrupt occurs twice, (yes possible if SW didn't fetch CMDFIFO but clears interrupt) the first entry should be the expected OPCODE and the next one is empty (`0x00`).
> > 
> > 
> > Ah, sw currently clears the interrupt before reading the fifo because I didn't expect that it would matter. I'll move the clear to the end of the function after everything is read and try again. Thanks!
> 
> Yep.. That is unfortunate side-effect of this change. To delay, the logic cannot use the SYS_CLK fifo empty. Hum, Maybe I can find a way to raise interrupt just once. Let me think about it.
>
Ah.. I wrote down the feasibility into my note. It is not possible, due to the OP complete commands (CHIP ERASE, BLOCK ERASE,...). There's no time the interrupt detects edge in this case if the commands come back to back.

**Comment by tjaychen** [comment] 2022-05-16 16:58
@alphan 
@eunchan 
this might be related to the other issue where you were discussing this, but are we really seeing CHIP_ERASE / SECTOR_ERASE back to back..? I would think the BUSY polling would be in-between.

@eunchan 
i might be misremembering here, but i thought you only create the interrupt based on the CSb rising event in case something is uploaded, if that's the case, why would there be multiples? let me know what i'm missing.

**Comment by alphan** [comment] 2022-05-16 17:07
> this might be related to the other issue where you were discussing this, but are we really seeing CHIP_ERASE / SECTOR_ERASE back to back..? I would think the BUSY polling would be in-between.

No, I see an erase command followed by `0x00`, which I think because the sw clears the intr_state register before reading from the cmdfifo.

**Comment by alphan** [comment] 2022-05-16 17:26
I moved the clearing of INTR_STATE to the end of `spi_device_cmd_get()` and here is what I get:

* host sends `CHIP_ERASE` (opcode `0xc7`) to the spi_device, `spi_device_cmd_get()` returns command opcode `0xc7`,
* host sends `READ_STATUS` (opcode `0x05, should be handled by the hardware) to the spi_device, `spi_device_cmd_get()` returns command opcode `0x00`.
* subsequent `READ_STATUS` commands sent to spi_device do not cause `spi_device_cmd_get()` to return.

**Comment by eunchan** [comment] 2022-05-16 17:33
> @alphan @eunchan this might be related to the other issue where you were discussing this, but are we really seeing CHIP_ERASE / SECTOR_ERASE back to back..? I would think the BUSY polling would be in-between.
> 
> @eunchan i might be misremembering here, but i thought you only create the interrupt based on the CSb rising event in case something is uploaded, if that's the case, why would there be multiples? let me know what i'm missing.
>
The multiple in this context is, when SW didnt pop the entry from the FIFO. The logic creates a pulse again at the next SPI transaction. The logic inside SCK cannot see if the interrupt is cleared by SW or not. Just keep creating events if the FIFO is not popped.

**Comment by eunchan** [comment] 2022-05-16 17:37
It may be considered same as use level signal as event. But the logic should not create a level. If SW pops the entry from CMD_FIFO and the next command is also upload command, then the level stays high. SW could not detect if the command is uploaded or not correctly.

**Comment by eunchan** [comment] 2022-05-16 17:37
> Also, the command opcode that I read from UPLOAD_CMDFIFO register after sending a PAGE_PROGRAM (`0x02`) command is still invalid (I seem to read back something stale like `0xc7`).

Sorry for making this complicated. Let me prepare full SPI_DEVICE IP level test for this. The previous test I did was in spid_upload module level pre_dv. I think I should make this to full IP level test to catch this issue.

**Comment by eunchan** [comment] 2022-05-17 00:28
Here's findings:

- After chip erase, I popped the FIFO entry and cleared the interrupt. I don't see any further interrupts so far. I need to think about a little bit deeper how ghost interrupt may occur.
- Page Program, as the opcode(`0x02`) is adjacent to Normal Read (`0x03`) I see an issue on the mux. the DP select signal is latched by SPI out clock (inverted SCK). So, when opcode is written, the mux is not switched to the upload module yet. I think I need to revise the mux to property change to upload module OR make command upload to happen in cmdparse module rather than upload module.

I will dig more. This could not be caught in pre_dv test as it does not have the mux at all :(

**Comment by tjaychen** [comment] 2022-05-17 01:16
hey @eunchan let me know if you want any help brainstorming or anything :)

**Comment by eunchan** [comment] 2022-05-17 17:22
I hope #12717 addresses the `Page Program` issue. I am still not sure how the `Read Status` issue happens. I may play with the latency of checking the `Chip Erase` command from SW so that there maybe a race condition or not. @alphan Is that issue consistent? (100% reproducible?)

**Comment by alphan** [comment] 2022-05-17 17:25
> I hope #12717 addresses the `Page Program` issue. I am still not sure how the `Read Status` issue happens. I may play with the latency of checking the `Chip Erase` command from SW so that there maybe a race condition or not. @alphan Is that issue consistent? (100% reproducible?)

Yes, it was quite reproducible for me. I can give it another try when trying the bitstream of #12717 and let you know if I notice any changes.

**Comment by eunchan** [comment] 2022-05-17 17:29
If the value is consistently `0x00` then it is the second interrupt for the first Chip Erase command. I think clearing the interrupt status or fetching the entry from the CMDFIFO has issues..

**Comment by alphan** [comment] 2022-05-17 17:33
> If the value is consistently `0x00` then it is the second interrupt for the first Chip Erase command. I think clearing the interrupt status or fetching the entry from the CMDFIFO has issues..

Yes, the value is consistently `0x00`. I've been working around both of these issues with a simple local patch. For what we suspect to be an extra interrupt, ignoring the command if `cmd.opcode == 0x0` works reliably.

**Comment by eunchan** [comment] 2022-05-17 17:35
How did you WA the `Page Program` issue? I think as long as we enable WREN/ WRDI, this issue should occur for every `Page Program`.

**Comment by alphan** [comment] 2022-05-17 17:38
> How did you WA the `Page Program` issue? I think as long as we enable WREN/ WRDI, this issue should occur for every `Page Program`.

Correct, but during bootstrap we don't really expect any command other that PAGE_PROGRAM to have payload. So, I just set cmd.opcode to 0x02 if there is a payload.

**Comment by alphan** [comment] 2022-05-18 19:56
@eunchan, I tried the bitstream of this [run](https://github.com/lowRISC/opentitan/runs/6495040901). It looks like the issue with page program is resolved: I get 0x02 instead of 0x00. But, the ghost interrupt issue remains, i.e. read_status command results in an interrupt even though it's handled by hw.

**Comment by eunchan** [comment] 2022-05-18 20:55
@tjaychen gave some hints of possible scenario.

@alphan if somehow SPI chip select has glitches, this issue may occur. If CSb asserted without SPI clock, the interrupt indicator remains high at the CSb release. It then triggers the `cmdfifo_notempty` interrupt without CMDFIFO entry. It is due to the status is reset by CSb asserted pulse signal not by CSb assertion (1->0).

To prove this hypothesis, could you run modified tests? If the assumption is correct, the cmdfifo_notempty occurs always after the actual command upload. 

So, if sequence is like: `CHIP ERASE` -> 2X `READ STATUS` -> `PAGE PROGRAM` -> 2X `READ STATUS`, then the first `READ STATUS` among two commands always see the `cmdfifo_notempty`.

Or, if your logic analyzer has some kind of b-trigger (counting the second or following event not the first trigger event), then we can catch the /CS glitch.

Thanks @tjaychen !

**Comment by alphan** [comment] 2022-05-20 16:25
Thanks for the update @eunchan. I had to wait for the CI to get a bitstream from #10874 to be able to use my logic analyzer.

Here is what I found:
* AFAICT, there is no glitch on the CSb line.
* However, I didn't see any ghost interrupts when I tried the sequence that you recommended.
* I've been using a very simplified version of `cw_spifash.py` to send individual spi flash commands to test things. I debugged further to understand why I see these ghost interrupts when I send `CHIP_ERASE` and `READ_STATUS` individually, i.e. invoke the script for each command, but I don't see them when I send these commands back to back in a single invocation. Currently, my best guess is that the part that initializes the pins of SAM3X, more specifically, the two lines that call `pin_set_output()` [here](https://github.com/lowRISC/opentitan/blob/dad98a7b6e7ad69a815442402c4e15206c689fad/util/fpga/cw_spiflash.py#L195) for `PIN_TAP_STRAP0` and `PIN_TAP_STRAP1` seem to be responsible for this since commenting these lines out seem to resolve this issue.

Since I'm not measuring these pins ATM I cannot tell for sure but since this initialization is supposed happen before entering bootstrap, this is a just a artifact of my test setup. I won't close this issue in case you want to investigate this further but there are no spi_device hw issues that are currently blocking the new bootstrap implementation. Thanks a lot @eunchan and @tjaychen!

**Comment by eunchan** [comment] 2022-05-20 16:34
Thanks for the investigation, I think touching the pad config in between may have chances to create CSb glitches . So, from the internal SPI_DEVICE point of view, it may see glitches. I don't have test setup on chip-level yet. So when we have, I will try that too.

**Comment by eunchan** [comment] 2022-05-26 17:43
Let me close this issue @alphan as seems like all things are sorted out. Please re-open this ticket if you find anything weird. Thanks!

**Closed by eunchan** 2022-05-26 17:43 UTC
Labels: Component:RTL, IP:spi_device
