### ISSUE TITLE
[sysrst_ctrl, dv] Trigger multiple interrupt events when the core clock is off 

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#12029] opened 2022-04-08 23:08 UTC
sysrst_ctrl should have this issue found in adc_ctrl #11759
We should enhance the test to trigger multiple interrupt events when the core clock is off 

Also, run the new test without the design fix #12027 and see if we can reproduce it.

cc: @msfschaffner

**Comment by msfschaffner** [comment] 2022-04-09 00:32
CC: @tjaychen

**Comment by patel-madhuri** [comment] 2022-05-13 13:04
Since the sysrst_ctrl_edge_detect test is enhanced with randomizing clock gating, we trigger multiple interrupt events when core clock is off for the random seeds. The test is merged and running in regression. We can close this issue.

**Closed by patel-madhuri** 2022-05-13 13:04 UTC
Labels: Component:DV, Priority:P1, Type:Task, IP:sysrst_ctrl, Milestone:V2
