### ISSUE TITLE
[test-triage] chip_sw_power_virus

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#17181] opened 2023-01-30 10:10 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out has 7 failures:

### Steps to Reproduce

- GitHub Revision: [91b09f2d4](https://github.com/lowrisc/opentitan/tree/91b09f2d4bfa63fbb344f250a7313d922953babc)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_power_virus --build-seed 2585102727 --fixed-seed 1723583023 --waves fsdb

### Tests with similar or related failures

- [ ] chip_sw_power_virus
- [ ] chip_sw_alert_handler_lpg_sleep_mode_alerts

**Comment by moidx** [comment] 2023-04-12 21:09
Hi @timothytrippel can this be closed now? We can open new issues if there are any problems integrating with downstream environments.

**Comment by moidx** [comment] 2023-04-12 21:10
Never mind I see that it is still failing. I remember we discussed the status offline.

**Comment by timothytrippel** [comment] 2023-04-14 22:44
I have identified the root cause. The test failure is due to a mismatch between the netlist constants used to compute the flash scrambling keys. It is the same reason `chip_sw_flash_scrambling_smoketest` is failing. The failure doesn't happen in private CI (only in nightlies) because the default HW build seed is used so the netlist consts don't change from the checked-in versions.

I am working on a fix for this.

**Closed** 2023-04-19 06:52 UTC
Labels: Priority:P1, Component:ChipLevelTest, Component:TestTriage
