### ISSUE TITLE
[flas_ctrl] flash is disabled with lc_escalate_en != Off

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#15232] opened 2022-10-03 07:10 UTC
Any random value of flash_ctrl.DIS except MuBi4False or
any random value of lc_escalate_en_i except lc_ctrl:On  will make
tb.dut.u_flash_hw_if.disable_i "not MuBi4False". And by This [line](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv;drc=1366f10298c49cfd318cccec21b1e775eb73fd88;l=568)
tb.dut.u_flash_hw_if.state_d[10:0] will be StDisabled which will make
Flash to disable state.

**Comment by tjaychen** [comment] 2022-10-04 00:04
ooooo i think i misunderstood what you were saying before.
I think this is intentional (but let me double check).

Since mubi is 4 bits, it means "disable" can take on a total of 16 values.  Given that, we want all but one of those values (Off) to mean "disable", so that if someone faults it, most of the time they would trigger disable.

Does that make sense to you? Don't close this yet, I will double check.

**Comment by tjaychen** [comment] 2022-10-06 03:07
i just confirmed that is indeed the case. All the flash decoding is using `true_loose`, meaning anything that's not `Off` will trigger disable.  This is working as intended.

**Closed** 2022-10-06 16:40 UTC
Labels: Priority:P2, Type:Question, Component:RTL, IP:flash_ctrl
