### ISSUE TITLE
[test-triage] chip_tap_straps_vseq checking failing

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15370] opened 2022-10-10 13:42 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

Several types of JTAG errors
```
UVM_ERROR @ * us: (chip_tap_straps_vseq.sv:229) [chip_tap_straps_vseq] Check failed jtag_vif.tdo === * (0xz [z] vs * [*]) has 6 failures:

Test chip_tap_straps_rma has 4 failures.
0.chip_tap_straps_rma.25546017
Line 4868, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_tap_straps_rma/latest/run.log

  UVM_ERROR @ 4089.709977 us: (chip_tap_straps_vseq.sv:229) [uvm_test_top.env.virtual_sequencer.chip_tap_straps_vseq] Check failed jtag_vif.tdo === 0 (0xz [z] vs 0x0 [0])
  UVM_INFO @ 4089.709977 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

```
UVM_ERROR @ * us: (jtag_riscv_driver.sv:209) [jtag_riscv_agent_pkg] Check failed sbcs_val[SbAccess32] == * (* [*] vs * [*]) expect SBA width to be * bits! has 2 failures:

Test chip_tap_straps_prod has 2 failures.
0.chip_tap_straps_prod.3867622379
Line 4864, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_tap_straps_prod/latest/run.log

  UVM_ERROR @ 4596.821778 us: (jtag_riscv_driver.sv:209) [jtag_riscv_agent_pkg] Check failed sbcs_val[SbAccess32] == 1 (0 [0x0] vs 1 [0x1]) expect SBA width to be 32 bits!
  UVM_INFO @ 4596.821778 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

```
UVM_ERROR @ * us: (chip_tap_straps_vseq.sv:153) [chip_tap_straps_vseq] Check failed cfg.m_jtag_riscv_agent_cfg.rv_dm_activated == exp_to_be_activated (* [*] vs * [*]) has 1 failures:

Test chip_tap_straps_dev has 1 failures.
1.chip_tap_straps_dev.287088058
Line 4850, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_tap_straps_dev/latest/run.log

  UVM_ERROR @ 2903.158057 us: (chip_tap_straps_vseq.sv:153) [uvm_test_top.env.virtual_sequencer.chip_tap_straps_vseq] Check failed cfg.m_jtag_riscv_agent_cfg.rv_dm_activated == exp_to_be_activated (1 [0x1] vs 0 [0x0])
  UVM_INFO @ 2903.158057 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

```
UVM_ERROR @ * us: (jtag_riscv_csr_seq.sv:46) [jtag_csr_seq] Check failed rsp.status == DmiNoErr (* [*] vs * [*]) JTAG DMI read access failed! has 1 failures:

Test chip_tap_straps_dev has 1 failures.
2.chip_tap_straps_dev.482702261
Line 4854, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/2.chip_tap_straps_dev/latest/run.log

  UVM_ERROR @ 2529.853770 us: (jtag_riscv_csr_seq.sv:46) [uvm_test_top.env.m_jtag_riscv_agent.sequencer.jtag_csr_seq] Check failed rsp.status == DmiNoErr (2 [0x2] vs 0 [0x0]) JTAG DMI read access failed!
  UVM_INFO @ 2529.853770 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

### Steps to Reproduce

GitHub revision: [c2a8c64cc](https://github.com/lowrisc/opentitan/tree/c2a8c64ccbca39707be7883dfd2f8c1100813730)
Build seed: 4265629825
Based on test results of Sunday October 09 2022 07:06:02 UTC and many other tests that have previously failed.

Possibly will be resolved with JTAG working in CI.

- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_tap_straps_vseq --fixed-seed 25546017 --build-seed 4265629825 --waves -v h

### Tests with similar or related failures

- [ ] chip_tap_straps_dev
- [ ] chip_tap_straps_rma
- [ ] chip_tap_straps_prod

**Comment by engdoreis** [comment] 2022-10-11 10:02
By the signature of this issue it seems to be related to #14872

**Comment by sriyerg** [comment] 2022-10-11 17:46
Please hold off on triaging this test. The test needs to be completely rewritten.

**Comment by tjaychen** [comment] 2022-10-21 15:57
this is still failing in latest regressions, but i need to double check if the fix made it in.
I'll close / keep open once I can confirm.

**Comment by tjaychen** [comment] 2022-10-21 22:44
i've taken tip of tree and run all the tap strap test a minimum of 20 seeds in my local area.
Things appear to be okay. I will close this down for now.

**Closed by tjaychen** 2022-10-21 22:44 UTC
Labels: Component:TestTriage
