### ISSUE TITLE
Verilator Lint warnings in reggen new generated code

### ISSUE THREAD

**Issue by Jacob-Levy** [lowRISC/opentitan#12540] opened 2022-05-09 00:01 UTC
@msfschaffner  @tjaychen 
The issue with the new Verilator (lint-only) warnings in the ast_reg_top.sv are a result of the following change:

`  208d34a3e - (3 weeks ago) [reggen] Add spurious WE check to autogen'd regfile - Michael Schaffner`

```
%Warning-UNUSED: /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:34: Signal is not used: 'clk_i'
                                                                                                    : ... In instance ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check
  input                          clk_i,
                                 ^~~~~
                 /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_reg_we_check.sv:47: ... note: In file included from prim_reg_we_check.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast_reg_top.sv:63: ... note: In file included from ast_reg_top.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast.sv:848: ... note: In file included from ast.sv
                 ... Use "/* verilator lint_off UNUSED */" and lint_on around source to disable this message.
%Warning-UNUSED: /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:35: Signal is not used: 'rst_ni'
                                                                                                    : ... In instance ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check
  input                          rst_ni,
                                 ^~~~~~
                 /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_reg_we_check.sv:47: ... note: In file included from prim_reg_we_check.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast_reg_top.sv:63: ... note: In file included from ast_reg_top.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast.sv:848: ... note: In file included from ast.sv
%Warning-UNUSED: /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/tlul/rtl//tlul_err.sv:9: Signal is not used: 'clk_i'
                                                                                          : ... In instance ast.u_reg.u_reg_if.u_err
  input clk_i,
        ^~~~~
                 /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/tlul/rtl//tlul_adapter_reg.sv:155: ... note: In file included from tlul_adapter_reg.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast_reg_top.sv:101: ... note: In file included from ast_reg_top.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast.sv:848: ... note: In file included from ast.sv
%Warning-UNUSED: /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/tlul/rtl//tlul_err.sv:10: Signal is not used: 'rst_ni'
                                                                                           : ... In instance ast.u_reg.u_reg_if.u_err
  input rst_ni,
        ^~~~~~
                 /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/tlul/rtl//tlul_adapter_reg.sv:155: ... note: In file included from tlul_adapter_reg.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast_reg_top.sv:101: ... note: In file included from ast_reg_top.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast.sv:848: ... note: In file included from ast.sv
%Warning-UNUSED: /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/tlul/rtl//tlul_err.sv:12: Bits of signal are not used: 'tl_i'[104:102,99:92,55:24,0]
                                                                                           : ... In instance ast.u_reg.u_reg_if.u_err
  input tl_h2d_t tl_i,
                 ^~~~
                 /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/tlul/rtl//tlul_adapter_reg.sv:155: ... note: In file included from tlul_adapter_reg.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast_reg_top.sv:101: ... note: In file included from ast_reg_top.sv
                 /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast.sv:848: ... note: In file included from ast.sv

%Warning-UNOPTFLAT: /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:58: Signal unoptimizable: Feedback to clock or circular logic: 'ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check.err_tree'
  logic [2**(NumLevels+1)-2:0] err_tree;  
                               ^~~~~~~~
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_reg_we_check.sv:47: ... note: In file included from prim_reg_we_check.sv
                    /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast_reg_top.sv:63: ... note: In file included from ast_reg_top.sv
                    /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast.sv:848: ... note: In file included from ast.sv
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:58:      Example path: ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check.err_tree
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:95:      Example path: ASSIGNW
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:58:      Example path: ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check.err_tree
%Warning-UNOPTFLAT: /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:56: Signal unoptimizable: Feedback to clock or circular logic: 'ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check.or_tree'
  logic [2**(NumLevels+1)-2:0] or_tree;
                               ^~~~~~~
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_reg_we_check.sv:47: ... note: In file included from prim_reg_we_check.sv
                    /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast_reg_top.sv:63: ... note: In file included from ast_reg_top.sv
                    /projects/opentitan/jlevy/ast_MR//nuvoton/design/ip_os/ast/rtl/ast.sv:848: ... note: In file included from ast.sv
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:56:      Example path: ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check.or_tree
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:92:      Example path: ASSIGNW
                    /projects/opentitan/jlevy/ast_MR//opentitan/hw/ip/prim/rtl//prim_onehot_check.sv:56:      Example path: ast.u_reg.u_prim_reg_we_check.u_prim_onehot_check.or_tree

```

**Comment by rswarbrick** [comment] 2022-05-13 09:58
I don't see this behaviour. Note that there are some lint waivers that were added in b10bdbe (before the commit you're mentioning). I'm running `fusesoc --cores-root=. run --target=lint --flag=fileset_top --setup --build lowrisc:systems:ast`.

Closing, since I don't think this is an issue. Please re-open (and give the command you're using to reproduce the error) if I'm wrong.

**Closed by rswarbrick** 2022-05-13 09:58 UTC

**Comment by Jacob-Levy** [comment] 2022-05-16 07:30
I am running directly the verilattor and not fusesoc. Will try to move to fusesoc to get all the .vlt in place.
