### ISSUE TITLE
Unable to connect gdb to virtual JTAG

### ISSUE THREAD

**Issue by mhoangy** [lowRISC/opentitan#17406] opened 2023-02-28 19:19 UTC
### Description

From current top of tree, I follow this [section](https://github.com/lowRISC/opentitan/blob/4828d53b105685cd25dc2c34bb82c450fe35ae81/doc/getting_started/setup_verilator.md#connect-with-openocd-to-the-jtag-port-and-use-gdb-optional) and:

1. run a test with debug symbols:

`$ bazel test --copt=-g --test_output=streamed //sw/device/tests:uart_smoketest_sim_verilator`

2. install OpenOCD from upstream and start the gdb server
`openocd -s util/openocd -f board/lowrisc-earlgrey-verilator.cfg`

~~~
Open On-Chip Debugger 0.12.0-rc2
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
DEPRECATED! use 'remote_bitbang port' not 'remote_bitbang_port'
DEPRECATED! use 'remote_bitbang host' not 'remote_bitbang_host'
Info : Hardware thread awareness created
Warn : `riscv set_prefer_sba` is deprecated. Please use `riscv set_mem_access` instead.
force hard breakpoints
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Warn : An adapter speed is not selected in the init scripts. OpenOCD will try to run the adapter at the low speed (100 kHz)
Warn : To remove this warnings and achieve reasonable communication speed with the target, set "adapter speed" or "jtag_rclk" in the init scripts.
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:44853
Info : remote_bitbang driver initialized
Info : This adapter doesn't support configurable speed
~~~

3. Try connecting to the gdb server (hardcoded elf path since bazel query and bazel test processes don't co-run)
`$ riscv32-unknown-elf-gdb -ex "target extended-remote :3333" -ex "info reg" "bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/tests/uart_smoketest_prog_sim_verilator.elf"`

~~~
GNU gdb (crosstool-NG 1.24.0.498_5075e1f) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=riscv32-unknown-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<toolchains@lowrisc.org>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/tests/uart_smoketest_prog_sim_verilator.elf...
:3333: Connection timed out.
The program has no registers now.
~~~

Adding gdp_port 3333 explicitly explicitly wasn't helpful. Wasn't able to find any recent changes that may have caused issue with the virtual JTAG.

After the test program finishes, it looks like the gdbserver wasn't able to halt the core.

~~~
Info : Connecting to localhost:44853
Info : remote_bitbang driver initialized
Info : This adapter doesn't support configurable speed
Error: Error on socket 'remote_bitbang_fill_buf': errno==104, message: Connection reset by peer.
Error: Trying to use configured scan chain anyway...
Error: Error on socket 'remote_bitbang_putc': errno==32, message: Broken pipe.
Error: Error on socket 'remote_bitbang_putc': errno==32, message: Broken pipe.
Warn : Bypassing JTAG setup events due to errors
Error: Error on socket 'remote_bitbang_putc': errno==32, message: Broken pipe.
Error: failed jtag scan: -4
Error: Unsupported DTM version: 12
Warn : target riscv.tap.0 examination failed
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections
shutdown command invoked
Error: Unsupported DTM version: 12
Error: Error on socket 'remote_bitbang_putc': errno==32, message: Broken pipe.
Error: failed: -4
~~~

Was able to see this on two different machines.

**Comment by dmcardle** [comment] 2023-02-28 22:23
Thanks for filing this issue! I think I saw this behavior months ago before switching focus to the CW310 FGPA.

I just reproduced this locally. My first step would be to investigate the OpenOCD error message that mentions errno 104. It's not clear to me whether this is a bug in OpenOCD or in Verilator. I'm happy to help anyone that wants to take this on, but I don't have enough availability to assign it to myself.

If the goal is to run GDB tests (e.g. [`rom_e2e_debug_test_otp_*`](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/e2e/BUILD;l=3411;drc=092bd850f6f671ed1f9dba3a197abb7476d9c84b)) against Verilated OpenTitan, it might be a good idea to extend [`gdb_test_coordinator.py`](https://cs.opensource.google/opentitan/opentitan/+/master:rules/scripts/gdb_test_coordinator.py).

Also, I recommend using the Bazel-managed GDB and OpenOCD (see [docs](https://docs.opentitan.org/doc/getting_started/install_openocd/)) rather than system binaries. In this case, it's not possible to `bazel run` them because the lock is already taken by the test command, but this hack will do the trick:
```bash
# Ensure tools are present in the bazel-out directory.
./bazelisk.sh build @lowrisc_rv32imcb_files//:bin/riscv32-unknown-elf-gdb //third_party/openocd:openocd_bin

# Get path to GDB binary. For some reason, it omits the "bazel-opentitan/" prefix from the path.
# "external/lowrisc_rv32imcb_files/bin/riscv32-unknown-elf-gdb"
GDB="bazel-opentitan/$(./bazelisk.sh outquery '@lowrisc_rv32imcb_files//:bin/riscv32-unknown-elf-gdb')"

# Get path to OpenOCD binary:
# "bazel-out/k8-fastbuild/bin/third_party/openocd/build_openocd/bin/openocd"
OPENOCD=$(./bazelisk.sh outquery //third_party/openocd:openocd_bin)

# Now, you can use these variables instead of the system binaries. For example:
$OPENOCD -s util/openocd -f board/lowrisc-earlgrey-verilator.cfg ...
```

**Comment by mhoangy** [comment] 2023-06-06 00:34
As an update, I was able to connect to the gdb server using openocd version 0.11. A change related to remote_bitbang between that version and the current 0.12 must have caused the virtual debugger to no longer function.

**Comment by msfschaffner** [comment] 2023-10-07 04:10
Closing this for now since it seems resolved - please reopen if that is not the case.

**Closed** 2023-10-07 04:10 UTC
Labels: Component:Tooling, Type:Bug
