### ISSUE TITLE
[i2c] Configurable support between stretch and nak.

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15227] opened 2022-09-30 23:42 UTC
When in target mode, the i2c AddrRead state also writes to the acq_fifo to indicate a start has been seen.
However, this write is not qualified by acq_wready_i, so in the event the `acq_fifo` is still full from the previous transaction, would just cause an overflow. 

The overflow does not stop the fsm from continuing or cause the device to issue a NAK, so it will just get silently dropped in the background. If software is expecting to read the "start" indication in the acquisition fifo, this may become a problem. 

@drewmacrae 
@a-will

**Comment by tjaychen** [comment] 2022-11-13 21:53
It turns out nack-ing while fifo full was not considered as part of the original features.
This will be moved to M3 since the focus of M2 is that basic functionality of i2c is present.

There is an effort to slightly restructure i2c's fsm so that nack-ing can be more easily added in the near future.

**Comment by tjaychen** [comment] 2022-11-30 17:17
@jesultra @a-will 
can you guys have a look at this one and let me know if this is an option we have to get in?

@jdonjdon fyi

**Comment by a-will** [comment] 2022-12-02 21:09
Does the original presentation of the issue still apply? Because I do think the FSM should not continue if the ACQ FIFO cannot take in the command (does the start/re-start condition get co-located with the command, or is it an entirely separate entry?).

**Comment by tjaychen** [comment] 2022-12-02 21:55
the command gets co-located into the same entry as the start (but not the restart).
So the way this currently works is that we always reserve at least 1 entry of space for a restart / stop.
Then when it cycles back around, if there is no space for the start / command, we then stretch the address. 

But I think the original spirit of this is that we could have configurable nak or stretches, for those situations where stretch is not supported.

**Comment by a-will** [comment] 2022-12-02 22:24
I'd recommend changing the title if we're going to make the conversation about handling systems without support for stretching.

And for that, I suspect it's not a requirement. For our most prominent use case, the TPM i2c spec requires support for stretching. Are there other critical use cases for an OT i2c target?

However, our i2c IP would be more complete if we had a "stretch timeout to NAK" feature (where no stretching would imply an immediate timeout). Note that there is no way to have anything but undefined behavior for stretching that has timed out in the middle of a target-transmitter sending data--If the FIFO is empty, garbage data goes out until the host stops clocking it out.

**Comment by tjaychen** [comment] 2022-12-03 02:14
yes let me clarify the original intent of this issue.
It was mostly meant to be a binary decision between "use nak" or "stretch".

The stretch to nak case I guess is less binary, and really supports both, and let's the target nak the host if it cannot respond in time.  I feel like this particular case is probably out of scope for M3.  The one I am less sure of is nak in general.

I suppose if we are in a system that does not support stretch at all, we will probably use an entirely different sideband system to indicate when it's safe to "do something"?   @jesultra Please let us know. 

Note adding the `nak` case would technically be a new feature. While the design burden is small, the verification would be much higher I think. @jdonjdon

**Comment by jesultra** [comment] 2023-01-14 05:58
I do not believe that we have to design for I2C hosts that do not support stretching.

I am happy as long as the OT I2C device will stretch the clock when appropriate, such that entries are never dropped even if the ACQ_FIFO is full.

@tjaychen , can you please confirm that safeguards are in place, such that all of START, DATA, RESTART and STOP entries are guaranteed to be inserted in the ACQ_FIFO.  (How do you make that guarantee for a STOP condition?  there is no ack bit to stretch.  Do we ensure that START and DATA insertions never fill the very last byte of the FIFO?)

**Comment by tjaychen** [comment] 2023-01-15 05:28
so the way this is done, in order to guarantee we can get the stop bit, the acq_fifo "full" basically happens at `full depth - 1`.  The idea is that we always reserve space for the STOP condition.

**Comment by tjaychen** [comment] 2023-01-15 05:30
thanks for the feedback at @jesultra , then unless others object, i will plan to drop this item to P4.

**Comment by GregAC** [comment] 2023-02-16 17:33
If I've understood this issue correctly the original bug it refers to is fixed by https://github.com/lowRISC/opentitan/pull/16249? Though it's still open as a potential new feature where a nak could be used instead of a stretch to deal with the acq full issue? @a-will maybe you could confirm?

**Comment by a-will** [comment] 2023-02-16 19:29
@GregAC Confirmed :) The original bug was that no mechanism was employed to prevent FIFO overflow in that case (neither stretching nor NACKing), and #16249 fixed it, implementing the stretching option alone.

With the current feature set, the IP should only be used in systems that support clock stretching. Ostensibly, that is fine for the use cases we had mapped out, but in a more general context, the guarantees aren't as good for systems that require time bounds on clock stretching (e.g. SMBus). Adding features to accommodate a NACK or stretch-to-NACK policy would help there.

**Comment by msfschaffner** [comment] 2024-01-19 16:39
@jesultra @moidx do we foresee any need to support this in the production design?

**Comment by a-will** [comment] 2024-01-19 17:04
I'll just note that proper SMBus timeout support may be of particular interest to folks using the I2C/SMBus sideband on the PCIE connector to talk to the RoT.

**Comment by jesultra** [comment] 2024-01-23 16:37
For ChromeOS use, where you only have the AP and GSC on the I2C bus, I am satisfied with the indefinite stretching as long as ACQ FIFO does not have room for the START record.  We do not need NAK after specific time, in case software fails to make room in the queue.

**Comment by a-will** [comment] 2024-01-23 17:05
> For ChromeOS use, where you only have the AP and GSC on the I2C bus, I am satisfied with the indefinite stretching in cases where ACQ FIFO does not have room for the START record. We do not need NAK after specific time, in the case software fails to make room in the queue.

That's good to know. Bear in mind that there are more users than ChromeOS, though. :smile:

**Comment by msfschaffner** [comment] 2024-01-26 17:16
Discussed in the triage today and we think it would be good to do this for PROD (for compatibility with other use cases as detailed above).

**Comment by marnovandermaas** [comment] 2024-02-29 16:51
I've created a draft PR with one proposed solution: https://github.com/lowRISC/opentitan/pull/21766
It goes down the route of sending a NACK instead of stretching. I assume this is fine and we don't need the "stretch-to-NACK" feature?

**Comment by a-will** [comment] 2024-02-29 17:57
> I've created a draft PR with one proposed solution: #21766 It goes down the route of sending a NACK instead of stretching. I assume this is fine and we don't need the "stretch-to-NACK" feature?

The stretch-to-NACK feature is a more general solution and a very simple one that builds a little atop what is already in the core, and it would take me quite a bit more effort to evaluate whether this halfway point is good enough in every context. "stretch-to-NACK" gives software time to respond to higher-occupancy watermark interrupts for longer transfers, yet guarantees our target mode will not hold the bus for longer than the SMBus spec allows.

Having to choose between an immediate NACK or risking a violation of the spec seems to end up causing sacrifices that I think shouldn't really be necessary here.

I feel it would be better to implement this simple feature instead of spending time analyzing whether a shortcut is good enough.

**Comment by msfschaffner** [comment] 2024-02-29 17:59
CC @vogelpi @andreaskurth

**Comment by marnovandermaas** [comment] 2024-03-01 16:58
Ok, let me rework the PR then.

**Comment by andreaskurth** [comment] 2024-03-02 11:01
Thanks @marnovandermaas. I think a CSR field that defines how long to stretch before resorting to NACK would be useful. SW can then set the register according to the specification of the protocol. For example, MCTP on SMBus/I2C allows target devices to stretch the clock by at most 250 us per byte. SMBus allows target devices to stretch the clock by up to 25 ms per message (which is about 95 us per byte for max-length messages). That should give us an idea of the range of values we should support.

**Comment by andreaskurth** [comment] 2024-03-04 13:00
Oh, and for SMBus compliance our I2C IP must, when its ACQ FIFO is full:
- ACK the byte with its own address (but not push it to the ACQ FIFO)
- NACK the subsequent byte (at that point unconditionally, i.e., even if the ACQ FIFO may now have space, because the 'start' byte did not get pushed into the ACQ FIFO)

@marnovandermaas: If you think it makes sense to also resolve that as part of your PR, please feel free to include it. If not, I'm happy to create an issue so that this can be resolved in a follow-up PR.

**Comment by marnovandermaas** [comment] 2024-03-04 15:26
> Oh, and for SMBus compliance our I2C IP must, when its ACQ FIFO is full:
> 
>     * ACK the byte with its own address (but not push it to the ACQ FIFO)
> 
>     * NACK the subsequent byte (at that point unconditionally, i.e., even if the ACQ FIFO may now have space, because the 'start' byte did not get pushed into the ACQ FIFO)
> 
> 
> @marnovandermaas: If you think it makes sense to also resolve that as part of your PR, please feel free to include it. If not, I'm happy to create an issue so that this can be resolved in a follow-up PR.

That's good to know. That should be part of the PR that I am working on.

**Comment by a-will** [comment] 2024-03-04 15:45
> > Thanks @marnovandermaas. I think a CSR field that defines how long to stretch before resorting to NACK would be useful. SW can then set the register according to the specification of the protocol. For example, MCTP on SMBus/I2C allows target devices to stretch the clock by at most 250 us per byte. SMBus allows target devices to stretch the clock by up to 25 ms per message (which is about 95 us per byte for max-length messages). That should give us an idea of the range of values we should support.
> 
> One thing to note is that for a "stretch-to-nack" feature we need to start stretching before deciding to send an ACK. This is different from what we currently do where we stretch after the acknowledge phase. I'm not sure if this is normal behavior for I2C targets. According to [the spec](https://web.archive.org/web/20210813122132/https://www.nxp.com/docs/en/user-guide/UM10204.pdf) section 3.1.9 stretching usually happens after acknowledgement.

We don't need to change where we stretch, actually. Stretching would happen in the same place (immediately following the ACK bit), and if the timeout expires, flop the commit to NACK. When we reach the ACK phase, check the flopped NACK decision, then NACK at the ACK bit if it's set. (and clear the flop on the next transfer start)

**Comment by marnovandermaas** [comment] 2024-03-04 15:53
> We don't need to change where we stretch, actually. Stretching would happen in the same place (immediately following the ACK bit), and if the timeout expires, flop the commit to NACK and release the stretch to proceed to the next state. When we reach the ACK phase, check the flopped NACK decision, then NACK if it's set. (and clear the flop on the next transfer start)
> 
> Stretching is for the same byte as the ACK decision. The actual signaling of the ACK or NACK might happen later, but the decision targets the same set of state as stretching. :)

That makes sense and makes the changes much easier. What happens if you get a stop, do you keep the NACK flop set and NACK the first byte of the next transaction (Andreas said to always ACK the address)?

**Comment by a-will** [comment] 2024-03-04 16:03
> That makes sense and makes the changes much easier. What happens if you get a stop, do you keep the NACK flop set and NACK the first byte of the next transaction (Andreas said to always ACK the address)?

Since a Start would clear it anyway, we don't really care, hehe. After a Stop, the NACK flop won't be observed until after the next Start.

**Comment by marnovandermaas** [comment] 2024-03-04 16:11
This would mean that the host would not know the difference between a transaction where the last byte is stretched to the timeout and then accepted into the ACQ FIFO at the last moment, and a transaction where the last byte actually hits the stretch timeout and is dropped altogether. Is it OK to fail silently in this case or do we need some way of notifying the host?

**Comment by a-will** [comment] 2024-03-04 17:15
> This would mean that the host would not know the difference between a transaction where the last byte is stretched to the timeout and then accepted into the ACQ FIFO at the last moment, and a transaction where the last byte actually hits the stretch timeout and is dropped altogether. Is it OK to fail silently in this case or do we need some way of notifying the host?

Recapping offline discussion: Ah, we probably do need some way to communicate that a NACK happened (to OT software), and we don't have a good mechanism to do that yet, do we...

The ACQ FIFO is awkward, since it combines control signals with a byte that we assume is ACK'd. If we didn't radically change this mechanism, we'd probably need another control bit to add whether data in the transfer was NACK'd.

Alternatively, we could make the NACK decision become a sticky bit that prevents any new data from entering the ACQ FIFO until software clears it (which would only be absorbed at the address/command ACK/NACK phase, so we're synchronized). A CSR bit would be needed to determine whether to always ACK an address, even if the transfer is committed to NACK from the outset.

**Comment by andreaskurth** [comment] 2024-03-05 08:25
We should only push the byte into the ACQ FIFO if it gets ACK'd (and not if it gets NACK'd), right? So we may have to change the RTL to delay the push to the instant at which the ACK/NACK decision is taken (I didn't check the RTL for how big this change would be, though, so maybe that's already possible?).

I agree it would be good to flag such a NACK-due-to-ACQ-full to SW; maybe with an IRQ and a corresponding bit in the `INTR_STATE` register? I think implementing that is not an immediate priority, though. If we agree on this, we should track it in an issue and implement it once we've finished working on the changes that influence the SCL/SDA behavior.

Since the ACQ FIFO has two bits to 'identify' each byte (i.e., distinguish if a byte came after a (repeated) START condition, before a STOP condition, or in the middle of a transfer), I think SW already has the means to know that a transfer didn't complete: a complete transfer ends with a byte that has `AcqStop` in its ID bits whereas an incomplete one ends with a byte that has `AcqData` in its ID bits. SW can know that a byte with `AcqData` is at the end of a transfer if the ACQ FIFO is empty or the next byte has `AcqStart` or `AcqRestart` in its ID bits (although the latter case would require SW to pop a byte from the ACQ FIFO that may belong to the next transfer, so SW would have to stash it away if it doesn't handle immediately handle that next transfer).

Re NACKing subsequent bytes: I agree with adding a sticky bit that prevents subsequent bytes from entering the ACQ FIFO and instead NACK them all. We should set it once the first byte of a transfer gets NACK'd and clear it on a (repeated) START or STOP condition. The rationale for this comes from the specs:
- I2C: "[...] this is defined as the Not Acknowledge signal. The controller can then generate either a STOP condition to abort the transfer, or a repeated START condition to start a new transfer." (3.1.6) To my understanding, this forbids the controller to continue the transfer, and if it does we should just NACK all other bytes.
- SMBus: "The controller upon detection [a NACK] must generate a STOP condition [...]" (5.2)
- MCTP: "An endpoint/bridge that NACKs a packet shall continue to NACK any remaining bytes for the transaction until it recognizes the next START or STOP condition on the bus." (6.14)

**Comment by marnovandermaas** [comment] 2024-03-05 11:30
> Alternatively, we could make the NACK decision become a sticky bit that prevents any new data from entering the ACQ FIFO until software clears it (which would only be absorbed at the address/command ACK/NACK phase, so we're synchronized). A CSR bit would be needed to determine whether to always ACK an address, even if the transfer is committed to NACK from the outset. A transfer that committed to NACKing the transfer at the address phase would skip adding anything to the ACQ FIFO for that transfer.

I think this alternative would show the I2C host on the other side to see an error happened, but I think I prefer Andreas' suggestion that a repeated start/ stop should still be possible.

> We should only push the byte into the ACQ FIFO if it gets ACK'd (and not if it gets NACK'd), right?

Yes, but the event of NACKing a byte needs to be communicated back to Ibex. One way of doing this is putting the "NACK" event in the ACQ FIFO.

> I agree it would be good to flag such a NACK-due-to-ACQ-full to SW; maybe with an IRQ and a corresponding bit in the INTR_STATE register?

The other one is as you mention, you can send an interrupt, but then you lose the ordering information in the ACQ FIFO, in which transaction did the NACK happen? I agree that we should prioritize the SCL/SDA

> SW can know that a byte with AcqData is at the end of a transfer if the ACQ FIFO is empty or the next byte has AcqStart or AcqRestart in its ID bits

This is a good point. If we had to NACK something we can just refuse to put the stop condition in the ACQ FIFO and then software will see a start (not restart) without a previous stop.

**Comment by andreaskurth** [comment] 2024-03-05 13:55
> This is a good point. If we had to NACK something we can just refuse to put the stop condition in the ACQ FIFO and then software will see a start (not restart) without a previous stop.

Exactly. This way we don't have to widen the enum by another bit (which we have store for each entry in a FIFO that will soon be quite deep).

**Comment by marnovandermaas** [comment] 2024-03-05 14:40
> > This is a good point. If we had to NACK something we can just refuse to put the stop condition in the ACQ FIFO and then software will see a start (not restart) without a previous stop.
> 
> Exactly. This way we don't have to widen the enum by another bit (which we have store for each entry in a FIFO that will soon be quite deep).

One thing I was discussing with @a-will was that instead of having the two bits we have now, just have one control bit which says whether the 8-bit payload is a data byte or an information byte. Then adding this NACK feedback does not add any extra bits to each ACQ FIFO entry. I vote for making that change in a future PR. I still think it is good to have the explicit NACK feedback unless you are firmly against this.

**Comment by a-will** [comment] 2024-03-05 16:33
> So we may have to change the RTL to delay the push to the instant at which the ACK/NACK decision is taken (I didn't check the RTL for how big this change would be, though, so maybe that's already possible?).

The decision to ACK / NACK for the current byte would happen before the bits are even received. If there is space, we ACK; if not, we NACK.

> a complete transfer ends with a byte that has AcqStop

This is where I nag about using precise terminology, hehe. A _transfer_ does not necessarily end with AcqStop. Formally, AcqStop indicates the end of a _transaction_. Remember that there can be multiple transfers per transaction, and software must know whether a subsequent transfer is part of the same transaction.

We actually don't handle this perfectly even now. I'm about to describe a contrived case, but... If we get a transfer in one transaction, but the last transfer isn't addressed to us for some reason, the ACQ FIFO will never see the Stop. Then, if a controller does a repeated start in a _different_ transaction to our target, the ACQ FIFO will make it look like both transfers were part of the same transaction (to software, which must process this).

Would this ever happen intentionally from a correctly-behaving controller? Probably not... But this does illustrate some of the hazards with this relatively free-form protocol.

For a sticky bit type, then we'll have to decide where it can be allowed to become unstuck (transfer start? transaction start?), and whether the consequences of NACKing everything (except addresses) until then are okay for all cases.

**Comment by marnovandermaas** [comment] 2024-03-06 11:53
Ok, I've created a pull request to hopefully address most of what we've discussed here: https://github.com/lowRISC/opentitan/pull/21857
I tried to explain my reasoning in the PR description for some decisions I've made but it would be good to get your feedback on it before I put more time into it: @andreaskurth, @a-will and @hcallahan-lowrisc.

Thanks for all your input on this, I really appreciate the thoughtful feedback and help!

**Comment by marnovandermaas** [comment] 2024-03-08 16:20
One thing I am wondering is once we have stretched after an ACQ and then sent a NACK, should the target then stretch the clock to delay the next transaction? At the moment I am going to the idle state immediately and the next transaction will be NACK'ed unconditionally if the ACQ FIFO is still full. This could lead to a high number of NACK'ed transactions in a short amount of time. Instead I could stretch after a NACK until the configure timeout to slow these transactions down, but I'm not sure if this is desirable.

**Comment by a-will** [comment] 2024-03-08 16:41
> One thing I am wondering is once we have stretched after an ACQ and then sent a NACK, should the target then stretch the clock to delay the next transaction? At the moment I am going to the idle state immediately and the next transaction will be NACK'ed unconditionally if the ACQ FIFO is still full. This could lead to a high number of NACK'ed transactions in a short amount of time. Instead I could stretch after a NACK until the configure timeout to slow these transactions down, but I'm not sure if this is desirable.

I2C is going to top out at 1 MHz, and that means software has at least ~20 microseconds from the stretch timeout point to remove an entry from the ACQ FIFO. Then there is the actual timeout and transmission time of the prior transfer on top of that (whatever time went past the watermark that probably should've been used). Software shouldn't really have trouble there.

Meanwhile, I2C is a shared bus, and stretching can be deleterious to full system performance. I think it's best to be a "good citizen" and not stretch again until software does its job and handles the condition.

**Comment by marnovandermaas** [comment] 2024-03-08 16:52
Ok, @a-will that makes sense. I'll leave my PR as is and just go directly to idle after sending a NACK.

**Comment by andreaskurth** [comment] 2024-03-19 12:38
Closing as completed in https://github.com/lowRISC/opentitan/pull/21857.

**Comment by andreaskurth** [comment] 2024-03-19 13:29
Actually #21857 hasn't been merged just yet. Reopening.

PR #21857 should auto-close this issue. Sorry for the noise.

**Closed** 2024-03-19 13:49 UTC
Labels: Priority:P2, IP:i2c, Type:FutureRelease, Earlgrey-PROD Candidate
