### ISSUE TITLE
[chip-test] chip_sw_sleep_pin_wake

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#16833] opened 2022-12-14 21:14 UTC
### Test point name

[chip_sw_sleep_pin_wake](https://github.com/lowRISC/opentitan/blob/316831f8c2199f2288dd57ac4aeaec3334b5dfb8/hw/top_earlgrey/data/chip_testplan.hjson#L428)

### Host side component

SystemVerilog

### OpenTitanTool infrastructure implemented

None

### Contact person

sriyerg

### Checklist

This test is already developed. This issue tracks the effort to address the V3 portion of the test enhancement as described in the testplan entry.

**Comment by msfschaffner** [comment] 2023-04-12 20:47
Closing since its a dupe of #17356.

**Closed by msfschaffner** 2023-04-12 20:47 UTC
Labels: Component:DV, Type:Task, TOP:earlgrey, Milestone:V3, Component:ChipLevelTest
