### ISSUE TITLE
[rv_dm] Writing read-only section of debug memory does not return an error

### ISSUE THREAD

**Issue by abdullahvarici** [lowRISC/opentitan#14921] opened 2022-09-14 16:34 UTC
The top-level test `csr_mem_rw_with_rand_reset` with build-seed `2008576760` and seed `4251724826` writes the debug memory at address `0x0001_04e0`, expects an error response, but gets an okay response and fails. According to [`rv_dm.hjson`](https://github.com/lowRISC/opentitan/blob/master/hw/ip/rv_dm/data/rv_dm.hjson#L110), the first 4 KiB of debug ROM are read-only from SW. However, as this top-level test shows, writing this read-only section does not return an error. The write changes the debug memory.

To resolve this, should the debug memory return an error in this case? Or should the test not expect an error response?

**Comment by abdullahvarici** [comment] 2022-09-14 16:35
@msfschaffner @GregAC

**Comment by sriyerg** [comment] 2022-09-15 10:12
Seems like a duplicate of https://github.com/lowRISC/opentitan/issues/10468.

**Comment by GregAC** [comment] 2022-09-23 15:00
>  writing this read-only section does not return an error. The write changes the debug memory.

Have you actually observed the write altering the memory?

**Comment by msfschaffner** [comment] 2022-09-27 20:54
I believe I know why this is happening - let me take a closer look (errors associated with TL-UL windows have to be generated outside the `reg_top` instance, and this may not be implemented correctly).

**Comment by msfschaffner** [comment] 2022-09-29 02:22
This issue has been fixed in https://github.com/lowRISC/opentitan/pull/15169.

**Closed by msfschaffner** 2022-09-29 02:22 UTC
