### ISSUE TITLE
[test-triage] chip_sw_sleep_pwm_pulses

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16354] opened 2022-11-15 12:08 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
UVM_ERROR @ * us: (i2c_monitor.sv:66) [monitor] Check failed r_bit === *'b* (* [*] vs * [*]) has 14 failures:

Test chip_sw_sleep_pwm_pulses has 1 failures.

0.chip_sw_sleep_pwm_pulses.605364621
Line 628, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_pwm_pulses/latest/run.log

  UVM_ERROR @ 9425.130260 us: (i2c_monitor.sv:66) [uvm_test_top.env.m_i2c_agent0.monitor] Check failed r_bit === 1'b0 (0x1 [1] vs 0x0 [0])
  UVM_INFO @ 9425.130260 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

### Steps to Reproduce

- GitHub Revision: [47d4bfa34](https://github.com/lowrisc/opentitan/tree/47d4bfa34b424d29fcaf2d13e2a64ce1bd815ec7)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i TEST_NAME --build-seed 4006484429 --fixed-seed 605364621 --waves fsdb

### Tests with similar or related failures

- [ ] chip_sw_sleep_pwm_pulses

**Comment by johngt** [comment] 2022-11-15 12:10
Recently the nightlies have started to not fully succeed. Last 3 nights have shown partial success.

|     | Tests                    |   2022-11-14 08:10:42 |   2022-11-13 08:12:54 |   2022-11-12 08:04:45 |   2022-11-11 08:07:48 |   2022-11-10 08:10:06 |   2022-11-09 08:04:06 |   2022-11-08 08:03:42 |   2022-11-07 08:08:10 |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 | Suite                    |
|----:|:-------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:-------------------------|
| 178 | chip_sw_sleep_pwm_pulses |                 66.67 |                 66.67 |                 66.67 |                   100 |                   100 |                   100 |                   100 |                   100 |                   100 |                   100 |                   100 |                   100 |                 66.67 |                   100 | chip_sw_sleep_pwm_pulses |

**Comment by tjaychen** [comment] 2022-11-15 18:28
@jdonjdon 
@weicaiyang 
i think this is probably another one that should be fixed with `monitor_en`.
Should we just mark it as root caused?

**Comment by jdonjdon** [comment] 2022-11-15 18:34
@tjaychen @weicaiyang Let me scan all share io agent to make sure it is properly disabled in chip_env.

**Comment by jdonjdon** [comment] 2022-11-15 22:14
This is the same failure as #16296 
Fixed by #16333

**Comment by engdoreis** [comment] 2022-11-22 11:44
Passing after the fix:
|     | Tests                    |   2022-11-21 08:11:59 |   2022-11-20 08:10:00 |   2022-11-19 08:10:46 |   2022-11-18 08:16:52 |   2022-11-17 08:11:05 |   2022-11-16 08:14:00 |   2022-11-15 08:11:58 |   2022-11-14 08:10:42 |   2022-11-13 08:12:54 |   2022-11-12 08:04:45 |   2022-11-11 08:07:48 |   2022-11-10 08:10:06 |   2022-11-09 08:04:06 |   2022-11-08 08:03:42 | Suite                    |
|----:|:-------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:-------------------------|
| 187 | chip_sw_sleep_pwm_pulses |                   100 |                   100 |                   100 |                   100 |                   100 |                   100 |                   100 |                 66.67 |                 66.67 |                 66.67 |                   100 |                   100 |                   100 |                   100 | chip_sw_sleep_pwm_pulses |

**Closed by engdoreis** 2022-11-22 11:44 UTC
Labels: Resolution:Duplicate, Component:TestTriage
