### ISSUE TITLE
[sw] DIF Peripheral Reset Behaviour

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#2366] opened 2020-06-01 16:00 UTC
There has been a longstanding question about the behaviour of `_init` functions in DIFs, and whether they should reset the peripheral registers or not.

As committed DIFs stand today (i.e. UART, GPIO, SPI device, and PLIC), `_init` does reset the hardware peripheral (by writing zeroes or other equivalent values to all registers), which means each stage in the boot is resetting the peripheral.

However, there are certain peripherals we do not want to do this with (padctrl, pinmux), and in general it seems that the DIFs should provide the programming model that `_init` is just inheriting a peripheral and its existing state (which may or may not be a 'good' or known state), and will reconfigure based on the needs of the current boot stage.

The reason we have been resetting has been so that interrupts are not triggered in one stage and serviced in a later stage, but we think this can be accomplished by disabling MIE at the end of each stage, and letting the next stage re-enable MIE when it has reconfigured its interrupts.

Having discussed this, we think the new approach will be:
1. Do not trust existing peripheral interrupt state (pending and intr_enable need to be cleared before MIE is re-enabled).
2. All other peripheral state is left as it was in the previous state, and can be explicitly reconfigured by DIF API calls.

This would mean `_init` must not blindly write zeroes over all existing state. If it has information as to how to reconfigure the peripheral, it can. And resetting the interrupt state should not happen in `_init`, it should happen with explicit API calls.

This should be compatible with a convention where future boot stages do not have to trust previous boot stages to leave peripherals in a known good state, but they also do not have to reconfigure them on `_init`. 

@gkelly and I would welcome feedback on this proposal for DIF initialization, specifically around whether this is compatible with the existing security implications. 

We realise it will change the boot stage handoffs slightly, which will require updates to the CRT.

**Comment by silvestrst** [comment] 2020-06-01 16:17
Some earlier attempt to tackle this issue #1505 .

**Comment by GregAC** [comment] 2020-06-01 16:28
Do you think including a convenience function that does a reset would be useful (in particular for padctrl you could give it a default attribute setting you want applied to all pads for instance)?

**Comment by silvestrst** [comment] 2020-06-01 16:32
The problem is that you don't know exactly how peripheral was configured. So, unless we want to take the peripheral _exactly_ as it is, we would have to completely reset the whole peripheral anyway, even for minimal configuration.

I guess there's no issue with doing: 
```
init
reset 
```
instead of just
`init`

I don't think this adds much though. We could just keep reset on init as default for some peripherals and not the others.

**Comment by mcy** [comment] 2020-06-01 20:00
I think this is a pretty good idea, though I wonder if we can't do something like the following, closely following what Silvestrs suggests:

- Require a `dif_ip_new(mmio_region_t, dif_ip_t *)`, which initializes `base_addr` and any other DIF fields.
- Require a `dif_ip_reset(const dif_ip_t *)`, which clobbers all interrupt state and instructs the hardware to abort all transactions and operations. Quite a few DIFs have one of these already, but it just gets called by `init()`.
- Require a `dif_ip_configure(const dif_ip_t *, dif_config_t)`, which performs configuration without clobbering any other state (control registers would get clobbered, but not, say, IRQ registers).

However, if we're prescribing this exact interface for all IPs, we should probably prescribe an interface for IRQs as well, since those are pretty closely related. I think the following is roughly what we seem to be converging on, for the IRQs of a "simple" peripheral (i.e., not plic). I'm not saying we should do exactly this, but we might want to start thinking about the common pattern.
- `dif_ip_irq_get()` produces whether the IRQ has fired.
- `dif_ip_irq_clear()` clears a single IRQ bit. (Maybe we want a "clear all", as well?)
- `dif_ip_irq_set_enable()` sets the enable bit for a given IRQ. (DIF users can't query individual bits).
- `dif_ip_irq_force()`, which forces a particular IRQ (for DIFs which have an IRQ_TEST register).
- `dif_ip_irq_save()`, which saves the enablement state and then clears the enable register. (Call with a `NULL` out-param to clear all when you don't plan to re-enable.)
- `dif_ip_irq_restore()`, which resets the enablement state to a state previously returned by `save()`.

In as much as possible, it'd be great to standardize this programming model, not just for readability, but because it would make it possible to write shorter tests (rather than write a full tedious test for all these IRQ routines for every IP, for example, we can write general test harness that tests each function in the same way).

**Comment by sriyerg** [comment] 2020-06-01 20:36
In testing, it is known that a peripheral is being initialized for the very first time. So resetting the CSRs is not needed (wastes sim time / resource usage). Just from that perspective, my preference it to not reset the CSRs within `_init` but provide a separate `_reset` routine instead.

**Comment by silvestrst** [comment] 2020-06-02 14:49
@silvestrst (for gmail filters)

**Comment by alphan** [comment] 2020-06-04 13:52
For peripherals that don't need to track any states, it seems like we are roughly converging to an API with `create/new`, `config`, and `reset` along with disabling and enabling MIE (I didn't want to reiterate my earlier comment on this but you can read it [here](https://github.com/lowRISC/opentitan/pull/1510#pullrequestreview-356268297)).

But if we need to support this for a peripheral that has some sort of state tracking, either internally or in its `dif_<peripheral>_t` struct, we probably need to wait until the peripheral reaches some _safe_ state or reset it to such a state before or after the handoff. If you agree, then should this be handled in `config` or some other function like `dif_*_init_after_handoff` (imagine we have a better name)?

**Comment by lenary** [comment] 2020-06-24 09:03
I need to read all the feedback above, though I think we might be converging on something.

One thing to note is how Tock separates init from config, which we should probably pay attention to.

One of the thoughts I've been having is that potentially `_init` should explicitly not be allowed to write anything out to hardware registers, and is only for configuring parameters which are relevant for addressing the registers etc. This fits with what's needed for `rv_timer`, and also for `usbdev` (the two peripherals with the most complex DIF state, the former has parameters, the latter has a stack of buffers to maintain in the DIF itself). I think almost every other DIF only needs its base address in the initialisation call, as it doesn't maintain other state, but I might have overlooked something like `spi_dev` (I have, and I need to think further about the other fields in `dif_spi_device_t` which look to be replicating some HW state).

**Comment by alphan** [comment] 2022-06-21 12:20
@moidx @timothytrippel 

Closing this since part of this issue is based on a misunderstanding around DIFs and production code. Regarding init/config we settled on:
* `dif_ip_init()`: Initializes the `dif_ip_t` struct.
* `dif_ip_configure()`: Configures the peripheral.

Any other peripheral-specific functionality, e.g. resetting buffers, are implemented a needed.

**Closed by alphan** 2022-06-21 12:20 UTC
Labels: Component:Software, SW:DIF
