### ISSUE TITLE
[dv/rstmgr] Apply different reset kinds where applicable

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#16148] opened 2022-11-09 04:48 UTC
Most unit tests use the default apply_reset kind argument. The rstmgr unit has both AON and non-AON domain components, so the apply_reset distinction is important. One way to exercise it could be to call apply_reset with a randomized kind argument between rounds of various tests.

> estimate 8

**Comment by sriyerg** [comment] 2022-11-09 06:43
Please see example:
https://github.com/lowRISC/opentitan/blob/82278f92b83d280102116941dd1d6c19e6953bd8/hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv#L57

For `rv_dm` I defined 3 different reset strings, each with a different behavior, with the same goal as yours - be able to apply different kinds of resets randomly and verify expected behavior.

**Comment by andreaskurth** [comment] 2023-02-23 09:34
Triaged for `pwrmgr`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because this would increase coverage around resets, which IMO is relevant.

**Comment by GregAC** [comment] 2023-02-23 11:09
Triaged for `rstmgr`, agree with @andreaskurth

**Comment by matutem** [comment] 2024-02-22 22:43
I undated the issue to state it only applies to rstmgr, not clk or pwrmgr.

**Comment by matutem** [comment] 2024-08-20 00:25
In rstmgr_reset_vseq we apply random resets, which include hard (aon) and regular resets, so this issue can be declared complete.

**Closed** 2024-08-20 00:25 UTC
Labels: Component:DV, Priority:P2, IP:rstmgr, Earlgrey-PROD Candidate
