### ISSUE TITLE
Failed to read priv register. after mdw 0x8000 0x10 

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#7692] opened 2021-08-11 06:58 UTC
> mdw 0x8000 0x10
Failed to read priv register.

nicolast0604@nicolast0604-VirtualBox:~$ telnet localhost 4444
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
> mdw 0x8000 0x10
Failed to read priv register.
0x00008000: 2ad0006f 00000000 00000000 2a70006f 00000000 00000000 00000000 2970006f 
0x00008020: 00000000 00000000 00000000 2870006f 00000000 00000000 00000000 00000000 

> 
Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter speed' not 'adapter_khz'
Info : Hardware thread awareness created
force hard breakpoints
none separate

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 30000 kHz
Info : JTAG tap: riscv.tap tap/device found: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
Warn : JTAG tap: riscv.tap       UNEXPECTED: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
Error: JTAG tap: riscv.tap  expected 1 of 1: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
Error: Trying to use configured scan chain anyway...
Warn : Bypassing JTAG setup events due to errors
Info : datacount=2 progbufsize=8
Info : Examined RISC-V core; found 1 harts
Info :  hart 0: XLEN=32, misa=0x40101104
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'telnet' connection on tcp/4444
Error: Failed to read priv register.

> estimate 2

**Comment by andreaskurth** [comment] 2023-02-23 09:51
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because we should try to reproduce this and ensure there's no bug hiding here.

**Comment by GregAC** [comment] 2023-04-03 17:29
Revised estimate lower. Given this is an old issue it's worth spending a little time to try the actions that lead to the reported problem but not spending excessive time on it as many fixed have been occurring around debug.

**Comment by GregAC** [comment] 2023-04-11 15:09
Closing as other test cases will cover this and this is an old issue that hasn't been reported as broken again.

**Closed by GregAC** 2023-04-11 15:09 UTC
Labels: Component:FPGA, Priority:P2, Type:Question, IP:rv_dm, Milestone:D3, Triaged
