### ISSUE TITLE
[spi_device,dv] Track outstanding effort to bring covergroups above 90%

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#19081] opened 2023-06-28 13:46 UTC
### Description

As of the latest nightly regression, there are two individual covergroups below the 90% level.

- [tl_errors_cg_wrap::tl_errors_cg](https://reports.opentitan.org/hw/ip/spi_device/dv/latest/cov_report/grp4.html) 12/15 bins (80%)
- [spi_device_env_cov::fw_rx_fifo_size_cg](https://reports.opentitan.org/hw/ip/spi_device/dv/latest/cov_report/grp17.html) 7/8 bins (87.5%)

The effort to fix these has been deferred, hence this issue now tracks the outstanding effort to fix these items.

https://github.com/lowRISC/opentitan/issues/18365 previously tracked outstanding effort for a number of covergroups (including these two), closing that issue in favour of this one.

**Comment by antmarzam** [comment] 2024-05-23 13:44
`spi_device_env_cov::fw_rx_fifo_size_cg` is no longer relevant since FW mode has been removed.

`tl_errors_cg_wrap::tl_errors_cg` is already 100%. Last few regressions showing it:

- [13/05/24](https://reports.opentitan.org/hw/ip/spi_device_2p/dv/2024.05.13_03.56.53/cov_report/grp4.html)
- [15/05/24](https://reports.opentitan.org/hw/ip/spi_device_2p/dv/2024.05.15_03.07.51/cov_report/grp4.html)
- [17/05/24](https://reports.opentitan.org/hw/ip/spi_device_2p/dv/2024.05.17_06.39.50/cov_report/grp4.html)
- [20/05/24](https://reports.opentitan.org/hw/ip/spi_device_2p/dv/2024.05.20_04.11.28/cov_report/grp4.html)

Closing since this ticket is no longer relevant

**Closed by antmarzam** 2024-05-23 13:44 UTC
Labels: Component:DV, Priority:P2, IP:spi_device, Type:FutureRelease, Earlgrey-PROD Candidate
