### ISSUE TITLE
[rv_dm] "debug_req_o" is stuck at single bit at top level even I set NrHarts parameter's default to 2.

### ISSUE THREAD

**Issue by pbf2014** [lowRISC/opentitan#8049] opened 2021-09-02 19:53 UTC
Hello,

The RV_DM seems able to support multiple Harts since it has parameter NrHarts (default =1).

When I tried to integrate the RV_DM into a two cores/harts top level, I changed the default NrHarts  value to 2 in the IP's rv_dm.hjson, then it re-generated the rv_dm_reg_pkg.sv correctly with parameter NrHarts =2.

However during top level generation, somehow the rv_dm's output signal "debug_req_o" is still  single bit (at top level).

Just curious if this is correct way to change NrHarts setting, or there is bug in the topgen.py?

Thanks,
Bangfei

**Comment by rswarbrick** [comment] 2021-09-03 09:59
I think I can reproduce what you're seeing. I think that what's happening is that the top-level signal (here, called `rv_dm_debug_req`) is getting sized based on logic in the "intermodule" code. The connection between `rv_dm` and the (only) Ibex core is defined in `top_earlgrey.hjson` with this line:
```
hw/top_earlgrey/data/top_earlgrey.hjson:      'rv_dm.debug_req': ['rv_core_ibex.debug_req'],
```
The Ibex-side connection is just one bit wide and it seems that the Python code that figures out the size of the inter-module connection is using that, rather than the declared width from the debug module.

If you modify the toplevel more dramatically so that there are actually hosts (and thus two connections) then I think you'll see the 2-bit signal you expect.

I'm closing this for now but please feel free to re-open if you have more details and think you're seeing something weird.

**Comment by pbf2014** [comment] 2022-06-27 22:24
Hi Rupert,

Just to follow up this issue again.

Earlier I can workaround by changing the parameter setting of NrHarts from default 1 to 2 in rv_dm.hjson, then hacked the top level to wire each bit of "debug_req_o" to different cores.

However, when I looked further (the synthesis will report error as well in multiple harts case), the "rv_dm.sv" wrapper file is already hard coded to one bit.  (See  line 275/276 https://github.com/lowRISC/opentitan/blob/master/hw/ip/rv_dm/rtl/rv_dm.sv), even though the instantiated "dm_top" module supports multiple harts inside.

Can I reopen and put this request again so your team can modify the RTL and run through proper verification?

Thanks,
Bangfei

**Comment by sriyerg** [comment] 2022-06-28 02:15
This does seem like a bug. Thanks for catching it. I can make a fix soon. 

Please note that we only verify `NrHarts == 1` case - the onus is on you to verify `NrHarts != 1` design works as intended.

**Closed** 2022-06-28 15:07 UTC
Labels: Priority:P2, Type:Bug, Component:RTL, IP:rv_dm

**Comment by sriyerg** [comment] 2022-06-28 15:09
@pbf2014, the fix for this is now merged. Please rebase and try. Let us know if it is working for you.
