### ISSUE TITLE
[tlul] sequence item constraints miss to create proper transactions.

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#19263] opened 2023-07-21 15:25 UTC
### Description

I encountered this issue while debugging one block level tl_errors test.

From section 4.6 of the tile link spec 1.7.1 (current design supports),

"The mask is also used for messages without a data payload. When the operation size is smaller
than the data bus, the mask should be generated identically to an operation which does carry a
data payload."

For the "Get" transaction with size 1, it should have a contiguous 2bits mask based on address[1:0].
Transactions that do not adhere to this rule should be marked as errors.

Example of  the Transaction:

- command ; Get
- address[1:0] : 2'b1
- size : 1
- mask: 4'b0010

The transaction mentioned above should be marked as an error due to 
illegal size of mask.

RTL behaves accordingly but the Testbench (TB) fails to detect the error.
The problem in the TB comes from [this constraint](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/sv/tl_agent/tl_seq_item.sv;drc=820380a20267272e9b8b5e2fc2d041a8a32b7b74;l=16)

Desired constraint should be
   a_opcode != PutPartialData || $countones(a_mask) == (1 << a_size)

However, implementing this desired constraint triggers other dependencies of the constraint, leading to broader failure in the Testbench.
As a result, addressing this constraint issue is currently put on hold until we can find a suitable solution that does not cause broader failures in the Testbench

**Comment by msfschaffner** [comment] 2023-10-09 22:31
CC @rswarbrick @GregAC

**Comment by rswarbrick** [comment] 2024-06-03 11:41
I think that things have got a little bit confused in this issue.

The transaction in the example is a `Get` operation where `size=1`. But that's the logarithm of the size
in bytes, which would mean there are two bytes of data. The address is 3, which fails an alignment
constraint (which is presumably why the RTL is treating it as an error)

A mask of `'b10` is perfectly reasonable: it just means that the host only intends to use the second
byte of the response.

The proposed change to the constraint is wrong. The constraint is currently:
```systemverilog
// For PutFullData message, mask needs to match with size
`define chk_prot_mask_w_PutFullData \
  a_opcode != PutFullData || $countones(a_mask) == (1 << a_size)
  
```
and is a property that is supposed to be true for an item to be valid. This constraint is saying (in
a slightly confusing way) that if an operation is `PutFullData` then it should have all the bits set
in `a_mask`.

That constraint is correct. The proposed change would by constraining `PutPartialData` wrongly.

Frustratingly, I don't think I can see enough in this issue to reproduce the failure that triggered
it. I will close this because I don't think there's any useful information to take further here.

**Closed by rswarbrick** 2024-06-03 11:41 UTC
Labels: Component:DV, Priority:P2, Type:Bug, IP:tlul, Earlgrey-PROD Candidate
