### ISSUE TITLE
[csrng] Coverage

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15743] opened 2022-10-26 13:28 UTC
Coverage must be closed
- Over 90% for covergroup coverage, but some still to be implemented
- Code coverage below 90%, in particular branch/expression/FSM low
- Code coverage holes may reveal testplan holes or functional coverage plan holes that need addressing
- 6 days to close coverage (assuming no major holes revealed in tests/coverage plan)

original estimate: 24
> estimate before 2022-11-18 16
> remaining 2022-11-17 14
> estimate 8
> #spent 2
> remaining 2022-11-18 4
> remaining 2022-11-21 3
> remaining 2022-11-22 1

**Comment by andreaskurth** [comment] 2022-11-14 17:10
Taking current `master` (034eaeadf) with #16322 (test fix) and #16321 (AES coverage exclusion) applied, we currently get

|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm   |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:-------:|:-----------:|:------------:|
| 93.42 % | 96.07 % | 90.25 %  |   96.54 %   |   90.83 %    | 91.89 %  | 59.28 % |   95.83 %   |   67.09 %    |

## FSM coverage
- `csrng_main_sm`:
  - States (93%): `Error` missing (need to investigate)
  - Transitions (41%): those from any state to `Idle` and `Error` missing (to `Idle` is related with reset; to `Error` is due to that state missing)
- `csrng_ctr_drbg_gen`:
  - States (75%): `ReqError` missing (need to investigate)
  - Transitions (100%), which seems a bit strange given one state is missing
- `csrng_cmd_stage` instances 0 and 1:
  - States (90%) `Error` missing (need to investigate)
  - Transitions (41%): those from any state to `Idle` and `Error` missing (to `Idle` is related with reset; to `Error` is due to that state missing)
- `csrng_cmd_stage` instance 2:
  - States (100%)
  - Transitions (44%): those from any state except `Idle` to `Idle` and `Error`

- [ ] Investigate why `Error` states are missing
- [ ] Apply usual approach for covering FSM reset transitions (need to read up what that is)

## Functional coverage
TODO

**Comment by andreaskurth** [comment] 2022-11-16 15:41
Update:
- Most missing coverage is detailed in #16388
- FSM transitions to _Idle_ are related with disabling and re-enabling, which is tracked in #15747
- What remains to be tracked in this issue is functional coverage of `csrng_recov_alert_sts_cg`, where bins `ACMD_FLAG0_FIELD_ALERT`, `CS_BUS_CMP_ALERT`, and `CS_MAIN_SM_ALERT` are currently not getting hit.

**Comment by marnovandermaas** [comment] 2022-11-17 19:15
I fixed the sampling for the recoverable alerts. We now see coverage properly for `ACMD_FLAG0_FIELD_ALERT`, and `CS_BUS_CMP_ALERT`. You can see this fix here: https://github.com/lowRISC/opentitan/pull/16437

Still TODO: stimulate `CS_MAIN_SM_ALERT`

> estimate before 2022-11-17 24
> estimate 16
> spent 2
> remaining 2022-11-17 14

**Comment by marnovandermaas** [comment] 2022-11-18 12:17
Created PR to hit cs_main_sm_alert: https://github.com/lowRISC/opentitan/pull/16459

Also, I think a lot of this effort is already captured in other issues so I am pulling down the estimate to 4 because of that.

> estimate before 2022-11-18 16
> estimate 8
> spent 2
> remaining 2022-11-18 4

**Comment by vogelpi** [comment] 2022-11-18 17:57
I have been discussing with @ctopal today that coverage changed a bit due to the FSM reworking and it seems that dvsim doesn't correctly load the exclusion file for AES. This needs to be investigated.

@ctopal would you mind sharing the latest coverage results you've collected with and without AES exclusions here please? This would then allow us to plan further actions.

**Comment by vogelpi** [comment] 2022-11-21 09:41
Based on the latest nightly regression, coverage numbers are currently as follows: 

Score | Block | Branch | Statement | Expression | Toggle | Fsm | Assertion | CoverGroup
-- | -- | -- | -- | -- | -- | -- | -- | --
91.40 | 90.76 | 78.02 | 95.51 | 90.40 | 92.25 | 98.15 | 97.11 | 76.85

We need to investigate the following:
- Branch: it looks like the AES exclusions are not properly loaded. -> @ctopal , please investigate and fix this
- CoverGroup: several things need to be looked at:
  - csrng_sfifo_cg we have some coverage holes in the cross cover points, we need to investigate whether these make sense or not -> @vogelpi
  - csrng_err_code_cg: low coverage in cp_hw_inst_exc, cp_sw_cmd_sts_cmd_rdy/sts -> @marnovandermaas 
  - csrng_err_code_test_cg: SFIFO_CMD_ERR gets a huge amount of hits whereas other groups aren't hit. This doen'st look right -> @marnovandermaas

**Comment by ctopal** [comment] 2022-11-21 14:31
>Branch: it looks like the AES exclusions are not properly loaded. -> @ctopal , please investigate and fix this

I opened up https://github.com/lowRISC/opentitan/pull/16491 for this. It should fix the problem.

**Comment by vogelpi** [comment] 2022-11-21 14:51
Thanks for your feedback @marnovandermaas .

> > ```
> >   * csrng_err_code_cg: low coverage in cp_hw_inst_exc, cp_sw_cmd_sts_cmd_rdy/sts -> @marnovandermaas
> > ```
> 
> I think this is only raised when the reseed counter exceeds the reseed interval which is currently not tested by our DV. Is this understanding correct? And do we want to extend the DV environment to hit this case?

The `csrng_intr` test has a function called `test_cs_hw_inst_exc()` to test this explicitly - at least `cp_hw_inst_exc` should be hit by this. Can you have a look at this please?

> 
> > ```
> >   * csrng_err_code_test_cg: SFIFO_CMD_ERR gets a huge amount of hits whereas other groups aren't hit. This doen'st look right -> @marnovandermaas
> > ```
> 
> From a run of 600 iterations of `csrng_err` test that I did on my local PC, all of the `err_code_test_cp` are being hit.

This is good to know. But how is the distribution? IIRC, the current dashboard indicates that this SFIFO_CMD_ERR is hit more than 150 times. Maybe it gets many hits in the `csrng_intr` test?

**Comment by marnovandermaas** [comment] 2022-11-21 15:54
> This is good to know. But how is the distribution? IIRC, the current dashboard indicates that this SFIFO_CMD_ERR is hit more than 150 times. Maybe it gets many hits in the `csrng_intr` test?

On my local runs `csrng_intr`, `csrng_alert`, `csrng_cmds`, `csrng_stress_all` and all the V1 tests do not hit any of the `csrng_err_code_test_cg` at all. As for the distribution of the `csrng_err` test, it seems to hit each bucket between 2 and 11 times for 600 iterations. I'm not exactly sure why there is a mismatch with the nightlies.

I will have a look at the `hw_inst_exc` now until I have a further thought on why this is.

**Comment by vogelpi** [comment] 2022-11-21 16:22
Thanks @marnovandermaas for feeding back. I think the `csrng_err_code_test_cg` isn't hit by `csrng_intr` because `csrng_intr` uses `cfg.which_fatal_err` instead of `cfg.which_err_code`. Only the latter includes the test bits. Thanks for looking into `hw_isnt_exc`.

**Comment by marnovandermaas** [comment] 2022-11-21 18:40
While investigating the value of `hw_exc_sts`, I couldn't find the logic for detecting an overflow of the reseed counter. I created a separate issue for it: https://github.com/lowRISC/opentitan/issues/16499

Tomorrow I will debug the `test_cs_hw_inst_exc()` which should work despite how the reseed counter works because it forces an illegal status.

> spent 4
> estimate before 2022-11-21 8
> estimate 12
> remaining 2022-11-21 4

**Comment by vogelpi** [comment] 2022-11-21 23:37
Here the latest coverage results:
|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm   |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:-------:|:-----------:|:------------:|
| 95.93 % | 97.60 % | 93.41 %  |   98.54 %   |   91.03 %    | 92.10 %  | 96.30 % |   96.47 %   |   78.54 %    |

Branch coverage is now good, thanks @ctopal !

CoverGroup keeps being below the requirement:
- cp_hw_inst_exc is still not hit -> @marnovandermaas 
- cp_sw_cmd_sts_cmd_rdy/sts are still not hit -> @ctopal ?
- cp_csrng_aes_fsm_err is not fully hit, let's increase the number of seeds further + change the distribution also for `which_fatal_alert` which is used by `csrng_intr` test (previously I changed the distribution for `which_err_code` used by `csrng_err` only. -> @vogelpi 
- csrng_sfifo_cg: some points/crosses will be hit by the disable/re-enable test of @andreaskurth 
- genbits_depth_cross: none of the cross points are hit where more than one genbits FIFO is full, as those FIFOs have a depth of just 1 this means no case is hit where more than one genbits FIFO valid data in it. This needs to be investigated. IMHO this is an important scenario we should hit.

**Comment by marnovandermaas** [comment] 2022-11-22 12:38
Ok for `cp_hw_inst_exc`, I have now opened a PR to fix the coverage assuming the current testing approach: https://github.com/lowRISC/opentitan/pull/16508

**Comment by vogelpi** [comment] 2022-11-22 16:14
I am now running a regression with coverage including all open CSRNG PRs. I will post the results shortly.

**Comment by marnovandermaas** [comment] 2022-11-22 16:54
Created 2 more PRs to help close this one out:
- https://github.com/lowRISC/opentitan/pull/16508
- https://github.com/lowRISC/opentitan/pull/16509

> estimate before 2022-11-22 12
> estimate 14
> spent 2
> remaining 2022-11-22 2

**Comment by vogelpi** [comment] 2022-11-22 17:16
Latest coverage numbers (Canberk's PR not included):
|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm   |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:-------:|:-----------:|:------------:|
| 96.12 % | 97.71 % | 93.76 %  |   98.64 %   |   91.14 %    | 92.25 %  | 98.18 % |   97.14 %   |   79.95 %    |

I don't know why CoverGroup is still that low. Almost all coverpoints inside cov_if are being hit.

**Comment by vogelpi** [comment] 2022-11-22 17:59
@andreaskurth and I have just analyzed the situation. The problem is that the `csrng_host_cmd_cg` and maybe also `csrng_genbits_cg` defined inside `csrng_agent` have very low coverage. In particular the invalid commands are never sampled resulting in extremely low cross coverage. What we need to do:
1. When pushing invalid commands, sample before getting the response because there will be no response. We already fixed this for the `alert_test` but not for the agent itself.
2. Randomize the `alert_test` to run invalid commands with varying glen, clen, flag0 etc. to push up the cross coverage.

I'll look into that later today.

**Comment by vogelpi** [comment] 2022-11-22 23:16
Some progress, still not there yet.

|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm    |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:--------:|:-----------:|:------------:|
| 96.44 % | 97.73 % | 93.80 %  |   98.68 %   |   90.96 %    | 92.25 %  | 100.00 % |   97.14 %   |   88.42 %    |

**Comment by vogelpi** [comment] 2022-11-23 00:30
Now we're almost there:
|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm    |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:--------:|:-----------:|:------------:|
| 96.52 % | 97.74 % | 93.85 %  |   98.70 %   |   91.21 %    | 92.25 %  | 100.00 % |   97.14 %   |   89.66 %    |

I am stopping here for today and will push a PR with the changes to get to this point together with some hints on what to try out further: Here's the full coverage report: [cov_report.tar.zip](https://github.com/lowRISC/opentitan/files/10072089/cov_report.tar.zip)

**Comment by vogelpi** [comment] 2022-11-23 00:51
The PR is here: https://github.com/lowRISC/opentitan/pull/16531

**Comment by marnovandermaas** [comment] 2022-11-23 09:45
This PR should improve coverage to over the required 90%: https://github.com/lowRISC/opentitan/pull/16531

**Closed** 2022-11-24 10:23 UTC
Labels: Component:DV, IP:csrng, Milestone:V2
