### ISSUE TITLE
[entropy_src] Coverage items to pass V2 threshold

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16063] opened 2022-11-07 15:09 UTC
Get the remaining two V2 tests above 90% pass rate.

>estimate 16
>remaining 2022-11-08 12
>remaining 2022-11-14 2

**Comment by andreaskurth** [comment] 2022-11-08 08:24
Preliminary results with recent `entropy_src` PRs (not merged as of yesterday morning) look promising; will reassess once those PRs are merged.

**Comment by andreaskurth** [comment] 2022-11-08 18:05
> remaining 2022-11-08 12

**Comment by andreaskurth** [comment] 2022-11-09 12:55
Current `master` plus PRs #14907, #16088, #16095, #16101, #16102, and #16103 applied:

### Test Results
Only `entropy_src_rng` test has <90% (42/50) pass rate. 7/8 fails are due to this check failing
https://github.com/lowRISC/opentitan/blob/0aa0b1cbfde8c0ad4646c90615404e0a1b5a3f3f/hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv#L1761-L1764
with `reg name: entropy_src_reg_block.repcnt_total_fails`. @martin-lueker: Is this something you are aware of, or should I investigate?

### Coverage Results

|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm    |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:--------:|:-----------:|:------------:|
| 94.72 % | 98.76 % | 96.54 %  |   98.96 %   |   95.89 %    | 81.54 %  | 100.00 % |   91.29 %   |   92.05 %    |

Only toggle coverage is currently <90%. This was discussed on Monday and should be fixed with additional refines.

**Comment by martin-lueker** [comment] 2022-11-10 20:50
> ### Test Results
> Only `entropy_src_rng` test has <90% (42/50) pass rate. 7/8 fails are due to this check failing
> 
> 
> with `reg name: entropy_src_reg_block.repcnt_total_fails`. @martin-lueker: Is this something you are aware of, or should I investigate?

This should be fixed by: https://github.com/lowRISC/opentitan/pull/16223

**Comment by andreaskurth** [comment] 2022-11-10 21:38
That would be amazing, thanks @martin-lueker! I'll run a full regression tomorrow and post the results.

**Comment by andreaskurth** [comment] 2022-11-11 09:52
[Current `master`](https://github.com/lowRISC/opentitan/tree/5a2b91c453b610dea9496579cc472efb1379bfe7) plus PR #16101 applied:

## Test Results

Only `entropy_src_fw_ov` has <90% (43/50) pass rate.
- 4/7 fails are due to `UVM_ERROR (entropy_src_scoreboard.sv:1773) [scoreboard] Check failed csr.get_mirrored_value() == item.d_data (* [*] vs * [*]) reg name: entropy_src_reg_block.recov_alert_sts`.
- 3/7 fails are due to `UVM_ERROR (cip_base_scoreboard.sv:214) [scoreboard] Check failed exp_alert[alert_name] == * (* [*] vs * [*]) alert recov_alert triggered unexpectedly`.

## Coverage Results

|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm   |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:-------:|:-----------:|:------------:|
| 92.63 % | 98.74 % | 96.48 %  |   98.92 %   |   95.22 %    | 81.20 %  | 97.87 % |   91.29 %   |   77.19 %    |

Toggle coverage will be fixed by additional refines, for which a PR should pop up later today.

### Functional Coverage

- Coverpoints are 100% hit except `one_way_ht_threshold_reg_cg.cp_offset` (7/9) bins `one_way_regs[{80,84}]`.
- Crosses below 90% are:
  - `csrng_hw_cg.cr_config` (319/720)
  - `observe_fifo_event_cg.cr_config` (258/480)
  - `cont_ht_cg.cr_all` (139/200)
  - `one_way_ht_threshold_reg_cg.cr_cross` (28/36) due to `cp_offset` (see above).

I'll try resolving the missing bins in the crosses
1. checking if some bins should be ignored or illegalized
2. tweak the test configs to cover more cross combinations
3. extend existing tests to cover more cross combinations

(with decreasing priority).

**Comment by andreaskurth** [comment] 2022-11-11 20:02
> remaining 2022-11-11 8

**Comment by martin-lueker** [comment] 2022-11-11 23:50
> 

Hi Andreas,
   Somehow my commentary on this was lost. Trying again.
   
I'm really surprised that that the functional coverage dropped so much.  Here are my local results from last night:
![image](https://user-images.githubusercontent.com/47870387/201442875-0ed22185-c3e5-4e91-ad63-3883594533fd.png)

With better rate on the `entropy_src_fw_ov` test.   (5 failures as opposed to 7, same errors as before).  Looking at the nature of the errors it seems that they are very similar (missing the prediction of an alert).  I'll try to have a fix in about a day or so.

Looking really closely at your statistics for the large covergroups, I see that I've missed some of your recent PR's in the last couple days.  (This explains the higher coverage on my local branch compared to mine) With the new CP for `otp_en_es_fw_over` and the addition to the crosses, that is going to reduce the coverage a fair deal, particularly on the maximally large `config` crosses.  One can add more crosses to debug/dilute the shortcomings in these high-dimensional `config` covergroups, but the only thing that will close them is to do more runs.   Most of the config coverage in the `entropy_src_rng` and `entropy_src_fw_ov` tests comes from stopping the DUT and restarting it many times, but the OTP values belong to the `env_cfg` (not the `dut_cfg`) which is fixed over the course of a run, as OTP is expected to be.

I'll rebase to master and try to reproduce your regression here. I'll also check if kicking up the run-count to 100 (or 200?) runs solves the problem.

**Comment by martin-lueker** [comment] 2022-11-13 23:39
`entropy_src_fw_ov` bugs are now fixed by #16301.  `entropy_src_fw_ov` test is now running at 100% (in 300 runs).
Some new errors however are cropping up in `entropy_src_rng` though the pass rate there is high: 97.33%

**Comment by martin-lueker** [comment] 2022-11-14 00:00
In #16302, I've also made the constraint and regression changes mentioned above with the following coverage results.

## Coverage Results

|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm   |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:-------:|:-----------:|:------------:|
| 94.71 % | 98.76 % | 96.54 %  |   98.92 %   |   95.04 %    | 82.15 %  | 97.87 % |   91.29 %   |   92.73 %    |

Results are for `master` (SHA: 51042ef5b7) plus #16301 and #16302.

I am reasonably confident that these covergroup changes would continue to fill out those large cross covergroups with enough simulation, with one exception: `cont_ht_cg.cr_all`.  If there is any place where refinement is now merited I think that is the spot.

I am also curious as to why the FSM coverage has dropped below 100%.  I'll have to take a look at that after the review.  There are a number of small documentation items I have to submit before then.

**Comment by andreaskurth** [comment] 2022-11-14 10:05
That's fantastic, thanks a lot @martin-lueker! I'll resolve toggle coverage in https://github.com/lowRISC/opentitan/pull/16256 and https://github.com/lowRISC/opentitan/pull/16270.

> remaining 2022-11-14 2

**Comment by andreaskurth** [comment] 2022-11-16 10:10
Those two PRs are superseded by #16378. Merging the latter shall close this issue.

**Comment by martin-lueker** [comment] 2022-11-16 20:38
FYI #16378 is merged.

**Comment by andreaskurth** [comment] 2022-11-17 10:57
Thanks @martin-lueker. With the current `master` (2807f454179b593fd978449c7af7ddab0946328e) plus the syntax fix for `entropy_src_UNR.vRefine` in #16421 applied, a full regression results in:

|  Score  |  Block  |  Branch  |  Statement  |  Expression  |  Toggle  |   Fsm   |  Assertion  |  CoverGroup  |
|:-------:|:-------:|:--------:|:-----------:|:------------:|:--------:|:-------:|:-----------:|:------------:|
| 97.82 % | 99.07 % | 97.42 %  |   99.65 %   |   94.70 %    | 99.96 %  | 97.87 % |   91.29 %   |   92.93 %    |

Coverage requirements are therefore met. :+1:

**Closed by andreaskurth** 2022-11-17 10:57 UTC
Labels: Component:DV, IP:entropy_src, Milestone:V2
