### ISSUE TITLE
[sysrst_ctrl] V2.5 TODOs

### ISSUE THREAD

**Issue by rnongie** [lowRISC/opentitan#18386] opened 2023-05-05 23:20 UTC
### Description

TODOs defined in [sysrst_ctrl Effort Scoping](https://docs.google.com/document/d/1q-rwRolWvOFtreGTS9BJOzAVWKgCWERKQ2Ohm_Yc0XM/edit#)

D2.5 / V2.5 TODO links
Do a full OpenTitan reset to check the EC stretch functionality [ec_pwr_on_rst_vseq#L48](https://github.com/marnovandermaas/opentitan/blob/47eff2793614d9169b56f40b3161b595e9c1853f/hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ec_pwr_on_rst_vseq.sv#L48) (1 d .. 4 d)

>estimate 16

**Comment by msfschaffner** [comment] 2023-05-08 17:06
CC @moidx @msfschaffner

**Comment by GregAC** [comment] 2023-05-09 09:48
@marnovandermaas any action needed for this TODO for M2.5.1?

**Comment by msfschaffner** [comment] 2023-05-10 02:23
I believe I intended to look into the sim to confirm @marnovandermaas finding that this is only a DV issue.
I will move it to M2.5.2, once confirmed.

**Comment by marnovandermaas** [comment] 2023-05-10 12:13
These TODOs have already been resolved in the main branch:
https://github.com/marnovandermaas/opentitan/blob/1bc8c83901c3cd8be9879d39a9d0a9b769ae32ba/hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ec_pwr_on_rst_vseq.sv#L48

**Closed by marnovandermaas** 2023-05-10 12:13 UTC
Labels: Component:DV, Priority:P1, IP:sysrst_ctrl, Submilestone:M2.5.1
