### ISSUE TITLE
[flash_ctrl] Compilation Errors In Base Testbench

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#10480] opened 2022-01-30 15:56 UTC
I am seeing the following issues in the base testbench components, which are giving me compilation errors.  Note this is using Xcellium

1) File : mem_bkdir_util.sv

Error seen:

```
xmvlog: *E,ILLPRI (../src/lowrisc_dv_mem_bkdr_util_0/mem_bkdr_util.sv,508|67): illegal expression primary [4.2(IEEE)].
(`include file: ../src/lowrisc_dv_mem_bkdr_util_0/mem_bkdr_util.sv line 508, file: ../src/lowrisc_dv_mem_bkdr_util_0/mem_bkdr_util_pkg.sv line 47)
package worklib.mem_bkdr_util_pkg:sv
errors: 1, warnings: 0
file: ../src/lowrisc_dv_sec_cm_0/sec_cm_pkg.sv
```

Code and possible fix:

```systemverilog
  virtual function void set_mem();
    bit res;
    `uvm_info(`gfn, "Set memory", UVM_LOW)
    for (int i = 0; i < depth; i++) begin
      res = uvm_hdl_deposit($sformatf("%0s[%0d]", path, i), '1);                                                 <-- POSSIBLE FIX
//      res = uvm_hdl_deposit($sformatf("%0s[%0d]", path, i), {default: '1});                               <-- GIVES ERROR
      `DV_CHECK_EQ(res, 1, $sformatf("set_mem uvm_hdl_deposit failed at index %0d", i))
    end
  endfunction
```

2) File: cip_base_pkg.sv

After 'fixing' the bove problem locally, I now see this

Error Seen:

```
xmvlog: *E,ILLPRI (../src/lowrisc_dv_cip_lib_0/cip_base_pkg.sv,94|22): illegal expression primary [4.2(IEEE)].
(`define macro: DV_CHECK [../src/lowrisc_dv_dv_macros_0/dv_macros.svh line 86], `define macro: DV_CHECK_FATAL [../src/lowrisc_dv_dv_macros_0/dv_macros.svh line 190], `define macro: DV_CHECK_STD_RANDOMIZE_WITH_FATAL [../src/lowrisc_dv_dv_macros_0/dv_macros.svh line 254], `define macro: _DV_MUBI_RAND_VAL [../src/lowrisc_dv_cip_lib_0/cip_base_pkg.sv line 83], file: ../src/lowrisc_dv_cip_lib_0/cip_base_pkg.sv line 94)
 `_DV_MUBI_RAND_VAL(4)
                                      |
 xmvlog: *E,ILLPRI (../src/lowrisc_dv_cip_lib_0/cip_base_pkg.sv,94|22): illegal expression primary [4.2(IEEE)].
```

Code Fix - Temporary Comment Out Lines:

```systemverilog
  // Create function - get_rand_mubi4_val
//  `_DV_MUBI_RAND_VAL(4)                        <-- COMMENT OUT
  // Create function - get_rand_mubi8_val
//  `_DV_MUBI_RAND_VAL(8)                        <-- COMMENT OUT
  // Create function - get_rand_mubi12_val
//  `_DV_MUBI_RAND_VAL(12)                        <-- COMMENT OUT
  // Create function - get_rand_mubi16_val
//  `_DV_MUBI_RAND_VAL(16)                        <-- COMMENT OUT

  `undef _DV_MUBI_RAND_VAL

  // Currently lc_tx_t is exactly the same as mubi4_t. Create a separate function in case these
  // 2 types are changed differently in the future.
  function automatic lc_ctrl_pkg::lc_tx_t get_rand_lc_tx_val(int t_weight = 2,
                                                             int f_weight = 2,
                                                             int other_weight = 1);
//    return lc_ctrl_pkg::lc_tx_t'(get_rand_mubi4_val(t_weight, f_weight, other_weight));                          <-- COMMENT OUT
  endfunction
```

I have made these 'fixes' locally to my repository which allows me to move forward, they need correcting ASAP

**Comment by rswarbrick** [comment] 2022-01-31 10:18
Nit: If you're putting big code examples in a GitHub issue or PR, please use markdown to make them more readable. I'll fix this up now, but it will save people time if you can do it yourself.

**Comment by rswarbrick** [comment] 2022-01-31 10:23
For the first fix: yep, I completely agree. Please could you make a PR?

For the second, the problem is that @msfschaffner switched the `lc_ctrl_t` encoding in d4655407b4. We were surprised that nothing broke, but it looks like we spoke too soon :-) The easiest fix is probably to define a function from `logic [3:0]` to itself that is a bijection and maps the true/false magic values appropriately. Then we can just apply it to the rather finicky mubi4_t randomisation that already exists. Are you able to make a PR to do that too?

**Comment by TimEwins** [comment] 2022-01-31 10:34
@rswarbrick As this is backbone TB code, it is not directly under my control (flash_ctrl), so I would suggest one of the other assignees take a look at this.  I am not sure I am allowed to PR for these changes.  Thanks.

**Comment by rswarbrick** [comment] 2022-01-31 10:40
You absolutely are! That's the joy of an open source project :-) Otherwise, someone will probably fix things eventually but it's going to be much quicker to do it yourself!

**Comment by tjaychen** [comment] 2022-01-31 17:56
I think @sriyerg is looking at a different overall fix for this as well.
But we should probably merge something quickly.

**Comment by sriyerg** [comment] 2022-01-31 22:09
#10494 fixes the second issue.

**Comment by sriyerg** [comment] 2022-01-31 22:11
> @rswarbrick As this is backbone TB code, it is not directly under my control (flash_ctrl), so I would suggest one of the other assignees take a look at this. I am not sure I am allowed to PR for these changes. Thanks.

You are free (and encouraged) to change anything that needs to be fixed - that is why we have a strict code review process in place.

**Closed** 2022-02-01 01:17 UTC
Labels: Priority:P1
