### ISSUE TITLE
CL S/W Test-Status I/F does not allow time for CDC to complete

### ISSUE THREAD

**Issue by yehuda-bejar** [lowRISC/opentitan#16211] opened 2022-11-10 16:51 UTC
When a S/W test is run on the Chip-Level test-bench, the simulation ends soon after the S/W Test Status I/F line "sw_test_done" is asserted.
In some IP's, write accesses to the CSR registers go via CDC logic in module: prim_reg_cdc.
This module has an internal signal "src_req" which is derived, directly from reg_we at the source domain
and another internal signal "src_ack" which is derived from the FIFO at the destination side.

The problematic scenario:
A CSR transaction starts (e.g. by the S/W) and shortly after, the S/W's test_main exits, which causes the simulation to "$finish".
The simulation will end AFTER "src_req" assertion but BEFORE "src_ack" assertion.

Module prim_reg_cdc has the following assertion:

  // If busy goes high, we must eventually see an ack
  `ASSERT(HungHandShake_A, $rose(src_req) |-> strong(##[0:$] src_ack), clk_src_i, !rst_src_ni)

So in the problematic scenario, this assertion will be offended at the last timepoint of the simulation.

Since UVM's report is also generated at that timepoint, the UVM report will not "notice" this error and will declare "test passed" in the log.
However, the "UVM_ERROR" associated with this assertion does appear in the run log,
so when dvsim greps all "ERROR" occurances in the log, it will see this one and will classify this tests run as fail.

This is problematic because:
1. it is confusing: UVM says "pass" bit dvsim says "fail".
2. this is a false error.

**Comment by tjaychen** [comment] 2022-11-10 16:52
do you know which module this is? 
@sriyerg went through this exercise a little while ago and we purposely silenced all transactions at the end of test.

**Comment by sriyerg** [comment] 2022-11-10 17:23
`dvsim` is correctly flagging the test failure because the test completed when there was still some unfinished activity in the DUT. 
You will most likely need to update the SW test to completely silience the DUT before exiting. 

This bug is a duplicate of https://github.com/lowRISC/opentitan/issues/14913. Lets use that one for discussion. I will close this, thanks!

**Closed** 2022-11-10 17:23 UTC
