### ISSUE TITLE
[clkmgr] rst_ni connection incorrect?

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#18328] opened 2023-05-04 09:41 UTC
### Description

There are some comments about rst_ni connections being incorrect in ip/clkmgr/rtl/clkmgr.sv -

  // the rst_ni connection below is incorrect, need to find a proper reset in the sequence to use
  // if the clkmgr is always on, can use por synced directly
  // if not, then need to generate something ahead of lc/sys

There is no accompanying TODO in the RTL. Is there a potential issue here, and/or is it being tracked somewhere, please?

Thanks -A
@matutem @johngt

**Comment by johngt** [comment] 2023-05-04 09:42
Thanks @alees24.
Yes we will probably need @matutem and @msfschaffner to look into this. Flagging also to @cindychip / @GregAC

**Comment by msfschaffner** [comment] 2023-05-04 20:25
Thanks for flagging this @alees24!

That file is stale and not used in `top_earlgrey`.
The correct file can be found here: https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv

Let me explain the history of this:

Several IPs, especially infrastructural ones like `rv_plic` and the `*mgrs` are partially templated to tailor them to a specific top-level configuration.

During initial development of these IPs, the template was rendered and checked into the IP subfolder under `hw/ip/<ipname>`. As we started to integrate these into the top-level, it became apparent that it makes more sense to keep the generated, top-specific parts under `hw/top_<name>/ ip/` instead.

The problem is that the tree still contains some of the old and stale files, since initially some lint targets still relied on that code. This is of course not ideal and we intend to clean this up and use a standardized way for generating such templated IPs - see https://github.com/lowRISC/opentitan/issues/8440.

Unfortunately we did not get to that yet due to our priorities, but I expect this to be cleaned up as part of the multi-top push.

**Comment by msfschaffner** [comment] 2023-05-04 20:26
Hence, I think we can close this unless you have any other questions regarding this topic - feel free to reopen :).

**Closed by msfschaffner** 2023-05-04 20:26 UTC
Labels: Component:RTL, IP:clkmgr
