### ISSUE TITLE
[test-triage] chip_sw_lc_walkthrough_testunlocks timeout

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15371] opened 2022-10-10 14:04 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
UVM_FATAL @ * us: (chip_sw_lc_walkthrough_testunlocks_vseq.sv:49) [chip_sw_lc_walkthrough_testunlocks_vseq] wait timeout occurred! has 3 failures:

Test chip_sw_lc_walkthrough_testunlocks has 3 failures.
0.chip_sw_lc_walkthrough_testunlocks.1250555558
Line 493, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_lc_walkthrough_testunlocks/latest/run.log

  UVM_FATAL @ 12908.820910 us: (chip_sw_lc_walkthrough_testunlocks_vseq.sv:49) [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] wait timeout occurred!
  UVM_INFO @ 12908.820910 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
  
1.chip_sw_lc_walkthrough_testunlocks.2704384854
Line 486, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_lc_walkthrough_testunlocks/latest/run.log

  UVM_FATAL @ 13032.561491 us: (chip_sw_lc_walkthrough_testunlocks_vseq.sv:49) [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] wait timeout occurred!
  UVM_INFO @ 13032.561491 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

```
UVM_FATAL @ * us: (chip_sw_lc_walkthrough_vseq.sv:61) [chip_sw_lc_walkthrough_vseq] wait timeout occurred! has 10 failures:

Test chip_sw_lc_walkthrough_dev has 3 failures.

0.chip_sw_lc_walkthrough_dev.3923158565
Line 490, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_lc_walkthrough_dev/latest/run.log

  UVM_FATAL @ 12631.841647 us: (chip_sw_lc_walkthrough_vseq.sv:61) [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_vseq] wait timeout occurred!
  UVM_INFO @ 12631.841647 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
  
1.chip_sw_lc_walkthrough_dev.4242067
Line 493, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_lc_walkthrough_dev/latest/run.log

  UVM_FATAL @ 12427.461193 us: (chip_sw_lc_walkthrough_vseq.sv:61) [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_vseq] wait timeout occurred!
  UVM_INFO @ 12427.461193 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
```

Timeouts are occurring again now. This behaviour was one of two observed in previous issue [[test-triage] chip_sw_lc_walkthrough_dev chip_sw_lc_walkthrough_prod chip_sw_lc_walkthrough_rma](https://github.com/lowRISC/opentitan/issues/14389)

### Steps to Reproduce

- Commit hash where failure was observed: [c2a8c64cc](https://github.com/lowrisc/opentitan/tree/c2a8c64ccbca39707be7883dfd2f8c1100813730)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_lc_walkthrough --fixed-seed 1250555558 --build-seed 4265629825 --waves -v h
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_lc_walkthrough --fixed-seed 3923158565 --build-seed 4265629825 --waves -v h
- Observed in over weekend tests

### Tests with similar or related failures

- [ ] chip_sw_lc_walkthrough_dev
- [ ] chip_sw_lc_walkthrough_prod
- [ ] chip_sw_lc_walkthrough_prodend
- [ ] chip_sw_lc_walkthrough_rma
- [ ] chip_sw_lc_walkthrough_testunlocks

**Comment by johngt** [comment] 2022-10-10 14:08
Previously cindychip / tjaychen / andreaskurth worked on this.
Not tagging but just capturing here.
Suggestion @engdoreis is to attempt this on a local machine and see if timeout is occurring, then if it is increase timeout and replicate. Given that this is named as testunlocks this may be expected behaviour so deprioritise over other on-call items.

**Comment by engdoreis** [comment] 2022-10-11 09:39
This bug is responsible for 22.22% of the failures on October 11 execution.

**Comment by andreaskurth** [comment] 2022-10-11 15:22
I could reproduce the failure locally at https://github.com/lowrisc/opentitan/tree/c2a8c64ccbca39707be7883dfd2f8c1100813730 with `--fixed-seed 3923158565 --build-seed 4265629825`. From the following run log, I think the test is stuck in Boot ROM and does not even reach the SW binary:
```
UVM_INFO @ 0.000000 us: reporter [RNTST] Running test chip_base_test...
UVM_INFO @   0.000000 us: (chip_env_cfg.sv:129) [cfg] ral_model_names: '{"chip_reg_block"}

Warning-[CNST-PPRW] Constraint randomize NULL object warning
../src/lowrisc_dv_dv_lib_0/dv_base_test.sv, 41
  Member object 'm_jtag_agent_cfg' was found to be NULL during randomization.
  Please make sure all random variables/arrays/function calls being randomized
  are allocated fully and properly.


Warning-[CNST-PPRW] Constraint randomize NULL object warning
../src/lowrisc_dv_dv_lib_0/dv_base_test.sv, 41
  Member object 'jtag_dmi_ral' was found to be NULL during randomization.
  Please make sure all random variables/arrays/function calls being randomized
  are allocated fully and properly.

UVM_INFO @   0.000000 us: (chip_base_test.sv:95) uvm_test_top [uvm_test_top] test_timeout_ns = 60000000
UVM_INFO @   0.000000 us: (mem_bkdr_util.sv:533) [mem_bkdr_util[FlashBank0Info]] Set memory
UVM_INFO @   0.000000 us: (mem_bkdr_util.sv:533) [mem_bkdr_util[FlashBank1Info]] Set memory
UVM_INFO @   0.000000 us: (tb.sv:275) [mem_bkdr_util[Otp]] Loading mem from file:
otp_ctrl_img_raw.vmem
UVM_INFO @   0.000000 us: (mem_bkdr_util.sv:542) [mem_bkdr_util[Rom]] Randomizing mem contents
UVM_INFO @   0.000000 us: (mem_bkdr_util.sv:524) [mem_bkdr_util[OtbnImem]] Clear memory
UVM_INFO @   0.000000 us: (mem_bkdr_util.sv:524) [mem_bkdr_util[OtbnDmem0]] Clear memory
UVM_INFO @   0.000000 us: (chip_base_vseq.sv:44) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] Asserting POR_N
  0.000000 us: Illegal instruction (hart 0) at PC 0xxxxxxxxx: 0xxxxxxxxx
  0.000000 us: Illegal instruction (hart 0) at PC 0xxxxxxxxx: 0xxxxxxxxx

tb.dut.u_ast.u_sys_clk.u_sys_osc: System Clock Power-up Frequency: 30623181 Hz

tb.dut.u_ast.u_usb_clk.u_usb_osc: USB Clock Power-up Frequency: 33966237 Hz
tb.dut.u_ast.u_usb_clk.u_usb_osc: USB Clock Drift: 33 ps

tb.dut.u_ast.u_aon_clk.u_aon_osc: AON Base Clock Power-up Frequency: 156421 Hz
tb.dut.u_ast.u_aon_clk.u_aon_osc: AON 1.0xBase Clock Power-up Frequency: 156421 Hz

tb.dut.u_ast.u_io_clk.u_io_osc: IO Clock Power-up Frequency: 30623181 Hz
UVM_INFO @  10.000000 us: (chip_base_vseq.sv:48) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] POR_N complete
UVM_INFO @  10.997367 us: (mem_bkdr_util.sv:533) [mem_bkdr_util[FlashBank0Data]] Set memory
UVM_INFO @  10.997367 us: (mem_bkdr_util.sv:533) [mem_bkdr_util[FlashBank1Data]] Set memory
UVM_INFO @  10.997367 us: (mem_bkdr_util.sv:542) [mem_bkdr_util[RamRet0]] Randomizing mem contents
UVM_INFO @  10.997367 us: (tb.sv:309) [mem_bkdr_util[Rom]] Loading mem from file:
test_rom_sim_dv.39.scr.vmem
UVM_INFO @  10.997367 us: (tb.sv:234) [mem_bkdr_util[FlashBank0Data]] Loading mem from file:
lc_walkthrough_testunlocks_test_prog_sim_dv.64.scr.vmem
UVM_INFO @  10.997367 us: (chip_sw_lc_walkthrough_testunlocks_vseq.sv:37) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] OTP unlock token 1f9f926dc54a284bfc8daaf9ffa08504 and OTP exit token d37f93f94b81d3a6bd30d839699e76bf
UVM_INFO @  10.997367 us: (chip_sw_base_vseq.sv:459) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] Overwriting symbol "kOtpExitToken" via backdoor in FlashBank0Data: abs addr = 0x2000366c, mem addr = 0x366c, size = 16, addr_mask = 0x7ffff
UVM_INFO @  10.997367 us: (chip_sw_base_vseq.sv:459) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] Overwriting symbol "kOtpUnlockToken" via backdoor in FlashBank0Data: abs addr = 0x2000365c, mem addr = 0x365c, size = 16, addr_mask = 0x7ffff
UVM_INFO @ 2510.523044 us: (chip_sw_base_vseq.sv:527) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] LC status LcReady.
UVM_INFO @ 2514.823044 us: (chip_sw_base_vseq.sv:628) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] Start LC transition request from DecLcStRaw state to DecLcStTestUnlocked0 state
UVM_INFO @ 2528.343044 us: (chip_sw_base_vseq.sv:650) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] Sent LC transition request
UVM_INFO @ 2620.733661 us: (chip_sw_base_vseq.sv:527) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] LC status LcTransitionSuccessful.
UVM_INFO @ 2620.733661 us: (chip_sw_base_vseq.sv:653) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] LC transition request succeed!
UVM_INFO @ 2620.733661 us: (chip_base_vseq.sv:44) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] Asserting POR_N
UVM_INFO @ 2630.733661 us: (chip_base_vseq.sv:48) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] POR_N complete
UVM_INFO @ 4564.037752 us: (sw_test_status_if.sv:51) [tb.u_sim_sram.u_sim_sram_if.u_sw_test_status_if] SW test transitioned to SwTestStatusInBootRom.
UVM_INFO @ 4564.987752 us: (sw_test_status_if.sv:51) [tb.u_sim_sram.u_sim_sram_if.u_sw_test_status_if] SW test transitioned to SwTestStatusInBootRomHalt.
UVM_FATAL @ 12631.841647 us: (chip_sw_lc_walkthrough_testunlocks_vseq.sv:49) [uvm_test_top.env.virtual_sequencer.chip_sw_lc_walkthrough_testunlocks_vseq] wait timeout occurred!
```

**Comment by andreaskurth** [comment] 2022-10-11 15:58
@tjaychen As the author of https://github.com/lowRISC/opentitan/commit/8b107c473157f391d25654168b62911b02f3d205, maybe you know if [`lc_walkthrough_test.c`](https://github.com/lowRISC/opentitan/blob/af9bcb398bbc60369f00f12eeb9396caeb5601ba/sw/device/tests/sim_dv/lc_walkthrough_test.c) or [`chip_sw_lc_walkthrough_vseq.sv`](https://github.com/lowRISC/opentitan/blob/d0b9668b20f6df02bb242a166ae31d1e7c55ad34/hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_vseq.sv) are missing code to set the OTP, so that the test binary can run?

**Comment by tjaychen** [comment] 2022-10-11 16:37
let me double check. I need refresh my memory a bit on what these tests do.

**Comment by tjaychen** [comment] 2022-10-11 20:48
You are right, since these tests perform life cycle walkthrough, they all seem to begin with the raw otp image.
This means the starting point of the test does not have `ROM_EXEC_EN` set to 1 and does not background load it at any point during the test.  This means when it is eventually time for software to run, it will just stall on `ROM_EXEC_EN`. 

I can make a fix for this.

@cindychip FYI.
Let me know if you think I should fix it a specific way.

**Comment by cindychip** [comment] 2022-10-11 20:52
> You are right, since these tests perform life cycle walkthrough, they all seem to begin with the raw otp image. This means the starting point of the test does not have `ROM_EXEC_EN` set to 1 and does not background load it at any point during the test. This means when it is eventually time for software to run, it will just stall on `ROM_EXEC_EN`.
> 
> I can make a fix for this.
> 
> @cindychip FYI. Let me know if you think I should fix it a specific way.

Thanks for debugging this issue. So after the test transitions from raw stage to test unlock, we need to set the `ROM_EXEC_EN`, is that the solution you proposed? 
I like the idea just wonder if there is any way to make it a common task or remind people if this field is not set?

**Comment by tjaychen** [comment] 2022-10-11 20:56
i could put it in `dut_init` but it's a little weird when the lc state is supposed to be raw and have this set though. 
I'm a little concerned that could hide other failures.

**Comment by cindychip** [comment] 2022-10-11 20:56
> i could put it in `dut_init` but it's a little weird when the lc state is supposed to be raw and have this set though. I'm a little concerned that could hide other failures.

Yeah.. Agree. I guess we can just fix this issue first. Maybe later we will have some better ideas.

**Comment by tjaychen** [comment] 2022-10-11 20:58
i could put it in `apply_reset`, but we'd probably need a separate cfg bit to indicate when we want this to be automatically set vs not.  Since there are a few tests that manually set this bit (only 1 as far as i know).

**Comment by cindychip** [comment] 2022-10-11 21:05
> i could put it in `apply_reset`, but we'd probably need a separate cfg bit to indicate when we want this to be automatically set vs not. Since there are a few tests that manually set this bit (only 1 as far as i know).

Sure, apply reset + a cfg flag sounds like a good solution! Thanks Tim.

**Comment by sriyerg** [comment] 2022-10-13 00:52
> ckground load it at any point during the test. This means when it is eventually time for software to run, it will just stall on `ROM_EXEC_EN`.

These tests used to pass. What exactly changed that caused it to fail with this symptom?

**Comment by andreaskurth** [comment] 2022-10-13 06:31
> These tests used to pass. What exactly changed that caused it to fail with this symptom?

These tests started failing in nightlies on 2022-10-08 with c2a8c64cc. The revision tested in nightlies just before, 144e5112d, passed these tests. Given 8b107c473157f391d25654168b62911b02f3d205 is between those two revisions and following [this](https://github.com/lowRISC/opentitan/issues/15371#issuecomment-1274873902) and [this](https://github.com/lowRISC/opentitan/issues/15371#issuecomment-1275258796) analysis, we think the problem is that these tests are not compatible with the change made in 8b107c473157f391d25654168b62911b02f3d205, which should be fixed by https://github.com/lowRISC/opentitan/pull/15424.

**Comment by tjaychen** [comment] 2022-10-17 18:32
it looks like the fix didn't address all of the failures, this one is still failing.

**Comment by tjaychen** [comment] 2022-10-18 16:04
this failure should be addressed by #15540

**Closed by tjaychen** 2022-10-18 16:04 UTC
Labels: Component:TestTriage
