### ISSUE TITLE
[test-triage] chip_sw_sleep_pin_wake

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15954] opened 2022-11-02 23:23 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

UVM_FATAL @ * us: (chip_sw_sleep_pin_wake_vseq.sv:89) [chip_sw_sleep_pin_wake_vseq] wait timeout occurred! has 1 failures:

Test chip_sw_sleep_pin_wake has 1 failures.
0.chip_sw_sleep_pin_wake.1427533016
Line 631, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_pin_wake/latest/run.log

  UVM_FATAL @ 13668.440144 us: (chip_sw_sleep_pin_wake_vseq.sv:89) [uvm_test_top.env.virtual_sequencer.chip_sw_sleep_pin_wake_vseq] wait timeout occurred!
  UVM_INFO @ 13668.440144 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---

### Steps to Reproduce

- GitHub Revision: [e1671fddf](https://github.com/lowrisc/opentitan/tree/e1671fddf58976e5e11db41cd51fa17de54dea14)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sleep_pin_wake --build-seed 600742595 --fixed-seed 1427533016 --waves fsdb

### Tests with similar or related failures

- [ ] chip_padctrl_attributes

**Comment by sriyerg** [comment] 2022-11-02 23:38
This test and `chip_padctrl_attributes` have similar symptoms, but different root causes. Fix coming soon.

**Comment by sriyerg** [comment] 2022-11-03 19:09
Fixed in #15988. 
The `chip_padctrl_attributes` was fixed in #15958.

**Comment by sriyerg** [comment] 2022-11-05 16:34
Test is passing in Nov 4 results.

**Closed by sriyerg** 2022-11-05 16:34 UTC
Labels: Component:TestTriage
