### ISSUE TITLE
[i2c] Target FSM Coverage for Spurious Start

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#18251] opened 2023-04-28 17:57 UTC
### Description

In the I2C FSM there are a few transitions that can happen in any state. The most important of which is the one that detects a start because the host may do this when it loses track of its state and just wants to start a new transaction:
https://github.com/lowRISC/opentitan/blob/3b1028fdeff7bbb883d2487f1e64e60cbdb43682/hw/ip/i2c/rtl/i2c_fsm.sv#L1302

In our current block-level tests, we are hitting the former one in some states, but not in the majority of ones. To hit this case in the majority of states (many of which only last one cycle), we would need to create a dedicated test.

This issue is spun out from: https://github.com/lowRISC/opentitan/issues/17448

> estimate 16

**Comment by crteja** [comment] 2023-05-04 08:48
> remaining 2023-05-03 12

**Comment by crteja** [comment] 2023-05-04 16:36
> remaining 2023-05-04 8

**Comment by crteja** [comment] 2023-05-05 10:55
Added a PR(#18335) to trigger FSM state transitions to `AcquireStart`/`Idle` by forcing internal signals `start_det`/`stop_det`. These transitions are only relevant for Target mode states as these variables are set only in target mode as shown below

https://github.com/lowRISC/opentitan/blob/39f9a9e57286f0d2a72c624bb19b9bd3a4c3bdf0/hw/ip/i2c/rtl/i2c_fsm.sv#L291-L295

Following transitions are covered with #18335

initial state | next state
-- | --
`StretchAddr`     | `AcquireStart`, `Idle` 
`AddrAckWait`     | `AcquireStart`, `Idle` 
`AddrAckSetup`    | `AcquireStart`, `Idle` 
`AddrAckPulse`    | `AcquireStart`, `Idle` 
`AddrAckHold`     | `AcquireStart`, `Idle` 
`TransmitWait`    | `AcquireStart`, `Idle` 
`TransmitSetup`   | `AcquireStart`, `Idle` 
`TransmitPulse`   | `AcquireStart`, `Idle` 
`TransmitHold`    | `AcquireStart`, `Idle` 
`TransmitAck`     | `AcquireStart`, `Idle`
`StretchTx`       | `AcquireStart`, `Idle` 
`StretchTxSetup`  | `AcquireStart`, `Idle` 
`AcquireAckWait`  | `AcquireStart`, `Idle` 
`AcquireAckSetup` | `AcquireStart`, `Idle` 
`AcquireAckPulse` | `AcquireStart`, `Idle` 
`AcquireAckHold`  | `AcquireStart`, `Idle`
`StretchAcqFull`  | `AcquireStart`, `Idle`

Below target mode transitions are already covered in other testcases and can be checked in latest [coverage report](https://reports.opentitan.org/hw/ip/i2c/dv/latest/cov_report/mod1.html#FSM) 
initial state | next state
------------- | -------------
`AddrRead` | `AcquireStart`, `Idle`
`TransmitAckPulse` | `AcquireStart`, `Idle`
`AcquireByte` | `AcquireStart`, `Idle`

With this all the target mode Spurious Star transitions are covered

**Comment by moidx** [comment] 2023-05-12 15:44
@GregAC to check failures in manual run of https://github.com/lowRISC/opentitan/pull/18335 and provide feedback on whether it is due to a test issue.

**Comment by GregAC** [comment] 2023-05-12 15:53
@crteja reports the failures are all testbench related. They're all timeouts related to existing known testbench issues: https://github.com/lowRISC/opentitan/issues/18410#issuecomment-1545850650

**Comment by GregAC** [comment] 2023-05-12 15:54
Moving to M2.5.2 to track remaining work to add waivers and achieve coverage goals in nightly regressions.

**Comment by marnovandermaas** [comment] 2023-05-15 18:35
Adding waivers are tracked in https://github.com/lowRISC/opentitan/issues/17448. Will leave this open until the coverage of the spurious starts appear in the nightly regression.

**Closed** 2023-05-17 09:07 UTC
Labels: Component:DV, Priority:P1, IP:i2c, Submilestone:M2.5.2
