### ISSUE TITLE
[test-triage] chip_csr_aliasing

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16213] opened 2022-11-10 17:20 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
Offending '(pwr_ast_i.io_clk_val || (!por_d0_ni))' has 1 failures:

Test chip_csr_aliasing has 1 failures.
1.chip_csr_aliasing.2680549163
Line 303, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_csr_aliasing/latest/run.log

      Offending '(pwr_ast_i.io_clk_val || (!por_d0_ni))'
  UVM_ERROR @ 43636.757000 us: (pwrmgr_ast_sva_if.sv:67) [ASSERT FAILED] IoClkHandshakeOn_A
  UVM_INFO @ 43636.757000 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

### Steps to Reproduce

- GitHub Revision: [81bde034a](https://github.com/lowrisc/opentitan/tree/81bde034a7b21e3444342c96555fc63595a03c65)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_csr_aliasing --build-seed 2742335380 --fixed-seed 2680549163 --waves fsdb

### Tests with similar or related failures

- [ ] csr_aliasing
- [ ] regwen_csr_and_corresponding_lockable_csr
- [ ] tl_d_outstanding_access
- [ ] tl_d_partial_access

**Comment by johngt** [comment] 2022-11-11 11:46
@sriyerg there are some intermittent issues with this but last night's report seemed to show it was ok.

|    | Tests             |   2022-11-10 08:10:06 |   2022-11-09 08:04:06 |   2022-11-08 08:03:42 |   2022-11-07 08:08:10 |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 | Suite                                                                                                 |
|---:|:------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:------------------------------------------------------------------------------------------------------|
|  1 | chip_csr_aliasing |                   100 |                    80 |                   100 |                   100 |                   100 |                   100 |                   100 |                    60 |                    80 |                    60 | csr_aliasing, regwen_csr_and_corresponding_lockable_csr, tl_d_outstanding_access, tl_d_partial_access |

Previous report - https://reports.opentitan.org/hw/top_earlgrey/dv/2022.11.09_17.04.47/report.html highlighted failure as
```
Offending '(pwr_ast_i.io_clk_val || (!por_d0_ni))' has 1 failures:

Test chip_csr_aliasing has 1 failures.
1.chip_csr_aliasing.2680549163
Line 303, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_csr_aliasing/latest/run.log

      Offending '(pwr_ast_i.io_clk_val || (!por_d0_ni))'
  UVM_ERROR @ 43636.757000 us: (pwrmgr_ast_sva_if.sv:67) [ASSERT FAILED] IoClkHandshakeOn_A
  UVM_INFO @ 43636.757000 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

**Comment by sriyerg** [comment] 2022-11-11 18:57
The failure needs to be debugged. The tests run with different randomization seeds each night. Depending on the seed value, they may occasionally hit a corner failure case. Lets keep the bug open.

**Comment by tjaychen** [comment] 2022-11-15 18:26
@ballifatih this seems like the same failure as the one you've encountered in #16154 right?

**Comment by ballifatih** [comment] 2022-11-15 21:29
@tjaychen Yes I think the failure is similar (both coming from `pwrmgr_ast_sva_if`). However, I think this test started failing earlier than the one in #16154. Unfortunately, I haven't been able to identify the root cause for the other one yet.

**Comment by ballifatih** [comment] 2022-11-18 01:19
I wasn't able to actually reproduce the same failure at [81bde034a](https://github.com/lowrisc/opentitan/tree/81bde034a7b21e3444342c96555fc63595a03c65), but the error that I got is slightly different:
```
 "../src/lowrisc_tlul_common_0.1/rtl/tlul_assert.sv", 296: tb.dut.top_earlgrey.u_xbar_main.tlul_assert_host_rv_core_ibex__cored.gen_assert_final[2].noOutstandingReqsAtEndOfSim_A: started at 45520370276ps failed at 45520370276ps
266   Offending '((pend_req[2].pend == 1'b0) || $test$plusargs("disable_assert_final_checks"))'
267 UVM_ERROR @ 45520.370276 us: (tlul_assert.sv:296) [ASSERT FAILED] noOutstandingReqsAtEndOfSim_A
268 UVM_INFO @ 45520.370276 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER] 
```

The seed I used was `2680549163`.

**Comment by weicaiyang** [comment] 2022-11-18 23:57
> I wasn't able to actually reproduce the same failure at [81bde034a](https://github.com/lowrisc/opentitan/tree/81bde034a7b21e3444342c96555fc63595a03c65), but the error that I got is slightly different:
> 
> ```
>  "../src/lowrisc_tlul_common_0.1/rtl/tlul_assert.sv", 296: tb.dut.top_earlgrey.u_xbar_main.tlul_assert_host_rv_core_ibex__cored.gen_assert_final[2].noOutstandingReqsAtEndOfSim_A: started at 45520370276ps failed at 45520370276ps
> 266   Offending '((pend_req[2].pend == 1'b0) || $test$plusargs("disable_assert_final_checks"))'
> 267 UVM_ERROR @ 45520.370276 us: (tlul_assert.sv:296) [ASSERT FAILED] noOutstandingReqsAtEndOfSim_A
> 268 UVM_INFO @ 45520.370276 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER] 
> ```
> 
> The seed I used was `2680549163`.

Is this the first error in the simulation? If not, we can ignore it and only deal with the first error.

If it's the 1st error, please let me know how to reproduce it.

**Comment by ballifatih** [comment] 2022-11-19 00:18
Yes in `run.log`, I only see this assertion failure. What I did was following (which is the seed from this issue):
![image](https://user-images.githubusercontent.com/7850700/202823223-049b1d84-5487-4294-a07e-0a493f1554e5.png)

Also, I couldn't find the log of the failed run in the nightly regression (looking at build nr 407 on 9th of Nov.). Are there multiple runs happening in the regression since the test passes %80?

**Comment by weicaiyang** [comment] 2022-11-19 00:44
Thanks @ballifatih. Let me have a try.

**Comment by ballifatih** [comment] 2022-11-19 01:02
Thanks @weicaiyang. I also started running another one just to make sure I didn't use wrong params. Last time it took around 2 hours though (current run is at 43 min now).

**Comment by ballifatih** [comment] 2022-11-19 02:16
@weicaiyang I actually got the expected result this time, I must have done something wrong the first time.
![image](https://user-images.githubusercontent.com/7850700/202829580-e811bb0a-6a53-4a6e-9398-9f67fd20a517.png)

**Comment by ballifatih** [comment] 2022-11-19 03:09
Could this be about the test writing `EXT_CLOCK_EN` of [lc_ctrl.TRANSITION_CTRL](https://docs.opentitan.org/hw/ip/lc_ctrl/doc/#Reg_transition_ctrl) (which I assume happens randomly)? 

The main reason for `pwr_ast_i.io_clk_val = clk_src_io_val_o` to be pulled down by ast seems like ast received `io_clk_byp_req = On` from LC (see below). That is the only input change to ast before `clk_src_io_val_o` goes down. (I removed a bunch of ast input/outputs that are stable in the vicinity of this change.)
![image](https://user-images.githubusercontent.com/7850700/202831215-b7d2add9-4d4d-485f-80ad-460bdbe8625d.png)


Within LC, I can see that a memory write comes to `TRANSITION_CTRL` by TL-UL (`tl_i.a_address` offset matches offset of this register). We cannot see in this waveform, but `pwr_ast_i.io_clk_val` signal goes down around 5 aon_clk cycles after LC propages byp_req.

![image](https://user-images.githubusercontent.com/7850700/202831008-c667a704-b5e5-4ad7-9d10-b08654464e7a.png)

**Comment by ballifatih** [comment] 2022-11-19 03:26
If overwriting `TRANSITION_CTRL` is the issue (or rather the violation of IoClkHandshakeOn_A from the mentioned commit), then I think this signal trigger should not violate the updated version of the same SVA since #16454. @matutem 

The old SVA from the commit [81bde034a](https://github.com/lowrisc/opentitan/tree/81bde034a7b21e3444342c96555fc63595a03c65)
https://github.com/lowRISC/opentitan/blob/81bde034a7b21e3444342c96555fc63595a03c65/hw/ip/pwrmgr/dv/sva/pwrmgr_ast_sva_if.sv#L67-L69

And the new SVA that is trigger sensitive:
https://github.com/lowRISC/opentitan/blob/08827b56858186f9a6c43ed29ace95188e2d7984/hw/ip/pwrmgr/dv/sva/pwrmgr_ast_sva_if.sv#L69-L71

And here is the original violation waveform:
![image](https://user-images.githubusercontent.com/7850700/202832187-0fef3db3-2712-454a-b4c6-ac919089c171.png)

Again, IF this was the cause.

**Comment by weicaiyang** [comment] 2022-11-19 05:03
Thanks @ballifatih for looking into this.

Seems like @matutem already fixed this. Let me run a test with 100 seeds. If no more failure, let's close this.

**Closed** 2022-11-22 10:37 UTC
Labels: Component:TestTriage

**Comment by weicaiyang** [comment] 2022-11-22 19:33
Forgot to update this issue. I ran 100 seeds, and this error no longer occurred. 
But I saw some other failures. Will look into it. If needed, will file another issue.
