### ISSUE TITLE
[flash_ctrl] Clarification Of Program/Read FIFO Access Using Interrupts

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#11882] opened 2022-04-04 17:23 UTC
Hi @tjaychen 

I am now verifying the Interrupts, with regard to Reading and Programming through the FIFOs.
Up until now we have only used 'polling' of the Status Bits

STATUS bits (polled)
rd_full
rd_empty
prog_full
prog_empty
init_wip

STATUS bits (Interrupt)
prog_empty
prog_lvl
rd_full
rd_lvl
op_done
corr_err

Also up until now we have generally only Programmed/Read up to 16 Words at a time, but
there are tasks to Program/Read more than 16 words, but these breakdown the full number of words into blocks of 16, and then the remainder.

BUT I notice that the Spec says that the NUM field in the CONTROL register is ...

27:16	rw	0x0	NUM	
One fewer than the number of bus words the flash operation should read or program. For example, to read 10 words, software should program this field with the value 9.

Bits 27:16 is considerably larger that 16 words.

Is the 16 word limit intended for both POLLED and INTERRUPT Modes?

I think this may be some restriction imposed by the Physical Flash, like send 16 words, wait for end of programming, etc

This is how we are currently accessing the Flash in the TB Using Polling (and more recently I have added the use of the op_done interrupt)

POLLED ACCESS

READ (<=16 Words)
1)	Start Flash Op Read
2)	Wait until op done (polled or interrupt)
3)	Loop { Check FIFO is not Empty
4)         Read value from FIFO}
5)	Repeat 3 & 4, until all words are read

WRITE (<=16 Words)
1)	Start Flash Op Write
2)	Loop {Check FIFO is not full)
3)	      Write to FIFO}
4)	Repeat 2 & 3 until all words are written
5)	Wait until Op Done (polled or interrupt)

The interrupts I am asking about are
prog_empty
prog_lvl
rd_full
rd_lvl

If there is a 16 word limit, then perhaps the interrupts make a little more sense, but if the intention is to, for example use the interrupt to flow control data to/from the fifos when num_words > 16, then I cannot see that the flags we have work?

I can test the given interrupts occur, but I was trying come up with use case scenarios.

In your opinion, is it sufficient just to test these interrupts standalone ? (full, empty, lvl)?

Or have I missed something here?

I notice the spec says this, which kind of spells it out ... but the CONTROL reg NUM field implies more

"Parameterized support for burst program / read, up to 64B.
Longer programs / reads are supported, however the protocol controller will directly back-pressure the bus if software supplies more data than can be consumed, 
or if software reads more than there is data available.
Software can also choose to operate by polling the current state of the FIFO or through FIFO interrupts (empty / full / level)."

If there is that 16 word limit, I think this might need to be clearer in the Spec register section

**Comment by TimEwins** [comment] 2022-04-05 09:56
Hi @tjaychen 

Thanks for the explanation.

So Programming is limited to up to 16 words, which is a physical flash requirement (and I would guess would ultimately depend on the flash being used).  

You agree that the program interrupts here are not helpful .... I can see that, I will just make sure they o what they say they do,

For Read, >16 words is possible using the mechanism you/we have suggested, so I will test that scenario.

So yes, I think I have a way forward with this ... thanks

Documentation updates advised.

**Comment by TimEwins** [comment] 2022-04-05 17:38
Hi @tjaychen 

Also @nikola-miladinovic 

I have been writing a test (directed at the moment) to read 32 words from the controller using the rd_full interrupt (its simple stuff at the moment)

The code is as below : -
----------------------------------------
    flash_op_intr.op         = FlashOpRead;
    flash_op_intr.partition  = FlashPartData;
    flash_op_intr.addr       = 0;
    flash_op_intr.num_words  = 32;
    flash_op_intr.erase_type = $urandom() ? FlashErasePage : FlashEraseBank;
    
    // READ FIFO
        
    flash_op_data.delete();

    flash_ctrl_start_op(flash_op_intr);              
      
    num_beats = 2;    
    for (int i=0; i<num_beats; i++)
    begin          
        // wait for rd_full intr
        `uvm_info("DEBUG", "--> Waiting for RdFull Intr", UVM_INFO)        
        @(posedge cfg.flash_ctrl_intr_vif.pins[FlashCtrlIntrRdFull]);                                                            
        `uvm_info("DEBUG", "--> Seen RdFull Intr", UVM_INFO)                
        // read fifo 16 words
        flash_ctrl_read(16, flash_op_data, poll_fifo_status);      
        csr_rd(.ptr(ral.intr_state), .value(data));  // Clear rd_full Interrupt
        csr_wr(.ptr(ral.intr_state), .value(data));      
    end
    wait_flash_op_done();
----------------------------------------

I thought this would work, but it does not seem to,  The fifo is 16 words deep, so if I read 32 words, thats two buffers worth of data.  So I start the op, with num_words=32.  I then do 2 reads of a full buffer, waiting for the interrupt to tell me the buffer is full.  After emptying the buffer I ack the interrupt, and then wait for the expected next interrupt.  When this happens I repeat the reads, and ack the full_intr, than wait for done.

BUT ... what I see in the waves is that the full interrupt occurs for the first 16 words, then we get an op_done, and nothing else happens.  (Screenshot enclosed).

It looks like the design is giving a done after 16 words when it should be giving it after 32 (in this scenario)

What do you think?

Regardless of the op_done I would have expected 32 words to be transfered.

Perhaps I am driving this incorrectly?

![Screen Shot 04-05-22 at 06 08 PM](https://user-images.githubusercontent.com/92723163/161814929-2d1db713-fddb-4bb2-a5ca-1c3703bc8c7f.PNG)

Perhaps this method might work (not tried it yet)

1) start read op (32 words)
2) wait for rd_full intr
3)read word from fifo, inc word count, fifo refills
4)if word count remaining is < 16
5)    read remaining words from fifo
6)    wait op_done
7) else 
8)    repeat 2, 3, 4,

**Comment by tjaychen** [comment] 2022-04-05 22:37
@TimEwins 
ah, i see what happened.
If you look at `u_rd_fifo.gen_normal_fifo.fifo_incr_wptr`, you will you first get 16 nicely ordered pulses, indicating the first 16 reads that fill up the read fifo.

At this point the interrupt is asserted (see `intr_rd_full`), and we begin to service the interrupt by reading out the fifo.
If you look at `incr_wptr` again, every time you read out a word, the flash is able to deposit a new word, so if you sum up the orderly increments and the disordely-looking increments, you will have 32 total (representing 32 words).

The problem in this case, is that the interrupt state is not cleared until you read the first 16. However, during that time, the flash deposits 16 entries again before the interrupt state is cleared. So the same state is simply set again, you do not get another "edge".

So the right way to do this is to clear the interrupt BEFORE you start the read.
This is likely what software would also, as the actual moving of the data inside the FIFO will be deferred until later, but the interrupt is handled first. 

```
    // wait for rd_full intr
    `uvm_info("DEBUG", "--> Waiting for RdFull Intr", UVM_INFO)        
    @(posedge cfg.flash_ctrl_intr_vif.pins[FlashCtrlIntrRdFull]);                                                            
    `uvm_info("DEBUG", "--> Seen RdFull Intr", UVM_INFO)                
    csr_rd(.ptr(ral.intr_state), .value(data));  // Clear rd_full Interrupt
    // read fifo 16 words
    flash_ctrl_read(16, flash_op_data, poll_fifo_status);      
```
Let me know if this helps.

**Comment by TimEwins** [comment] 2022-04-06 15:10
Hi @tjaychen 

For Info @nikola-miladinovic 

I was thinking about this yesterday evening, and I realised what I had misunderstood.  Today I have looked at TWO soultions, and enclosed them here .. both work for the simple case of reading 32 words via the FIFO (need to enhance) using the rd_full interrupt (and will modify for the rd_lvl interrupt too).

I propose METHOD 1 and METHOD 2. 

I think the best way to go is METHOD 1 ?  ... METHOD 2 is an alternative way of doing it, but it may not scale as well as METHOD 1.  We can always enhance the tests later, when we have more time.

I explain what each test does, and also include some waveforms from Xcelium.

**Comment by TimEwins** [comment] 2022-04-06 15:12
METHOD 1 - READ (Using Interrupt rd_full)
========================================= 

This works.  The test reads 32 words using the interrupt rd_full. 

Pseudo Code
1)  Setup Read Op of 32 Words (Bigger than a FIFO buffer)
2)  Start Flash Op Read
3)  Loop (16)
4)    Wait for Interrupt rd_full
5)    Ack Interrupt
6)    Read word from FIFO, push into data queue
7)  end
8)  The code above reads 16 word, wit the interrupt occuring every word, 
    as the FIFO refills
9)  Wait for interrupt rd_full (again)
10) FIFO fills again, but only one rd_full intr, as no more data is written
11) Read remaining words from FIFO, push into data queue
12) Queue holds all the data read
13  Compare data read with backdoor
14) flash_op_done is not needed as it would have occured before the remaining words were read

This obviously needs work to accept different word lengths, and also use the rd_lvl interrupt as well

flash_op_intr.op         = FlashOpRead;
flash_op_intr.partition  = FlashPartData;
flash_op_intr.addr       = 0;
flash_op_intr.num_words  = 32;
flash_op_intr.erase_type = $urandom() ? FlashErasePage : FlashEraseBank;

// READ FIFO
        
flash_op_intr_data.delete();
flash_ctrl_start_op(flash_op_intr);              

// Read 32 Words
  
for (int i=0; i<16; i++)
begin
  // wait for rd_full intr
  @(posedge cfg.flash_ctrl_intr_vif.pins[FlashCtrlIntrRdFull]);                                                            
  csr_rd(.ptr(ral.intr_state), .value(data), .backdoor(1));  // Clear Interrupt
  csr_wr(.ptr(ral.intr_state), .value(data));
  mem_rd(.ptr(ral.rd_fifo), .offset(0), .data(data));
  flash_op_intr_data.push_back(data);      
end

// wait for rd_full intr - Last rd_full - Remaining Data in Fifo
@(posedge cfg.flash_ctrl_intr_vif.pins[FlashCtrlIntrRdFull]);                                                            
csr_rd(.ptr(ral.intr_state), .value(data), .backdoor(1));  // Clear Interrupt
csr_wr(.ptr(ral.intr_state), .value(data));

for (int i=0; i<16; i++)
begin
  mem_rd(.ptr(ral.rd_fifo), .offset(0), .data(data));
  flash_op_intr_data.push_back(data);      
end       

// wait_flash_op_done(); // Not Needed, happened in the past
                        
cfg.flash_mem_bkdr_read_check(flash_op_intr, flash_op_intr_data);  // Check Data Inegrity

![3 1](https://user-images.githubusercontent.com/92723163/162007717-a749580b-0852-4bdf-a9d0-536cf3d2236f.PNG)

**Comment by TimEwins** [comment] 2022-04-06 15:12
METHOD 2 - READ (Using Interrupt rd_full)
========================================= 

This works.  The test reads 32 words using the interrup rd_full. 

Pseudo Code
1)  Setup Read Op of 32 Words (Bigger than a FIFO buffer)
2)  Start Flash Op Read
3)  Wait for Interrupt rd_full - FIFO is Full (16 words)
4)  Ack Interrupt
5)  Read 16 words from the FIFO, push into queue - rd_full interrupt will go high again
6)  If the rd_full interrupt is still high - Remaining Data in FIFO
7)  Read 16 words from the FIFO, push into queue
8)  Ack Interrupt
9)  Queue holds all the data read
10  Compare data read with backdoor
11) flash_op_done is not needed as would have occured before the remaining words were read

This obviously needs work to accept different word lengths, and also use the rd_lvl interrupt as well

flash_op_intr.op         = FlashOpRead;
flash_op_intr.partition  = FlashPartData;
flash_op_intr.addr       = 0;
flash_op_intr.num_words  = 32;
flash_op_intr.erase_type = $urandom() ? FlashErasePage : FlashEraseBank;

// READ FIFO
    
flash_op_intr_data.delete();

flash_ctrl_start_op(flash_op_intr);              

// Read 32 Words

// wait for rd_full intr
@(posedge cfg.flash_ctrl_intr_vif.pins[FlashCtrlIntrRdFull]);                                                            
csr_rd(.ptr(ral.intr_state), .value(data), .backdoor(1));  // Clear Interrupt
csr_wr(.ptr(ral.intr_state), .value(data));
  
// Read 16 words from FIFO -- rd_full interrupt will go high again
for (int i=0; i<16; i++)
begin
  mem_rd(.ptr(ral.rd_fifo), .offset(0), .data(data));
  flash_op_intr_data.push_back(data);      
end

// If rd_full interrupt still high  - Last rd_full - Remaining Data in Fifo
if (cfg.flash_ctrl_intr_vif.pins[FlashCtrlIntrRdFull] == 1) begin
  for (int i=0; i<16; i++)
  begin
    mem_rd(.ptr(ral.rd_fifo), .offset(0), .data(data));
    flash_op_intr_data.push_back(data);      
  end       
  
  csr_rd(.ptr(ral.intr_state), .value(data), .backdoor(1));  // Clear Interrupt
  csr_wr(.ptr(ral.intr_state), .value(data));

end

// wait_flash_op_done(); // Not Needed, happened in the past
                        
cfg.flash_mem_bkdr_read_check(flash_op_intr, flash_op_intr_data);  // Check Data Inegrity

![3 2](https://user-images.githubusercontent.com/92723163/162007849-2e98ce58-d835-4d9c-8415-66a5ec95cee0.PNG)

**Comment by tjaychen** [comment] 2022-04-06 15:29
METHOD 1 looks fine to me... but i think I overlooked the fact that flash reads are so fast, it's basically matching the host side read outs 1 to 1, ie, you get interrupts one after another.  Normally for something like UART, the fill rate from the hardware side is so much lower than you'd be able to quickly drain from software side and not get a bunch of interrupts like this. 

I think it might be a good idea to expose the FIFO level directly to software so that software/dv can double check when a FIFO full interrupt shows up like this.

**Comment by tjaychen** [comment] 2022-04-06 15:57
@TimEwins i think ideally how this should behave... is that every time a full interrupt is seen by the software, it attempts to read 16 entries. It's a bit odd in METHOD 1 we are clearing on every read.  As I mentioned, this is a side effect of the two sides being almost the same speed. 

At these speeds, it's probably better to not have these interrupts at all, but if the flash deposits were so much slower for some reason, it would still be beneficial. 

So what I think we should do is expose the read levels as a status to the software / DV.

Imagine the below scenario:

1. We issue an operation for n=32
2. the first 16 are deposited into the fifo by the flash, and a full interrupt is triggered
3. software / dv comes in and does 16 reads. However, as you've shown, each read triggers another full interrupt
4. Imagine that flash for whatever reason, deposits only 14 entries
5. After software / dv completes its 16 reads, it will still see a "full" interrupt, caused by the almost 1 to 1 matching.
6. This would be erroneous behavior to software, because it would get a full interrupt despite not actually being "full" due to the sticky nature of interrupts.

So i think what I need to do is actually expose the level in the FIFO as a read back, so that software / dv can double check.
On a full interrupt, we should only perform the read if there are 16 entries in the FIFO. 

This all feels very hoaky though, because the full interrupt is essentially unreliable under these scenarios.

@a-will for any ideas. Really I think when the read speeds are this close, we probably shouldn't even bother with interrupt mode at all.

**Comment by TimEwins** [comment] 2022-04-06 16:02
@tjaychen @a-wii @nikola-miladinovic 

I agree that the use of the interrupts as given is not that intuitive.  One idea I had is that maybe the rd_full should be a not_empty status .. which I think is what you are concluding.

**Comment by a-will** [comment] 2022-04-06 16:44
@tjaychen @TimEwins 

I'd agree with the use of FIFO occupancy here. Because the flash controller is quite fast at filling up its FIFO relative to CPU speeds, I'd guess interrupts will likely not be used for flash reads on OT. Instead, the firmware will almost certainly be better off polling.

With an occupancy counter, I'd probably leave the related flash_ctrl interrupts masked, set the rd_lvl threshold such that it acts as a "not empty" signal, and proceed with this flow:

While there is still data required for the requested transaction...
1. Check intr_state for op_done (for early termination) and rd_lvl (for data available).
2. If op_done but no data, skip to error handling.
3. If there is no data, but the operation isn't done, continue spinning on intr_state. (back to 1)
4. There is data. Get the occupancy level.
5. Read out the number of words found in (4), and update software's write pointer.

Not shown: Some means of doing a timeout for what could be an endless loop (in the case of a fault or bug).

**Comment by tjaychen** [comment] 2022-04-06 20:34
yeah that sounds good.
So seems like the answer here for now is I should add a status read back for level, is that right? 
That would make it more useable under this scenario.  In the future if we pair with a flash where flash read speeds are MUCH slower (say..NAND flash), then the fifo would probably be more beneficial.

**Comment by tjaychen** [comment] 2022-04-12 00:42
this should be addressed by making the FIFO level readable.
@TimEwins i will close this for now, please re-open if anything is unclear.

**Closed by tjaychen** 2022-04-12 00:42 UTC
Labels: IP:flash_ctrl
