### ISSUE TITLE
Logic loop in crossbar?

### ISSUE THREAD

**Issue by nmoroze** [lowRISC/opentitan#1657] opened 2020-03-02 22:41 UTC
I'm working on a flow using Yosys to compile OpenTitan to an SMTlib description for a verification project (see #1550 for more context on this build flow). I got to a point where I was able to generate a flattened Verilog source for the OpenTitan, but Yosys gives an error regarding a logic loop when trying to dump the (post-synthesis) SMT output. After digging a bit, it seems that the loop comes from a signal on the Ibex instruction memory output (`instr_req_o`), feeds through the crossbar (along the path to the ROM), then feeds back to the `data_error_i` Ibex input, which ultimately feeds back to `core_instr_req_o`, creating a large combinational loop. 

I think a similar loop may exist in the crossbar connection to flash storage, but I removed flash from the top level module in order to try and work around it. I haven't had a chance to go back and look at this particular loop more closely. 

The exact chain of signals in this loop is relatively complex, so I haven't had a chance to fully take a look at what's going on yet. However, I was able to break this loop by setting the `IbexPipeline` parameter on the Ibex core to 1, disabling the passthrough in the FIFO interfacing the Ibex to the crossbar. 

The above solution seems like a good workaround for me for now, but I'm curious if this logic loop actually exists in the OpenTitan, or if it's something possibly introduced by a bug in [sv2v](https://github.com/zachjs/sv2v)  (the tool I use to convert from SystemVerilog -> Verilog), or a bug in Yosys. Does it seem plausible that a logic loop like this exists intentionally (or unintentionally) in the OT design? I'm not exactly sure what implications it might have for device timing/performance in simulation/FPGA/ASIC realizations (and if it would have necessarily been caught already if it did exist).

**Comment by tjaychen** [comment] 2020-03-03 04:23
hmmmm it seems weird there would be a logic loop..especially since we run
lint on the whole opentitan design, and i would think an actual logic loop
would show up.
However, what you are describing does seem possible, since I would image a
write transaction (if it could be issued from the instruction bus, meaning
we didn't tie it off somehow) would error back at the ROM level and maybe
that would cause the behavior you are suggesting.

I can help take a look tomorrow.

**Comment by nmoroze** [comment] 2020-03-03 04:42
Thanks! If it helps, here's a big image dumped from Yosys showing the signals and their connections in the supposed logic loop. It's a lot to go through, but it might help you see what places things are supposedly going bad.

[output-unsplit.pdf](https://github.com/lowRISC/opentitan/files/4279278/output-unsplit.pdf)

Let me know if there's any other helpful info I can provide!

**Comment by eunchan** [comment] 2020-03-03 19:06
Thanks for the detailed logic flow @nmoroze . As I remember, TL-UL mandates the `valid` shouldn't be affected by `ready` and return signal. So TL-UL protocol is fine. 

The problem is: as crossbar returns the error within a cycle, it creates the error return to the core within a cycle. The Ibex also has a logic that creates new instruction fetch right when it receives the store error. Either Ibex or the crossbar should break the path. I will take a look at the error response module inside the crossbar and check if putting the register slice is easy or not.

**Comment by tjaychen** [comment] 2020-03-03 20:01
Eunchan any guesses as to why this escaped lint?

**Comment by eunchan** [comment] 2020-03-03 20:02
If Pipeline parameter is turned on, there's chance. Let me check lint 
configuration for top.

**Comment by tjaychen** [comment] 2020-03-03 20:06
i feel like if pipeline were turned on...it would delay the response /
request...and Greg would have flagged it as part of his coremark
measurements.
I could be wrong about this.

**Comment by eunchan** [comment] 2020-03-03 20:13
I've checked the RTL. TL-UL error reponse ties the `d_error` to 'b1. Expecting 
the error response only can be used when `d_valid` is 1. But Ibex uses the 
error_i directly. I think this signal should be guarded by d_valid. :)

**Comment by eunchan** [comment] 2020-03-03 20:17
@GregAC I think it would be better also Ibex breaks the loop. Shouldn't it see the error signal when the return data is valid?

**Comment by eunchan** [comment] 2020-03-03 20:20
CC: @udinator

**Comment by tjaychen** [comment] 2020-03-03 21:33
ah that makes sense...but then when is there loop though..?
unless we have a same cycle return from a_valid->d_valid, it doesn't seem
like there's an actual loop here right?

**Comment by eunchan** [comment] 2020-03-03 21:36
I need to look into Ibex code in depth. `instr_error_i` seems to affect the 
prefetcher without looking at `d_valid` ( @GregAC correct me if I am wrong ). 
Then it has actual loop.

**Comment by sriyerg** [comment] 2020-03-04 07:22
`rv_core_ibex` is not coverage-closed in DV at any level (at the mercy of chip level DV which is slow) this is definitely a concern since it has a lot of glue logic (Ibex interface <-> TL conversion). I think we should move that glue logic to a separate module as I had originally suggested [here](https://github.com/lowRISC/opentitan/issues/35#issuecomment-509857362). We can then run FPV on it to get some coverage.

**Comment by GregAC** [comment] 2020-03-04 10:03
The issue here is indeed on the Ibex side, tracking it here: https://github.com/lowRISC/ibex/issues/649

The issue is error factors into a signal `special_req` which is basically telling the Ibex controller we're jumping to some exception handler. An error response causes the jump to happen the cycle after but due to an `else` in the controller it stills end up factoring into the `pc_set` signal anyway.

I'd note Ibex does pay attention to the valid signal (error without valid shouldn't cause Ibex to take any action)

**Comment by GregAC** [comment] 2020-03-04 17:26
I have a fix for the ibex side of things, but I'm still testing it, so will probably appear as a PR against Ibex tomorrow.

**Comment by eunchan** [comment] 2020-03-04 17:50
Thanks for the note. I will close this PR as Ibex already honors the valid 
signal.

**Comment by nmoroze** [comment] 2020-03-04 20:26
Thanks everyone for being so responsive in taking a look at this! I've been following along and looking a bit more closely for myself, and one thing I'm curious about is whether this loop could actually cause problems during normal operation. 

Since the problematic outgoing signal from the Ibex is passed along the instruction memory bus, and the return signal is on the data memory bus, does that mean this actually would not be an issue assuming correct operation of the TLUL crossbar? 

I understand @GregAC's [comment](https://github.com/lowRISC/opentitan/pull/1668#issuecomment-594410862) in #1668 to mean that regardless of if this loop is ever realized during operation, we still don't want it to physically exist in hardware. That makes sense intuitive sense to me, but I'm still curious what concrete consequences it could have?

**Comment by GregAC** [comment] 2020-03-05 09:51
The underlying assumption behind any design based on sequential logic is, as the name states, it is sequential. Loops can introduce different behavior and the tools aren't setup to deal with it as it breaks that assumption. 

Specifically implementation may see issues (the simulator can spin around the loop a couple of times until it settles or find it doesn't actually end up looping around at all which I think will be the case in this example). Timing analysis tools may not give correct results with loops, you may get DFT (design for test, ensuring the circuit you produce is testable) issues with loops. 

You may even get a broken circuit. Whilst logically you can work out how a loop resolves and see it'll end up with a sensible steady value under all cases physically you have gates and wires with different delays which can introduce glitches e.g. for A & B either input == 0 means output == 0, but say you have A transitioning from 0 -> 1  and B transitioning from 1 -> 0 depending on the various delays there could be a time where A == 1 and B == 1 and the gate outputs a short pulse. The glitch could then end up going round the loop. It'll probably settle down at some point but this isn't the way the tools were expecting the circuit to behave so it could cause things to go wrong (maybe it doesn't settle down and you'll end up with oscillator!).

You can have loops in some cases (essential when building flip flops and other primitives for example) but they generally require careful analysis. Simply avoiding them is the best option.

**Comment by GregAC** [comment] 2020-03-06 15:24
Fix has been merged in Ibex: https://github.com/lowRISC/ibex/pull/656

PR open against OT to get the latest version of Ibex with the fix: https://github.com/lowRISC/opentitan/pull/1700

**Closed** 2020-03-11 11:26 UTC
