### ISSUE TITLE
[test-triage] chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#16457] opened 2022-11-18 10:35 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
Exit reason: Error: User command failed Job returned non-zero exit code has 3 failures:

Test chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq has 3 failures.
0.chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq.3710754990
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq/latest/run.log

  (02:45:10) Loading:
  (02:45:10) Loading: 1 packages loaded
  (02:45:10) ERROR: Skipping '//sw/device/tests/sim_dv:sram_ctrl_main_scrambled_access_test_sim_dv': no such target '//sw/device/tests/sim_dv:sram_ctrl_main_scrambled_access_test_sim_dv': target 'sram_ctrl_main_scrambled_access_test_sim_dv' not declared in package 'sw/device/tests/sim_dv' defined by /workspace/mnt/repo_top/sw/device/tests/sim_dv/BUILD
  (02:45:10) WARNING: Target pattern parsing failed.
  (02:45:10) ERROR: no such target '//sw/device/tests/sim_dv:sram_ctrl_main_scrambled_access_test_sim_dv': target 'sram_ctrl_main_scrambled_access_test_sim_dv' not declared in package 'sw/device/tests/sim_dv' defined by /workspace/mnt/repo_top/sw/device/tests/sim_dv/BUILD
  (02:45:10) INFO: Elapsed time: 5.468s
  (02:45:10) INFO: 0 processes.
  (02:45:10) FAILED: Build did NOT complete successfully (2 packages loaded)
  (02:45:10) FAILED: Build did NOT complete successfully (2 packages loaded)
  make: *** [/workspace/mnt/repo_top/hw/dv/tools/dvsim/sim.mk:73: sw_build] Error 1
1.chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq.2704551550
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq/latest/run.log

  (02:49:53) Loading:
  (02:49:53) Loading: 1 packages loaded
  (02:49:53) ERROR: Skipping '//sw/device/tests/sim_dv:sram_ctrl_main_scrambled_access_test_sim_dv': no such target '//sw/device/tests/sim_dv:sram_ctrl_main_scrambled_access_test_sim_dv': target 'sram_ctrl_main_scrambled_access_test_sim_dv' not declared in package 'sw/device/tests/sim_dv' defined by /workspace/mnt/repo_top/sw/device/tests/sim_dv/BUILD
  (02:49:53) WARNING: Target pattern parsing failed.
  (02:49:53) ERROR: no such target '//sw/device/tests/sim_dv:sram_ctrl_main_scrambled_access_test_sim_dv': target 'sram_ctrl_main_scrambled_access_test_sim_dv' not declared in package 'sw/device/tests/sim_dv' defined by /workspace/mnt/repo_top/sw/device/tests/sim_dv/BUILD
  (02:49:53) INFO: Elapsed time: 7.982s
  (02:49:53) INFO: 0 processes.
  (02:49:53) FAILED: Build did NOT complete successfully (2 packages loaded)
  (02:49:53) FAILED: Build did NOT complete successfully (2 packages loaded)
  make: *** [/workspace/mnt/repo_top/hw/dv/tools/dvsim/sim.mk:73: sw_build] Error 1
... and 1 more failures.
```

### Steps to Reproduce

- GitHub Revision: [f76c18cba](https://github.com/lowrisc/opentitan/tree/f76c18cba6b16896af1179f9859376bae1d368f0)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq --build-seed 3877704665 --fixed-seed 3710754990 --waves fsdb

### Tests with similar or related failures

- [ ] chip_sw_clkmgr_extended_range

**Comment by johngt** [comment] 2022-11-18 10:39
@msfschaffner / @ariel9678 
I know that this test just went in with https://github.com/lowRISC/opentitan/issues/14782 and so this is probably a case of just needing to wait for the next nightly.

**Comment by msfschaffner** [comment] 2022-11-18 17:37
This appears to be a test renaming issue. It may only be partially fixed - let me look into that.

**Comment by msfschaffner** [comment] 2022-11-18 18:23
#16465 should take care of this particular signature - although note that this class of scrambled access tests have a different failure signature, too. It's ok to close this issue here though (once #16465 is merged) since that other failure mode is tracked in #16416.

**Comment by engdoreis** [comment] 2022-11-23 09:59
Updating the error message:
```
 UVM_ERROR @ 4649.082264 us: (sw_logger_if.sv:523) [sram_ctrl_scrambled_access_test_prog_sim_dv(sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c:265)] CHECK-fail: Failed as it didn't generate enough ECC errors(2/1)
  UVM_INFO @ 4649.082264 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```
## Steps to Reproduce
GitHub Revision: [56db55c04](https://github.com/lowrisc/opentitan/tree/56db55c04a15724174c635601abc6c0721e09aea)
dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq --build-seed 3908033694 --fixed-seed 2459178159

**Comment by abdullahvarici** [comment] 2022-11-23 17:03
I have run the test with 15 seeds and it passed all of them. I also checked the log file and the codes. 2 of the 16 words do not have ECC errors with `--build-seed 3908033694 --fixed-seed 2459178159`. It is very low probability this to be happen but it is possible. I think we can ignore it. What do you think?

**Comment by engdoreis** [comment] 2022-11-24 09:34
I agree, it passed again in the last nighlty.

**Comment by engdoreis** [comment] 2022-11-28 10:50
This is test is failing more than expected, so I'm investigating it.
|     | Tests                                                          |   2022-11-27 08:09:15 |   2022-11-26 08:09:18 |   2022-11-25 08:08:49 |   2022-11-24 08:12:13 |   2022-11-23 08:13:17 |   2022-11-22 08:08:19 |   2022-11-21 08:11:59 |   2022-11-20 08:10:00 |   2022-11-19 08:10:46 | Suite                         |
|----:|:---------------------------------------------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:------------------------------|
| 198 | chip_sw_sram_ctrl_main_scrambled_access_jitter_en_reduced_freq |                 66.67 |                   100 |                   100 |                 66.67 |                   100 |                 66.67 |                   100 |                   100 |                   100 | chip_sw_clkmgr_extended_range |

**Closed** 2022-11-29 18:52 UTC
Labels: Component:TestTriage
