### ISSUE TITLE
[chip-test] chip_sw_pwrmgr_random_sleep_power_glitch_reset

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14164] opened 2022-08-09 23:00 UTC
### Test point name

chip_sw_pwrmgr_random_sleep_power_glitch_reset

### Host side component

None Required

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by msfschaffner** [comment] 2022-08-09 23:01
This still needs to be added to the chip-level testplan.

**Comment by tjaychen** [comment] 2022-08-22 20:33
testplan added in #14440

**Comment by johngt** [comment] 2022-11-15 12:05
@jeoongp / @msfschaffner / @tjaychen - highlighting a test that now seems to be implemented - it's shown up in the nightlies recently but not yet passing. If this issue is duplicated by a more recent issue please just comment on the issue that duplicates this and close this issue.

|     | Tests                                          |   2022-11-14 08:10:42 |   2022-11-13 08:12:54 |   2022-11-12 08:04:45 | 2022-11-11 08:07:48   | 2022-11-10 08:10:06   | 2022-11-09 08:04:06   | 2022-11-08 08:03:42   | 2022-11-07 08:08:10   | 2022-11-06 07:11:02   | 2022-11-05 07:11:23   | 2022-11-04 07:12:05   | 2022-11-03 07:11:23   | 2022-11-02 07:03:26   | 2022-11-01 07:10:18   | Suite                                          |
|----:|:-----------------------------------------------|----------------------:|----------------------:|----------------------:|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:-----------------------------------------------|
| 150 | chip_sw_pwrmgr_random_sleep_power_glitch_reset |                     0 |                     0 |                     0 | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | chip_sw_pwrmgr_random_sleep_power_glitch_reset |

**Comment by msfschaffner** [comment] 2022-11-16 00:59
This test seems to be implemented now - but as you point out it is not passing. The issue is not duplicated - hence we can leave this open until we resolved the problem.

**Comment by msfschaffner** [comment] 2022-11-16 01:04
There appear to be at least two different failure modes:
```
UVM_FATAL @ * us: (chip_sw_random_power_glitch_vseq.sv:58) [chip_sw_random_power_glitch_vseq] *- has 1 failures:

Test chip_sw_pwrmgr_random_sleep_power_glitch_reset has 1 failures.
0.chip_sw_pwrmgr_random_sleep_power_glitch_reset.2876183829
Line 536, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_pwrmgr_random_sleep_power_glitch_reset/latest/run.log

  UVM_FATAL @ 12119.700888 us: (chip_sw_random_power_glitch_vseq.sv:58) [uvm_test_top.env.virtual_sequencer.chip_sw_random_power_glitch_vseq] 1-
  UVM_INFO @ 12119.700888 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
UVM_ERROR @ * us: (chip_sw_base_vseq.sv:242) virtual_sequencer [chip_sw_random_power_glitch_vseq] SW TEST TIMED OUT. STATE: SwTestStatusInTest, TIMEOUT = * ns has 1 failures:

Test chip_sw_pwrmgr_random_sleep_power_glitch_reset has 1 failures.
2.chip_sw_pwrmgr_random_sleep_power_glitch_reset.1578290822
Line 504, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/2.chip_sw_pwrmgr_random_sleep_power_glitch_reset/latest/run.log

  UVM_ERROR @ 17414.454604 us: (chip_sw_base_vseq.sv:242) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_random_power_glitch_vseq] SW TEST TIMED OUT. STATE: SwTestStatusInTest, TIMEOUT = 12000000 ns
  
  UVM_INFO @ 17414.454604 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

**Comment by msfschaffner** [comment] 2022-11-16 01:06
Repro instructions (with [5ebd4769b](https://github.com/lowrisc/opentitan/tree/5ebd4769beae91a2120307212173a951675fc3af)):
```
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_pwrmgr_random_sleep_power_glitch_reset --build-seed 861587486 --fixed-seed 2876183829 --waves fsdb

./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_pwrmgr_random_sleep_power_glitch_reset --build-seed 861587486 --fixed-seed 1578290822 --waves fsdb
```

**Comment by jeoongp** [comment] 2022-11-16 01:07
Thanks @msfschaffner. Let me reproduce these cases and see what's wrong

**Comment by jeoongp** [comment] 2022-11-16 03:42
Timeout error was fixed in my local. But, the next error shows up as follows.

UVM_INFO @ 8704.353000 us: ([ast_supply_if.sv:57](http://ast_supply_if.sv:57/)) [ast_supply_if] forcing vcmain_pok_h_o to 1
"../src/lowrisc_dv_pwrmgr_ast_sva_if_0.1/[pwrmgr_ast_sva_if.sv](http://pwrmgr_ast_sva_if.sv/)", 48: tb.dut.top_earlgrey.pwrmgr_ast_sva_if.CoreClkGlitchToEnOff_A: started at 8679353000ps failed at 8779353000ps
    Offending '(!pwr_ast_o.core_clk_en)'
UVM_ERROR @ 8779.353000 us: ([pwrmgr_ast_sva_if.sv:48](http://pwrmgr_ast_sva_if.sv:48/)) [ASSERT FAILED] CoreClkGlitchToEnOff_A

This error looks pretty similar to https://github.com/lowRISC/opentitan/issues/16154

**Comment by msfschaffner** [comment] 2022-11-16 03:58
Ok, thanks for debugging this. Let's fix the timeout for this test and then wait for resolution of https://github.com/lowRISC/opentitan/issues/16154.

**Comment by jeoongp** [comment] 2022-11-16 17:26
SG. The timeout error is fixed in https://github.com/lowRISC/opentitan/pull/16395.

**Comment by matutem** [comment] 2022-11-17 19:18
Regarding the scenario where the test times-out: the reason is that a main power glitch is sent while the device is in deep sleep and the non-aon power domain is off. In that case pwrmgr does not even look for main power glitches since they are not expected to occur, so the timeout should be expected. We could avoid sending main power glitches in deep sleep to prevent this from happening.

A watchdog reset could be added, but upon reset there may be no software visible trace of the cause. The SV side could detect this... but I believe this is a case that can only happen due to tampering, and the only response viable is a full POR.

@tjaychen, could you confirm?

**Comment by matutem** [comment] 2022-11-17 20:24
The other scenario where *ClkGlitchToEnOff_A fail is due to incorrect SVAs: when a main power glitch is triggered the AST will drop its *clk_val outputs, regardless of its *clk_en inputs. The slow pwrmgr fsm is in charge of toggling *clk_en, and it is not involved in these resets, so we don't expect *clk_en to toggle at all.

I will create a PR to fix the SVA.

**Comment by matutem** [comment] 2022-11-29 19:48
The non-SVA failure should be fixed by #16554. Closing this.

**Closed by matutem** 2022-11-29 19:48 UTC
Labels: Help Wanted : SW, Help Wanted : DD, Component:TestTriage
