### ISSUE TITLE
[csrng] V1 Signoff 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21011] opened 2024-01-25 01:57 UTC
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by vogelpi** [comment] 2024-03-01 16:21
We've decided in today's triaging meeting to move all remaining CSRNG issues to M3. There was nothing absolutely critical for CSRNG (no area impact, no timing impact, there were software workarounds for the important things as opposed to ENTROPY_SRC). So we focused on other blocks first.

What remains is to check the DV stats for the signoff to ensure we're still at the level of the ES. I am lowering the the effort here from 12 to 0. FYI @johngt

**Comment by andreaskurth** [comment] 2024-03-28 09:31
@vogelpi: For a V1 signoff I think we don't need the DV stats. The smoke test still passes according to [current nightly results](https://reports.opentitan.org/hw/ip/csrng/dv/latest/report.html), and if the changes made to CSRNG as part of M2 are covered either by existing tests or by additional testplan items (with issues to track their completion in M4/M5), then I think this can be closed as completed.

**Comment by vogelpi** [comment] 2024-03-30 00:41
Just had a look at the DV stats of the [last green nightly regression](https://reports.opentitan.org/hw/ip/csrng/dv/2024.03.27_04.30.09/report.html).
![Screenshot from 2024-03-30 01-20-42](https://github.com/lowRISC/opentitan/assets/20307557/d38ce0c4-2bff-42c1-8b27-f42d45a36e65)

Pass rates are all above the bar for V2/V2S but the expression and branch coverage dropped to below 90%. So we can't sign off at V2/V2S and have to drop down to V1. Most likely this happened due to the area reduction changes (coverage exclusion needs to be updated and reviewed again). It's a pity since we for M2, we didn't do functional RTL changes but quite some DV improvements (see #20976). This is now tracked in #22354.

A PR to bump the version (because of the changes now coming over the next weeks) and lowering the verification version to V1 is here: #22355.

**Closed** 2024-03-30 00:46 UTC
Labels: Component:DV, IP:csrng
