### ISSUE TITLE
Unable to connect OpenOCD and GDB

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#5810] opened 2021-03-25 20:14 UTC
With the lowRISC/opentitan@99cb19827ebbd5dcee097c061a271ac09be5b523 bitstream built from the CI I am unable to connect OpenOCD and GDB.

Using mainline OpenOCD 0.11.0 and the RISC-V fork results in the same problem.

The first time I try and connect OpenOCD successfully connects, but then when I attach with GDB I see this error printed continuously:

```
Error: OpenOCD only supports Debug Module version 2 (0.13) and 3 (0.14), not 0 (dmstatus=0x0). This error might be caused by a JTAG signal issue. Try reducing the JTAG clock speed.
```

After that if I kill GDB and OpenOCD and try and re-connecte with OpenOCD I just see these errors and GDB is unable to connect:

```
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 30000 kHz
Error: JTAG scan chain interrogation failed: all zeroes
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: riscv.tap: IR capture error; saw 0x00 not 0x01
Warn : Bypassing JTAG setup events due to errors
Error: Unsupported DTM version 1. (dtmcontrol=0x1071)
Warn : target riscv.tap.0 examination failed
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
Error: Target not examined yet
Error executing event gdb-attach on target riscv.tap.0:
```

> estimate 16

**Comment by sajjadahmed677** [comment] 2021-03-27 08:36
Why it is showing the error of version I guess the implemented version of debug module is 0.13?? Are you using openocd according to this version??

**Comment by GregAC** [comment] 2021-03-29 08:24
Just tried OpenOCD and GDB with a verilator sim build from that commit and all looks to be working, so this may be an FPGA specific issue, I don't have a board to hand so can't check myself.

Have you a tried a newer bitstream?

**Comment by sajjadahmed677** [comment] 2021-03-30 13:40
Actually i am also doing it on verilator.

**Comment by alistair23** [comment] 2021-03-30 15:36
The latest master commit doesn't fix the issue.

It seems that I can sometimes get a connection and somethings seem to work. The part that reliably doesn't work is resetting the board with the `monitor reset halt` command in GDB.

**Comment by GregAC** [comment] 2021-03-30 15:44
Given we're pushing the FPGA to its limit on area at least I wonder if it's a timing issue, given the message 'This error might be caused by a JTAG signal issue. Try reducing the JTAG clock speed.'

I do now have a board so I can take a look

**Comment by alistair23** [comment] 2021-04-08 16:06
Any updates? I checked today with the latest bitstream and I'm seeing lots of errors when trying to using GDB

**Comment by tjaychen** [comment] 2021-04-08 16:12
did you get a chance to try Greg's suggestion of reducing the clock speed?

**Comment by alistair23** [comment] 2021-04-08 16:15
Ah, sorry I missed that. I have tried reducing the clock speed OpenOCD uses but that didn't help.

**Comment by aroelke** [comment] 2021-05-10 21:58
I'm seeing an error similar to this, except it skips the GDB error and goes straight to OpenOCD failing with the same message.  I also tried reducing the JTAG clock speed (and even went as far as to reduce the entire system clock), but it still didn't work.  Has anyone figured out what's causing this?

**Comment by alistair23** [comment] 2021-05-17 06:34
No luck here either. Still seems to not work

**Comment by likewise** [comment] 2021-05-17 19:12
Is there a last-known-good working commit/board/configuration for this?

**Comment by alistair23** [comment] 2021-05-17 22:21
Yep, lowRISC/opentitan@99cb19827ebbd5dcee097c061a271ac09be5b523

**Comment by alistair23** [comment] 2021-06-30 07:49
Confirming that this is still a problem with a28c280bb976ef15b7192779c2a3f93b746fa2ca

**Comment by likewise** [comment] 2021-07-09 07:17
Although I am using Ibex independently with a debug module in my case I had a similar error when I used TRSTn. Removing that wire (or using reset_config none in the OpenOCD configuration) helped me pass. (I am not sure why that is, TRST should reset the TAP controller). I am not too familiar with the OpenTitan setup, but are you all using the same debug dongle, OpenOCD settings and FPGA board?

**Comment by pt07L** [comment] 2021-09-16 07:50
Any update on this issue? I have the same problem with current master (5b842cd9f) on the NexysVideo board

UART output of the FPGA:

> I00000 boot_rom.c:60] Version:    opentitan-earlgrey_silver_release_v5-1066-g5b842cd9f
> Build Date: 2021-09-15, 15:26:54
> 
> I00001 boot_rom.c:76] Boot ROM initialisation has completed, jump into flash!
> I00000 boot_rom.c:60] Version:    opentitan-earlgrey_silver_release_v5-1066-g5b842cd9f
> Build Date: 2021-09-15, 15:26:54
> 
> I00001 bootstrap.c:192] Bootstrap requested, initialising HW...
> I00002 bootstrap.c:223] HW initialisation completed, waiting for SPI input...
> I00003 bootstrap.c:136] Processing frame #0, expecting #0
> I00004 bootstrap.c:162] Flash erase successful
> I00005 bootstrap.c:136] Processing frame #0, expecting #1
> I00006 bootstrap.c:136] Processing frame #1, expecting #1
> I00007 bootstrap.c:136] Processing frame #0, expecting #2
> I00008 bootstrap.c:136] Processing frame #0, expecting #2
> I00009 bootstrap.c:136] Processing frame #2, expecting #2
> I00010 bootstrap.c:136] Processing frame #0, expecting #3
> I00011 bootstrap.c:136] Processing frame #0, expecting #3
> I00012 bootstrap.c:136] Processing frame #3, expecting #3
> I00013 bootstrap.c:136] Processing frame #0, expecting #4
> I00014 bootstrap.c:136] Processing frame #0, expecting #4
> I00015 bootstrap.c:136] Processing frame #4, expecting #4
> I00016 bootstrap.c:136] Processing frame #0, expecting #5
> I00017 bootstrap.c:136] Processing frame #0, expecting #5
> I00018 bootstrap.c:136] Processing frame #5, expecting #5
> I00019 bootstrap.c:172] Bootstrap: DONE!
> I00020 boot_rom.c:76] Boot ROM initialisation has completed, jump into flash!
> I00000 hello_world.c:65] Hello World!
> I00001 hello_world.c:66] Built at: Sep 15 2021, 15:27:05
> I00002 demos.c:18] Watch the LEDs!
> I00003 hello_world.c:73] Try out the switches on the board
> I00004 hello_world.c:74] or type anything into the console window.
> I00005 hello_world.c:75] The LEDs show the ASCII code of the last character.
> I00006 demos.c:56] FTDI control changed. Enable JTAG

OpenOCD output:

> ./build/src/openocd -s tcl -f board/lowrisc-earlgrey-nexysvideo.cfg
> Open On-Chip Debugger 0.11.0+dev-00385-gb61a28086-dirty (2021-09-13-10:31)
> Licensed under GNU GPL v2
> For bug reports, read
> 	http://openocd.org/doc/doxygen/bugs.html
> DEPRECATED! use 'adapter speed' not 'adapter_khz'
> Info : Hardware thread awareness created
> force hard breakpoints
> none separate
> 
> Info : Listening on port 6666 for tcl connections
> Info : Listening on port 4444 for telnet connections
> Info : clock speed 10000 kHz
> Error: JTAG scan chain interrogation failed: all ones
> Error: Check JTAG interface, timings, target power, etc.
> Error: Trying to use configured scan chain anyway...
> Error: riscv.tap: IR capture error; saw 0x1f not 0x01
> Warn : Bypassing JTAG setup events due to errors
> Error: Unsupported DTM version: 15
> Warn : target riscv.tap.0 examination failed
> Info : starting gdb server for riscv.tap.0 on 3333
> Info : Listening on port 3333 for gdb connections

**Comment by tjaychen** [comment] 2022-02-10 01:32
@alistair23 could you give #10625 a try? it should officially add support now.

**Comment by alistair23** [comment] 2022-06-03 05:51
I have tried the latest commit and still no luck. There is `openocd -s util/openocd -f board/lowrisc-earlgrey-cw310.cfg` file as specified at https://docs.opentitan.org/doc/getting_started/setup_fpga/ so I'm unable to start an OpenOCD instance

**Comment by andreaskurth** [comment] 2023-02-23 09:54
Triaged for `rv_dm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because we should try to reproduce this with current HW and SW and ensure there's no bug hiding here.

@alistair23: Have you tried this again recently?

**Comment by moidx** [comment] 2023-04-04 00:33
@timothytrippel is this still an issue? I believe we have some test infrastructure in place for this. Feel free to close as obsolete if we already have test coverage in the ROM E2E or manufacturing.

**Comment by timothytrippel** [comment] 2023-04-04 04:12
yes we have ROM E2E tests using this infra on the CW310. So I think we can close this? Feel free to reopen if this is still an issue.

**Closed by timothytrippel** 2023-04-04 04:12 UTC
Labels: Component:FPGA, Priority:P3, Type:Bug, IP:rv_dm, Milestone:D3, Triaged

**Comment by parisaeliasi** [comment] 2025-04-30 13:17
Hi,
I am using CW340 board and when I run 
./bazelisk.sh run //third_party/openocd -- \
    -f "util/openocd/board/cw340_ftdi.cfg" \
    -c "adapter speed 500; transport select jtag; reset_config trst_only" \
    -f util/openocd/target/lowrisc-earlgrey.cfg
I still get: 
Error: JTAG scan chain interrogation failed: all zeroes
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: riscv.tap: IR capture error; saw 0x00 not 0x01
Warn : Bypassing JTAG setup events due to errors
Error: dtmcontrol is 0. Check JTAG connectivity/board power.
Warn : target riscv.tap.0 examination failed
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections

I already run:
./bazel-bin/sw/host/opentitantool/opentitantool --logging info\
        --exec "gpio write TAP_STRAP0 false" \
        --exec "gpio write TAP_STRAP1 true" \
        no-op
Without error and with Command result: success.
However, when I check the value of TAP_STRAP0 I still have true. Perhaps something (not the software) is overwriting it. I am unable to find a solution to the issue.

**Comment by parisaeliasi** [comment] 2025-04-30 13:18
Hi,
I am using CW340 board and when I run
./bazelisk.sh run //third_party/openocd --
-f "util/openocd/board/cw340_ftdi.cfg"
-c "adapter speed 500; transport select jtag; reset_config trst_only"
-f util/openocd/target/lowrisc-earlgrey.cfg
I still get:
Error: JTAG scan chain interrogation failed: all zeroes
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: riscv.tap: IR capture error; saw 0x00 not 0x01
Warn : Bypassing JTAG setup events due to errors
Error: dtmcontrol is 0. Check JTAG connectivity/board power.
Warn : target riscv.tap.0 examination failed
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections

I already run:
./bazel-bin/sw/host/opentitantool/opentitantool --logging info
--exec "gpio write TAP_STRAP0 false"
--exec "gpio write TAP_STRAP1 true"
no-op
Without error and with Command result: success.
However, when I check the value of TAP_STRAP0 I still have true. Perhaps something (not the software) is overwriting it. I am unable to find a solution to the issue.
