### ISSUE TITLE
[bazel] FusoSoC sometimes appears to corrupt the cache and requires a `bazel clean` to get unstuck

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#12349] opened 2022-04-27 14:45 UTC

**Comment by a-will** [comment] 2022-04-27 20:28
It looks like this sequence may reveal the symptoms:
1. Build verilator with a commit where usbuart still existed
2. Check out a commit after that horizon, and try to build again

bazel-out/ will still show many references to the usbuart IP, but the repo source has none.

**Comment by cfrantz** [comment] 2022-04-28 01:56
It would be interesting to know if the error could be reproduced by invoking fusesoc manually while moving across the usbuart deletion horizon.

Unfortunately, the bazel `fusesoc_build` rule is not hermetic and, IMHO, isn't as strict about its deps as it ought to be, but for the time being, I don't think that problem is worth solving in bazel.

**Comment by msfschaffner** [comment] 2023-10-06 23:23
@cfrantz @a-will @timothytrippel anything left to do here?

**Comment by a-will** [comment] 2023-10-06 23:54
Likely fixed by #19466, which causes fusesoc builds to happen in a sandbox.

**Comment by a-will** [comment] 2023-10-06 23:54
I'll close it, since I'm not aware of any remaining issues. Please re-open (or open a new issue) if this comes up again.

**Closed by a-will** 2023-10-06 23:54 UTC
Labels: Component:Software, Priority:P3, Type:Bug, Earlgrey-PROD Triaged
