### ISSUE TITLE
[test-triage] rom_e2e_boot_policy_valid_a_bad_b_good_test_unlocked0

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#18057] opened 2023-04-19 11:00 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out

### Steps to Reproduce

GitHub Revision: [24fcee5a4](https://github.com/lowrisc/opentitan/tree/24fcee5a423290416785a58ca3de6328646c1bc9)
dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
```sh
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i rom_e2e_boot_policy_valid_a_bad_b_good_test_unlocked0 --build-seed 4127990797 --fixed-seed 2785944455 --waves fsdb
```

### Tests with similar or related failures

- [ ] rom_e2e_boot_policy_valid_a_bad_b_good_test_unlocked0

**Comment by johngt** [comment] 2023-04-19 11:03
This looks like the job just timed out - let's try this on a local system and then see if there is an underlying issue.

**Comment by johngt** [comment] 2023-05-02 13:05
@luismarques - it might be worth getting an H cloud instance and seeing if you can re-run the tests. If it passes then it's purely a timeout issue and we will just need to increase the test timeouts. If there is a non timeout issue then this will need further investigation.

**Comment by luismarques** [comment] 2023-05-04 13:50
I've reproduced it. No termination at the 4 hour mark so far. Would it help if I shared the `run.log` or something else?

**Comment by moidx** [comment] 2023-05-12 01:33
Fixed by https://github.com/lowRISC/opentitan/pull/18547

**Closed** 2023-05-12 01:33 UTC
Labels: Priority:P1, Component:ChipLevelTest, Component:TestTriage, Submilestone:M2.5.2
