### ISSUE TITLE
[sw,tests,dv] Top level test permission problems

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#13087] opened 2022-06-07 17:30 UTC
I am having a problem with running top level tests.

In a newly checked out repository (a few hours ago), I am trying to run this command (this is just one example):

`util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sleep_sram_ret_contents`

The output is:

```
$TEST_TMPDIR defined: output root default is '/scratch/google/goo_opentitan/davidwil/bazel_temp' and max_idle_secs default is '15'.
WARNING: Output base '/scratch/google/goo_opentitan/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f' is on NFS. This may lead to surprising failures and undetermined behavior.
cp: cannot create regular file '/projects/google/goo_opentitan/davidwil/commit1/opentitan/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.logs.txt': Permission denied
cp: cannot create regular file '/projects/google/goo_opentitan/davidwil/commit1/opentitan/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.rodata.txt': Permission denied
cp: cannot create regular file '/projects/google/goo_opentitan/davidwil/commit1/opentitan/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.64.scr.vmem': Permission denied
make: *** [sw_build] Error 123

```
It should be noted that I have set the environment variable TEST_TEMPDIR which causes Bazel to use a specific directory for its cache files. By default it was using ~/.cache/bazel. This fills up the quota of my linux home drive so needed changing.

Also there is the warning about using NFS (all our drives, home, project, scratch are on NFS)

After the test has run and fails, below are the contents of the directory where the errors are (the files have been created mostly read-only so seemingly can't be rewritten to later in the build process):

```
ll /projects/google/goo_opentitan/davidwil/commit1/opentitan/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/
total 3.2M
-r-xr-xr-x. 1 davidwil goo_opentitan 2.7K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test.d
-r-xr-xr-x. 1 davidwil goo_opentitan  15K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test.o
-r-xr-xr-x. 1 davidwil goo_opentitan  37K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv
-r-xr-xr-x. 1 davidwil goo_opentitan  49K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.64.scr.vmem
-r-xr-xr-x. 1 davidwil goo_opentitan  43K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.64.vmem
-r-xr-xr-x. 1 davidwil goo_opentitan  18K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.bin
-r-xr-xr-x. 1 davidwil goo_opentitan  31K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.elf
-r-xr-xr-x. 1 davidwil goo_opentitan 9.5K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.logs.txt
-r-xr-xr-x. 1 davidwil goo_opentitan  13K Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.rodata.txt
-rwxr-xr-x. 1 davidwil goo_opentitan  380 Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_sim_dv
-r-xr-xr-x. 1 davidwil goo_opentitan 3.0M Jun  7 11:51 sram_ctrl_sleep_sram_ret_contents_test_sim_dv.runfiles_manifest

```

**Comment by timothytrippel** [comment] 2022-06-08 06:08
Thanks for capturing this @davebwil . Unfortunately, after several tries I am not able to reproduce this on my side. Could you perhaps provide the log files that were generated by dvsim? Additionally, could you provide me with the output of `find -L $(bazel info output_path)/  -type f -name "sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv*"` after running a failed test?

**Comment by davebwil** [comment] 2022-06-08 12:12
Hi @timothytrippel,
I have run again, changed TEST_TMPDIR and scratch to be on /tmp of the compute server I am using to avoid NFS paths.

the output of the find command:

```
find -L /tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out -type f -name "sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv*"
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild-ST-97f470ee3b14/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.64.scr.vmem
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild-ST-97f470ee3b14/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.rodata.txt
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild-ST-97f470ee3b14/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.logs.txt
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild-ST-97f470ee3b14/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.64.vmem
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild-ST-97f470ee3b14/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.elf
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild-ST-97f470ee3b14/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.bin
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild-ST-97f470ee3b14/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_sim_dv.runfiles/lowrisc_opentitan/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.rodata.txt
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_sim_dv.runfiles/lowrisc_opentitan/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.logs.txt
/tmp/davidwil/bazel_temp/_bazel_davidwil/9aac7972b16d65fae27b9052e1a1f79f/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_sim_dv.runfiles/lowrisc_opentitan/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.64.scr.vmem
```

The contents of /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out/run.log

```
[Executing]:
make -f /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/dv/tools/dvsim/sim.mk run post_run_cmds='' pre_run_cmds='/projects/google/goo_opentitan/davidwil/commit1/opentitan/util/design/gen-otp-img.py \
      --img-cfg /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/ip/otp_ctrl/data/otp_ctrl_img_raw.hjson \
      --out /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out/otp_ctrl_img_raw.vmem \
      --quiet --img-seed 568855359 && /projects/google/goo_opentitan/davidwil/commit1/opentitan/util/design/gen-otp-img.py \
     --img-cfg /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/ip/otp_ctrl/data/otp_ctrl_img_dev.hjson \
     --out /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out/otp_ctrl_img_dev.vmem \
     --quiet --img-seed 568855359 && /projects/google/goo_opentitan/davidwil/commit1/opentitan/util/design/gen-otp-img.py \
      --img-cfg /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson \
      --out /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out/otp_ctrl_img_rma.vmem \
      --quiet --img-seed 568855359' proj_root=/projects/google/goo_opentitan/davidwil/commit1/opentitan run_cmd=/tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/default/simv run_dir=/tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out run_opts='+sw_test_timeout_ns=20000000 +sw_build_bin_dir=/tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin +sw_build_device=sim_dv +sw_images=sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test:1,sw/device/lib/testing/test_rom/test_rom:0 +UVM_NO_RELNOTES +UVM_VERBOSITY=UVM_LOW +prim_cdc_rand_delay_mode=disable -licqueue -ucli -do /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/dv/tools/sim.tcl +ntb_random_seed=568855359 -assert nopostproc +UVM_TESTNAME=chip_base_test +UVM_TEST_SEQ=chip_sw_base_vseq' sw_build_device=sim_dv sw_build_dir=/tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs sw_images='sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test:1 sw/device/lib/testing/test_rom/test_rom:0' uvm_test=chip_base_test uvm_test_seq=chip_sw_base_vseq

[make]: pre_run
mkdir -p /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out
cd /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out && /projects/google/goo_opentitan/davidwil/commit1/opentitan/util/design/gen-otp-img.py \
      --img-cfg /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/ip/otp_ctrl/data/otp_ctrl_img_raw.hjson \
      --out /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out/otp_ctrl_img_raw.vmem \
      --quiet --img-seed 568855359 && /projects/google/goo_opentitan/davidwil/commit1/opentitan/util/design/gen-otp-img.py \
     --img-cfg /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/ip/otp_ctrl/data/otp_ctrl_img_dev.hjson \
     --out /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out/otp_ctrl_img_dev.vmem \
     --quiet --img-seed 568855359 && /projects/google/goo_opentitan/davidwil/commit1/opentitan/util/design/gen-otp-img.py \
      --img-cfg /projects/google/goo_opentitan/davidwil/commit1/opentitan/hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson \
      --out /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_sram_ret_contents/out/otp_ctrl_img_rma.vmem \
      --quiet --img-seed 568855359
WARNING: Commandline override of img_seed with 568855359.
WARNING: Commandline override of img_seed with 568855359.
WARNING: Commandline override of img_seed with 568855359.
[make]: sw_build
# Loop through the list of sw_images and invoke Bazel on each.
# `sw_images` is a space-separated list of tests to be built into an image.
# Optionally, each item in the list can have additional metadata / flags using
# the delimiter ':'. The format is as follows:
# <path-to-sw-test>:<index>:<flag1>:<flag2>
#
# If no delimiter is detected, then the full string is considered to be the
# <path-to-sw-test>. If 1 delimiter is detected, then it must be <path-to-sw-
# test> followed by <index>. The <flag> is considered optional.
set -e; \
mkdir -p /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs; \
for sw_image in sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test:1 sw/device/lib/testing/test_rom/test_rom:0; do \
	image=`echo $sw_image | cut -d: -f 1`; \
	index=`echo $sw_image | cut -d: -f 2`; \
	flags=(`echo $sw_image | cut -d: -f 3- --output-delimiter " "`); \
	target_dir=`dirname /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/$image`; \
	mkdir -p $target_dir; \
	cd /projects/google/goo_opentitan/davidwil/commit1/opentitan; \
	if [[ -z $image ]]; then \
		echo "ERROR: SW image \"$sw_image\" is malformed."; \
		echo "Expected format: path-to-sw-test:index:optional-flags."; \
		exit 1; \
	fi; \
	if [[ ${flags[@]} =~ "prebuilt" ]]; then \
		echo "SW image \"$image\" is prebuilt - copying sources."; \
		cp /projects/google/goo_opentitan/davidwil/commit1/opentitan/$image* $target_dir/.; \
	else \
		echo "Building SW image \"$image\"."; \
		bazel_label="//`dirname ${image}`:`basename ${image}`"; \
		if [[ $index == "1" ]]; then \
			bazel_label+="_sim_dv"; \
		fi; \
		bazel_opts="--define DISABLE_VERILATOR_BUILD=true"; \
		if [[ -z ${BAZEL_PYTHON_WHEELS_REPO} ]]; then \
			echo "Building \"${bazel_label}\" on network connected machine."; \
			bazel_cmd="./bazelisk.sh"; \
		else \
			echo "Building \"${bazel_label}\" on air-gapped machine."; \
			bazel_opts+=" --distdir=${BAZEL_DISTDIR} --repository_cache=${BAZEL_CACHE}"; \
			bazel_cmd="bazel"; \
		fi; \
		${bazel_cmd} build ${bazel_opts} ${bazel_label}; \
		find -L $(${bazel_cmd} info output_path)/ \
			-type f -name "$(basename ${image})*" | \
			xargs -I % cp % ${target_dir}; \
	fi; \
done;
Building SW image "sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test".
Building "//sw/device/tests:sram_ctrl_sleep_sram_ret_contents_test_sim_dv" on network connected machine.
$TEST_TMPDIR defined: output root default is '/tmp/davidwil/bazel_temp' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //sw/device/tests:sram_ctrl_sleep_sram_ret_contents_test_sim_dv (1 packages loaded)
Analyzing: target //sw/device/tests:sram_ctrl_sleep_sram_ret_contents_test_sim_dv (1 packages loaded, 0 targets configured)
Analyzing: target //sw/device/tests:sram_ctrl_sleep_sram_ret_contents_test_sim_dv (68 packages loaded, 1561 targets configured)
Analyzing: target //sw/device/tests:sram_ctrl_sleep_sram_ret_contents_test_sim_dv (185 packages loaded, 6090 targets configured)
INFO: Analyzed target //sw/device/tests:sram_ctrl_sleep_sram_ret_contents_test_sim_dv (227 packages loaded, 13368 targets configured).

INFO: Found 1 target...
[0 / 15] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[12 / 95] checking cached actions
[173 / 176] checking cached actions
Target //sw/device/tests:sram_ctrl_sleep_sram_ret_contents_test_sim_dv up-to-date:
  bazel-bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_sim_dv
INFO: Elapsed time: 11.651s, Critical Path: 1.58s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
$TEST_TMPDIR defined: output root default is '/tmp/davidwil/bazel_temp' and max_idle_secs default is '15'.
cp: cannot create regular file \u2018/tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.rodata.txt\u2019: Permission denied
cp: cannot create regular file \u2018/tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.logs.txt\u2019: Permission denied
cp: cannot create regular file \u2018/tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test_prog_sim_dv.64.scr.vmem\u2019: Permission denied
make: *** [sw_build] Error 123

```
Build log attached from /tmp/davidwil/scratch/toplevel_tests_sram_ret_contents_fix/chip_earlgrey_asic-sim-vcs/default/build.log:

[build.log](https://github.com/lowRISC/opentitan/files/8861379/build.log)

**Comment by timothytrippel** [comment] 2022-06-08 17:09
Thanks @davebwil. @sha-ron is experiencing a similar issue and is working on debugging this too. Sorry for any inconvenience here.

**Comment by a-will** [comment] 2022-06-08 17:29
Hm... are `\u2018` and `\u2019` referring to the unicode characters for left single quote and right single quote? Do we have some unicode handling problems with paths somewhere?

**Comment by timothytrippel** [comment] 2022-06-11 00:32
Thanks for the update @sha-ron . After discussing this with @cfrantz and @arunthomas , we had a couple more questions:

1. Did you try running your fix on a clean checkout of the repo? (i.e. a fresh `git clone`)?
1. did you try using a `cp -f ...` on [this line](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/tools/dvsim/sim.mk;drc=e7f754ffc8d592421981e7321aa254901df883f0;l=103) to see if that helps?
1. are you building on an NFS mount?

@davebwil @sha-ron If none of this helps, then let's try to setup a call early next week (Monday / Tuesday) and @cfrantz and I can help you debug. We can find a time that works for both of us. Unfortunately, as I mentioned above, we are not able to reproduce this issue on our side, nor in CI, so a call with multiple eyes on the problem might be the quickest way to resolve this. Again, sorry for any inconveniences.

**Comment by sha-ron** [comment] 2022-06-11 12:55
1. Trying a clean checkout of the repo didn't help.
2. I tried now the cp -f, still fail on the "same file" error :(
3. I have $TEST_TMPDIR defined: output root default is '/home/users/stopaz' and max_idle_secs default is '15'.
I will be in Boston next week and not sure about the schedule yet.  I can check if someone else from Nuvoton can attend.

**Comment by davebwil** [comment] 2022-06-13 12:41
I am able to run tests again.
I rebased my repo, deleted the cache for bazel (pointed to by $TEST_TMPDIR) for a fresh start.
Made the cp -f change to sim.mk.
In addition I noticed that I had a previous bazel install in my PATH (from when I was testing a unittest change). I have removed that from the path to avoid any possible conflict.
All of my directories are on NFS mounts  (home, project, scratch, bazel test tmpdir).

**Comment by timothytrippel** [comment] 2022-06-13 19:00
@sha-ron could you try what @davebwil describes and see if that fixes the issue?

**Comment by timothytrippel** [comment] 2022-06-13 19:00
CC: @arunthomas @cfrantz (for visibility)

**Comment by sha-ron** [comment] 2022-06-14 02:16
After cloning the repo again and deleting what I have under $TEST_TMPDIR I can run a test once but then I fail with the errors below:

 _INFO: Build completed successfully, 3 total actions_
__$TEST_TMPDIR defined: output root default is '/home/users/stopaz' and max_idle_secs default is '15'._
**cp:** '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.logs.txt' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.logs.txt'  **are the same file**
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.64.scr.vmem' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.64.scr.vmem' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.elf' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.elf' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles_manifest' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles_manifest' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_sim_dv' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_sim_dv' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest.d' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest.d' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.rodata.txt' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.rodata.txt' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.64.vmem' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.64.vmem' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.bin' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest_prog_sim_dv.bin' are the same file
cp: '/home/users/stopaz/_bazel_stopaz/78fa2193dfc4cb11104e6b9be43225e2/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/bin/sw/device/tests/pwrmgr_smoketest_sim_dv.runfiles/lowrisc_opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest.o' and '/tanap1/proj_cd14/opentitan/stopaz/freeze/dv_ver_69_tmp2/opentitan/hw/top_earlgrey/scratch/master/chip_earlgrey_asic-sim-vcs/build-bin/sw/device/tests/pwrmgr_smoketest.o' are the same file
make: *** [sw_build] Error 123_

**Comment by sha-ron** [comment] 2022-06-14 02:18
I am using bazel  version 5.1.1, is it ok?

**Comment by timothytrippel** [comment] 2022-06-14 06:53
yes, that is the correct version of Bazel. are you getting the above error even after you  add the `-f` flag to the `cp` command on [this line](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/tools/dvsim/sim.mk;drc=e7f754ffc8d592421981e7321aa254901df883f0;l=103)?

**Comment by sha-ron** [comment] 2022-06-14 10:49
Yes I am getting the error after adding -f flag to the cp command (without the -f I fail on permission denied error).

**Comment by Jacob-Levy** [comment] 2022-06-16 07:52
After getting the last few fixes merged, CI(private) finally passes!

         [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]                                                            
00:24:43  [    build    ]: [Q: 000, D: 000, P: 043, F: 000, K: 000, T: 043] 100%                                                                            
01:18:58  [     run     ]: [Q: 000, D: 000, P: 119, F: 000, K: 000, T: 119] 100%

**Comment by Jacob-Levy** [comment] 2022-06-16 17:17
@sha-ron Can you run your tests to make sure you are getting the same results as I did...

**Closed** 2022-06-27 16:07 UTC
Labels: Type:Bug, Component:OT_Blocks_Foundry, SW:Build System
