### ISSUE TITLE
Does it support debug core in nexysvideo reuced 

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#7759] opened 2021-08-15 09:38 UTC
Hi All
I found several issues and was wondering if it is because debug core is reduced in nexysvideo?

refresh_hw_device [lindex [get_hw_devices xc7a200t_0] 0]
INFO: [Labtools 27-1434] Device xc7a200t (JTAG device index = 0) is programmed with a design that has no supported debug core(s) in it.
refresh_hw_device [lindex [get_hw_devices xc7a200t_0] 0]
INFO: [Labtools 27-1434] Device xc7a200t (JTAG device index = 0) is programmed with a design that has no supported debug core(s) in it.

> mdw 0x8000 0x10
Failed to read priv register.
0x00008000: cda00e00 a9dcd635 e759405c e8b0263d 51a514ef bb6cb7d3 2d65024c 1b12b38f 
0x00008020: e874692d 4369c5e9 7048aa0c 9fe6f501 2a0784c7 8f9135fe 25ae3247 6384eace 

(gdb) disassemble 0x200005c0,0x200005c0+16*4
Dump of assembler code from 0x200005c0 to 0x20000600:
   0x200005c0:	Cannot access memory at address 0x200005c0
(gdb) x/16xw 0x200005c0
0x200005c0:	Cannot access memory at address 0x200005c0

Warn : JTAG tap: riscv.tap       UNEXPECTED: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
Error: JTAG tap: riscv.tap  expected 1 of 1: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
Error: Trying to use configured scan chain anyway...
Warn : Bypassing JTAG setup events due to errors

**Comment by tjaychen** [comment] 2021-08-17 00:11
the reduced version shouldn't remove the debug core.
did you follow the latest build instructions? it specifically loads certain
values into the otp that will "allow" debug to happen.

there may also be some issue with our fpga pinmuxing for the debug
interface right now, I'm not sure when was the last time we explicitly
tested against it.

**Comment by msfschaffner** [comment] 2021-08-17 20:25
Hi @nicolast0604, can you tell us a bit more about your setup? 
Via which connector on the board are you trying to connect the JTAG, for instance?

**Comment by nicolast0604** [comment] 2021-08-18 02:34
Hi msfschaffner

Great thanks for your response. 
I connect my host to the nexys video FPGA board with 2 micro usb cables according to the guideline of opentitan.
I didn't use any debug adaptor like J-linke or others like ones.

Nicolas

**Comment by nicolast0604** [comment] 2021-08-18 02:40
Hi tjaychen
Great thanks for your response.
I checked the issue [fpga, pinmux] One issue to fpga debug interface not working #7783.
I am not sure if I can fully understand as I am a beginner to this but I have this issue only on FPGA and in verilator it seems works very well.

What's the next shall I try? do I need to switch the USB ports or something ?

BR
Nicolas

**Comment by tjaychen** [comment] 2021-08-18 02:48
Hi Nicolas,
let me double check with a few others, but i'm afraid this is an issue with
how our FPGA models this stuff.
Unless you want to jump in and help us make a fix :), my feeling is that
there's nothing you can do right now (at the connector level) to make this
work.

**Comment by nicolast0604** [comment] 2021-08-18 07:16
Hi Tjaychen
Could you please elaborate more about this issue on FPGA models? 
Though I have very little knowledge but please feel free to let me know if there is anything I can do to help.

Nicolas

**Comment by tjaychen** [comment] 2021-08-18 17:54
if you look at the linked issue, you'll see the issue is two fold

- the current configuration doesn't actually allocate a pin necessary to select the jtag interface
- our scripts right now i do not believe drive the appropriate signals needed to select the jtag interface.

So there is both a design change and a scripting change needed.

**Comment by msfschaffner** [comment] 2021-08-18 20:07
It could be one of the points that Tim has mentioned - but technically the pin mapping should be fine if only the RISC-V TAP needs to be selected (we would need another input pin to select other TAPs in the system, though). The scripts should be able to handle this as well, since even before the new TAP selection mechanism it was necessary to drive a "JTAG select signal" to the same pin (IOB7).

So it looks like some more debugging is needed to figure out the root cause of this issue...

**Comment by vogelpi** [comment] 2022-05-23 16:28
I am closing this issue as there hasn't been activity here for quite some time. Also, it has been decided to drop support for the NexysVideo in the meantime. Our main FPGA platform is the ChipWhisperer CW310 board.

**Closed by vogelpi** 2022-05-23 16:28 UTC
Labels: Component:FPGA, Priority:P3, Type:Question, IP:rv_dm, Milestone:D3
