### ISSUE TITLE
[hw,uart] noise filter issue with CDC instrumentation

### ISSUE THREAD

**Issue by crteja** [lowRISC/opentitan#18912] opened 2023-06-14 13:36 UTC
### Description

With CDC enabled, the `primt_flop_2sync` module introduces a random delay of 1 cycle. 
https://github.com/lowRISC/opentitan/blob/3bf9d8741d1cf4369d3b34cba477718c22065946/hw/ip/uart/rtl/uart_core.sv#L230-L239

Due to this, a pulse of one cycle will randomly 
- produce a pulse of two cycles
- miss the pulse
- passthrough the pulse
![Screenshot from 2023-06-14 14-32-03](https://github.com/lowRISC/opentitan/assets/124047397/32ea2776-0f99-4581-98ae-a24c2aace714)

The noise filter in `uart` module filters glitches of up to one cycle.

**Comment by GregAC** [comment] 2023-06-14 13:49
@msfschaffner please note.

I don't think this should be considered a bug, the sync module here being used to synchronize an async input rather than being used in CDC. The RTL is implementing what the spec asks for.

A separate question is whether the specified noise filter is sufficient, at a 25 MHz clock you'll filter any pulse at under 40ns. Seems OK though there may be an expectation that UART lines can handle more noise.

**Comment by msfschaffner** [comment] 2023-06-16 11:03
Agreed, I don't think that should be treated as a bug. 
It is also questionable whether that noise filter spec is meaningful, given that it can only filter very short noise pulses (as you already pointed out).

**Comment by rswarbrick** [comment] 2024-03-07 16:52
Is there anything left in this issue that needs doing? (@msfschaffner / @GregAC)

**Comment by msfschaffner** [comment] 2024-03-07 19:05
Does this still lead to test failures or was this just an observation?
If it is the latter, I think this is "working as intended".

**Comment by rswarbrick** [comment] 2024-03-08 10:00
As far as I can see, this is working as intended either way. DV fixes might be needed, but this issue doesn't describe them :-)

Let's close this and worry about any future problems if they arise.

**Closed by rswarbrick** 2024-03-08 10:00 UTC
Labels: Priority:P2, Component:RTL, IP:uart, Earlgrey-PROD Candidate
