### ISSUE TITLE
[otbn] done_o mismatch between the model and rtl

### ISSUE THREAD

**Issue by vrozic** [lowRISC/opentitan#7773] opened 2021-08-17 08:40 UTC
It seems that in some cases signal otbn_model_done  is set one cycle before otbn_done_q.

For example, when running error test:

./build/lowrisc_ip_otbn_top_sim_0.1/sim-verilator/Votbn_top_sim --trace  --load-elf ./build-bin/sw/otbn/err_test.elf 

the following errors appear

ERROR: At time 52, otbn_done_q != otbn_model_done (1 != 0).
ERROR: At time 54, otbn_done_q != otbn_model_done (0 != 1).

**Comment by rswarbrick** [comment] 2021-08-17 12:51
Please can you give instructions about how to reproduce this? What is `err_test.elf`?

**Comment by vrozic** [comment] 2021-08-17 14:31
To reproduce the error:

1. Build executables
`cd "$REPO_TOP"`
`./meson_init.sh`
`ninja -C build-out all`

2. Build the environment for OTBN simulation
`fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ip:otbn_top_sim`

3. load and run err_test.elf
`./build/lowrisc_ip_otbn_top_sim_0.1/sim-verilator/Votbn_top_sim --trace  --load-elf ./build-bin/sw/otbn/err_test.elf`

err_test.s is an OTBN code designed to trigger BadDataAddr error

It is located in:
 `./sw/otbn/code-snippets/`

**Comment by rswarbrick** [comment] 2021-08-17 15:25
Ahah. That's caused by a faulting `LW` and is to do with stall timing. Fixed by #7655.

**Closed** 2021-08-18 16:03 UTC
Labels: Component:OTBN
