### ISSUE TITLE
[test-triage] chip_sw_lc_ctrl_transition dummy.num() == 0

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18528] opened 2023-05-11 12:46 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
Test chip_sw_lc_ctrl_transition has 1 failures.
6.chip_sw_lc_ctrl_transition.4027830492
Line 1073, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/6.chip_sw_lc_ctrl_transition/latest/run.log

  UVM_ERROR @ 1813.308903 us: (chip_sw_base_vseq.sv:692) [uvm_test_top.env.virtual_sequencer.chip_sw_lc_ctrl_transition_vseq] Check failed status_val >> dummy.num() == 0 (11487 [0x2cdf] vs 0 [0x0]) Unexpected status error 2cdf000
  UVM_INFO @ 1813.308903 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

### Steps to Reproduce

- GitHub Revision: [bbebcaff9](https://github.com/lowrisc/opentitan/tree/bbebcaff907f3b02206742f6b3b18d0c4a2a40c3)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_lc_ctrl_transition --build-seed 1483844113 --fixed-seed 4027830492 --waves fsdb

### Tests with similar or related failures

- [ ] chip_sw_lc_ctrl_init
- [ ] chip_sw_lc_ctrl_transitions
- [ ] chip_sw_lc_ctrl_kmac_req
- [ ] chip_sw_lc_ctrl_broadcast
- [ ] chip_sw_kmac_app_lc
- [ ] chip_otp_ctrl_init
- [ ] chip_sw_otp_ctrl_program

**Comment by moidx** [comment] 2023-05-13 06:23
Root caused as DV sequencing issue. Committed fix. Moving to M2.5.2 to follow up after we get regression results.

**Comment by jdonjdon** [comment] 2023-05-15 22:03
fixed by #18582

**Closed by jdonjdon** 2023-05-15 22:03 UTC
Labels: Priority:P1, IP:lc_ctrl, Component:TestTriage, Submilestone:M2.5.2
