### ISSUE TITLE
[test-triage] chip_sw_aes_sideload

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#14332] opened 2022-08-17 17:02 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
UVM_ERROR @ 5286.263870 us: (sw_logger_if.sv:521) [aes_sideload_test_prog_sim_dv(w/device/lib/testing/keymgr_testutils.c:112)] CHECK-fail: Unexpected status: 3
  UVM_INFO @ 5286.263870 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```
New issue - only observed since 17 August. All runs before passing

### Steps to Reproduce

Observed only since 17 August
[cab5ffb90](https://github.com/lowrisc/opentitan/tree/cab5ffb9055258dcad355d60ac2c655519fbc000)
Build seed 3773991536, VCS

### Tests with similar or related failures

- [ ] chip_sw_keymgr_sideload_aes

**Comment by abdullahvarici** [comment] 2022-08-22 16:11
I have tried to find the root cause for this issue. 

After running [this](https://github.com/lowRISC/opentitan/blob/72e092e3837aa2ab96e4a58cb3c5f416e52a19a7/sw/device/tests/aes_sideload_test.c#L47) function, KEYMGR.OP_STATUS becomes "0x3 - DONE_ERROR" and lsb bit of the KEYMGR.ERR_CODE is set meaning "Invalid operation issued to key manager, synchronous error". 

Maybe error is due to [this](https://github.com/lowRISC/opentitan/blob/72e092e3837aa2ab96e4a58cb3c5f416e52a19a7/sw/device/lib/testing/keymgr_testutils.h#L37) line of code. Need to check specification. 

Any idea?

**Comment by tjaychen** [comment] 2022-08-22 16:50
that is very peculiar. Let me have a look as well.
the `error` suggests we issued a transaction that `keymgr` does not support, given the state the module is in. 
But it's pretty strange it's suddenly happening since this stuff is pretty static.

**Comment by tjaychen** [comment] 2022-08-22 20:08
just a note to issue filing, it would be good to indicate both the build seed and the run seed. 
Most of the time, the run seed is probably more important.

**Comment by tjaychen** [comment] 2022-08-26 03:55
unassigned since this is not currently being triaged.

**Comment by tjaychen** [comment] 2022-08-26 21:11
assigning to @tjaychen for triage.

**Comment by tjaychen** [comment] 2022-08-26 21:31
this issue appears to have been resolved and working in the latest nightly.
I will resolve this for now and re-open later if needed.

**Closed by tjaychen** 2022-08-26 21:31 UTC
Labels: Component:TestTriage

**Comment by tjaychen** [comment] 2022-08-26 21:54
i ran a quick local regression of 50 seeds and also could not reproduce the issue.
