### ISSUE TITLE
[ci] Use clearer suffixes for test_rom and mask_rom bitstreams

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#13203] opened 2022-06-14 14:11 UTC
The `splice_rom.sh` script uses `.orig` for test\_rom and `.splice` for mask\_rom which can be confusing in other scripts.
We could probably just use `.test_rom` and `.mask_rom` or something similar.

**Comment by dmcardle** [comment] 2022-07-22 20:26
Closing as a dupe of #13807

**Closed by dmcardle** 2022-07-22 20:26 UTC
Labels: Priority:P3, Type:Enhancement, Component:CI
