### ISSUE TITLE
[chip, dv, cov] Address low coverage of alert_dump and crashdump signals

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#15427] opened 2022-10-12 00:24 UTC
The `alert_dump` and `crashdump` signals from alert handler and ibex respectively are "saved" in registers in rstmgr during an unexpected event causing a reset (such as alert escalation). These signals do not have a full 100% toggle coverage. 

Filing an issue to see if there is a scope for improving existing tests to get these to 100%. The crashdump signal holds PC / addresses which may be hard to get to 100% coverage, so they will need to be excluded. It will be a good idea to add these signals to FPV and blanket exclude for DV. Soliciting feedback to close on these soon before M2.

**Comment by sriyerg** [comment] 2022-10-12 23:34
Discussed offline and agreed on excluding these buses in DV sims in favor of:

- [ ] Ensuring proper latching of these dump signals is done correctly and verified in `ibex_top` and `alert_handler` testbenches
- [ ] Ensuring rstmgr verifies these inputs are randomized and read-checked for correctness after mimicking a reset req scenario
- [ ] Having basic chip level has tests verifying the crash / alert dump paths from source to rstmgr dest, AND these dump values verified for correctness post reset 
- [ ] Adding crash and alert dump paths to FPV connectivity tests

@tjaychen @msfschaffner @matutem @cindychip @GregAC do we all agree?

**Comment by msfschaffner** [comment] 2022-10-13 01:26
This SGTM!

**Comment by tjaychen** [comment] 2022-10-13 17:05
@jeoongp 

For the first point, the latching is done partly inside `ibex` and partly inside `rv_core_ibex`.  So for the double fault related things we'll probably need to rely on the 3rd check point. 

I believe the 2nd point is already covered in block level, but would need @matutem to confirm.

**Comment by matutem** [comment] 2022-10-28 22:47
Well, both dumps are essentially inactive, meaning they don't really trigger actions, and are simply captured to be read subsequently. This means each bit is independent of the others. Apparently they cannot be cleared either, they are just overwritten when another reset occurs.

A few rstmgr unit tests sets them to random and reads a few times to confirm the value is as expected, meaning they are overwritten. There are also checks for resets that should not cause them to be captured. I don't recall any test failure due to this functionality: it is actually quite simple.

I think if the per bit toggle is low we may need to add some more randomization or more reseeds.

In addition, the rv_core_ibex and alert_handler unit tests should check the output is expected for the different kinds of resets. With this, in top-level, all we would really need is to confirm connectivity. Nevertheless, there are many tests where we actually test individual bits.

I do not think toggling all bits in top-level tests is a sensible goal.

**Comment by msfschaffner** [comment] 2022-10-28 23:10
Thanks @matutem! I think we are aligned on the fact that toggling all bits in the top-level tests is needed.

Given that the block-level environments check these outputs, the only thing left to do here appears to be the connectivity checks - I can do that.

**Comment by msfschaffner** [comment] 2022-10-28 23:23
Double checked with @cindychip: the alert handler block level DV checks the crashdump outputs.

**Comment by matutem** [comment] 2022-10-31 22:14
Wanted to clarify: @msfschaffner you said above "I think we are aligned on the fact that toggling all bits in the top-level tests is needed."... Did you misstate this? I thought we agreed we did *not* need all bits to toggle at top-level tests, rather all toggling at the three unit levels involved plus connectivity.

**Comment by msfschaffner** [comment] 2022-10-31 22:19
woops, I may have stumbled over my fingers when writing this, thanks for pointing it out. there is a missing NOT in that sentence. I corrected the comment.

**Comment by msfschaffner** [comment] 2022-10-31 22:20
The only part that remains to be confirmed is whether the Ibex crashdump is adequately tested. We can discuss this in the V2 meeting for Ibex tomorrow.

CC @GregAC @vogelpi @ctopal

**Comment by GregAC** [comment] 2022-11-01 13:44
No testing for crashdump within Ibex DV currently, may just need some assertions to do it.

**Comment by tjaychen** [comment] 2022-11-01 17:31
@GregAC when you say assertions, do you mean that we would check the dump output accurately reflects what is inside the core? 

I guess the other thing is the double fault stuff, which is handled outside the core in `rv_core_ibex`.  We do have tests on that, but it'd be great if you guys can have a look at that top level test and see if you feel coverage is sufficient. I think @HU90m and @engdoreis already did this, but I wanted to double check.

**Comment by engdoreis** [comment] 2022-11-03 10:37
@HU90m will confirm, but as far as I can tell, we are testing most of the possible scenarios on the SW perspective in the `chip_sw_rstmgr_cpu_info`

**Comment by HU90m** [comment] 2022-11-07 09:00
The `chip_sw_rstmgr_cpu_info` test checks the fields of cpu info dump after a single and a double fault. It doesn't have any randomization so, for example, the fault is always caused by the same memory access faults at the same addresses. I think it is currently sufficient for a top level test, but if it's lacking coverage we could add some randomization?

**Comment by vogelpi** [comment] 2022-11-07 09:22
Hi @HU90m ,
adding some randomization sounds reasonable to me. But @engdoreis has probably a better overview of the current state of TLT to judge where further effort is best spent.

For inspiration, you can have a look at the [`otbn_mem_scramble_test.c`](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/otbn_mem_scramble_test.c) which uses randomness from rv_core_ibex (provided through EDN) to randomize addresses to be accessed within OTBN.

**Comment by HU90m** [comment] 2022-11-07 14:59
I just spoke to @engdoreis. We're interested in whether adding randomization to the fault cause and, for memory faults, the addresses would increase coverage for `rv_core_ibex` (the wrapper) or `rstmgr`?

**Comment by tjaychen** [comment] 2022-11-07 17:45
yeah i think some of it relates to the memory address.
However, if you look at what the crash dump actually contains, it contains things like the data address, current pc, next pc etc. 
So even if you randomize the memory fault address, it only impacts the first.  The current pc / next pc may not shift around a ton because the test is pretty much going to be the same.  So I don't believe the coverage of those signals will really change.

**Comment by sriyerg** [comment] 2022-11-07 19:05
Adding elements of randomization to maximize the coverage of these signals (to the extent possible) would be great, but not a high priority IMO. We can address it in M3. They have already been excluded from coverage collection at the chip level.

**Comment by msfschaffner** [comment] 2022-11-07 19:18
Yeah I agree, let's work on the randomization enhancements in M3 then.

@GregAC plans on add an assertion in ibex to check the basic functionality which should address the concern that we had here (see https://github.com/lowRISC/ibex/issues/1901).

**Comment by johngt** [comment] 2022-11-08 12:53
@msfschaffner safe to retag this issue as M3 based on discussion above? https://github.com/lowRISC/ibex/issues/1901 captures the M2 part of this / V2.

**Comment by msfschaffner** [comment] 2022-11-08 21:55
Yes, let's do that.

**Comment by GregAC** [comment] 2022-11-12 10:18
> @GregAC plans on add an assertion in ibex to check the basic functionality which should address the concern that we had here (see https://github.com/lowRISC/ibex/issues/1901).

Had a look at this in more detail, only easy assertions to add are just basic connectivity checks that only go down a level or hierarchy or two (within `ibex_top`), though I guess better than nothing: https://github.com/lowRISC/ibex/pull/1924

I think this combined with the `chip_sw_rstmgr_cpu_info` TLT @HU90m mentioned should be sufficient for M2, we can consider more detailed testing for M3 (e.g. The Ibex cosim could predict values but it'll be a little tricky to sync this up so I don't want to attempt it now).

**Comment by GregAC** [comment] 2022-11-12 10:19
@msfschaffner @sriyerg please confirm you're happy with the above

**Comment by msfschaffner** [comment] 2022-11-14 18:10
That sounds good to me.

**Comment by GregAC** [comment] 2023-02-24 18:05
I don't think more detailed testing as mentioned above is needed for M2.5, though worth looking at if time permits.

**Comment by matutem** [comment] 2024-07-22 20:43
All pending items are completed. Closing this issue.

**Closed by matutem** 2024-07-22 20:43 UTC
Labels: Component:DV, Priority:P3, Type:Task, IP:rv_core_ibex, TOP:earlgrey, Milestone:V3, Earlgrey-PROD Candidate
