### ISSUE TITLE
DFT – In ibex_lockstep block rst_shadow_set_q reset should be controlled in scan-mode

### ISSUE THREAD

**Issue by NoamGottlieb** [lowRISC/opentitan#6161] opened 2021-04-18 13:48 UTC
rst_shadow_set_q affecting 1814 FFs. In scan mode it is not controlled, hence these FFs are removed from scan.
SpyGlass message: 'chip_earlgrey_asic.top_earlgrey.u_rv_core_ibex.u_core.\gen_lockstep.u_ibex_lockstep .rst_shadow_set_q' is not disabled for 1814 flip-flop(s)
ibex_lockstep.sv file, line 117: rst_shadow_set_q <= rst_shadow_set_d;
![image](https://user-images.githubusercontent.com/79256454/115144851-8e019780-a057-11eb-8863-72c0ab7bc2a1.png)
 

Suggested fix in ibex_lockstep.sv file - add a scan reset mux for rst_shadow_set_q

**Comment by NoamGottlieb** [comment] 2021-04-18 13:49
@tjaychen
@msfschaffner
@tomroberts-lowrisc

**Comment by NoamGottlieb** [comment] 2021-04-18 13:50
@arnonsha

**Comment by tjaychen** [comment] 2021-04-19 17:53
yes this one is known.  Please see #6058

**Comment by imphil** [comment] 2021-04-19 17:55
Closing as duplicate of #6058. Let's keep one issue around to make tracking easier.

**Closed by imphil** 2021-04-19 17:55 UTC
