### ISSUE TITLE
[ast] Asserts in AST firing

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#11195] opened 2022-03-02 18:30 UTC
I have been working on updates for "chip_sw_sram_scrambled_access" and rebased my branch twice in the last couple of days. Since then I have been experiencing random firing of asserts in the AST block.

e.g.

from Xcelium
xmsim: *E,ASRTST (..../chip_earlgrey_asic-sim-xcelium/default/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sender.sv,92): (time 15876 NS) Assertion tb.dut.u_ast.u_ast_clks_byp.u_io_clk_byp_ack.OutputsKnown_A has failed 
xmsim: *E,ASRTST (..../chip_earlgrey_asic-sim-xcelium/default/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sender.sv,92): (time 15876 NS) Assertion tb.dut.u_ast.u_ast_clks_byp.u_all_clk_byp_ack.OutputsKnown_A has failed 
xmsim: *E,ASRTST (..../chip_earlgrey_asic-sim-xcelium/default/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sync.sv,140): (time 15876 NS) Assertion tb.dut.u_ast.u_ast_clks_byp.u_all_clk_byp_req.OutputsKnown_A has failed 
xmsim: *E,ASRTST (..../chip_earlgrey_asic-sim-xcelium/default/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sync.sv,140): (time 15876 NS) Assertion tb.dut.u_ast.u_ast_clks_byp.u_io_clk_byp_req.OutputsKnown_A has failed 

from VCS.
"../src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sync.sv", 140: tb.dut.u_ast.u_ast_clks_byp.u_io_clk_byp_req.OutputsKnown_A: started at 14392000ps failed at 14392000ps

These asserts come and go unpredictably as I am working on the code.

When I added the following assertoff in the test vseq the asserts go away but looking at the waves for the blocks there seems to be nothing that would trigger the assert. ($assertoff(0,"tb.dut.u_ast.u_ast_clks_byp");)

The latest version of my test code (exactly the same for all) behaves as follows:

VCS (no waves). Asserts triggered.
VCS (with waves) Asserts not triggered.
Xcelium (no waves) Asserts not triggered.

It looks like the asserts are subject to the dynamics of the simulation which vary with sim, wave capture and minor changes to the test.

Are they glitchy or in some other way subject to simulation dynamics? Could you take a look?

Thanks.

**Comment by Jacob-Levy** [comment] 2022-03-02 19:51
The AST does not have any asserts written in the ast_clk_byp.sv block. The block is using the prim_mubi4_sync.sv and prim_mubi4_sender.sv that has assertions that seem to be firing. It might be related to reset on those prim cell. @msfschaffner  is more familiar with those prim cell assertions.

**Comment by tjaychen** [comment] 2022-03-03 01:31
@matutem 

so various people seem to be encountering some flakiness in this area. I still haven't had a chance to see a wave so I can't say for certain.

@davebwil if you happen to have a test that reproduces this, can you send it my way?

**Comment by tjaychen** [comment] 2022-03-03 02:37
i think i have some idea why this is happening. I am discussing a few people offline, please stay tuned.

**Comment by Jacob-Levy** [comment] 2022-03-03 11:39
The issue found to be the at aon_clk oscillator code (and others). 
It is not egnouth to start the oscillator at time 0 with 0, it has to stay 0  during the first half of the period.
The 0 at time 0 was good for some runs but it failed in others.
I made sure the the free running oscillator stay at 0 for the first half period and it sould resolve the issue.

**Comment by tjaychen** [comment] 2022-03-03 22:38
i believe this should be fixed now, please give it a try and let us know.

**Comment by davebwil** [comment] 2022-03-04 16:50
Thanks, the asserts are now gone. (on Xcelium.)
However, I am having a problem with VCS. The simulator is crashing. I tried this on a clean checkout on a different branch to isolate it from my test under development and used some existing tests (specifically chip_sw_sram_ctrl_smoketest and chip_sw_kmac_mode_cshake_test). 

Xcelium seems to work ok.

An example of the VCS run.log is below. I don't know if this is related to this issue specifically or whether something else was checked in overnight that might be causing it. Could you guys see if you can recreate this crash?

```
Stopping new assertion attempts at time 0ps: level = 0 arg = dut.top_earlgrey.u_pinmux_aon.AonWkupReqKnownO_A (from inst tb (../src/lowrisc_dv_chip_sim_0.1/tb/tb.sv:295))
UVM_INFO @ 0 ps: reporter [RNTST] Running test chip_base_test...
UVM_INFO @         0 ps: (mem_bkdr_util.sv:519) [mem_bkdr_util[FlashBank0Info]] Set memory
UVM_INFO @         0 ps: (mem_bkdr_util.sv:519) [mem_bkdr_util[FlashBank1Info]] Set memory
UVM_INFO @         0 ps: (tb.sv:366) [mem_bkdr_util[Otp]] Loading mem from file:
otp_ctrl_img_rma.vmem
UVM_INFO @         0 ps: (mem_bkdr_util.sv:528) [mem_bkdr_util[Rom]] Randomizing mem contents
Assertion failed "0" at line 815 in file assignmentpattern.cc

An unexpected termination has occurred in ...../toplevel_tests_testing/chip_earlgrey_asic-sim-vcs/default/simv due to an assertion failure in the tool
Hostname fm03.wk.ensilica.com


Command line: ...../toplevel_tests_testing/chip_earlgrey_asic-sim-vcs/default/simv +sw_build_bin_dir=...../toplevel_tests_testing/chip_earlgrey_asic-sim-vcs/build-bin +sw_build_device=sim_dv +sw_images=sw/device/tests/sram_ctrl_smoketest:1,sw/device/lib/testing/test_rom/test_rom:0 +UVM_NO_RELNOTES +UVM_VERBOSITY=UVM_LOW -licqueue -ucli -do /projects/google/goo_opentitan/davidwil/commit7/opentitan/hw/dv/tools/sim.tcl +ntb_random_seed=2239141836 -assert nopostproc +UVM_TESTNAME=chip_base_test +UVM_TEST_SEQ=chip_sw_base_vseq

--- Stack trace follows:

Dumping VCS Annotated Stack:
#0  0x00002aaac4438a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00002aaac35d8c2f in SNPSle_95c894712e6f9118bc51d0bbc485432a () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#2  0x00002aaac35d90d6 in SNPSle_de8e8fbcd7ecf84c9ae14573df0a2ec6 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#3  0x00002aaac3685565 in SNPSle_57415c5b07ec5e8b8118f96e6212a2c42c69fd3f49376c0d () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#4  0x00002aaac368a226 in SNPSle_1ac40924fdff8310f5184d6eb67c5798036a89169a27d790 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#5  0x00002aaac368c000 in SNPSle_a00aeeb47fd325df3eff4946e57739a1 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#6  0x00002aaac368c7c7 in SNPSle_8aaad5c586c7296aafc380368752bb09 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#7  0x00002aaac368c7e6 in SNPSle_8aaad5c586c7296a () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#8  0x00002aaac35da4bc in SNPSle_94a979f2a5637ee494a8dd1225b7e6c6 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libuclinative.so
#9  0x00002aaac4434ea5 in start_thread () from /lib64/libpthread.so.0
#10 0x00002aaac4a49b0d in clone () from /lib64/libc.so.6
#0  0x00002aaac4a10659 in waitpid () from /lib64/libc.so.6
#1  0x00002aaac498df62 in do_system () from /lib64/libc.so.6
#2  0x00002aaac498e311 in system () from /lib64/libc.so.6
#3  0x00002aaaba9f85db in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313e639d2928478c79b3f673f99203bcf8be64600612100082236bffb2007f1e0ef9 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/liberrorinf.so
#4  0x00002aaaba9fa0c7 in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313efba706aab251478fa49e66610e453774633a6c152e7ef778f2202cda681f3d4e () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/liberrorinf.so
#5  0x00002aaaba9f2622 in SNPSle_d35ca1ff70d465c2b9b1a72eee90a50630165806651fae961ce1525e42aba82d () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/liberrorinf.so
#6  0x00002aaaba9f2d31 in SNPSle_b99eb917516be923fc05e2a3c06e04c8 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/liberrorinf.so
#7  0x00002aaaba9f2dc2 in SNPSle_b99eb917516be9239434618208845a0ee01bf61ea4fd0e30 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/liberrorinf.so
#8  0x00002aaabf507d55 in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e024165e204bdeb1fb5b7e682ccf8a2e834994f1a3fc9ef1ce1a680b302dddeae9efc8cd2d50cf57d6d1b3ad16d6982c91d1 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#9  0x00002aaabf50b2c3 in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e02444e7583aa80903e89f5ecf4e1af2a132b6cd797406c2196c83b17ac813888baf020ea3a5bdda8c9ff810f9d33b74ace5 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#10 0x00002aaabf50b25b in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e02444e7583aa80903e89f5ecf4e1af2a132b6cd797406c2196c83b17ac813888baf020ea3a5bdda8c9ff810f9d33b74ace5 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#11 0x00002aaabf50bc52 in SNPSle_68a2920116cfe3675277508869bbf41d1e7e823570a4e0247b3eb0fd170a9b5a83b610e005dde3eee35987accc43897e69620faf47120bc2 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#12 0x00002aaabf50be95 in SNPSle_217b54a4fd79459801d29acbc1c64a4019c148b895e6cf94 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#13 0x00002aaab42904a2 in N_VCSgd_IzxFE () from ...../toplevel_tests_testing/chip_earlgrey_asic-sim-vcs/default/simv.daidir/_31080_archive_1.so
#14 0x00002aaab4290154 in N_VCSgd_IzxFE () from ...../toplevel_tests_testing/chip_earlgrey_asic-sim-vcs/default/simv.daidir/_31080_archive_1.so
#15 0x00002aaabd4c32fe in SNPSle_63c7abb936d47b0787bcc066faceb6081f288c247f8a3aba () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#16 0x00002aaabd678387 in SNPSle_490598bfebcc8e81efcf3d1815066cc9 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#17 0x00002aaabd691455 in SNPSle_490598bfebcc8e81 () from /tools/synopsys/installs/R-2020.12-SP2-2_vcs/linux64/lib/libvcsnew.so
#18 0x000000000047e3bf in main ()

Process VmPeak: 819868 kb, VmSize: 809164 kb
System Free Memory: 151054920 kb, System Free Swap: 15868748 kb

No context available
make: *** [simulate] Error 255
```

**Comment by tjaychen** [comment] 2022-03-04 18:07
@davebwil this latest failure is related to #11246 
just get the latest, and things should be okay.

**Comment by tjaychen** [comment] 2022-03-04 18:07
if it's okay with you, i will close this first since the issue is resolved on at least xcelium and the vcs issue is something else.

**Closed by tjaychen** 2022-03-04 18:07 UTC
