### ISSUE TITLE
[test-triage] chip_sw_rstmgr_alert_info failure

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#15237] opened 2022-10-03 16:52 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

UVM_ERROR @ 13196.098712 us: (sw_logger_if.sv:522) [rstmgr_alert_info_test_prog_sim_dv(sw/device/tests/rstmgr_alert_info_test.c:879)] CHECK-fail: Should have reset before this line
  UVM_INFO @ 13196.098712 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]

### Steps to Reproduce

Commit hash :[67a41e3bc](https://github.com/lowrisc/opentitan/tree/67a41e3bc3ff025554a024cdb15fbf892c4752b3)
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_rstmgr_alert_info --fixed-seed 582793670 --build-seed 3413385032 -w fsdb -v m

**Comment by tjaychen** [comment] 2022-10-03 21:40
@jdonjdon i pushed #15210 last week, hoping it would resolve this issue... maybe the timeout i added still isn't enough?

**Comment by jdonjdon** [comment] 2022-10-03 21:41
@tjaychen hard to tell. This is from Sunday's regression.

**Comment by msfschaffner** [comment] 2022-10-05 00:54
This is still failing in Monday's regression:

```
build-seed 3413385032

Test chip_sw_rstmgr_alert_info has 1 failures.
2.chip_sw_rstmgr_alert_info.582793670
Line 632, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/2.chip_sw_rstmgr_alert_info/latest/run.log

  UVM_ERROR @ 11780.718860 us: (sw_logger_if.sv:522) [rstmgr_alert_info_test_prog_sim_dv(sw/device/tests/rstmgr_alert_info_test.c:879)] CHECK-fail: Should have reset before this line
  UVM_INFO @ 11780.718860 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

**Comment by jdonjdon** [comment] 2022-10-05 01:05
> This is still failing in Monday's regression:
> 
> ```
> build-seed 3413385032
> 
> Test chip_sw_rstmgr_alert_info has 1 failures.
> 2.chip_sw_rstmgr_alert_info.582793670
> Line 632, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/2.chip_sw_rstmgr_alert_info/latest/run.log
> 
>   UVM_ERROR @ 11780.718860 us: (sw_logger_if.sv:522) [rstmgr_alert_info_test_prog_sim_dv(sw/device/tests/rstmgr_alert_info_test.c:879)] CHECK-fail: Should have reset before this line
>   UVM_INFO @ 11780.718860 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
>   --- UVM Report catcher Summary ---
> ```

@tjaychen made fix candidate [here](https://github.com/lowRISC/opentitan/pull/15275)

**Comment by msfschaffner** [comment] 2022-10-07 00:30
The test passed again in the nightlies today.
I also reran this with 128 seeds on https://github.com/lowrisc/opentitan/tree/610db294aa521f730e7a44d14795a51a9dc6a337  and got one other (different) timeout failure:
```
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_rstmgr_alert_info --reseed 128 -mp 128

|  Stage  |              Name               | Tests                     |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:-------------------------------:|:--------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V2    |    chip_sw_rstmgr_alert_info    | chip_sw_rstmgr_alert_info |      1.018h       |     30.254ms     |    127    |   128   |   99.22 %   |
|   V2    | chip_sw_alert_handler_crashdump | chip_sw_rstmgr_alert_info |      1.018h       |     30.254ms     |    127    |   128   |   99.22 %   |
|   V2    |                                 | **TOTAL**                 |                   |                  |    127    |   128   |   99.22 %   |
|         |                                 | **TOTAL**                 |                   |                  |    127    |   128   |   99.22 %   |

## Failure Buckets

* `UVM_ERROR @ * us: (chip_sw_base_vseq.sv:223) virtual_sequencer [chip_sw_rstmgr_alert_info_vseq] SW TEST TIMED OUT. STATE: SwTestStatusInTest, TIMEOUT = * ns` has 1 failures:
    * Test chip_sw_rstmgr_alert_info has 1 failures.
        * 63.chip_sw_rstmgr_alert_info.3289902341\
          Line 1093, in log /workspaces/repo/scratch/master/chip_earlgrey_asic-sim-vcs/63.chip_sw_rstmgr_alert_info/latest/run.log

                UVM_ERROR @ 37762.602101 us: (chip_sw_base_vseq.sv:223) uvm_test_top.env.virtual_sequencer [uvm_test_top.env.virtual_sequencer.chip_sw_rstmgr_alert_info_vseq] SW TEST TIMED OUT. STATE: SwTestStatusInTest, TIMEOUT = 30000000 ns
                
                UVM_INFO @ 37762.602101 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
                --- UVM Report catcher Summary ---
```
maybe we need to increase the SW test timeout as well now?

**Comment by tjaychen** [comment] 2022-10-07 01:07
yeah it's possible. The issue with this test is that it expects there to be a ping timeout error. But the ping timeouts don't necessarily happen immediately since the selection vector is almost 2x the size of our actual number of alerts.   I think I gave it enough time to to try...4 times? it's about 50/50 each time... we could extend that to 8 times or something to "almost" guarantee it will happen.

**Comment by tjaychen** [comment] 2022-10-11 16:26
yes let's close. We merged a fix for it explicitly a few days ago.  Sorry I forgot to come back here and close it.

**Closed as completed by tjaychen** 2022-10-11 16:26 UTC
Labels: Component:TestTriage
