### ISSUE TITLE
[docker] Docker build failures

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8569] opened 2021-10-07 19:24 UTC
For whatever reason, when I attempt to build, I get the following error.
I build with the `--no-cache` option.

This error seems specific to my system, and will work as long as I take `USER dev` out (which however leads to other minor issues that can be worked around).

I can't figure out what's different about my setup that's causing this, so let me know if anyone has an idea. 

```
Step 28/36 : RUN groupadd dev     && useradd --create-home -g dev dev     && usermod -p '*' dev     && passwd -u dev
 ---> Running in fb719128e4e7
passwd: password expiry information changed.
Removing intermediate container fb719128e4e7
 ---> 65f00193577e
Step 29/36 : USER dev
 ---> Running in 64e1bfb1be11
Removing intermediate container 64e1bfb1be11
 ---> 329a005b4c9b
Step 30/36 : COPY sw/vendor/rustup/rustup-init.sh /tmp/rustup-init.sh
 ---> f988406b4660
Step 31/36 : RUN /tmp/rustup-init.sh -y --default-toolchain ${RUST_VERSION}
 ---> Running in da594716d393
/bin/sh: /tmp/rustup-init.sh: Permission denied
The command '/bin/sh -c /tmp/rustup-init.sh -y --default-toolchain ${RUST_VERSION}' returned a non-zero code: 126
```

**Comment by timothytrippel** [comment] 2021-10-08 04:57
After cleaning out my cache and building from scratch I'm having the same probelm, now too. I looked into this further and got the image to build by moving the copying of the`rustup-init.sh` and `python-requirements.txt` into the Docker image (and setting the file permissions on those files) **before** the `USER dev` stage where the execution privileges change (after some debugging I realized that when the `rustup-init.sh` and `python-requirements.txt` the are owned by `root` not `dev` (see below).

<img width="675" alt="Screen Shot 2021-10-07 at 9 44 58 PM" src="https://user-images.githubusercontent.com/5633066/136500128-441c2eb1-a2be-4a24-bc8a-6f8d48066b1f.png">

However, while the build succeeds, when I go to run the container with `docker run -ti -v $(pwd):/home/dev/src  -e DEV_UID=$(id -u) -e DEV_GID=$(id -g) opentitan:latest bash` (to set the correct user and group ID to that of my host) it hangs at the `exec gosu dev:dev /bin/bash -c "$@"` line in the `util/container/start.sh` script.

However if I run the following command to launch the container `docker run -ti -v $(pwd):/home/dev/src  opentitan:latest bash` (NOT setting the user and group ID of the container to match my host) it enters the container no problem.

Some very strange behavior ... still debugging ... 

Here is my local branch with the fix I made, in case anyone wants to play around with it more: https://github.com/timothytrippel/opentitan/tree/fix-docker-image

**Comment by imphil** [comment] 2021-10-11 13:01
#8597 should fix the permission/user part of the problem. 

I'm unable to reproduce the long delay when running the container that you experienced, @timothytrippel. Can you retry with #8597 applied? And can you check the subshell commands to ensure it's not them taking a long time?

```
time echo docker run -ti -v $(pwd):/home/dev/src -e DEV_UID=$(id -u) -e DEV_GID=$(id -g) opentitan:latest bash
```

**Comment by timothytrippel** [comment] 2021-10-12 22:59
Confirmed, above is just a local issue, closing this.

**Closed by timothytrippel** 2021-10-12 22:59 UTC
Labels: Component:Tooling, Type:Bug
