### ISSUE TITLE
[test-triage] sysrst_ctrl_ec_rst_l_test assertion timeout 

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#15679] opened 2022-10-24 16:08 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

 UVM_ERROR @ 14969.358000 us: (sw_logger_if.sv:522) [sysrst_ctrl_ec_rst_l_test_prog_sim_dv(w/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c:148)] CHECK-fail: Timed out after 2500 usec (250000 CPU cycles) waiting for current_phase != kTestPhase
  UVM_INFO @ 14969.358000 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---

### Steps to Reproduce

- GH revision: [9c0b24ddb](https://github.com/lowrisc/opentitan/tree/9c0b24ddbeb5616bd8db661ec1395f2d4f326bc4)
- util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sysrst_ctrl_ec_rst_l --build-seed 2483310614 

### Tests with similar or related failures

- [ ] sysrst_ctrl_ec_rst_l_test
- [ ] chip_sw_sysrst_ctrl_ec_rst_l

> estimate 16

**Comment by ballifatih** [comment] 2022-10-26 15:11
Thanks @GregAC for digging out the cause of this issue. For the record, this issue is also a blocker for `chip_sw_sysrst_ctrl_ulp_z3_wakeup`, though it is not merged yet #15403.

**Comment by engdoreis** [comment] 2022-10-26 17:35
Thanks @GregAC for the findings. In my opinion we should somehow fix the backdoor mechanism, because it may become a problem with new tests or even existing ones.
So for me, trying to invalidate the cache would be the first option and if that’s too risky we can then move the variable to SRAM, however we would have to review other tests using the same backdoor mechanism.
@tjaychen @weicaiyang @sriyerg @timothytrippel Would you have any other option in mind?

**Comment by tjaychen** [comment] 2022-10-26 17:43
ah... the flash read only buffers will actually invalidate if you attempt a program to the same location.
So even though this will be somewhat annoying, we can employ a similar mechanism. Ie, before doing a read, just do a program of all 1's to that location (a program of all 1's is effectively a nop).

It's curious we've not encountered this issue elsewhere...

**Comment by weicaiyang** [comment] 2022-10-26 21:09
Looks like we only use this polling for a SV backdoor update in sysrst_ctrl tests.
```
static void wait_next_test_phase(void) {
  uint8_t current_phase = kTestPhase;
  // Set WFI status for testbench synchronization,
  // no actual WFI instruction is issued.
  test_status_set(kTestStatusInWfi);
  test_status_set(kTestStatusInTest);
  IBEX_SPIN_FOR(current_phase != kTestPhase, kTestPhaseTimeoutUsec);
}
```

The other tests most likely just do one read on the location that SV may backdoor update.
Tim's approach SGTM - write a all 1's to it if SW needs to poll an update from SV.
We can make a macro and call `IBEX_SPIN_SV_UPDATE` or similar.

**Comment by engdoreis** [comment] 2022-10-27 10:06
SGTM as well as long as we have a common API (macro or function) to be used by all the sw tests to correctly read the backdoor variables.
@GregAC, feel free to assign this issue to me.

**Comment by GregAC** [comment] 2022-10-28 11:04
@engdoreis though beware I ran a test using the fix @ballifatih had done, that just placed the variable in SRAM and that hit some different failure. If you could handle doing the change @tjaychen suggests and report back I can pick it up again if we're hitting another issue.

**Comment by ballifatih** [comment] 2022-10-28 13:51
About the fix @tjaychen  suggested, I wasn't able to write `0xff` from sw to the backdoored variable, which is defined like this:
https://github.com/lowRISC/opentitan/blob/64ea3bd268b0ad00e771aa65d735a3a89a7febcb/sw/device/tests/sim_dv/sysrst_ctrl_outputs_test.c#L78-L79
Since `kTestPhase` is const, it doesn't compile if I write `0xff` to it. If I drop const from the variable definition, then the variable moves from `FlashBank0Data` to `RamMain0`. Is there a way to go around this compiler issue, or force the variable to be in `FlashBank0Data` without const?

**Comment by tjaychen** [comment] 2022-10-28 17:28
ah, then maybe you can move this variable to the volatile scratch area that @alphan has defined.
That will allow us to explicitly declare this variable as part of flash, while still allowing for these backdoor attributes.

**Comment by weicaiyang** [comment] 2022-10-28 18:24
> ah, then maybe you can move this variable to the volatile scratch area that @alphan has defined. That will allow us to explicitly declare this variable as part of flash, while still allowing for these backdoor attributes.

I'm curious how to move the variable to that defined area, or is it documented somewhere?

**Comment by tjaychen** [comment] 2022-10-28 18:29
ah yes. Let me find an example.  I can never remember where it is.

**Comment by tjaychen** [comment] 2022-10-28 18:30
see [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/example_test_from_flash.c;l=73-84?q=non_volatile_scratch&ss=opentitan%2Fopentitan)

**Comment by weicaiyang** [comment] 2022-10-28 18:32
> see [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/example_test_from_flash.c;l=73-84?q=non_volatile_scratch&ss=opentitan%2Fopentitan)

Great! Thanks Tim.

**Comment by alphan** [comment] 2022-10-28 20:07
> see [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/example_test_from_flash.c;l=73-84?q=non_volatile_scratch&ss=opentitan%2Fopentitan)

Thanks @tjaychen!

**Comment by engdoreis** [comment] 2022-10-31 11:15
@tjaychen I've implemented the solution you've proposed here https://github.com/lowRISC/opentitan/pull/15811.

**Comment by tjaychen** [comment] 2022-10-31 17:48
o did that actually solve the issue?

**Comment by engdoreis** [comment] 2022-11-02 11:59
> o did that actually solve the issue?

Yes, and it passed in the latest regression.

**Comment by tjaychen** [comment] 2022-11-02 16:14
sounds great.

**Comment by johngt** [comment] 2022-11-08 12:32
Per comment to @engdoreis it looks like it passed only one nightly and has been failing since. Reopening and assigning to @engdoreis . If inaccurate, please close the issue.

|     | Tests                        |   2022-11-07 08:08:10 |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 |   2022-10-27 07:09:48 |   2022-10-26 07:06:46 |   2022-10-25 07:06:33 | Suite                                                        |
|----:|:-----------------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:-------------------------------------------------------------|
| 198 | chip_sw_sysrst_ctrl_ec_rst_l |                     0 |                     0 |                     0 |                     0 |                     0 |                     0 |                   100 |                     0 |                     0 |                     0 | chip_sw_sysrst_ctrl_ec_rst_l, chip_sw_sysrst_ctrl_flash_wp_l |

**Comment by HU90m** [comment] 2022-11-11 14:52
The failure in the [2022-11-07 report](https://reports.opentitan.org/hw/top_earlgrey/dv/2022.11.07_04.24.21/report.html) was caused by the `flash_wp` asserted restart check failing. Due to it being checked after the software de-asserted `flash_wp`. This appears to have been fixed in https://github.com/lowRISC/opentitan/pull/16045 .

However, the test has failed with a different error since (in the [2022-11-09 report](https://reports.opentitan.org/hw/top_earlgrey/dv/2022.11.09_17.04.47/report.html)). Investigating this now.

**Comment by cindychip** [comment] 2022-11-15 00:12
Hey @HU90m are you still working on this? Is there anything we can help with?

**Comment by HU90m** [comment] 2022-11-15 23:09
Sorry, I have been trying to close out https://github.com/lowRISC/opentitan/issues/14152 and neglected this issue.

I have only had a quick look at the failure seen in the 2022-11-09 report:

* revision: https://github.com/lowrisc/opentitan/commit/81bde034a7b21e3444342c96555fc63595a03c65
* build seed: 2742335380
* fixed seed: 229071523

The issue appears to be in the `PhaseOverrideOnes` of the test. The `ec_rst_l` isn't the expected value, which is 1 because the software is meant to have override value for all the pins to 1.

Thanks for offering help @cindychip, much appreciated! I would be grateful for any ideas pertaining to the above failure.
Also, if someone has time and/or ideas and wants to take on this issue, I am more than happy to unassign myself.

**Comment by cindychip** [comment] 2022-11-17 00:07
Thank you for the information @HU90m 
I think @weicaiyang mentioned something about the flash_wait function (the pseudo write should happen at everytime ibex compare data, not just the first time), I will try something on my end and update in this thread.

**Comment by HU90m** [comment] 2022-11-21 16:40
I'm free and more than happy to take this issue back if you would like me to @cindychip

**Comment by cindychip** [comment] 2022-11-21 22:48
> I'm free and more than happy to take this issue back if you would like me to @cindychip

Thanks Hugo, sorry I was not able to find out the root cause. @weicaiyang and I were suspending here:
https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/testing/flash_ctrl_testutils.c#L395
Should that be:
```
while (!expected) {
  // Fake flash write
  // Check timeout 
}
```
We thought the while loop inside `IBEX_SPIN_FOR` might need to be taken out?
But when I implemented a similar idea in https://github.com/lowRISC/opentitan/pull/16408, I found it very flaky..  Still not really sure what is the root cause..

**Comment by HU90m** [comment] 2022-11-30 12:43
The test has failed on one seed in the [2022-11-28 report](https://reports.opentitan.org/hw/top_earlgrey/dv/2022.11.28_22.03.58/report.html) with the same error described in https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1315991274:

```
  UVM_FATAL @ 12793.614680 us: (chip_sw_sysrst_ctrl_ec_rst_l_vseq.sv:62) [uvm_test_top.env.virtual_sequencer.chip_sw_sysrst_ctrl_ec_rst_l_vseq] Check failed cfg.chip_vif.ec_rst_l_if.sample_pin(0) == exp_ec_rst_l (0 [0x0] vs 1 [0x1])
  UVM_INFO @ 12793.614680 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

**Comment by HU90m** [comment] 2022-12-01 14:38
Passed the last nightly (2022-11-30). Closing as agreed in https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1332306723

**Comment by engdoreis** [comment] 2023-02-07 10:42
This test is having some failures once a week, so I think it's worth invesgating and improving the pass rate.

**Closed** 2023-03-29 09:58 UTC
Labels: Priority:P2, IP:sysrst_ctrl, Component:TestTriage, Triaged
