### ISSUE TITLE
[test-triage] csr_mem_rw_with_rand_reset

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#14653] opened 2022-08-30 13:58 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

UVM_ERROR @ * us: (chip_scoreboard.sv:78) [scoreboard] Check failed item.d_error == * (* [*] vs * [*]) has 1 failures:

Test chip_csr_mem_rw_with_rand_reset has 1 failures.
12.chip_csr_mem_rw_with_rand_reset.733567193
Line 308, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/12.chip_csr_mem_rw_with_rand_reset/latest/run.log

  UVM_ERROR @ 2663.555660 us: (chip_scoreboard.sv:78) [uvm_test_top.env.scoreboard] Check failed item.d_error == 1 (0 [0x0] vs 1 [0x1])
  UVM_INFO @ 2663.555660 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---

### Steps to Reproduce

Happens on 27 Aug and 29 Aug nightlies. 
https://reports.opentitan.org/hw/top_earlgrey/dv/2022.08.27_03.35.21/report.html build seed 528771580
Also happened on Aug 12, 15, 16.
Success rate varies between 90 and 100%.

### Tests with similar or related failures

- [ ] chip_csr_mem_rw_with_rand_reset (just this test)

**Comment by abdullahvarici** [comment] 2022-09-12 16:02
Success rate dropped 0% in the latest regression (11th September). I think I should try to root cause for occasional failure in earlier commits.

**Comment by abdullahvarici** [comment] 2022-09-14 20:15
The test passes with 100% success rate with the current state of the design (commit no: 1b4bb0e07) with the build seed `528771580`. But I also checked latest nigthly regression failures and tried the build seed 2008576760 as the test was failing on [August 31](https://reports.opentitan.org/hw/top_earlgrey/dv/2022.08.31_16.44.30/report.html) with that seed. The root cause is found and an [issue](https://github.com/lowRISC/opentitan/issues/14921) is opened.

**Comment by msfschaffner** [comment] 2022-09-29 03:42
I reran this test with the newest state on master (https://github.com/lowRISC/opentitan/commit/e4116b590bb573a35f51cfff9889a2fe336fd2d8) and 256 run seeds and got only one failure:

```
## Failure Buckets

* `UVM_ERROR @ * us: (cip_base_scoreboard.sv:431) [scoreboard] Check failed item.d_error == exp_d_error (* [*] vs * [*]) On interface chip_reg_block, TL item: req: (cip_tl_seq_item@30547) { a_addr: * a_data: * a_mask: * a_size: * a_param: * a_source: * a_opcode: * a_user: * d_param: * d_source: * d_data: * d_size: * d_opcode: * d_error: * d_sink: * d_user: * a_source_is_overridden: * a_valid_delay: * d_valid_delay: * a_valid_len: * d_valid_len: * req_abort_after_a_valid_len: * rsp_abort_after_d_valid_len: * req_completed: * rsp_completed: * tl_intg_err_type: TlIntgErrNone max_ecc_errors: * }` has 1 failures:
    * Test chip_csr_mem_rw_with_rand_reset has 1 failures.
        * 57.chip_csr_mem_rw_with_rand_reset.2890480638\
          Line 180, in log /workspaces/repo/scratch/master/chip_earlgrey_asic-sim-vcs/57.chip_csr_mem_rw_with_rand_reset/latest/run.log

                UVM_ERROR @ 1955.903880 us: (cip_base_scoreboard.sv:431) [uvm_test_top.env.scoreboard] Check failed item.d_error == exp_d_error (0 [0x0] vs 1 [0x1]) On interface chip_reg_block, TL item: req: (cip_tl_seq_item@30547) { a_addr: 'h41150640  a_data: 'hc9ba8959  a_mask: 'h1  a_size: 'h0  a_param: 'h0  a_source: 'h17  a_opcode: 'h1  a_user: 'h27b25  d_param: 'h0  d_source: 'h17  d_data: 'h0  d_size: 'h0  d_opcode: 'h0  d_error: 'h0  d_sink: 'h0  d_user: 'h152a  a_source_is_overridden: 'h0  a_valid_delay: 'h0  d_valid_delay: 'h0  a_valid_len: 'h0  d_valid_len: 'h0  req_abort_after_a_valid_len: 'h0  rsp_abort_after_d_valid_len: 'h0  req_completed: 'h0  rsp_completed: 'h0  tl_intg_err_type: TlIntgErrNone  max_ecc_errors: 'h3  }
                , unmapped_err: 1, mem_access_err: 0, bus_intg_err: 0, byte_wr_err: 0, csr_size_err: 0, tl_item_err: 0, write_w_instr_type_err: 0, cfg.tl_mem_access_gated: 0 ecc_err: 0
                UVM_INFO @ 1955.903880 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
                --- UVM Report catcher Summary ---

```

repro:


```
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_csr_mem_rw_with_rand_reset --build-seed 55 --fixed-seed 2890480638
```

**Comment by msfschaffner** [comment] 2022-09-30 00:53
After cherry-picking the fixes for the `chip_tl_errors` test in #15192 onto https://github.com/lowRISC/opentitan/commit/e4116b590bb573a35f51cfff9889a2fe336fd2d8, the above failure is gone. I also checked out the newest state on master (https://github.com/lowRISC/opentitan/commit/6b8e4cfb79cdd0dc0485cb407ca3bf0f18f6326c) and reran with 512 seeds and the test did not fail anymore. Hence I think it is safe to close this bug now.

**Closed by msfschaffner** 2022-09-30 00:53 UTC
Labels: Component:TestTriage
