### ISSUE TITLE
SIM: Questa support: FATAL error from RAL 

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4377] opened 2020-12-02 17:37 UTC
Hello,
  I made few fixes to get Questa up and running and am stuck at the following.

>> #    Time: 0 ps  Iteration: 10  Process: /uvm_pkg::uvm_phase::m_run_phases/#FORK#2213_7fefec684a8 Fil opentitan/scratch/uart.sim.questa/qsta-support/default/sim-vcs/../src/lowrisc_dv_dv_base_reg_0/csr_excl_item.sv Line: 35
>> # UVM_FATAL @         0 ps: (dv_base_reg_block.sv:161) [ral] Check failed ((base_addr & mask) == '0)  

And sim exits (FATAL). I can mask the above, but am wondering if there is a better/correct way. I also see few warnings from non-existant assoc-array access just before this FATAL as below:

```log
#    Time: 0 ps  Iteration: 10  Process: /uvm_pkg::uvm_phase::m_run_phases/#FORK#2213_7fefec684a8 File:  /opentitan/scratch/uart.sim.questa/qsta-support/default/sim-vcs/../src/lowrisc_dv_dv_base_reg_0/csr_excl_item.sv Line: 34
# ** Warning: (vsim-3829) Non-existent associative array entry. Returning default value.
#    Time: 0 ps  Iteration: 10  Process: /uvm_pkg::uvm_phase::m_run_phases/#FORK#2213_7fefec684a8 File:  opentitan/scratch/uart.sim.questa/qsta-support/default/sim-vcs/../src/lowrisc_dv_dv_base_reg_0/csr_excl_item.sv Line: 35
 
 /lowrisc_dv_dv_base_reg_0/csr_excl_item.sv Line: 35
# UVM_FATAL @         0 ps: (dv_base_reg_block.sv:161) [ral] Check failed ((base_addr & mask) == '0)  
# UVM_INFO @         0 ps: (uvm_report_server.svh:847) [UVM/REPORT/SERVER] 
# --- UVM Report Summary ---
```

Any clues?
Thanks
Srini

**Comment by cindychip** [comment] 2020-12-02 20:15
Do you mind providing your command to trigger the regression? Is that some uart test?

**Comment by weicaiyang** [comment] 2020-12-02 20:38
@svenka3 
For the warning, we don't see it in vcs and xcelium but it's probably easy to fix. Can you try to add below before line 34 to initialize it before using?
`if (!exclusions.exists(obj)) exclusions[obj] = 0;
`https://github.com/lowRISC/opentitan/blob/23b882050e91bd9ef392bde871d2cdd64db30646/hw/dv/sv/dv_base_reg/csr_excl_item.sv#L34

For the fatal error, it's very strange. Can you help to print out the value of `base_addr` and `mask`.

**Comment by svenka3** [comment] 2020-12-03 15:40
@cindychip Command to run

 util/dvsim/dvsim.py hw/ip/uart/dv/uart_sim_cfg.hjson -t questa -i uart_smoke

(Pull from my fork, qsta-support branch)

**Comment by svenka3** [comment] 2020-12-03 16:03
Printed base_addr and mask:

> UVM_INFO @         0 ps: (dv_base_reg_block.sv:161) [ral] base_addr: 0xffffffff mask: 0x3f

**Comment by rswarbrick** [comment] 2020-12-03 16:17
Hmm, that's interesting. I haven't got access to Questa here, so can't try it out myself. This test is supposed to pick a base address that's aligned to the mask (which is what the failing check is making sure of). I suspect that what's going wrong is that the `if (base_addr == '1)` check is failing. Is it possible that you've got a 64-bit `uvm_reg_addr_t` but are passing in `(1 << 32) - 1`?

I know that there was some discussion about the width of `uvm_reg_addr_t` in a previous issue: does something just need recompiling?

**Comment by rswarbrick** [comment] 2020-12-03 16:20
Following up on this: the default argument to `dv_base_reg_block::set_base_addr` is a bit of a red herring. The only call site is in `dv_base_env_cfg`, where we pass it a value of width `bus_params::BUS_AW`, with default value `'1`. This *should* just work because we've got the same width in both cases. Of course, it won't work if `uvm_reg_addr_t` isn't 32 bits.

Anyway, it probably wouldn't hurt to tidy that up - I'll push a PR to do so in a minute.

**Comment by svenka3** [comment] 2020-12-03 16:54
I see ADDR_WIDTH as 32 in build.log, so no issues there. Also see the print

0xffffffff 

That's is 32 bits all 1

But mask sounds fishy below:

mask: 0x3f

Of course am a stranger to this magic masking logic, you guys would know.

Cheers

**Comment by rswarbrick** [comment] 2020-12-03 17:00
The mask is computed from the block's address map by finding the byte with the largest offset that appears in a register or memory, rounding that offset up to the next power of two, and subtracting one. Since `0x3f = 63`, that means the block has a maximum offset between 32 and 63.

I think you're going to need to add some print lines to figure out what's going on.

**Comment by weicaiyang** [comment] 2020-12-03 18:41
mask value is expected. base address isn't right, which should be LSB 7 bits=0, the other bits=random value.
Seems like this condition isn't true. maybe `uvm_reg_addr_t` isn't 32 bit wide
https://github.com/lowRISC/opentitan/blob/41fd2b0005e98d40674e4ea4fb1daf482b0bb847/hw/dv/sv/dv_base_reg/dv_base_reg_block.sv#L163-L166

can you check if UVM_REG_ADDR_WIDTH is set to 32 and also confirm if above `if` condition is true?
```typedef  bit unsigned [`UVM_REG_ADDR_WIDTH-1:0]  uvm_reg_addr_t ;```

**Comment by sriyerg** [comment] 2020-12-04 05:59
> @cindychip Command to run
> 
> util/dvsim/dvsim.py hw/ip/uart/dv/uart_sim_cfg.hjson -t questa -i uart_smoke
> 
> (Pull from my fork, qsta-support branch)

Hi @svenka3, I cloned your fork and tried to run the above sim. The build passed but the simulation failed. I see the following error:
```console
[make]: simulate
Error in startup script: 
Initialization problem, exiting.

Initialization problem, exiting.

    while executing
"InitializeINIFile quietly"
    invoked from within
"ncFyP12 -+"
    (file "/mtitcl/vsim/vsim" line 1)
** Fatal: Read failure in vlm process (0,0)

```

I wonder if there are other files / environment variables licenses etc. that I may be missing. Let me know if you know a way to get past this.

**Comment by svenka3** [comment] 2020-12-04 06:05
You need a fairly recent Questa version - I started with Questa 2019.xx, had a crash, moved to 2020.4 it all worked. So I strongly suggest you move to the latest. 10.4 is indeed very old, not sure if UVM 1.2 may not run in that.

**Comment by sriyerg** [comment] 2020-12-04 07:26
I tried 19.2 (which is the latest we have). It went past the previous error but ended up with the following error:
```
# ** Error: ../src/lowrisc_dv_cip_lib_0/cip_base_pkg.sv(45): Questa has encountered an unexpected internal error: ../../src/vlog/vallocate.c(1098). Please contact Questa support at http://supportnet.mentor.com/
# 
```
Unfortunately, we are unable to reproduce it. 

Perhaps you can try confirming it is indeed getting into the if condition and the randomization is happening. Maybe Questa does not like the use of assignment pattern `'1` in the context of an expression, so if the condition is failing, you can try changing it to:
```
  if (base_addr == {`UVM_REG_ADDR_WIDTH{1'b1}}) begin
```

**Comment by svenka3** [comment] 2020-12-04 17:52
OK, let me ask differently - what value of base_addr is seen in your VCS/XLM runs? Maybe I can feed in that here?

**Comment by weicaiyang** [comment] 2020-12-04 18:28
> OK, let me ask differently - what value of base_addr is seen in your VCS/XLM runs? Maybe I can feed in that here?

after the randomization, it should be base_addr[6:0] = 0, the other bits are random. You use base_addr=0 to bypass the fatal error.
But it's good to figure out why the if condition isn't entered correctly, since we use `'1` assignment in many places.

**Comment by svenka3** [comment] 2020-12-04 18:47
Good news - finally it is resolved. The issue seems to be bit more complicated and is not with the self-determined expr length (base_addr == '1). 

I have pushed code on my branch if you want to see/review. I would say some clean-up is needed at my end, for now I have another UVM_ERROR (50 of them) to look at.

Very briefly - the issue seems (Some guess, some debug, some print-help) to be:

>> Questa has pre-compiled UVM lib for easy use. But it has 64 bits by default as UVM_REG_ADDR_WIDTH. So if users were to change that, it *may* require custom UVM compile. 

That along with a series of mix-up in OT code on uvm_reg_addr_t vs. bus_params_pkg::AW (See my fixes in qsta-support branch) seems to lead to this strange error.

For now, I will move on with some fixes to the next hurdle.

Cheers
Srini

**Comment by weicaiyang** [comment] 2020-12-04 18:56
Thanks @svenka3 for figuring this out. Pre-compile UVM lib doesn't work for OT. I should use custom UVM compile in Questa.

**Comment by sriyerg** [comment] 2020-12-04 19:21
Aah I just noticed `-L $QUESTA_HOME/uvm-1.2` in your setup. Yes, that does not work. You will need to get mentor to compile with the `+define+` opts from scratch.

**Comment by sriyerg** [comment] 2020-12-04 19:41
FYI, one of the fixes you need to get the build going is in `hw/dv/sv/dv_utils/dv_vif_wrap.sv`. Add these lines after line 61:
```systemverilog
`elsif QUESTA \
  vif = interface::self(); \
```
This is a non-LRM compliant way of an interface referencing itself within. As with other simulators, please add `+define+QUESTA` to `build_opts` within `questa.hjson`.

**Comment by svenka3** [comment] 2020-12-11 20:54
Quick update - I have uploaded fixes to my branch,some rel-notes:

1. Custom compile of uvm-1.2 lib code is added to build_opts (questa.hjson)
2. Now with UVM_REG_ADDR is burnt into uvm-1.2 library as per OT code (32), we don't see the csr_addr issue any more. I've masked them under a define that is not defined, will clean up this. Summary - no fix needed here
3. We do need few additional fixes for virtual interface, will open a new issue.

Please pull code and see if you have any more comments.

**Comment by weicaiyang** [comment] 2020-12-11 22:58
> Quick update - I have uploaded fixes to my branch,some rel-notes:
> 
> 1. Custom compile of uvm-1.2 lib code is added to build_opts (questa.hjson)
> 2. Now with UVM_REG_ADDR is burnt into uvm-1.2 library as per OT code (32), we don't see the csr_addr issue any more. I've masked them under a define that is not defined, will clean up this. Summary - no fix needed here
> 3. We do need few additional fixes for virtual interface, will open a new issue.
> 
> Please pull code and see if you have any more comments.

@svenka3 
Thanks for the update. Looks like we can close this issue, right?

**Comment by sriyerg** [comment] 2020-12-12 06:49
Closing this, feel free to reopen if needed.

**Closed by sriyerg** 2020-12-12 06:49 UTC
