### ISSUE TITLE
[test-triage] chip_sw_sleep_pwm_pulses Pass patterns missing

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#15374] opened 2022-10-10 14:32 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
Some pass patterns missing: ['^TEST PASSED (UVM_)?CHECKS$'] has 17 failures:

Test chip_sw_sleep_pwm_pulses has 1 failures.

0.chip_sw_sleep_pwm_pulses.3860101830
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_sleep_pwm_pulses/latest/run.log

  [617 / 991] Compiling Rust rlib regex_syntax v0.6.27 (32 files); 67s processwrapper-sandbox ... (60 actions, 59 running)
  INFO: From Running Cargo build script libftdi1_sys:
  Build Script Warning: Config for libftdi1 not found, falling back to default search path: `"pkg-config" "--libs" "--cflags" "libftdi1" "libftdi1 >= 1.4"` did not exit successfully: exit status: 1
  [647 / 991] Linking sw/device/lib/arch/libsim_dv.a; 126s processwrapper-sandbox ... (58 actions running)
  [668 / 991] Action sw/device/lib/testing/test_rom/chip_info.h; 195s processwrapper-sandbox ... (56 actions running)
  [678 / 991] Action sw/device/lib/testing/test_rom/chip_info.h; 246s processwrapper-sandbox ... (55 actions running)
  [688 / 991] Action sw/device/lib/testing/test_rom/chip_info.h; 324s processwrapper-sandbox ... (57 actions running)
  [693 / 991] Action sw/device/lib/testing/test_rom/chip_info.h; 410s processwrapper-sandbox ... (54 actions, 53 running)
  [694 / 991] Action sw/device/lib/testing/test_rom/chip_info.h; 503s processwrapper-sandbox ... (54 actions, 53 running)
  [710 / 991] Action sw/device/lib/testing/test_rom/chip_info.h; 618s processwrapper-sandbox ... (60 actions, 59 running)
```

### Steps to Reproduce

- Commit hash where failure was observed: [c2a8c64cc](https://github.com/lowrisc/opentitan/tree/c2a8c64ccbca39707be7883dfd2f8c1100813730)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sleep_pwm_pulses --fixed-seed 3860101830 --build-seed 4265629825 --waves -v h

### Tests with similar or related failures

- [ ] Just chip_sw_sleep_pwm_pulses

**Comment by tjaychen** [comment] 2022-10-20 19:43
it looks like this test has been passing for multiple nightlies.
The error seen here is most likely a regression infrastructure issue (there's been a few) that has since been fixed. I will close this one down for now.

**Closed by tjaychen** 2022-10-20 19:43 UTC
Labels: Component:TestTriage
