### ISSUE TITLE
Build failed for master 

### ISSUE THREAD

**Issue by Avani8** [lowRISC/opentitan#1030] opened 2019-11-20 20:34 UTC
![Screenshot from 2019-11-20 15-33-55](https://user-images.githubusercontent.com/12041484/69275845-32558500-0bab-11ea-8814-811470be5b15.png)

**Comment by imphil** [comment] 2019-11-20 20:40
Thanks for reporting this bug @Avani8. This is a duplicate of #1024. Please ensure that you have set the right bootrom file by passing `--ROM_INIT_FILE path/to/rom.vmem` to fusesoc.

**Comment by towoe** [comment] 2019-11-20 21:40
Just as an addition, be sure to follow the rule for the file path given in https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/top_earlgrey_nexysvideo.core#L31

**Comment by Avani8** [comment] 2019-11-20 23:19
Thanks, @imphil for the quick response...that helped.

**Comment by towoe** [comment] 2019-12-02 12:15
Fixed by #1034

**Closed by towoe** 2019-12-02 12:15 UTC
Labels: Resolution:Duplicate
