### ISSUE TITLE
[test-triage] //sw/device/tests:csrng_smoketest_fpga_cw310_sival_rom_ext times out in CI

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#22140] opened 2024-03-20 16:35 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

If it is the second or later test to be run after loading the bitstream, `//sw/device/tests:csrng_smoketest_fpga_cw310_sival_rom_ext` fails due to a timeout. It makes no UART-visible progress after the first OTTF console print (the "Running..." line).

### Steps to Reproduce

- GitHub Revision: a9785f3f3c
```
git checkout a9785f3f3c
# Make sure to use the correct cached bitstream
./bazelisk.sh sync --configure
```
- Command to reproduce results
```
# The first run passes if a new bitstream is loaded
./bazelisk.sh test --test_output=streamed --nocache_test_results //sw/device/tests:csrng_smoketest_fpga_cw310_sival_rom_ext
# The second run (and all subsequent runs) fail
./bazelisk.sh test --test_output=streamed --nocache_test_results //sw/device/tests:csrng_smoketest_fpga_cw310_sival_rom_ext
```

**Comment by a-will** [comment] 2024-03-20 16:43
Failures began after merging https://github.com/lowRISC/opentitan/pull/22054. However, the PR's CI run was good, and local testing has shown that success to be reproducible. Thus, this seems to be a case of merge skew.

This is the list of commits that were present in the `master` CI run that weren't in the PR CI run:
https://github.com/lowRISC/opentitan/compare/5292a0464f79a7ed79f32e7df3507310c0a34bce...ec5cc907dd8515bfc83d87910bfec22987955be3

After cherry-picking all software-only and DV-only commits (so as not to need a new bitstream), the adjusted PR branch still passed. That leaves us with these PRs as representing possible companion sources of merge skew failures:

- https://github.com/lowRISC/opentitan/pull/22045
- https://github.com/lowRISC/opentitan/pull/22069
    - Seems unlikely to be the one
- https://github.com/lowRISC/opentitan/pull/22046

**Comment by a-will** [comment] 2024-03-20 17:02
It appears the failure also only occurs if the test runs atop ROM_EXT with the sival OTP configuration (i.e. `//hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival_bringup:otp_img_prod_manuf_personalized`). Tests running atop ROM_EXT with the `//sw/device/silicon_creator/rom_ext/e2e:otp_img_secret2_locked_rma` still passed.

**Comment by andreaskurth** [comment] 2024-03-25 15:05
@a-will: Do you know if this is the UART problem described in #22152?

**Comment by a-will** [comment] 2024-03-28 23:23
> @a-will: Do you know if this is the UART problem described in #22152?

Given that it only occurs with a specific OTP setting (with repeated tests against each environment), that seems unlikely. I don't have proof one way or another, though.

**Comment by vogelpi** [comment] 2024-04-01 13:39
Can it be that depending on the OTP configuration, the entropy complex and in particular CSRNG is left in a different state at the end o ROM_ext?

Because what [csrng_smoketest](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/csrng_smoketest.c) is doing is enabling CSRNG and then triggering an Uninstantiate command followed by a wait and then an Instantiate command. But it doesn't check if CSRNG was already enabled before. If that is the case and if a Generate was running without all entropy having been consumed, the Uninstantiate/Instantiate commands may get ignored (not entirely sure). CSRNG might never become ready. @h-filali might now better what the expected behavior is and how this will change with the CSRNG RTL PRs currently in flight. Hakim is however out this week...

Maybe it would be better to first completely disable/re-enable the entropy complex to bring it into a known state at the beginning of the test.

**Comment by a-will** [comment] 2024-04-01 14:25
Just another little observation, but I'll note that the failure mode suggests there is some triggering state that survives a POR. (e.g. state in a RAM or flash)

The manifestation of a failing test ostensibly may be something ROM_EXT does together with one of those PRs. There could be a latent bug in ROM_EXT that involves reading uninitialized memory and using that value leads to bad configuration or something on the second boot, for example. More investigation would be needed.

**Comment by vogelpi** [comment] 2024-05-09 13:13
I just re-ran the test on the FPGA `//sw/device/tests:csrng_smoketest_fpga_cw310_sival_rom_ext`. It's working both on master (https://github.com/lowRISC/opentitan/commit/622018b25190bc6129f6495edc98dec642b6c037) and earlgrey_es_sival (https://github.com/lowRISC/opentitan/commit/7f1ef1c112fbdb0e5b3dab8030044a4c21d2c946). It seems that the [keymgr related fixes outlined here](https://github.com/lowRISC/opentitan/issues/22819#issuecomment-2095648654) solved this issue.

Closing :-)

**Closed by vogelpi** 2024-05-09 13:13 UTC
Labels: Component:TestTriage

**Comment by vogelpi** [comment] 2024-05-09 13:37
The PR to mark this as unbroken is here: #23035
