### ISSUE TITLE
[otbn] Running p256_ecdsa_sign application twice in a row locks up

### ISSUE THREAD

**Issue by colinoflynn** [lowRISC/opentitan#8935] opened 2021-10-28 12:40 UTC
In the `otbn_ecdsa_p256_test.c` file trying to run the sign operation twice in a row will lock up. The simplest test case is as follows:

```
bool test_main() {
  entropy_testutils_boot_mode_init();
  test_ecdsa_p256_roundtrip();

  entropy_testutils_boot_mode_init();
  test_ecdsa_p256_roundtrip();

  return true;
}
```
This will give an output as follows:

```
I00000 otbn_ecdsa_p256_test.c:113] Initialization took 134635 cycles or 1346 us @ 100 MHz.
I00001 otbn_ecdsa_p256_test.c:276] Signing
I00002 otbn_ecdsa_p256_test.c:113] Sign took 762488 cycles or 7624 us @ 100 MHz.
I00003 otbn_ecdsa_p256_test.c:282] Clearing OTBN memory and reloading app
I00004 otbn_ecdsa_p256_test.c:289] Verifying
I00005 otbn_ecdsa_p256_test.c:113] Verify took 482387 cycles or 4823 us @ 100 MHz.
I00006 otbn_ecdsa_p256_test.c:301] Clearing OTBN memory
I00007 otbn_ecdsa_p256_test.c:113] Initialization took 134635 cycles or 1346 us @ 100 MHz.
I00008 otbn_ecdsa_p256_test.c:276] Signing
```

And it will stick on the `CHECK(otbn_busy_wait_for_done(otbn_ctx) == kOtbnOk);` line.

Some other tests:

* Adjusting `test_ecdsa_p256_roundtrip` so it runs sign only once shows the verify operation can run twice in a row without issue, running sign is the problematic one.
* Adding the following reset code between runs does not fix the problem:
```
  dif_otbn_t otbn;
  mmio_region_t addr = mmio_region_from_addr(TOP_EARLGREY_OTBN_BASE_ADDR);
  CHECK_DIF_OK(dif_otbn_init(addr, &otbn));
  dif_otbn_reset(&otbn);
```

Other minor changes (not calling `entropy_testutils_boot_mode_init();`, not calling verify) also don't have any noticeable effect. Not sure if this is OTBN related or test application related, but seems suspicious around the sign being the only problematic area.

**Comment by rswarbrick** [comment] 2022-02-08 23:48
@colinoflynn: Is this still something you're working on? Do you still see this being broken?

**Comment by colinoflynn** [comment] 2022-02-09 00:36
We had worked around it for ECDSA testing using RND so it's not a real block. Running the test case above with a recent (earlier today) checkout of opentitan seems to have the same behaviour (test fails second time). It may be an "invalid" error related to something w.r.t. URND usage in the test mode, in which case ok to close!

**Comment by rswarbrick** [comment] 2022-02-09 09:37
Hmm, that's frustrating.

@mwbranstad: Looking back at the conversation above, it looks like there was a possible bug in the EDN/CSRNG interface. I know that this was all a bit flaky back in October, but it should be more robust now, I think? The fact that things are still not working for this system test suggests there's still something broken. Have you got time to look into this further? If not, someone at lowRISC can try to find time but it won't be for a few days and (at least historically) this bug doesn't seem to have been caused by our blocks.

**Comment by mwbranstad** [comment] 2022-02-09 15:47
@rswarbrick to your question, yes, the entropy blocks are much more tested at the unit level. However, basic flow has not changed that much from when this thread started. I would like to confirm that the rtl is working properly, but we cannot seem to run chip level tests at WD because of tool issues. So I will again offer to debug this issue with a live meeting over a desktop share. Please schedule a time and let's take a look.

**Comment by mwbranstad** [comment] 2022-02-10 14:43
If @rasmus-madsen can get this chip level test running in the WD env, I would be happy to look at this test and do local debug on it.

**Comment by rswarbrick** [comment] 2022-02-10 16:15
I think you can probably do the following:
- Hack `test_main` in `otbn_ecdsa_p256_test.c` to duplicate things as described in the original report
- Build everything (`ninja -C build-out all`)
- Run the chip-level test through pytest.
  - Run the test with `pytest test/systemtest/earlgrey/test_sim_verilator.py --log-cli-level=DEBUG -k otbn_ecdsa_p256_test`
  - Assuming that works, you can get waves by looking at the long command line that appeared and tweaking it to add a `-t` argument.
  - This will run a factor of 10 or so slower. YAAAWN!
  - You'll end up with a `sim.fst` in the current directory.

**Comment by martin-lueker** [comment] 2022-02-10 21:37
@rswarbrick: I'm truly sorry, I was trying to quote your flow chart above, and instead I edited it (and deleted most of it).  Most sincere apologies.   Is there someway to unedit that?

**Comment by martin-lueker** [comment] 2022-02-10 21:40
> @rswarbrick: I'm truly sorry, I was trying to quote your flow chart above, and instead I edited it (and deleted most of it). Most sincere apologies. Is there someway to unedit that?

Never mind, I fixed it.

**Comment by mwbranstad** [comment] 2022-02-16 20:46
> * Hack test_main in otbn_ecdsa_p256_test.c to duplicate things as described in the original report
> * Build everything (`ninja -C build-out all` and `ci/scripts/build-chip-verilator.sh earlgrey`)
> * Run the test with `pytest test/systemtest/earlgrey/test_sim_verilator.py --log-cli-level=DEBUG -k otbn_ecdsa_p256_test`
> * Assuming that works, you can get waves by looking at the long command line that appeared and tweaking it to add a -t argument.
>   
>   * This will run a factor of 10 or so slower. YAAAWN!
> 
> You'll end up with a sim.fst in the current directory.

@rswarbrick for some reason when I run your command, the output claims that it is skipping this test. I am able to run other tests, even the otbn smoketest. But not this one:
...work/mark.branstad/opentitan>pytest test/systemtest/earlgrey/test_sim_verilator.py --log-cli-level=DEBUG -k otbn_ecdsa_p256_test
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.6.6, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /wdc/proj/cto/top/work/mark.branstad/opentitan
plugins: timeout-2.1.0
collected 38 items / 37 deselected / 1 selected                                                                                                                                 

test/systemtest/earlgrey/test_sim_verilator.py::test_apps_selfchecking[otbn_ecdsa_p256_test] 
-------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------
INFO     systemtest.conftest:conftest.py:68 Using build outputs from $REPO_TOP/build-bin (/wdc/proj/cto/top/work/mark.branstad/opentitan/build-bin)
SKIPPED (Test otbn_ecdsa_p256_test skipped on Verilator.)                                                                                                                 [100%]

======================================================================= 1 skipped, 37 deselected in 0.04s =======================================================================
...work/mark.branstad/opentitan>

**Comment by mwbranstad** [comment] 2022-02-16 22:44
"Assuming that works, you can get waves by looking at the long command line that appeared and tweaking it to add a -t argument."
@rswarbrick  Very confused by this. I would expect a parameter to be set as input into the pytest script.

**Comment by rswarbrick** [comment] 2022-02-16 23:42
Ah. You also need to hack `test/systemtest/earlgrey/config.py` to add `sim_verilator` to the list of targets for the test. Sorry, I forgot that would be needed.

For the `-t` argument: try it :-) Pytest doesn't support wave dumping at all (it's a Python testing framework: that would be some serious mission creep :-D). So this is a hack: running pytest with `--log-cli-level=DEBUG` tells it to print out the command that it's using to actually run the RTL simulation. If you run that by hand, you get basically the same thing, but without checkers making sure that the test output looks like what they expect. Of course, you can now fiddle with the command line arguments and at the `-t` as I described.

**Comment by vogelpi** [comment] 2022-08-22 09:53
I just had another look at this. With e7fcdad95951dc92314348fd4661757f17bd04cd the problem seems to be solved. The following snippet can be run without issues:
```c
bool test_main() {
  entropy_testutils_boot_mode_init();
  test_ecdsa_p256_roundtrip();

  entropy_testutils_boot_mode_init();
  test_ecdsa_p256_roundtrip();

  return true;
}
```
I am thus closing this issue. 

Note, the second call to `entropy_testutils_boot_mode_init()` can also be replaced by `entropy_testutils_auto_mode_init()` and then we can run several round trips in a row. In other words, also this works now:
```c
bool test_main(void) {
  entropy_testutils_boot_mode_init();
  test_ecdsa_p256_roundtrip();

  entropy_testutils_auto_mode_init();
  test_ecdsa_p256_roundtrip();
  test_ecdsa_p256_roundtrip();
  test_ecdsa_p256_roundtrip();
  test_ecdsa_p256_roundtrip();

  return true;
}

```

However, what doesn't work is 1) directly calling `auto_mode_init()` at the beginning and 2) calling `auto_mode_init()` after `boot_mode_init()` without round trip in between. I think this is strongly related to #14409.

Also note that the round trip currently let's Ibex overwriting the entire DMEM with zeros twice. This takes a lot of time and we should replace that by a secure wipe. This is tracked in #14385.

**Closed by vogelpi** 2022-08-22 09:53 UTC
Labels: Type:Bug, Component:RTL
