### ISSUE TITLE
[test-triage] Chip_sw_pwrmgr_deep_sleep_all_reset_reqs

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#23051] opened 2024-05-10 15:25 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

Offending '(pend_req[h2d.a_source].pend == 0)'
  UVM_ERROR @ 11024.558788 us: (tlul_assert.sv:268) [ASSERT FAILED] pendingReqPerSrc_M
  UVM_INFO @ 11024.558788 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---

### Steps to Reproduce

- GitHub Revision: [9656691e03](https://github.com/lowrisc/opentitan/tree/9656691e037c6fc5b87369d8fbab300cb34dff80)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_pwrmgr_deep_sleep_all_reset_reqs --build-seed 30170103562476460183108208532025718695603957360441815475011549460912256789439 --fixed-seed 23307110412515452149089605935788136274096898854134937574384102260651442782440 --waves fsdb
- Kokoro build number if applicable

### Tests with similar or related failures

Ping @andreaskurth @matutem 
Also @jwnrt who is assigned to the SiVal version of the test

**Comment by matutem** [comment] 2024-06-11 21:02
This test is passing in master latest regression (also in a couple recent regressions), and I cannot reproduce the failure with the given repro instructions. It seems we can close it.

**Comment by moidx** [comment] 2024-06-11 21:11
Thanks @matutem!

**Closed by moidx** 2024-06-11 21:11 UTC
Labels: Component:TestTriage
