### ISSUE TITLE
[test-triage] chip_same_csr_outstanding

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14204] opened 2022-08-10 22:47 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

~~UVM_ERROR @ * us: (cip_base_vseq.sv:250) [chip_common_vseq] Check failed masked_data == exp_data (* [*] vs * [*]) addr * read out mismatch has 1 failures:~~

New error message:
UVM_ERROR @ 5596.731437 us: (tl_monitor.sv:179) uvm_test_top.env.m_tl_agent_chip_reg_block.monitor [uvm_test_top.env.m_tl_agent_chip_reg_block.monitor] Number of pending a_req exceeds limit 4

### Steps to Reproduce

GH revision: [9c0b24ddb](https://github.com/lowrisc/opentitan/tree/9c0b24ddbeb5616bd8db661ec1395f2d4f326bc4)
util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_same_csr_outstanding --build-seed 2483310614 --fixed-seed 850130150

### Tests with similar or related failures

chip_csr_aliasing
chip_csr_rw

**Comment by johngt** [comment] 2022-08-30 11:26
According to the nightlies the last time that this was showing <100 pass rate was https://reports.opentitan.org/hw/top_earlgrey/dv/2022.08.24_15.46.18/report.html with 40% success rate.

It appears that in all nightlies after that this is resolved. Not sure which PR would have resolved this.
This is a candidate for closing / resolved once tagged with PR that resolved this.

**Comment by weicaiyang** [comment] 2022-10-24 17:56
@engdoreis Thanks for opening this. I changed the max outstanding number to be 8 recently. Looks like the xbar may take 9 outstanding items. Need to dump a waveform and confirm it with designer. 
If you haven't looked into this, I can take it.

**Comment by weicaiyang** [comment] 2022-10-24 23:14
@eunchan @tjaychen 

Looks like the ibex TL data port (tb.dut.top_earlgrey.u_rv_core_ibex.tl_adapter_host_d_ibex.tl_o/tl_i) can actually take 9 outstanding items. Sounds like the async fifos in xbar takes 8 items and peripheral takes 1 item. Can you help confirm if this is expected? If so, I can make a PR to increase the max outstanding to 9.

I reproduced the failure here.

> /mnt/disks/filestores/opentitan-shared/users/weicai/scratch/HEAD/chip_earlgrey_asic-sim-vcs/0.chip_same_csr_outstanding/latest

**Comment by tjaychen** [comment] 2022-10-24 23:56
hmm.. i'm not sure this was a conscious choice. It's more like the async fifo's are able to absorb a certain number of transactions to cover the clock crossing latency. I don't think it absorbs 8 though, (i thought it was either 2 or 4), so we'd have to take a look to see what's happening there.

**Comment by eunchan** [comment] 2022-10-25 00:08
I checked the generated codes. As of now, TL async socket has 4 depth of req and rsp FIFOs. So total 8 req (4 + 4) can be outstanding inside xbar.

At that time the async FIFO should be greater than 2. So the depth is set to 4. I think current async FIFO can support depth of 2. We can revise Xbar and reduce the number of outstanding also.

**Comment by tjaychen** [comment] 2022-10-25 02:42
hmm... i took a peek at the timestamp @weicaiyang pointed me to where the test was erroring, and at least the tlul async fifo's response and request fifos all had write depths of 0. 

I think my larger question is..what exactly are we testing? Because usually when I think of outstanding capacity, I think about a host's ability to continually issue before it sees a response. So that would usually be a fixed number on the host side. Or we could think of it as a device's ability to keep accepting transactions before it responds (in the case of a memory controller).  But I'm not quite sure what we intend to do here with the fabric.  The fabric should certainly be able to support at least the number of outstanding transactions a host can issue, but it's not clear what placing an upper limit number on it means. 

Is the test trying to say the fabric should be able to support "at least" a certain number? Because that would make sense to me, but making sure it's smaller than a certain number...I'm not sure what that means.

**Comment by weicaiyang** [comment] 2022-10-25 03:58
> hmm... i took a peek at the timestamp @weicaiyang pointed me to where the test was erroring, and at least the tlul async fifo's response and request fifos all had write depths of 0.
> 
> I think my larger question is..what exactly are we testing? Because usually when I think of outstanding capacity, I think about a host's ability to continually issue before it sees a response. So that would usually be a fixed number on the host side. Or we could think of it as a device's ability to keep accepting transactions before it responds (in the case of a memory controller). But I'm not quite sure what we intend to do here with the fabric. The fabric should certainly be able to support at least the number of outstanding transactions a host can issue, but it's not clear what placing an upper limit number on it means.
> 
> Is the test trying to say the fabric should be able to support "at least" a certain number? Because that would make sense to me, but making sure it's smaller than a certain number...I'm not sure what that means.

Let me clarify. This is for a covergroup which comes from TL agent. Since we hijack the ibex data port with a TL agent, this coverage is added automatically.
Now we see our CSR tests can occasionally hit 9 outstanding items. At the time stamp of the error, it queues 9 outstanding reqs with 9 different source ID. These reqs are accepted in A channel, but D channel rsp haven't completed.

We could either set the right max outstanding number or exclude this coverage. Since ibex can only support 2 outstanding item, this limit doesn't really matter. But may be worth understanding why it supports much more than the host could send.
As @eunchan mentioned, this may be the area we could optimize.

**Comment by engdoreis** [comment] 2022-10-25 11:06
Thanks @weicaiyang for working on this.

**Comment by tjaychen** [comment] 2022-10-25 15:14
@weicaiyang i might have to check in with you later. I'm not sure if i'm looking at the wrong thing. When I looked at the failing timestamp, it was claiming that none of the FIFO's had any entries, so I might be looking at the wrong place.

**Comment by tjaychen** [comment] 2022-10-26 00:07
thanks @weicaiyang and @eunchan for explaining. I finally see what's happening. 
It definitely makes sense to reduce the fifo depth...especially on the response side. I think our core in general does not issue new transactions until it sees a response to the previous (with the exception of a few cases that do not go to peripherals).

But we should probably double check with @GregAC to be sure before changing.

**Comment by tjaychen** [comment] 2022-10-26 18:32
alright! i checked in with @GregAC. On ibex data side, we only issue 1 transaction at a time unless its a misaligned instruction. The instruction side can issue more, but that would never go through the async fifo path anyways.

So I think I will follow along @weicaiyang / @eunchan suggestion of shrinking the the async fifo depth.

**Comment by weicaiyang** [comment] 2022-10-26 18:43
SG, thanks @tjaychen

**Comment by weicaiyang** [comment] 2022-11-01 16:42
This test is still failing. Let me take a look.

**Comment by weicaiyang** [comment] 2022-11-01 21:18
2 observations
1. I set the max_outstanding_num to 3, but flash_ctrl mem adapter can support 2 outstanding req, so we need to at least change this value to 4.
2. there are many async fifo with depth = 2, should we reduce them to one? If not, we may need to increase the max_outstanding_num to 6. @tjaychen Any thoughts?
![Screen Shot 2022-11-01 at 2 10 30 PM](https://user-images.githubusercontent.com/49293026/199342910-88bf1ce4-a086-4c79-8c54-2d243805bf38.png)

waves:
/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/top_km/chip_earlgrey_asic-sim-vcs/0.chip_same_csr_outstanding/latest

The UVM_ERROR shows it hits 5 outstanding items.

Sorry, I didn't test my update thoroughly, and now this affects many CSR tests.

Please skip looking at this error in other tests.
>  UVM_ERROR @ 5596.731437 us: (tl_monitor.sv:179) uvm_test_top.env.m_tl_agent_chip_reg_block.monitor [uvm_test_top.env.m_tl_agent_chip_reg_block.monitor] Number of pending a_req exceeds limit 4

**Comment by tjaychen** [comment] 2022-11-01 21:51
These are actually sync FIFO's inside socketm1 and socket1n. 
@eunchan and I actually went through this some time ago and reduced a lot of the depths to 0 [already](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv;l=907-912)

Did we miss some of them..?

**Comment by weicaiyang** [comment] 2022-11-01 21:59
> These are actually sync FIFO's inside socketm1 and socket1n. @eunchan and I actually went through this some time ago and reduced a lot of the depths to 0 [already](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv;l=907-912)
> 
> Did we miss some of them..?

This [one](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/tlul/rtl/tlul_socket_m1.sv;l=33?q=tlul_socket_m1&ss=opentitan%2Fopentitan) in socket m1 is still using 2. So is this [one](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/tlul/rtl/tlul_socket_1n.sv;l=50?q=tlul_soc&ss=opentitan%2Fopentitan) in socket n1.

**Comment by tjaychen** [comment] 2022-11-01 22:06
i thought all the n1s were instantiated with 0's? is that not the case?
The m1 one does make sense to default it to 1.

**Comment by weicaiyang** [comment] 2022-11-01 22:13
> i thought all the n1s were instantiated with 0's? is that not the case? The m1 one does make sense to default it to 1.

I'm afraid not. Not all the parameters are set in xbar_main. Please look at the lines I pointed in the links below. Those still use default parameters which set depth to 2. And the depth passes down to a fifo.
> This [one](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/tlul/rtl/tlul_socket_m1.sv;l=33?q=tlul_socket_m1&ss=opentitan%2Fopentitan) in socket m1 is still using 2. So is this [one](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/tlul/rtl/tlul_socket_1n.sv;l=50?q=tlul_soc&ss=opentitan%2Fopentitan) in socket n1.

**Comment by tjaychen** [comment] 2022-11-01 22:18
hm? but those just link to the socket1n module.  Is there an instantiation of socket1n where you do not see it being set to 0?
socketm1 i think that was indeed the case, but we can probably change the default.

**Comment by eunchan** [comment] 2022-11-01 22:23
`xbar_main.sv` and `xbar_peri.sv` instantiates those modules with Depth 0 always, as far as I know. So, they are fine.

**Comment by eunchan** [comment] 2022-11-01 22:26
let me correct. I checked `xbar_main.sv`. As Tim mentioned, `socket_m1` has D side FIFO (depth of 2).

**Comment by eunchan** [comment] 2022-11-01 22:53
Above my comments are incorrect. Weicai will add a comment here for the summary of the offline discussion.

**Comment by weicaiyang** [comment] 2022-11-01 23:08
As discussed with @eunchan offline, perhaps we need to update max_outstanding to 6

flash mem can take 2 outstanding req and it goes through this [m1](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv;l=963?q=xbar_main&ss=opentitan%2Fopentitan) socket, which can take 2 items in each req and rsp fifo.
```
  tlul_socket_m1 #(
    .HReqDepth (12'h0),
    .HRspDepth (12'h0),
    .DReqPass  (1'b0),
    .DRspPass  (1'b0),
    .M         (3)
  ) u_sm1_31 (
    ....
```

The other M1 don't have more than 2 items in each req/rsp fifo and the other IPs don't support higher than 2 outstanding req.

The socket 1n that ibex D port goes through doesn't have extra fifo. So, we will have max_outstanding = 6 for ibex D port.

@tjaychen does this make sense to you?

**Comment by weicaiyang** [comment] 2022-11-02 16:53
Thanks to Tim, this should be fixed by #15918. the xbar can hold maximum 2 items now, plus another one in peripheral, the total is 3 which is what we set on DV side.

**Comment by engdoreis** [comment] 2022-11-07 10:33
Closing this issue as the tests passed 4 regressions already:
|    | Tests             |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 |   2022-10-27 07:09:48 |   2022-10-26 07:06:46 |   2022-10-25 07:06:33 |   2022-10-24 07:05:24 | Suite                                                                                                 |
|---:|:------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:------------------------------------------------------------------------------------------------------|
|  1 | chip_csr_aliasing |                   100 |                   100 |                   100 |                    60 |                    80 |                    60 |                   100 |                   100 |                   100 |                   100 | csr_aliasing, regwen_csr_and_corresponding_lockable_csr, tl_d_outstanding_access, tl_d_partial_access |
|  5 | chip_csr_rw       |                   100 |                   100 |                   100 |                   100 |                    95 |                    65 |                   100 |                   100 |                   100 |                   100 | csr_rw, regwen_csr_and_corresponding_lockable_csr, tl_d_outstanding_access, tl_d_partial_access       |

**Closed by engdoreis** 2022-11-07 10:33 UTC
Labels: Component:TestTriage
