### ISSUE TITLE
[test-triage] `usbdev` bad-traffic injection temporary woes

### ISSUE THREAD

**Issue by elliotb-lowrisc** [lowRISC/opentitan#24067] opened 2024-07-19 15:09 UTC
### Hierarchy of regression failure

Block level

### Failure Description

Affected tests:
- `usbdev_timeout_missing_host_handshake`
- `usbdev_device_timeout`
- `usbdev_invalid_sync`
- `usbdev_stress_usb_traffic`
- `usbdev_iso_retraction`

Adrian says: RTL fix postponed to post-tapeout. DV override TODO.

### Steps to Reproduce

N/A

**Comment by vogelpi** [comment] 2024-07-22 17:06
IIUC, this is related to the improvements discussed in #23770 and checking the usbdev waiver document for M5, I can see that the tests listed here match the failing tests mentioned in the waiver.

Since the RTL change got deferred, we should patch up the DV to work with the current RTL. This work is planned in the waiver. For now, I am assigning the default P2. I assume that the effort required to align those tests is already captured in the V2S signoff issue #22325. Is this correct @alees24 ?

**Comment by alees24** [comment] 2024-07-25 20:11
#24115 (on top of 23999) should close this, as well as having introduced additional verification in the form of a functional model of the USB device; awaiting confirmation from nightly regressions.

**Comment by vogelpi** [comment] 2024-07-26 13:50
Thanks a lot for your feedback @alees24 and of course for working on this!

I see the updated regression results are here now and the only two tests which are not at 100% are:
- usbdev_rand_bus_resets @ 80% - not covered by this issue I believe
- usbdev_iso_retraction @ 92% - covered by this issue but now above the threshold

I think we can close this issue :-)

**Closed** 2024-07-26 15:51 UTC
Labels: IP:usbdev, Component:TestTriage, Triage Priority
