### ISSUE TITLE
[chip-test] yes

### ISSUE THREAD

**Issue by Adam11072000** [lowRISC/opentitan#18154] opened 2023-04-24 20:10 UTC
### Test point name

aes

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Checklist

we added another aes module to check for fault injections, i.e we compare the result between our ads core and the result of the current aes core, and if it's not the same, we raise an alert.
we simulated the aes as a standalone via Verilator, it works, the signals make sense, and the alert works too.
now we want to start chip-level testing via dvsim
the tests fail, we fail at line 252 in aes.sv, asserting that edn_o should have a value after reset.
our module is present in aes_core, thus it's not related to end_o.
first question:
any idea how we could get waves and how does vcs dump them using ./util/dvsim/dvsim.py hw/ip/aes/dv/aes_no_masking_sim_cfg.hjson --tool vis --waves fsdb?
2nd question:
why does it fail if we did not change the outer layer and only the inner logic of comparing?
the outputs of aes_core.sv did not change after our module (we disabled the alerts from our module, thus all the outputs are still the same)
thanks

**Comment by Adam11072000** [comment] 2023-04-24 21:24
Actually tests now passed, our branch was out of sync from the main branch, pull rebase solved it.
Now just need to know how to dump waves and open them.
Thanks

**Comment by msfschaffner** [comment] 2023-05-03 19:37
Hi @Adam11072000

The command you are running should dump an `fsdb` file into the working directory of the simulation (typically somewhere under `./scratch/<branch name>/<testbench name>/<seed.testname>`). If you have verdi, you can open that with `verdi -ssf <path to fsdb file>`.

Alternatively you can also use Xcelium and dump an `shm` file that you can then open with SimVision.

**Comment by vogelpi** [comment] 2023-07-21 09:34
This seems to be a duplicate of #17696. Closing.

**Closed by vogelpi** 2023-07-21 09:34 UTC
Labels: Component:ChipLevelTest
