### ISSUE TITLE
[DVSim] Running with global sw_build_opts/sw_images causes a Python MemoryError failure on large regressions

### ISSUE THREAD

**Issue by dkabely-ot** [lowRISC/opentitan#20550] opened 2023-12-03 15:05 UTC
### Description

When adding a global `sw_build_opts` in the hjson simulation config file, large regression simulations won't start and eventually the entire run will fail due to a Python's MemoryError exception.

The root cause of the problem is a [copy by reference of the global `sw_build_opts`](https://github.com/lowRISC/opentitan/blob/078de8dae7f7eb584cd9bac812c67ce1127675bd/util/dvsim/Modes.py#L413C29-L413C29) to each of the Tests entries, which later [copies itself over and over](https://github.com/lowRISC/opentitan/blob/master/util/dvsim/Modes.py#L455C18-L455C18), causing large regression simulations to eventually run out of memory.

Another problem that arises is duplication of `sw_build_opts`, as each Tests entry gets the global `sw_build_opts` [here](https://github.com/lowRISC/opentitan/blob/078de8dae7f7eb584cd9bac812c67ce1127675bd/util/dvsim/Modes.py#L413C29-L413C29), and then again [here](https://github.com/lowRISC/opentitan/blob/master/util/dvsim/Modes.py#L455C18-L455C18), although once the copy-by-reference problem is resolved it's not much of an issue.

An identical case can be made for `sw_images` list.

A possible solution is to deepcopy any iterable object required test entry fields (`sw_build_opts`/`sw_images`) and set them as the attribute of the Tests entry instead of just setting the reference of the global `SimCfg.sw_build_opts` as the attribute of the Tests object, and to treat both `sw_build_opts/sw_images` as a Python set instead of a list object.

**Comment by rswarbrick** [comment] 2023-12-04 11:48
This is a bit silly about our scripts, and probably not too hard to fix. Is there an easy way to reproduce the problem from here? I think I have an idea about what will fix things, but it would be nice to see it dying and then fixed by a change!

**Comment by rswarbrick** [comment] 2023-12-05 12:26
Wow, thanks for debugging this so carefully. I guess a super-stupid initial fix would be to add something like the following in `create_tests` as a work-around:
```python3
                    if global_val is not None and global_val != default_val:
                        if isinstance(global_val, list):
                            global_val = list(global_val)
                        setattr(test_obj, attr, global_val)
```

Clearly this isn't something that we should be committing to the repository! :-) But it will presumably avoid the current "append X to itself" behaviour.

**Comment by msfschaffner** [comment] 2024-03-06 17:19
This is currently blocking Nuvoton from running nightly regressions in their environment.

**Comment by rswarbrick** [comment] 2024-03-07 11:35
I think the "short-term bodge" is a very good idea. I'll file a PR in a few minutes. Honestly, this bit of the dvsim code is a right mess and I had grand plans to tidy it up a bit more dramatically. But that's a longer-term problem, I think.

**Comment by rswarbrick** [comment] 2024-03-07 11:55
I've wrapped the proposed change into PR #21885. I didn't include the `Iterable` check because it's a bit awkward (the `Iterable` type isn't something that's visible without an unusual import) and I think that calling `deepcopy` on an atom will waste a trivially small amount of space. Shout on the PR if I'm missing something.

**Comment by dkabely-ot** [comment] 2024-03-07 14:19
Looks fine, thanks!

**Closed** 2024-03-11 14:31 UTC
Labels: Priority:P0, Type:Bug
