### ISSUE TITLE
[pinmux] Pinmux WKUP_CAUSE incorrect after deep sleep resume

### ISSUE THREAD

**Issue by jettr** [lowRISC/opentitan#22242] opened 2024-03-25 20:43 UTC
### Description

When testing the resume path for deep sleep (i.e. sleep that requires chip to restart from ROM/ROM_EXT upon resume), we noticed that the [`WKUP_CAUSE`][0] register always returns `0x00`, even when the [`WAKE_INFO.REASONS`][1] register is reporting `PinmuxAonPinWkupReq` (0x04) as the peripheral wake up reason.

---

It is worth noting, that [`WKUP_CAUSE`][0] does report values _correctly_ for the normal sleep (i.e. sleep that retains SRAM and PC) resume path.

[0]:https://opentitan.org/book/hw/ip/pinmux/doc/registers.html#wkup_cause
[1]:https://opentitan.org/book/hw/top_earlgrey/ip_autogen/pwrmgr/doc/registers.html#wake_info--reasons

**Comment by johngt** [comment] 2024-03-26 13:06
@andreaskurth / @vogelpi  - I believe that this is a bug that could be corrected as part of M4.

**Comment by andreaskurth** [comment] 2024-03-26 14:10
Likely a bug but not critical; to be fixed with P2 in M4.

**Comment by moidx** [comment] 2024-06-06 19:27
Closing as this is no longer the issue. The problem was root caused to https://github.com/lowRISC/opentitan/issues/22204.

**Closed by moidx** 2024-06-06 19:27 UTC
Labels: Type:Bug, Component:RTL, IP:pinmux, prodc-integration
