### ISSUE TITLE
[flash_ctrl] XBar connectivity and Memory Protection

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#6736] opened 2021-05-27 00:31 UTC
It looks like the flash memory protection only applies to read/write operations that are initiated by SW through the `flash_ctrl` CSRs.

However, at the moment, the memory mapped read-only interface to `eflash` is accessible by all bus masters - i.e., `corei`, `cored` and `dm_sba`:
https://github.com/lowRISC/opentitan/blob/a21d01f081319424ef6b8a0767a7b80d48ccd48b/hw/top_earlgrey/data/xbar_main.hjson#L153-L168

So, even if one programs the flash memory protection to disallow e.g. SW reads to certain partitions, this can currently be sidestepped by just performing the read to the memory mapped region (i.e., going through the `cored` -> `eflash` path).

Is this intentional, or should the memory mapped region only be connected to the `corei` host?

I am not overly familiar with this part, so let me know if I missed something :).

**Comment by msfschaffner** [comment] 2021-06-16 23:14
CC @tjaychen

**Comment by tjaychen** [comment] 2021-06-16 23:20
great catch @msfschaffner ! this is indeed true, and this is something i should clarify in the documentation. 

The path is basically split in two.
From host -> flash, the expected path is host -> pmp -> flash, so the restriction is done there.
For program / erase, the expected path is host -> flash_ctrl -> flash_ctrl_pmp (the protection we are referring to here) -> flash

I'll make sure to clarify this. I just noticed there's no language actually stating this, but there's a picture that "implies" it, so i'm not sure what's going on.

**Comment by tjaychen** [comment] 2021-06-17 20:28
closing this issue for now since this is working as intended. 
Added #7011 since that is the desired function software would like to have.

**Closed by tjaychen** 2021-06-17 20:28 UTC
Labels: Type:Question
