### ISSUE TITLE
PWM frequency testing and there is 6.75% error 

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#9830] opened 2021-12-27 10:17 UTC
Is there anyone met the same problem with me for the PWM in opentitan?

clk_div | measured frequency | expected frequency
--         | --                               | --
0x8000 |     17.88                     | 19.07Hz
0x800   |     286                        | 305.03
0x80     | 4.543k                        | 4845
0x8       | 65.1k                          | 69444
0x0       | 586k                           | 625k

> estimate 2

**Comment by cindychip** [comment] 2021-12-28 18:08
CC: @tjaychen

**Comment by martin-lueker** [comment] 2022-01-04 18:59
Hi @nicolast0604, can you describe your measurement setup?

**Comment by nicolast0604** [comment] 2022-01-10 08:41
[PWM.zip](https://github.com/lowRISC/opentitan/files/7837600/PWM.zip)

This is the testing program for your reference.

**Comment by martin-lueker** [comment] 2022-01-10 17:11
Hi @nicolast0604, 
  Great thanks!  I'm presuming you ran this from within the OpenTitan test framework. Could you please send some explicit instructions how to reproduce the test?  Having the code is great, but's only part of the process.  You can take a look at this [issue description, particularly the part that the bottom where it says "to reproduce this issue"](https://github.com/lowRISC/opentitan/issues/7621#issue-961921263).   I find that the best issue descriptions have:
1. A pointer to a branch on someone's fork so that the exact repository state can pre reproduced
2. An explicit sequence to run the test.

For confirmation: I'm presuming you are running this in verilator?

**Comment by rasmus-madsen** [comment] 2022-01-11 22:43
Hi @nicolast0604 
I am trying to recreate your findings but I am not seeing the same issue as you see.

the easiest is to talk in clock vs frequency as the numbers will match no matter what frequency.

I did some simulations and my findings are that the output matches what I expect.
here are a few of my simulation results:

Clkdiv of 0, duty-cycle 1, resolution 15 - we would expect a pulse every 2^16 clk
which is what I see
![image](https://user-images.githubusercontent.com/53917183/149030732-571b37da-4207-49df-a859-ce27231ce708.png)

now simulating full resolution for larger values of ClkDiv becomes impractical so I have used a resolution setting of 12.
same simulation with a resolution of 12
ClkDiv of 0, duty-cycle 1, resolution 12 (one pulse every 2^(12+1) clk  ) which equals a pulse every 8192 clk
![image](https://user-images.githubusercontent.com/53917183/149030943-3287a0ab-abea-49b8-8727-7edc22f1adeb.png)

ClkDiv of h8, duty-cycle 1, resolution 12 (one pulse every 2^(12+1) clk)
Should give 1 pulse every 2^13*9 cycles (73728)
![image](https://user-images.githubusercontent.com/53917183/149031174-b9787b2c-fdf2-41c1-b4d5-5145eb67eb4f.png)

Could you re-check your results
it would be helpful if you could also share your PWM configuration values

**Comment by nicolast0604** [comment] 2022-01-13 02:13
Hi 
Great thanks for your quick and detail response.
My PWM configurations is as below. and my testing procedure is in the word file.

[PWM testing procedure  en-US.docx](https://github.com/lowRISC/opentitan/files/7859286/PWM.testing.procedure.en-US.docx)

#ifndef _PWM_REG_DEFS_
#define _PWM_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define PWM_PWM_PARAM_REG_WIDTH					32

// Alert Test Register
#define PWM_ALERT_TEST_REG_OFFSET				0x0
#define PWM_ALERT_TEST_REG_RESVAL				0x0
#define PWM_ALERT_TEST_FATAL_FAULT_BIT			0

// Write enable Register
#define PWM_REGWEN_REG_OFFSET					0x4
#define PWM_REGWEN_REG_RESVAL					0x1

// Configuration Register
#define PWM_CFG_REG_OFFSET						0x8
#define PWM_CFG_REG_RESVAL						0x38008000
#define PWM_CFG_CLK_DIV_MASK					0x7ffffff
#define PWM_CFG_CLK_DIV_OFFSET					0
#define PWM_CFG_CLK_DIV_FIELD 					((bitfield_field32_t) { \
													.mask = PWM_CFG_CLK_DIV_MASK, \
													.index = PWM_CFG_CLK_DIV_OFFSET \
												})
#define PWM_CFG_DC_RESN_MASK					0xf
#define PWM_CFG_DC_RESN_OFFSET					27
#define PWM_CFG_DC_RESN_FIELD					((bitfield_field32_t) { \
													.mask = PWM_CFG_DC_RESN_MASK, \
													.index = PWM_CFG_DC_RESN_OFFSET \
												})
#define PWM_CFG_CNTR_EN_BIT						31

// PWM Enable Register
#define PWM_PWM_EN_REG_OFFSET					0xc
#define PWM_PWM_EN_REG_RESVAL					0x0
#define PWM_PWM_EN_0_BIT						0
#define PWM_PWM_EN_1_BIT						1
#define PWM_PWM_EN_2_BIT						2
#define PWM_PWM_EN_3_BIT						3
#define PWM_PWM_EN_4_BIT						4
#define PWM_PWM_EN_5_BIT						5

// PWM Invert register
#define PWM_INVERT_REG_OFFSET					0x10
#define PWM_INVERT_REG_RESVAL					0x0
#define PWM_INVERT_0_BIT						0
#define PWM_INVERT_1_BIT						1
#define PWM_INVERT_2_BIT						2
#define PWM_INVERT_3_BIT						3
#define PWM_INVERT_4_BIT						4
#define PWM_INVERT_5_BIT						5

// PWM Channel Parameters register common defines
#define PWM_PWM_PARAM_REG_RESVAL				0x0
#define PWM_PWM_PARAM_PHASE_DELAY_MASK			0xffff
#define PWM_PWM_PARAM_PHASE_DELAY_OFFSET		0
#define PWM_PWM_PARAM_PHASE_DELAY_FIELD			((bitfield_field32_t) { \
													.mask = PWM_PWM_PARAM_PHASE_DELAY_MASK, \
													.index = PWM_PWM_PARAM_PHASE_DELAY_OFFSET \
												})
#define PWM_PWM_PARAM_HTBT_EN_BIT				30
#define PWM_PWM_PARAM_BLINK_EN_BIT				31

// PWM Channel Parameters 0 register
#define PWM_PWM_PARAM_0_REG_OFFSET				0x14
#define PWM_PWM_PARAM_0_REG_RESVAL				PWM_PWM_PARAM_REG_RESVAL
#define PWM_PWM_PARAM_0_PHASE_DELAY_0_MASK		PWM_PWM_PARAM_PHASE_DELAY_MASK
#define PWM_PWM_PARAM_0_PHASE_DELAY_0_OFFSET	PWM_PWM_PARAM_PHASE_DELAY_OFFSET
#define PWM_PWM_PARAM_0_PHASE_DELAY_0_FIELD		PWM_PWM_PARAM_PHASE_DELAY_FIELD
#define PWM_PWM_PARAM_0_HTBT_EN_0_BIT			PWM_PWM_PARAM_HTBT_EN_BIT
#define PWM_PWM_PARAM_0_BLINK_EN_0_BIT			PWM_PWM_PARAM_BLINK_EN_BIT

// PWM Channel Parameters 1 register
#define PWM_PWM_PARAM_1_REG_OFFSET				0x18
#define PWM_PWM_PARAM_1_REG_RESVAL				PWM_PWM_PARAM_REG_RESVAL
#define PWM_PWM_PARAM_1_PHASE_DELAY_1_MASK		PWM_PWM_PARAM_PHASE_DELAY_MASK
#define PWM_PWM_PARAM_1_PHASE_DELAY_1_OFFSET	PWM_PWM_PARAM_PHASE_DELAY_OFFSET
#define PWM_PWM_PARAM_1_PHASE_DELAY_1_FIELD		PWM_PWM_PARAM_PHASE_DELAY_FIELD
#define PWM_PWM_PARAM_1_HTBT_EN_1_BIT			PWM_PWM_PARAM_HTBT_EN_BIT
#define PWM_PWM_PARAM_1_BLINK_EN_1_BIT			PWM_PWM_PARAM_BLINK_EN_BIT

// PWM Channel Parameters 2 register
#define PWM_PWM_PARAM_2_REG_OFFSET				0x1c
#define PWM_PWM_PARAM_2_REG_RESVAL				PWM_PWM_PARAM_REG_RESVAL
#define PWM_PWM_PARAM_2_PHASE_DELAY_2_MASK		PWM_PWM_PARAM_PHASE_DELAY_MASK
#define PWM_PWM_PARAM_2_PHASE_DELAY_2_OFFSET	PWM_PWM_PARAM_PHASE_DELAY_OFFSET
#define PWM_PWM_PARAM_2_PHASE_DELAY_2_FIELD		PWM_PWM_PARAM_PHASE_DELAY_FIELD
#define PWM_PWM_PARAM_2_HTBT_EN_2_BIT			PWM_PWM_PARAM_HTBT_EN_BIT
#define PWM_PWM_PARAM_2_BLINK_EN_2_BIT			PWM_PWM_PARAM_BLINK_EN_BIT

// PWM Channel Parameters 3 register
#define PWM_PWM_PARAM_3_REG_OFFSET				0x20
#define PWM_PWM_PARAM_3_REG_RESVAL				PWM_PWM_PARAM_REG_RESVAL
#define PWM_PWM_PARAM_3_PHASE_DELAY_3_MASK		PWM_PWM_PARAM_PHASE_DELAY_MASK
#define PWM_PWM_PARAM_3_PHASE_DELAY_3_OFFSET	PWM_PWM_PARAM_PHASE_DELAY_OFFSET
#define PWM_PWM_PARAM_3_PHASE_DELAY_3_FIELD		PWM_PWM_PARAM_PHASE_DELAY_FIELD
#define PWM_PWM_PARAM_3_HTBT_EN_3_BIT			PWM_PWM_PARAM_HTBT_EN_BIT
#define PWM_PWM_PARAM_3_BLINK_EN_3_BIT			PWM_PWM_PARAM_BLINK_EN_BIT

// PWM Channel Parameters 4 register
#define PWM_PWM_PARAM_4_REG_OFFSET				0x24
#define PWM_PWM_PARAM_4_REG_RESVAL				PWM_PWM_PARAM_REG_RESVAL
#define PWM_PWM_PARAM_4_PHASE_DELAY_4_MASK		PWM_PWM_PARAM_PHASE_DELAY_MASK
#define PWM_PWM_PARAM_4_PHASE_DELAY_4_OFFSET	PWM_PWM_PARAM_PHASE_DELAY_OFFSET
#define PWM_PWM_PARAM_4_PHASE_DELAY_4_FIELD		PWM_PWM_PARAM_PHASE_DELAY_FIELD
#define PWM_PWM_PARAM_4_HTBT_EN_4_BIT			PWM_PWM_PARAM_HTBT_EN_BIT
#define PWM_PWM_PARAM_4_BLINK_EN_4_BIT			PWM_PWM_PARAM_BLINK_EN_BIT

// PWM Channel Parameters 5 register
#define PWM_PWM_PARAM_5_REG_OFFSET				0x28
#define PWM_PWM_PARAM_5_REG_RESVAL				PWM_PWM_PARAM_REG_RESVAL
#define PWM_PWM_PARAM_5_PHASE_DELAY_5_MASK		PWM_PWM_PARAM_PHASE_DELAY_MASK
#define PWM_PWM_PARAM_5_PHASE_DELAY_5_OFFSET	PWM_PWM_PARAM_PHASE_DELAY_OFFSET
#define PWM_PWM_PARAM_5_PHASE_DELAY_5_FIELD		PWM_PWM_PARAM_PHASE_DELAY_FIELD
#define PWM_PWM_PARAM_5_HTBT_EN_5_BIT			PWM_PWM_PARAM_HTBT_EN_BIT
#define PWM_PWM_PARAM_5_BLINK_EN_5_BIT			PWM_PWM_PARAM_BLINK_EN_BIT

// PWM DUTY CYCLE register common defines
#define PWM_DUTY_CYCLE_REG_RESVAL				0x7fff7fff
#define PWM_DUTY_CYCLE_A_MASK					0xffff
#define PWM_DUTY_CYCLE_A_OFFSET					0
#define PWM_DUTY_CYCLE_A_FIELD					((bitfield_field32_t) { \
													.mask = PWM_DUTY_CYCLE_A_MASK, \
													.index = PWM_DUTY_CYCLE_A_OFFSET \
												})
#define PWM_DUTY_CYCLE_B_MASK					0xffff
#define PWM_DUTY_CYCLE_B_OFFSET					16
#define PWM_DUTY_CYCLE_B_FIELD					((bitfield_field32_t) { \
													.mask = PWM_DUTY_CYCLE_B_MASK, \
													.index = PWM_DUTY_CYCLE_B_OFFSET \
												})

// PWM DUTY CYCLE 0 register
#define PWM_DUTY_CYCLE_0_REG_OFFSET				0x2c
#define PWM_DUTY_CYCLE_0_REG_RESVAL				PWM_DUTY_CYCLE_REG_RESVAL
#define PWM_DUTY_CYCLE_0_A_0_MASK				PWM_DUTY_CYCLE_A_MASK
#define PWM_DUTY_CYCLE_0_A_0_OFFSET				PWM_DUTY_CYCLE_A_OFFSET
#define PWM_DUTY_CYCLE_0_A_0_FIELD				PWM_DUTY_CYCLE_A_FIELD
#define PWM_DUTY_CYCLE_0_B_0_MASK				PWM_DUTY_CYCLE_B_MASK
#define PWM_DUTY_CYCLE_0_B_0_OFFSET				PWM_DUTY_CYCLE_B_OFFSET
#define PWM_DUTY_CYCLE_0_B_0_FIELD				PWM_DUTY_CYCLE_B_FIELD

// PWM DUTY CYCLE 1 register
#define PWM_DUTY_CYCLE_1_REG_OFFSET				0x30
#define PWM_DUTY_CYCLE_1_REG_RESVAL				PWM_DUTY_CYCLE_REG_RESVAL
#define PWM_DUTY_CYCLE_1_A_1_MASK				PWM_DUTY_CYCLE_A_MASK
#define PWM_DUTY_CYCLE_1_A_1_OFFSET				PWM_DUTY_CYCLE_A_OFFSET
#define PWM_DUTY_CYCLE_1_A_1_FIELD				PWM_DUTY_CYCLE_A_FIELD
#define PWM_DUTY_CYCLE_1_B_1_MASK				PWM_DUTY_CYCLE_B_MASK
#define PWM_DUTY_CYCLE_1_B_1_OFFSET				PWM_DUTY_CYCLE_B_OFFSET
#define PWM_DUTY_CYCLE_1_B_1_FIELD				PWM_DUTY_CYCLE_B_FIELD

// PWM DUTY CYCLE 2 register
#define PWM_DUTY_CYCLE_2_REG_OFFSET				0x34
#define PWM_DUTY_CYCLE_2_REG_RESVAL				PWM_DUTY_CYCLE_REG_RESVAL
#define PWM_DUTY_CYCLE_2_A_2_MASK				PWM_DUTY_CYCLE_A_MASK
#define PWM_DUTY_CYCLE_2_A_2_OFFSET				PWM_DUTY_CYCLE_A_OFFSET
#define PWM_DUTY_CYCLE_2_A_2_FIELD				PWM_DUTY_CYCLE_A_FIELD
#define PWM_DUTY_CYCLE_2_B_2_MASK				PWM_DUTY_CYCLE_B_MASK
#define PWM_DUTY_CYCLE_2_B_2_OFFSET				PWM_DUTY_CYCLE_B_OFFSET
#define PWM_DUTY_CYCLE_2_B_2_FIELD				PWM_DUTY_CYCLE_B_FIELD

// PWM DUTY CYCLE 3 register
#define PWM_DUTY_CYCLE_3_REG_OFFSET				0x38
#define PWM_DUTY_CYCLE_3_REG_RESVAL				PWM_DUTY_CYCLE_REG_RESVAL
#define PWM_DUTY_CYCLE_3_A_3_MASK				PWM_DUTY_CYCLE_A_MASK
#define PWM_DUTY_CYCLE_3_A_3_OFFSET				PWM_DUTY_CYCLE_A_OFFSET
#define PWM_DUTY_CYCLE_3_A_3_FIELD				PWM_DUTY_CYCLE_A_FIELD
#define PWM_DUTY_CYCLE_3_B_3_MASK				PWM_DUTY_CYCLE_B_MASK
#define PWM_DUTY_CYCLE_3_B_3_OFFSET				PWM_DUTY_CYCLE_B_OFFSET
#define PWM_DUTY_CYCLE_3_B_3_FIELD				PWM_DUTY_CYCLE_B_FIELD

// PWM DUTY CYCLE 4 register
#define PWM_DUTY_CYCLE_4_REG_OFFSET				0x3c
#define PWM_DUTY_CYCLE_4_REG_RESVAL				PWM_DUTY_CYCLE_REG_RESVAL
#define PWM_DUTY_CYCLE_4_A_4_MASK				PWM_DUTY_CYCLE_A_MASK
#define PWM_DUTY_CYCLE_4_A_4_OFFSET				PWM_DUTY_CYCLE_A_OFFSET
#define PWM_DUTY_CYCLE_4_A_4_FIELD				PWM_DUTY_CYCLE_A_FIELD
#define PWM_DUTY_CYCLE_4_B_4_MASK				PWM_DUTY_CYCLE_B_MASK
#define PWM_DUTY_CYCLE_4_B_4_OFFSET				PWM_DUTY_CYCLE_B_OFFSET
#define PWM_DUTY_CYCLE_4_B_4_FIELD				PWM_DUTY_CYCLE_B_FIELD

// PWM DUTY CYCLE 5 register
#define PWM_DUTY_CYCLE_5_REG_OFFSET				0x40
#define PWM_DUTY_CYCLE_5_REG_RESVAL				PWM_DUTY_CYCLE_REG_RESVAL
#define PWM_DUTY_CYCLE_5_A_5_MASK				PWM_DUTY_CYCLE_A_MASK
#define PWM_DUTY_CYCLE_5_A_5_OFFSET				PWM_DUTY_CYCLE_A_OFFSET
#define PWM_DUTY_CYCLE_5_A_5_FIELD				PWM_DUTY_CYCLE_A_FIELD
#define PWM_DUTY_CYCLE_5_B_5_MASK				PWM_DUTY_CYCLE_B_MASK
#define PWM_DUTY_CYCLE_5_B_5_OFFSET				PWM_DUTY_CYCLE_B_OFFSET
#define PWM_DUTY_CYCLE_5_B_5_FIELD				PWM_DUTY_CYCLE_B_FIELD

// PWM Blink/Heartbeat Parameters register common defines
#define PWM_BLINK_PARAM_REG_RESVAL				0x0
#define PWM_BLINK_PARAM_X_MASK					0xffff
#define PWM_BLINK_PARAM_X_OFFSET				0
#define PWM_BLINK_PARAM_X_FIELD					((bitfield_field32_t) { \
													.mask = PWM_BLINK_PARAM_0_X_0_MASK, \
													.index = PWM_BLINK_PARAM_0_X_0_OFFSET \
												})
#define PWM_BLINK_PARAM_Y_MASK					0xffff
#define PWM_BLINK_PARAM_Y_OFFSET				16
#define PWM_BLINK_PARAM_Y_FIELD					((bitfield_field32_t) { \
													.mask = PWM_BLINK_PARAM_0_Y_0_MASK, \
													.index = PWM_BLINK_PARAM_0_Y_0_OFFSET \
												})

// PWM Blink/Heartbeat Parameters 0 register
#define PWM_BLINK_PARAM_0_REG_OFFSET			0x44
#define PWM_BLINK_PARAM_0_REG_RESVAL			PWM_BLINK_PARAM_REG_RESVAL
#define PWM_BLINK_PARAM_0_X_0_MASK				PWM_BLINK_PARAM_X_MASK
#define PWM_BLINK_PARAM_0_X_0_OFFSET			PWM_BLINK_PARAM_X_OFFSET
#define PWM_BLINK_PARAM_0_X_0_FIELD				PWM_BLINK_PARAM_X_FIELD
#define PWM_BLINK_PARAM_0_Y_0_MASK				PWM_BLINK_PARAM_Y_MASK
#define PWM_BLINK_PARAM_0_Y_0_OFFSET			PWM_BLINK_PARAM_Y_OFFSET
#define PWM_BLINK_PARAM_0_Y_0_FIELD				PWM_BLINK_PARAM_Y_FIELD

// PWM Blink/Heartbeat Parameters 1 register
#define PWM_BLINK_PARAM_1_REG_OFFSET			0x48
#define PWM_BLINK_PARAM_1_REG_RESVAL			PWM_BLINK_PARAM_REG_RESVAL
#define PWM_BLINK_PARAM_1_X_1_MASK				PWM_BLINK_PARAM_X_MASK
#define PWM_BLINK_PARAM_1_X_1_OFFSET			PWM_BLINK_PARAM_X_OFFSET
#define PWM_BLINK_PARAM_1_X_1_FIELD				PWM_BLINK_PARAM_X_FIELD
#define PWM_BLINK_PARAM_1_Y_1_MASK				PWM_BLINK_PARAM_Y_MASK
#define PWM_BLINK_PARAM_1_Y_1_OFFSET			PWM_BLINK_PARAM_Y_OFFSET
#define PWM_BLINK_PARAM_1_Y_1_FIELD				PWM_BLINK_PARAM_Y_FIELD

// PWM Blink/Heartbeat Parameters 2 register
#define PWM_BLINK_PARAM_2_REG_OFFSET			0x4c
#define PWM_BLINK_PARAM_2_REG_RESVAL			PWM_BLINK_PARAM_REG_RESVAL
#define PWM_BLINK_PARAM_2_X_2_MASK				PWM_BLINK_PARAM_X_MASK
#define PWM_BLINK_PARAM_2_X_2_OFFSET			PWM_BLINK_PARAM_X_OFFSET
#define PWM_BLINK_PARAM_2_X_2_FIELD				PWM_BLINK_PARAM_X_FIELD
#define PWM_BLINK_PARAM_2_Y_2_MASK				PWM_BLINK_PARAM_Y_MASK
#define PWM_BLINK_PARAM_2_Y_2_OFFSET			PWM_BLINK_PARAM_Y_OFFSET
#define PWM_BLINK_PARAM_2_Y_2_FIELD				PWM_BLINK_PARAM_Y_FIELD

// PWM Blink/Heartbeat Parameters 3 register
#define PWM_BLINK_PARAM_3_REG_OFFSET			0x50
#define PWM_BLINK_PARAM_3_REG_RESVAL			PWM_BLINK_PARAM_REG_RESVAL
#define PWM_BLINK_PARAM_3_X_3_MASK				PWM_BLINK_PARAM_X_MASK
#define PWM_BLINK_PARAM_3_X_3_OFFSET			PWM_BLINK_PARAM_X_OFFSET
#define PWM_BLINK_PARAM_3_X_3_FIELD				PWM_BLINK_PARAM_X_FIELD
#define PWM_BLINK_PARAM_3_Y_3_MASK				PWM_BLINK_PARAM_Y_MASK
#define PWM_BLINK_PARAM_3_Y_3_OFFSET			PWM_BLINK_PARAM_Y_OFFSET
#define PWM_BLINK_PARAM_3_Y_3_FIELD				PWM_BLINK_PARAM_Y_FIELD

// PWM Blink/Heartbeat Parameters 4 register
#define PWM_BLINK_PARAM_4_REG_OFFSET			0x54
#define PWM_BLINK_PARAM_4_REG_RESVAL			PWM_BLINK_PARAM_REG_RESVAL
#define PWM_BLINK_PARAM_4_X_4_MASK				PWM_BLINK_PARAM_X_MASK
#define PWM_BLINK_PARAM_4_X_4_OFFSET			PWM_BLINK_PARAM_X_OFFSET
#define PWM_BLINK_PARAM_4_X_4_FIELD				PWM_BLINK_PARAM_X_FIELD
#define PWM_BLINK_PARAM_4_Y_4_MASK				PWM_BLINK_PARAM_Y_MASK
#define PWM_BLINK_PARAM_4_Y_4_OFFSET			PWM_BLINK_PARAM_Y_OFFSET
#define PWM_BLINK_PARAM_4_Y_4_FIELD				PWM_BLINK_PARAM_Y_FIELD

// PWM Blink/Heartbeat Parameters 5 register
#define PWM_BLINK_PARAM_5_REG_OFFSET			0x58
#define PWM_BLINK_PARAM_5_REG_RESVAL			PWM_BLINK_PARAM_REG_RESVAL
#define PWM_BLINK_PARAM_5_X_5_MASK				PWM_BLINK_PARAM_X_MASK
#define PWM_BLINK_PARAM_5_X_5_OFFSET			PWM_BLINK_PARAM_X_OFFSET
#define PWM_BLINK_PARAM_5_X_5_FIELD				PWM_BLINK_PARAM_X_FIELD
#define PWM_BLINK_PARAM_5_Y_5_MASK				PWM_BLINK_PARAM_Y_MASK
#define PWM_BLINK_PARAM_5_Y_5_OFFSET			PWM_BLINK_PARAM_Y_OFFSET
#define PWM_BLINK_PARAM_5_Y_5_FIELD				PWM_BLINK_PARAM_Y_FIELD

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _PWM_REG_DEFS_

**Comment by nicolast0604** [comment] 2022-01-19 09:29
@rasmus-madsen rasmus-madsen

https://github.com/lowRISC/opentitan/files/7859286/PWM.testing.procedure.en-US.docx

**Comment by rasmus-madsen** [comment] 2022-01-19 14:46
@nicolast0604 this is interesting - although we currently have some wierd behavior with the never versions of PWM that is being looked into.
please see https://github.com/lowRISC/opentitan/issues/10062

once we have a stable PWM core I will see if I can reproduce your findings - since the problem also excist without the clock divider enabled I am thinking that this might actually be a problem with the input clock and not the pwm module it self.

**Comment by nicolast0604** [comment] 2022-01-21 03:12
Thanks for your help.

The input clock is set to 10Mhz as the same as the CPU clock. 

Please feel free to let me know any recommendations.

**Comment by msfschaffner** [comment] 2022-10-21 16:01
@jdonjdon @tjaychen @msfschaffner we should double check whether anything needs to be fixed here for M2.

**Comment by andreaskurth** [comment] 2023-02-27 10:28
Triaged for `pwm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because we should check if this problem still exists and fix it if necessary.

**Comment by moidx** [comment] 2023-05-04 22:28
De-prioritizing `pwm` for M2.5.

**Comment by johngt** [comment] 2024-04-16 10:20
Assigning to @engdoreis to investigate. If issues are found - please report to @andreaskurth . If more analysis is needed please contact @nasahlpa

**Comment by engdoreis** [comment] 2024-04-17 15:05
I made some experiments measuring with the logic analyser: 

### FPGA CW340 with aon clock = 250khz

clk_div   | expected (Hz)| CW340 FPGA (Hz)
--        | --              | --
0x8000    | 3.814697265625 | 3.815
0x800      | 61.03515625 | 61.006
0x80      | 976.5625 | 960.002
0x8        | 15625 | 13889
0x0        | 125k |125k 

### Silicon with aon clock = 200khz
clk_div   | expected (Hz)| Silicon (Hz)
--        | --              | --
0x8000    | 3.0517578125 | 3.067
0x800      | 48.828125 | 49.051
0x80      | 781.25 | 779.056
0x8        | 12500 | 11166
0x0        | 100000 |100503

**Comment by johngt** [comment] 2024-04-17 15:34
@moidx / @andreaskurth / @vogelpi please see PWM analysis results carried out by @engdoreis. The percentage deviation seems to be fine for all apart from the 0x8 clk_div

### FPGA CW340 with aon clock = 250khz

clk_div   | expected (Hz)| CW340 FPGA (Hz) | Percentage diff
--        | --              | --              | --
0x8000    | 3.814697265625 | 3.815 | +0.007936
0x800      | 61.03515625 | 61.006 |  -0.0477696
0x80      | 976.5625 | 960.002 | -1.6957952
0x8        | 15625 | 13889 |  -11.1104
0x0        | 125k |125k | 0

### Silicon with aon clock = 200khz
clk_div   | expected (Hz)| Silicon (Hz) | Percentage diff
--        | --              | --              | --
0x8000    | 3.0517578125 | 3.067 |  +0.499456
0x800      | 48.828125 | 49.051 |  +0.456448
0x80      | 781.25 | 779.056 |  +0.280832
0x8        | 12500 | 11166 |  -10.672
0x0        | 100000 |100503 |  +0.503

**Comment by vogelpi** [comment] 2024-04-18 10:24
Thanks for doing the measurements @engdoreis and for feeding the results back @johngt . This looks good to me. The deviation at 0x8 looks systematic to me. I think we're actually dividing by 9 instead:
- 250k / 2 / 9 = 13888
- 200k / 2 / 9 = 11111

We might be one clock tick off or something. This should be investigated.

**Comment by andreaskurth** [comment] 2024-04-19 14:39
Thx @engdoreis -- reassigning to @rswarbrick as M4 HW coordinator of pwm to investigate (or delegate)

**Comment by andreaskurth** [comment] 2024-05-16 20:10
Looking at [pwm's specification](https://opentitan.org/book/hw/ip/pwm/doc/theory_of_operation.html#pwm-phase-counter)
![image](https://github.com/lowRISC/opentitan/assets/3583291/d8eb61da-04d8-4c16-b93a-632be54d0139)
the numbers in the **Silicon (Hz)** column of the table above look **correct** to me for DC_RESN = 0 and f_coreclk = 200 kHz:
| clk_div | calculated (Hz) | Silicon (Hz) | Percentage diff |
|:---------|-----------:|-----:|-----:|
| 0x0 | 100e3 | 100503 | +0.5%
| 0x8 | 11.1e3 | 11166 | +0.5%
| 0x80 | 775 | 779.056 | +0.5%
| 0x800 | 48.8 | 49.051 | +0.5%
| 0x8000 | 3.05 | 3.067| +0.5%

So I think the AON clock (which is pwm's core_clk) on the measured chip just runs 0.5% faster than 200 kHz, and since pwm's output is derived from that clock, the output is faster as well. We don't have a tolerance specification for pwm AFAIK, but given the intended use case I think this is totally fine.

What is not clear to me, though: Where do the values in the **expected (Hz)** column in the tables above come from, @engdoreis?

**Comment by a-will** [comment] 2024-05-16 20:43
> What is not clear to me, though: Where do the values in the **expected (Hz)** column in the tables above come from, @engdoreis?

Looks like it's just an off-by-one error in the interpretation of the encoding. @engdoreis was missing the **+ 1** in the divisor.

**Comment by andreaskurth** [comment] 2024-05-17 14:52
Ah, I see, makes sense. SGTM, let's close this. @engdoreis and @johngt if you think we have overlooked something in the last two comments, please reopen.

**Closed by andreaskurth** 2024-05-17 14:52 UTC
Labels: Priority:P2, Type:Bug, Component:RTL, IP:pwm, Milestone:V2, Earlgrey-PROD Candidate

**Comment by engdoreis** [comment] 2024-05-20 11:14
Yes, @a-will is right, the `expected` column is the clock that I computed, but I forgot to add the `+1` in the divisor, as in the formula above.
