### ISSUE TITLE
[sw] Private CI is broken, since merging PR #9316

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#9383] opened 2021-11-24 23:15 UTC
I suspect it's just a matter of two conflicting PRs going in: CI was green for the [PR itself](https://github.com/lowRISC/opentitan/pull/9316).

@timothytrippel: Would you mind taking a look? If you don't get a chance, no problem: we can either do some debugging or back out the change tomorrow morning UK time.

**Comment by rswarbrick** [comment] 2021-11-24 23:25
Looks like I should have got to the bottom of my inbox before filing this! Possible back-out PR at #9381.

**Comment by timothytrippel** [comment] 2021-11-25 00:54
Yes, it was the case of some conflicting PRs going in. @sriyerg has found there was some X's coming out of SRAM and is working on a more permanent solution such that we can keep the optimization originally introduced in #9316, but I have reverted #9316 in #9381 to get things working again in the meantime. Sorry about that!

**Comment by timothytrippel** [comment] 2021-11-25 02:53
I believe we can close this as the root cause was addressed in #9382.

**Closed by timothytrippel** 2021-11-25 02:53 UTC
Labels: Component:SW, Type:Bug
