### ISSUE TITLE
aes_csr tests failing

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#10617] opened 2022-02-04 13:26 UTC
./util/dvsim/dvsim.py hw/ip/aes/dv/aes_sim_cfg.hjson -i aes_shadow_reg_errors_with_csr_rw -r 1 -t xcelium -s=627433368

fails with the following message:

> UVM_ERROR @  31296262 ps: (csr_utils_pkg.sv:432) [csr_utils::csr_rd_check] Check failed obs == exp (39297 [0x9981] vs 72067 [0x11983]) Regname: aes_reg_block.ctrl_shadowed 

I have made two observations - 

1.  the expected value does not match what is actually written to the CTRL reg. because the test does not expect the operation to be forced to 01 for illegal values
2. the response is missing the FORCE_ZERO_MASKS bit

starting with the first issue:

as expected the ctrl register is updated twice as required for shadow regs.
the first update is a partial write
address: 0x1E3E3F74
Mask:0x7
Data: F37599BB
the ctrl reg is only 17 bits so we can narrow it down to this
the data is then 199BB
converting this to the fields of the register
```
1      1  001     1  001  1011 10  11
|      | |__|     | |__| |_______| |_|
|      |   |      |   |        |    |_   illegal  operation  -> will map to 01
|      |   |      |   |        |________  invalid mode will map to AES_NONE -> 10_000
|      |   |      |   |______________ key_len 128         -> 001
|      |   |      |__ _____________ sideload_en  -> 1
|      |   |____________________  prng_reseed_rate ->001
|      |_______________________ manual mode -> 1
|___________________________ force_zero_mast -> 1
```
with the updated values due to illegal values this turns into
1 1001 1001 1000 0001 (0x19981) (expected was 0x19983)

so Clearly the CSR test is not aware that an illegal operation will map to 01

the second write to CTRL is (**notice how the two values doesn't match - but no alert is thrown I assume this is because they are invalid and mapped to 0x20)**
address 1E3E3F74
data(17bits) 1993B
```
1      1  001     1  001  1011 10  11
|      | |__|     | |__| |_______| |_|
|      |   |      |   |        |    |_   illegal  operation  -> will map to 01
|      |   |      |   |        |________  invalid mode will map to AES_NONE -> 10_000
|      |   |      |   |______________ key_len 128         -> 001
|      |   |      |__ _____________ sideload_en  -> 1
|      |   |____________________  prng_reseed_rate ->001
|      |_______________________ manual mode -> 1
|___________________________ force_zero_mast -> 1
```
with the updated values due to illegal values this turns into
1 1001 1001 1000 0001 (0x19981) (expected was 0x19983)

but the read data is only 0x9981 (the force zero mask bit has somehow been reset?)
![image](https://user-images.githubusercontent.com/53917183/152536116-49341c82-c450-412b-955b-c8f5879272b4.png)

**Comment by cindychip** [comment] 2022-02-04 23:28
Thanks Rasmus for the detailed debug analysis.
Since this register does not take write data as it is, but rather mapping it to legal values, do you think we can exclude the register from read check in the csr automated tests?
You can add a tag (either to the entire register, or to specific fields that map illegal value): 
```
    tags: [// Explain why we exclude it 
           "excl:CsrNonInitTests:CsrExclCheck"]
```

**Comment by rasmus-madsen** [comment] 2022-02-06 14:09
Sure that is fine with me - I will make a PR with the update

**Comment by rasmus-madsen** [comment] 2022-02-06 14:29
@cindychip it looks like the exclusion is already there but it is being ignored.
I tried changing it to all - but it still checks the value.

could you take a look and see why the exclusion is not working?

**Comment by cindychip** [comment] 2022-02-07 18:30
sure I will take a look!

**Comment by cindychip** [comment] 2022-02-08 07:29
Oh sorry my bad! I totally did not check the regression results. I will fix `aes_shadow_reg_errors_with_csr_rw` and `aes_shadow_reg_errors` tests. I was just waiting for the alignment on this issue: https://github.com/lowRISC/opentitan/issues/8460

**Comment by vogelpi** [comment] 2022-02-21 11:29
Hey guys, sorry I wasn't aware that this issue was blocked by an outstanding response from my side. I've now replied to #8460 .

**Comment by vogelpi** [comment] 2022-10-21 13:33
When moving some shadow register bits around for #15641 I came again across this issue. I went through it again. The corresponding tests are passing, and the behavior of DV and RTL is documented (with links to this issue and lowRISC/OpenTitan#8460). I am now closing this issue.

Please feel free to re-open if you don't agree.

**Closed by vogelpi** 2022-10-21 13:33 UTC
Labels: Component:DV, Priority:P2, Type:Bug, IP:aes, Milestone:V2
