### ISSUE TITLE
[test-triage] chip_sw_otbn_smoketest

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#16030] opened 2022-11-04 20:55 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

No signature available on the dashboard (unknown why).

CC @tjaychen @sriyerg 

### Steps to Reproduce

- GitHub Revision: [3e32a31a2](https://github.com/lowrisc/opentitan/tree/3e32a31a2ba47298a1041913daa27e827b5068b0)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_otbn_smoketest --build-seed 2797157030 --fixed-seed (unknown) --waves fsdb

### Tests with similar or related failures

There are a few other tests that also do not have a signature on the dashboard.

- [x] chip_sw_edn_entropy_reqs
- [x] chip_sw_edn_entropy_reqs_jitter
- [x] chip_sw_entropy_src_csrng

**Comment by sriyerg** [comment] 2022-11-04 21:26
It should be the same error signature as this one:
```
Test chip_sw_otbn_ecdsa_op_irq_jitter_en has 3 failures.
0.chip_sw_otbn_ecdsa_op_irq_jitter_en.2715923446
Line 614, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_otbn_ecdsa_op_irq_jitter_en/latest/run.log

      Offending '$stable(edn_o[1].edn_bus)'
  UVM_ERROR @ 2336.252838 us: (edn.sv:121) [ASSERT FAILED] EdnDataStable_A
  UVM_INFO @ 2336.252838 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
```
Notice `...and 4 more tests`. These are the 4.

**Comment by msfschaffner** [comment] 2022-11-04 21:57
Oh I see. Let me link that as a potential duplicate then: [#16027](https://github.com/lowRISC/opentitan/issues/16027)

**Comment by msfschaffner** [comment] 2022-11-07 22:06
@moidx I think you added that part - WDYT?

**Comment by moidx** [comment] 2022-11-07 22:31
Is this because `LOG_ERROR` gets logged as a test bench error? If so, we can update it to `LOG_INFO`. I just wanted to have some feedback in the log from the otbn runtime to debug in other platforms.

**Comment by moidx** [comment] 2022-11-07 22:34
Also, which model is the `TODO` comment referring to? Is the error being observed something we should fix? I feel that TODO should at least point to an issue tracking the work required to get things to work.

**Comment by msfschaffner** [comment] 2022-11-07 22:37
> Is this because `LOG_ERROR` gets logged as a test bench error? If so, we can update it to `LOG_INFO`. I just wanted to have some feedback in the log from the otbn runtime to debug in other platforms.

That would work I think, yes. Let me propose a fix.

**Comment by msfschaffner** [comment] 2022-11-07 22:37
> Also, which model is the `TODO` comment referring to? Is the error being observed something we should fix? I feel that TODO should at least point to an issue tracking the work required to get things to work.

It's the OTBN C model. @GregAC probably knows better whether there already exists an issue for this that could be linked.

**Comment by johngt** [comment] 2022-11-08 12:47
@engdoreis although this is marked as resolved - the nightlies have not yet shown this passing. Another one to observe to see if failures are still being reported.

**Comment by msfschaffner** [comment] 2022-11-08 16:48
Ah this got auto-closed since it was linked in the PR - sorry about that. We can reopen it for observation.

**Comment by engdoreis** [comment] 2022-11-09 11:33
The test passed last regression, I'll watching and I'll close this issue when it passes 3 regressions.

**Comment by johngt** [comment] 2022-11-11 12:35
This has passed the last 3 nightlies, so closing out. @engdoreis 

|     | Tests                  |   2022-11-10 08:10:06 |   2022-11-09 08:04:06 |   2022-11-08 08:03:42 |   2022-11-07 08:08:10 |   2022-11-06 07:11:02 |   2022-11-05 07:11:23 |   2022-11-04 07:12:05 |   2022-11-03 07:11:23 |   2022-11-02 07:03:26 |   2022-11-01 07:10:18 | Suite             |
|----:|:-----------------------|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|:------------------|
| 129 | chip_sw_otbn_smoketest |                   100 |                   100 |                   100 |                     0 |                     0 |                     0 |                     0 |                     0 |                   100 |                   100 | chip_sw_smoketest |

**Closed by johngt** 2022-11-11 12:35 UTC
Labels: Component:TestTriage
