### ISSUE TITLE
[usbdev] Fix smoke test

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#10255] opened 2022-01-21 17:57 UTC
>estimate 160
>From https://github.com/lowRISC/opentitan/issues/10255#issuecomment-1481647000

**Comment by a-will** [comment] 2022-03-10 22:42
It's not so much "fix" as it is "implement": https://github.com/lowRISC/opentitan/blob/master/hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv#L12

(Plus adding "usbctrl" to the list of handled CSRs in the scoreboard.)

**Comment by michael-etzkorn** [comment] 2022-04-05 21:17
@a-will Is version one of `usbdev` purely CSR verification then? I'm new to OpenTitan, but I see no tests of USB functionality in the DV document so I'm wondering if there's any software tests or direct tests from the initial design work since I see `FEATURE_COMPLETE` for D2 is done. Presumably during design, there was initial work done on testing the features?

**Comment by a-will** [comment] 2022-04-05 21:29
> @a-will Is version one of `usbdev` purely CSR verification then? I'm new to OpenTitan, but I see no tests of USB functionality in the DV document so I'm wondering if there's any software tests or direct tests from the initial design work since I see `FEATURE_COMPLETE` for D2 is done. Presumably during design, there was initial work done on testing the features?

For the "DV simulation" target, it is only CSR verification. For the FPGA and verilator targets, we have a chip-level test that involves implementing a google simple-serial interface on top of the USB device and exercising it (checked in https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/usbdev_test.c ).

The targets all do their own peculiar thing for this usbdev chip-level test. On the verilator target, for example, stimulus is implemented directly in a DPI module at https://github.com/lowRISC/opentitan/tree/master/hw/dv/dpi/usbdpi

For usbdev DV, there is much work to be done.

**Comment by johngt** [comment] 2022-12-19 15:39
Tagging @alees24 for ref

**Comment by alees24** [comment] 2023-03-23 17:59
> estimate 160

**Comment by johngt** [comment] 2023-04-01 15:31
Given the large amount of effort estimate, tagging for discussion and breaking down into smaller tasks.

**Comment by johngt** [comment] 2023-06-05 13:44
@alees24 / @hcallahan-lowrisc - can you denote which parts of the smoketest / verification are still needed to assure ourselves that the block will work according to the use-cases we expect / know-of?
Main thing is to identify what work is still due for the next sprint close-off.

**Comment by moidx** [comment] 2023-06-15 15:59
Marking as complete as we decided to focus on implementing a smoke test for M2.5.{1,2}, and this is now integrated into the nightly regression.

**Closed by moidx** 2023-06-15 15:59 UTC
Labels: Component:DV, Type:Bug, Hotlist:Silicon, IP:usbdev, Milestone:V1, Triaged, Submilestone:M2.5.2
