### ISSUE TITLE
[pwrmgr] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21025] opened 2024-01-25 02:12 UTC
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by matutem** [comment] 2024-03-08 19:20
# pwrmgr V2(S) Signoff

This is not a focus area block.

## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
af85dad7af
$ git log Earlgrey-M2.5.2-RC0..af85dad7af --oneline -- hw/ip/pwrmgr hw/ip_templates/pwrmgr
```

- dd117372ca [doc,pwrmgr] Document wakeup signal requirements
  - Document-only clarification
- b16179dd74 [ipgen,rstmgr] Fix BUILD files
  - Change related to ipgen transition
- ab4b36f6b9 [ipgen,rstmgr] Fix paths to rstmgr in md files
  - Change related to rstmgr ipgen transition
- ce648ca68e [ipgen.pwrmgr] Change core files to vlnv naming and label as virtual
  - Fix related to pwrmgr ipgen transition
- 4a9a881d44 [topgen] Pass topname key/value pair to ipgen
  - Fix related to ipgen transition
- da087bbddd [rtl,pwrmgr] Fix escalation timeout persistence
  - Fixes RTL issue #20516 needed for PROD
- de31bdf1c2 [reggen] Remove the devmode input
  - devmode was tied to 1'b1 and the change is a net improvement with no functional impact
- 963a5006cc [doc] Minor tweak to md sanitisation code
  - Documentation-only change
- 748235cbb6 [dv,pwrmgr] Fix pwrmgr_escalation_timeout test
  - Fixes the test that verifies issue #20516
- 729f744642 [dv/pwrmgr] Add escalation_timeout test
  - Adds a test to verify #20516
- c87db05473 [pwrmgr,ipgen] Remove the hw/ip/pwrmgr and their autogen files
  - Change related to pwrmgr ipgen transition
- 7215f8d9cb [pwrmgr,ipgen] Fix hjson files
  - Change related to pwrmgr ipgen transition
- 78c7edd733 [pwrmgr,ipgen] Fix pwrmgr template and autogen core files
  - Change related to pwrmgr ipgen transition
- 988b584da3 [pwrmgr,ipgen] Fix BUILD files
  - Change related to pwrmgr ipgen transition
- 3f88a55120 [pwrmgr,ipgen] Generate pwrmgr ip_autogen files with topgen
  - Change related to pwrmgr ipgen transition
- 8034e000d6 [pwrmgr,ipgen] Turn a few more files into templates
  - Change related to pwrmgr ipgen transition
- a8529ce8a9 [pwrmgr,ipgen] Copy all hw/ip/pwrmgr files to ip_templates
  - Change related to pwrmgr ipgen transition
- c288cc3968 [pwrmge,ip_gen] Add tpldesc hjson file
  - Change related to pwrmgr ipgen transition
- 77278de68f [pwrmgr] Replace tab with spaces in test plan
  - hjson formatting change
- 709d4e7ca0 [doc/pwrmgr] Improve theory of operation doc
  - Documentation-only improvement
- 9e006e2554 [sival,pwrmgr] Add features in pwrmgr.hjson.tpl
  - Adds features needed for the sival flow
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
  - Fixes a bug on MuBi CSR RTL
- f4f5d98064 [dv/pwrmgr] Allow transitions to invalid fsm state
  - DV fix for SVA
- 59f8142826 [doc] Moved badges over to using hosted images
  - Documentation-only improvement
- 13c6152a0e [doc] pwrmgr registers and interfaces now use CMDGEN
  - Documentation-only improvement
- f7edbbb6a3 [pwrmgr,dv] Correct name of disabled assertion
  - DV fix for SVA
- 51d31a1aae [dv/pwrmgr] Complete SVAs for rom integrity checks
  - DV fix for SVA issue #18236
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
  - RTL fix for issue #15333
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
  - Reverts the change below
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
  - This change was reverted
- 9a61b02fe1 [pwrmgr] Fix xcelium compile error
  - Fix for xcelium, no functional change
- 143faa6be5 [pwrmgr] Synchronize lc signals
  - DV fix for SVA
- e47df29f3e [misc] Use lc_tx_t testing functions at endpoints
  - RTL cleanup that doesn't affect functionality

## Issues closed since the Earlgrey-ES tapeout

- https://github.com/lowRISC/opentitan/issues/21451 [chip-test, pwrmgr] chip_sw_pwrmgr_escalation_reset Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21450 [chip-test, pwrmgr] chip_sw_pwrmgr_b2b_sleep_reset_req Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21449 [chip-test, pwrmgr] chip_sw_pwrmgr_sleep_power_glitch_reset Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21448 [chip-test, pwrmgr] chip_sw_pwrmgr_deep_sleep_power_glitch_reset Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21447 [chip-test, pwrmgr] chip_sw_pwrmgr_random_sleep_power_glitch_reset Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21446 [chip-test, pwrmgr] chip_sw_pwrmgr_main_power_glitch_reset Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21445 [chip-test, pwrmgr] chip_sw_pwrmgr_aon_power_glitch_reset Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21444 [chip-test, pwrmgr] chip_sw_sensor_ctrl_deep_sleep_wake_up Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21443 [chip-test, pwrmgr] chip_sw_pwrmgr_normal_sleep_all_wake_ups Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21442 [chip-test, pwrmgr] chip_sw_pwrmgr_external_full_reset Component:ChipLevelTest IP:pwrmgr Priority:P2 SiVal:Autogen

- https://github.com/lowRISC/opentitan/issues/21026 [rstmgr] V2(S) Signoff Component:DV IP:rstmgr

- https://github.com/lowRISC/opentitan/issues/21024 [clkmgr] V2(S) Signoff Component:DV IP:clkmgr

- https://github.com/lowRISC/opentitan/issues/21014 [lc_ctrl] V2(S) Signoff Component:DV IP:lc_ctrl

- https://github.com/lowRISC/opentitan/issues/20991 [rstmgr] D2(S) Signoff Component:RTL IP:rstmgr

- https://github.com/lowRISC/opentitan/issues/20989 [clkmgr] D2(S) Signoff Component:RTL IP:clkmgr

- https://github.com/lowRISC/opentitan/issues/20979 [lc_ctrl] D2(S) Signoff Component:RTL IP:lc_ctrl

- https://github.com/lowRISC/opentitan/issues/20858 [doc,pwrmgr] Improve documentation of wakeup recording Component:Doc

- https://github.com/lowRISC/opentitan/issues/20700 [ip,doc] Fix inaccurate references to reset behavior Component:Doc Milestone:V3 Priority:P2

- https://github.com/lowRISC/opentitan/issues/20580 [sival,test] Flakiness in detecting PASS! in Rust test harnesses Component:ChipLevelTest Component:SiliconValidation Help Wanted Priority:P1 Type:Bug

- https://github.com/lowRISC/opentitan/issues/20516 [rtl,pwrmgr] escalation timeout should persist Component:RTL Component:Security Earlgrey-PROD Candidate IP:pwrmgr Priority:P1

- https://github.com/lowRISC/opentitan/issues/20415 [top_darjeeling] watch dog reset should be mapped to bit 0 Component:Darjeeling Component:DV Component:TestTriage

- https://github.com/lowRISC/opentitan/issues/20392 [sysrst_ctrl] Unable to reset OT Priority:P1

- https://github.com/lowRISC/opentitan/issues/20158 [dv,pwrmgr] Add test for escalation_timeout testpoint Component:DV Earlgrey-PROD Candidate

- https://github.com/lowRISC/opentitan/issues/20135 [chip-test] chip_sw_pwrmgr_random_sleep_all_reset_reqs Component:ChipLevelTest Component:SiliconValidation

- https://github.com/lowRISC/opentitan/issues/20134 [chip-test] chip_sw_pwrmgr_sleep_por_reset Component:ChipLevelTest Component:SiliconValidation

- https://github.com/lowRISC/opentitan/issues/20133 [chip-test] chip_sw_pwrmgr_deep_sleep_por_reset Component:ChipLevelTest Component:SiliconValidation

- https://github.com/lowRISC/opentitan/issues/20058 [chip-test] chip_sw_pwrmgr_random_sleep_all_wake_ups Component:ChipLevelTest

- https://github.com/lowRISC/opentitan/issues/19858 [chip-test] chip_sw_sysrst_ctrl_combo_reset Component:ChipLevelTest Component:SiliconValidation IP:sysrst_ctrl SiVal:BazelLinkNeeded SiVal:draft/WIP

- https://github.com/lowRISC/opentitan/issues/19819 [top_englishbreakfast,util] Fix paths to ip-specific ips in prepare_sw.py

- https://github.com/lowRISC/opentitan/issues/19403 [top_level,tests] Convert sim_dv sysrst_ctrl test to use opentitantool Component:ChipLevelTest Earlgrey-PROD Triaged

- https://github.com/lowRISC/opentitan/issues/19051 [pwrmgr/sram_ctrl] Use synchronizers on all LC signals IP:pwrmgr IP:sram_ctrl Priority:P1 Type:Bug

- https://github.com/lowRISC/opentitan/issues/18696 [test-triage] rom_e2e_* Component:ChipLevelTest Component:TestTriage

- https://github.com/lowRISC/opentitan/issues/18510 [i2c] Unexpected data in ACQ FIFO after deep sleep wakeup Earlgrey-PROD Candidate IP:i2c Priority:P2

- https://github.com/lowRISC/opentitan/issues/18341 [aon_timer, rtl/doc] No wakeup signalled on watchdog bite if it occurs before bark Component:Doc IP:aon_timer

- https://github.com/lowRISC/opentitan/issues/18236 [dv/pwrmgr] verify rom integrity check transitions Component:DV

- https://github.com/lowRISC/opentitan/issues/17085 [top_darjeeling] fake pinmux or direct connection Component:Darjeeling

- https://github.com/lowRISC/opentitan/issues/16960 [ci] Airgapped builds failing Component:CI Type:Bug

- https://github.com/lowRISC/opentitan/issues/16735 [pwrmgr] Potential improvement on escalation path to avoid crossing slow FSM Earlgrey-PROD Candidate Hotlist:Security IP:pwrmgr

- https://github.com/lowRISC/opentitan/issues/16689 [dv/cdc] Enable CDC instrumentation in all ips Component:DV Priority:P2 Triaging:MultipleBlocks

- https://github.com/lowRISC/opentitan/issues/16562 Flow error that dc is unsupported for job runtime extraction

- https://github.com/lowRISC/opentitan/issues/14867 [escalation / rma entry] Better cross handling in the future IP:alert_handler IP:lc_ctrl IP:pwrmgr Triaging:MultipleBlocks Type:FutureRelease

## Currently open issues

- https://github.com/lowRISC/opentitan/issues/21706 [sival,triag] Some SiVal ROM_EXT are broken

- https://github.com/lowRISC/opentitan/issues/21222 [chip-test] Incomplete SiVal Stage 1 and 2 tests
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/21083 [sival] test_locked_all_tests
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/21081 [sival] test_unlocked1_all_tests
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/21076 [sival] test_unlocked_all_tests
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/21075 [sival] raw_all_tests
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/21074 [sival] dev_all_tests
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/21025 [pwrmgr] V2(S) Signoff Component:DV IP:pwrmgr

- https://github.com/lowRISC/opentitan/issues/21012 [flash_ctrl] V2(S) Signoff Component:DV IP:flash_ctrl
  - This is unrelated, probably bad labelling
- https://github.com/lowRISC/opentitan/issues/20990 [pwrmgr] D2(S) Signoff Component:RTL IP:pwrmgr

- https://github.com/lowRISC/opentitan/issues/20983 [otp_ctrl] D2 Signoff Component:RTL IP:otp_ctrl
  - This is unrelated, bad labelling?
- https://github.com/lowRISC/opentitan/issues/20798 [sival,sensor_ctrl] Fix unexpected alert 5 Component:RTL Component:SiliconValidation
  - Unrelated to pwrmgr
- https://github.com/lowRISC/opentitan/issues/20518 [rtl,pwrmgr] escalation reset requests should not be delayed so much Component:RTL Component:Security Earlgrey-PROD Candidate IP:pwrmgr Priority:P2
  - To be done, has no counter-measure impact
- https://github.com/lowRISC/opentitan/issues/20194 [sival] prod_all_tests
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/19861 [chip-test] chip_sw_sysrst_ctrl_ulp_wakeup Component:ChipLevelTest Component:SiliconValidation IP:sysrst_ctrl SiVal:BazelLinkNeeded SiVal:draft/WIP
  - Does not affect pwrmgr
- https://github.com/lowRISC/opentitan/issues/19810 [doc,dif] Fix link in dif header files
  - Documentation-only
- https://github.com/lowRISC/opentitan/issues/19797 [bazel, dvsim] Convert dvsim-executed tests to the new rules Earlgrey-PROD Triaged Priority:P1 SW:Build System Type:Task
  - All pwrmgrs tests are done
- https://github.com/lowRISC/opentitan/issues/19124 [pwrmgr] Error FSM state is not observable in pwrmgr_fsm Earlgrey-PROD Candidate Priority:P2
  - There is an alternative way to implement the assertion for formal.
- https://github.com/lowRISC/opentitan/issues/19059 [aon_timer] Consider requirements for clk_aon_i vs clk_i Earlgrey-PROD Candidate IP:aon_timer Priority:P2 Type:FutureRelease
  - It has no impact on pwrmgr
- https://github.com/lowRISC/opentitan/issues/18513 [doc] AON Timer wdog bite reset missing sw initialization documentation Earlgrey-PROD Candidate
  - Documentation-only issue.
- https://github.com/lowRISC/opentitan/issues/17086 [dv/mem_bkdr_util] Improve memory write performance Component:DV Earlgrey-PROD Candidate Type:Icebox
  - No impact on D/V2(S)
- https://github.com/lowRISC/opentitan/issues/16636 [chip-test] Move C tests without external host from tests/sim_dv/ to tests/ Component:ChipLevelTest Earlgrey-PROD Triaged IP:alert_handler IP:csrng IP:entropy_src IP:flash_ctrl IP:lc_ctrl IP:otp_ctrl IP:pwrmgr IP:sram_ctrl Priority:P3 Subsystem:Entropy Triaging:MultipleBlocks Type:Enhancement
  - pwrmgr tests are done
- https://github.com/lowRISC/opentitan/issues/16148 [dv/rstmgr] Apply different reset kinds where applicable Component:DV Earlgrey-PROD Candidate IP:rstmgr Priority:P2
  - It does not apply to pwrmgr
- https://github.com/lowRISC/opentitan/issues/15986 [rtl,reset] Improve handling of main domain power glitches Component:DV Component:RTL Earlgrey-PROD Triaged IP:ast IP:pwrmgr IP:rstmgr Type:FutureRelease
  - This is not staged for PROD
- https://github.com/lowRISC/opentitan/issues/14887 [chip/prim_esc_receiver] check if prim_esc_receiver is out-of-sync Component:DV Earlgrey-PROD Candidate IP:alert_handler IP:prim IP:pwrmgr Priority:P2 TOP:earlgrey
  - I think this should not block D/V2(S)
- https://github.com/lowRISC/opentitan/issues/12848 [top/doc] Autogenerated tables for top-specific IP Component:Doc Earlgrey-PROD Triaged IP:alert_handler IP:clkmgr IP:pinmux IP:pwrmgr IP:rstmgr IP:rv_plic Triaging:MultipleBlocks Type:Cleanup Type:FutureRelease Type:Icebox
  - Documentation-only issue
- https://github.com/lowRISC/opentitan/issues/11520 [dv/exclusions] Change handling of full-chip exclusions Component:DV Earlgrey-PROD Candidate IP:clkmgr IP:pwrmgr IP:rstmgr Priority:P3
  - Not a D/V2(S) issue
- https://github.com/lowRISC/opentitan/issues/10323 [rom_ext] Possibly check ROM digest against a known value? Component:Software Earlgrey-PROD Triaged Priority:P3 SW:ROM_EXT
  - No impact on pwrmgr, since it only looks at the result of the checks as reported by rom_ctrl
- https://github.com/lowRISC/opentitan/issues/9206 [top, doc] Top level documentation for keymgr seed flow Component:Doc Earlgrey-PROD Triaged IP:flash_ctrl IP:keymgr IP:lc_ctrl IP:otp_ctrl IP:pwrmgr Priority:P4 TOP:earlgrey Triaging:MultipleBlocks
  - Documentation-only issue
- https://github.com/lowRISC/opentitan/issues/8440 [tracking] Use ipgen to produce templated IPs Component:Tooling Earlgrey-PROD Candidate IP:clkmgr IP:flash_ctrl IP:pwrmgr IP:rstmgr Priority:P2 Triaging:MultipleBlocks Type:Cleanup
  - The pwrmgr part of this is done
- https://github.com/lowRISC/opentitan/issues/7978 [ast] Make ast a comportable module or at least a comportable front-end Component:RTL Earlgrey-PROD Triaged IP:ast Priority:P2 Type:FutureRelease
  - Not pwrmgr related
- https://github.com/lowRISC/opentitan/issues/7612 [pwrmgr] Documentation update Component:Doc Earlgrey-PROD Triaged IP:pwrmgr Priority:P3 Type:Task
  - Documentation-only
- https://github.com/lowRISC/opentitan/issues/3353 [flash_ctrl] TODO list for open source portion of flash controller Component:RTL Earlgrey-PROD Candidate IP:flash_ctrl Priority:P2 Type:Task
  - Not pwrmgr related
- https://github.com/lowRISC/opentitan/issues/2083 [topgen] topgen flow Component:MultiTop Component:Tooling Earlgrey-PROD Triaged Priority:P3 TOP:earlgrey Type:FutureRelease
  - Not staged for PROD

**Comment by andreaskurth** [comment] 2024-03-19 15:41
@matutem's currently working on improving the failing nightly regressions, because pwrmgr at this point doesn't fulfill V2 requirements. We'll revisit this on Thu and may decide to postpone to M4.

**Comment by matutem** [comment] 2024-03-20 01:08
The expectation is that https://github.com/lowRISC/opentitan/pull/22120 will take all tests above 90% passing.

**Comment by matutem** [comment] 2024-03-20 18:45
Closing this since all pending items are done. The block version 1.0.0 is already at V2S.

**Comment by matutem** [comment] 2024-03-20 18:46
Closing this since all pending items are done. The block version 1.0.0 is already at V2S.

**Closed by matutem** 2024-03-20 18:46 UTC
Labels: Component:DV, IP:pwrmgr
