### ISSUE TITLE
[test-triage] chip_sw_entropy_src_fuse_en_fw_read_test

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#14840] opened 2022-09-08 21:01 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

  UVM_ERROR @ 3796.860552 us: (sw_logger_if.sv:521) [entropy_src_fuse_en_fw_read_test_prog_sim_dv(sw/device/tests/sim_dv/entropy_src_fuse_en_fw_read_test.c:66)] DIF-fail: dif_entropy_src_configure(entropy_src, config, kDifToggleEnabled) returns 3

A return value of 3 most likely means regwen is 0.

### Steps to Reproduce

- Commit hash: https://github.com/lowrisc/opentitan/tree/b73727cd502c1a66545c7f84d7861a1474342963
- ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_entropy_src_fuse_en_fw_read_test --fixed-seed 897575948 --build-seed 2341666946 --waves -v h

Notice all three seeds run failed the same way.

**Comment by johngt** [comment] 2022-09-13 16:13
@moidx - I see that you have self-assigned. We think that one of our engineers - @abdullahvarici could start looking into this. If it is something you want to continue to work on please just respond saying so, otherwise please feel free to reassign to @abdullahvarici to look into this week.

**Comment by moidx** [comment] 2022-09-13 16:52
Thanks @johngt, reassigned the issue.

**Comment by abdullahvarici** [comment] 2022-09-16 15:07
Root cause found. The bug fixed and tested OK. PR#14976 opened.

**Comment by engdoreis** [comment] 2022-09-30 10:23
Closing this issue as it seems healthy.
Tests | latest | 2022.09.28 | 2022.09.27 | 2022.09.26/1 | 2022.09.26/2 | 2022.09.24 | 2022.09.23 | 2022.09.22/1 | 2022.09.22/2 |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
chip_sw_entropy_src_fuse_en_fw_read_test | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 |

**Closed by engdoreis** 2022-09-30 10:23 UTC
Labels: Component:TestTriage
