### ISSUE TITLE
[sw/rtl] Desired debug behaviour with breakpoints and interrupts

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#15051] opened 2022-09-21 15:40 UTC
Whilst trialing usage of rv_dm with Ibex I've discovered potentially odd behaviour around breakpoints and interrupts. I had a breakpoint set on a particular line and found that every time I continued I just went straight back to the breakpoint without executing anything further. At first I thought this was a bug then I tried single stepping and ended up in a timer interrupt handler.

What I was running had a timer interrupt setup to fire periodically so when you hit the breakpoint unless you continued quickly next time you continued the timer had expired so we went into the timer interrupt, serviced that and then went straight back to the breakpoint.

In the RISC-V debug spec the hardware trigger points (which provide hardware breakpoints) are recommended to trigger before the instruction they trigger on has executed. So what I was seeing was correct behaviour. We haven't executed the instruction at the breakpoint, we continue and immediately take an interrupt, execute all of that and jump back to the instruction with the breakpoint to execute it (at which point we hit the breakpoint again).

Note that interrupts are entirely disabled whilst we're in debug mode but that ceases when we exit debug mode via executing `dret`. The IRQ is then unmasked so we enter the handler before we can execute the breakpointed instruction (which would otherwise have been the next instruction after the `dret`).

Whilst this was surprising (to me) behaviour initially it does look to be the correct behaviour. Though I can see how it may annoy/frustrate debugging efforts.

I'd like to gather opinions on this behaviour and if we feel we should do something different, though I'm not sure what that would be. One fix would be to ensure the instruction following a `dret` gets executed regardless of interrupts though I think that would be confusing in other ways plus a likely violation of the RISC-V specification:

> These conditions for an interrupt trap to occur must be evaluated in a bounded amount of time from when an interrupt becomes, or ceases to be, pending in mip, and must also be evaluated immediately following the execution of an x RET instruction or an explicit write to a CSR on which these interrupt trap conditions expressly depend (including mip, mie, mstatus, and mideleg)

From https://github.com/riscv/riscv-isa-manual/releases/download/Priv-v1.12/riscv-privileged-20211203.pdf Section 3.1.9

Perhaps this is simply a hazard of debugging the system when timer interrupts are enabled programmers need to be aware of and deal with appropriately (e.g. having some way to prevent the timer getting re-armed when you're doing debug work it messes with)?

**Comment by GregAC** [comment] 2022-09-21 15:41
@tjaychen @msfschaffner @mundaym @alphan @arunthomas @cfrantz @a-will any thoughts?

**Comment by alphan** [comment] 2022-09-21 15:46
@dmcardle

**Comment by alphan** [comment] 2022-09-21 15:49
@GregAC thanks for creating this issue. Can you confirm that you were trying to debug `rom` (not `test_rom`) and the thing that was being triggered was the watchdog NMI, at roughly 1 s)? If so, this is by design and the first thing that should be done during a debugging session should be to disable interrupts (see #15024).

**Comment by a-will** [comment] 2022-09-21 15:59
The rv_dm is supposed to follow the riscv-debug-spec, right? In that spec, it says that all interrupts should be masked upon entering debug mode in section 4.1.

**Comment by tjaychen** [comment] 2022-09-21 16:01
> The rv_dm is supposed to follow the riscv-debug-spec, right? In that spec, it says that all interrupts should be masked (including NMI) upon entering debug mode in section 4.1.

i think the issue is that when we run again (exiting debug), we immediately jump into the interrupt handler and later return to the same place, which break points again.

**Comment by tjaychen** [comment] 2022-09-21 16:03
> The rv_dm is supposed to follow the riscv-debug-spec, right? In that spec, it says that all interrupts should be masked (including NMI) upon entering debug mode in section 4.1.
> 
> Edit: Oh, but you did a continue right away? I'd probably suggest implementing that as a single-step (in debug mode) + resume.

yeah that seems reasonable..so instead of just resuming from the same place. As Greg says this feels like correct behavior to me. So either we disable the interrupt, so I guess in most cases, we would probably execute the instruction we broke on (or jump somewhere else) and continue.

**Comment by GregAC** [comment] 2022-09-21 16:04
> > The rv_dm is supposed to follow the riscv-debug-spec, right? In that spec, it says that all interrupts should be masked (including NMI) upon entering debug mode in section 4.1.
> 
> i think the issue is that when we run again (exiting debug), we immediately jump into the interrupt handler and later return to the same place, which break points again.

Exactly, interrupts are masked when we enter debug mode. The issue is they become unmasked on a `dret` and the IRQ then takes priority over executing the next instruction pointed to by `depc` (which in this case in the instruction that has a hardware breakpoint set) and the RISC-V privileged requires this behaviour.

**Comment by GregAC** [comment] 2022-09-21 16:10
> > Edit: Oh, but you did a continue right away? I'd probably suggest implementing that as a single-step (in debug mode) + resume.
> 
> You'll see the same issue with the single step as the next instruction out of debug mode will be the first instruction of the interrupt handler so you'll single step that.

This is incorrect, RISC-V debug spec defines a control bit that allows you to say whether or not interrupts should be handled during single stepping, for Ibex this bit is hard-wired to 0. Whether or not this actually behaves correctly is another question, I'm looking at that now.

**Comment by GregAC** [comment] 2022-09-21 16:14
Yes so a bit of a false alarm here. Though it does appear that ibex is servicing interrupts when single stepping which it shouldn't do. I will sort out a fix and review whether our current DV setup would have caught this (the single step test is currently failing in nightly regressions and we had yet to take a detailed look).

**Comment by GregAC** [comment] 2022-09-21 16:40
Ibex issue here to track the fix: https://github.com/lowRISC/ibex/issues/1814 should be pretty straight forward

**Comment by msfschaffner** [comment] 2022-10-28 15:58
Fixed - closing!

**Closed by msfschaffner** 2022-10-28 15:58 UTC
