### ISSUE TITLE
[chip-test] chip_sw_sram_lc_escalation

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15970] opened 2022-11-03 05:28 UTC
### Test point name

[chip_sw_sram_lc_escalation](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson;l=2553?q=chip_sw_sram_lc_escalation&ss=opentitan%2Fopentitan:hw%2F)

### Contact person

@matutem @tjaychen

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by weicaiyang** [comment] 2022-11-03 05:29
AIs from the last DV meeting for this test

- [ ] [matute] Enhance all_escalation to read any location of the sram and expect it returns all 0s due to lc_esc
- [ ] [matute] update sw_data_integrity to test both sram

**Comment by matutem** [comment] 2022-11-04 17:46
I just got very busy with the recent change in reset domains. Here is what is missing from this issue:
-[] Cross reference chip_sw_sram_lc_escalation to both chip_sw_all_escalation_resets and chip_sw_data_integrity
As for the pending issues above, checks are okay for the main_sram now, so only ret_sram is missing: the all_escalation test needs to read from ret_sram before incrementing the nmi_interrupt count when the fault was injected into ret_sram, and expect the nmi_interrupt count for ret_sram to be zero since the nmi CSR should not complete due to the attempted read.

**Comment by johngt** [comment] 2022-11-08 13:03
@engdoreis. The draft PR might also assist with chip_sw_all_escalation_resets that is mentioned by @matutem above. If not we will likely need a new separate issue for dealing with the regression found in the test highlighted.

**Comment by msfschaffner** [comment] 2022-11-08 15:59
@johngt I believe we just fixed the issue for `chip_sw_all_escalation_resets` in a separate pull request here (unless there has been another regression): https://github.com/lowRISC/opentitan/pull/16106

The draft PR above is only for an extension of the `chip_sw_all_escalation_resets` and `chip_sw_data_integrity` tests.

**Comment by engdoreis** [comment] 2022-11-09 09:36
This test `chip_sw_sram_lc_escalation` is linked to `chip_sw_all_escalation_resets` in the testplan, which passed in the last regression due to https://github.com/lowRISC/opentitan/pull/16106 I assume.
So I'll keep this issue opened until the test pass 3 regressions in a row.

**Comment by msfschaffner** [comment] 2022-11-16 03:37
Quick note: I am extending the all escalations test in #16380 and noted that while the SRAM controller correctly returns bus errors when it has escalated locally, Ibex does not read back 0xFFFFFFFF. From looking at the waves, this is not because the SRAM controller does not return 0xFFFFFFFF on bus errors (in fact it does), but because the Ibex LSU prevents writes from being committed to the register file when a bus error has occurred. 

I think this is correct architectural behavior, so we may want to relax the check to just make sure a bus error is seen, instead of checking for 0xFFFFFFFF in the test program.

CC @GregAC @tjaychen

**Comment by msfschaffner** [comment] 2022-11-16 19:02
The action items have now all been resolved, so we can close this issue.

**Closed by msfschaffner** 2022-11-16 19:02 UTC
Labels: Component:ChipLevelTest
