### ISSUE TITLE
[otbn] Correct model for handling staggered rma_req_i transitions

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#20835] opened 2024-01-15 13:45 UTC
### Description

If the RMA signal (`lc_rma_req_i`) has an invalid value, this can cause OTBN to go into a locked state. I think the intention was that any value except for `MuBi4True` would be treated as `MuBi4False`.

The lock happens because the start/stop control sees its `rma_req_i` signal get an invalid value. This gets mirrored to `rma_ack_d`, then `rma_ack_q`. But the invalid contents of `rma_ack_q` then cause the state to go to `OtbnStartStopStateLocked`.

To see this going wrong, run
```
  util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_escalate --fixed-seed=2
```
with the current head of the integrated-dev branch (df396017ee).

I suspect a correct fix would be to weaken the check for invalid `rma_ack_q` that's currently on line 373 in that file.

**Comment by vogelpi** [comment] 2024-01-18 23:13
Thanks for filing the issue @rswarbrick and providing the details to reproduce this.

With this particular seed we are "lucky" and the invalid `rma_req_i` arrives at the start stop control exactly when we finish the secure wipe. This is the only time when `rma_ack_d/q` are driven by this signal. In practice, any `rma_req_i` will have fully stabilized at that point because only the valid ON encoding of `rma_req_i` initiates the secure wipe. This is documented in the start stop controller:
https://github.com/lowRISC/opentitan/blob/integrated_dev/hw/ip/otbn/rtl/otbn_start_stop_control.sv#L358

Since we would like to have exactly this behavior, otherwise multiple glitches in `rma_ack_q` while the secure wipe is still going on can trigger the RMA entry early, I am wondering if it would be feasible to modify the model instead?

**Comment by vogelpi** [comment] 2024-01-18 23:16
For reference, here is the PR where I changed this: https://github.com/lowRISC/opentitan-integrated/pull/381

**Comment by rswarbrick** [comment] 2024-01-19 10:57
I think modifying the model is almost certainly the right solution. I'm not completely certain I've got the "correct behaviour" straight in my head, though. Do we just need to modify the model to lock if `rma_req_i` happens to be invalid on the cycle when we're finishing a secure wipe?

**Comment by vogelpi** [comment] 2024-01-19 11:03
Yes, I think you're right :-) It's when the start stop controller is in the `OtbnStartStopSecureWipeComplete` state.

**Comment by vogelpi** [comment] 2024-02-09 10:40
Hey @rswarbrick , I've now filed a PR #21272 that carries the critical change over to `master`. We absolutely need this for the production TO. Would you be fine to take care of the model changes please? I don't think it's high priority though. I am labeling this as M4.

**Comment by moidx** [comment] 2024-06-10 16:49
We have rma entry coverage at TLT level. This is still a high priority for M5. Updating to P1 and moving to `Earlgrey-PROD.M5`

**Closed** 2024-07-10 14:16 UTC
Labels: Component:DV, IP:otbn, Earlgrey-PROD Candidate
