### ISSUE TITLE
[mask_rom] Securely build DV-specific images

### ISSUE THREAD

**Issue by lenary** [lowRISC/opentitan#3563] opened 2020-09-23 16:25 UTC
In #3440, @tjaychen and @sriyerg raised the issue of wanting to use `sw/device/mask_rom` as the first boot stage for DV, but wanted a way to disable the RSA check.

@gkelly and I are unwilling to have an `if (device == DV)` codepath in the production mask rom images, as this is way more dangerous than we are happy with. We also cannot use an `#ifdef` as this is not how our compilation flows are currently set up.

In the short term, `sw/device/boot_rom` will still exist, which does not do any image verification or the like. However, we would like to get rid of that.

The longer-term solution is that we can substitute out the implementations of the functions defined in `sw/device/mask_rom/sig_verify.h` (much as we already provide a few different implementations of files like `test_coverage_{llvm,none}.c` for `test_coverage.h`). And then at meson-configuration time, we choose the implementation we plan on using. This might also nicely solve the issue of managing a transition from software-implemented verification routines to hardware-assisted verification routines.

We should remember we can take this approach in more places if we need to, though we might want to be more principled about how we do so in future, and have clearer guidance for when that's helpful.

**Comment by alphan** [comment] 2020-09-23 16:34
Thanks for creating this issue @lenary, sounds good.

**Comment by moidx** [comment] 2021-09-28 16:45
Marking as duplicate of #264.

**Closed by moidx** 2021-09-28 16:45 UTC
Labels: Component:Mask ROM
