### ISSUE TITLE
[i2c,dv] Failing block level DV tests as a result of changes.

### ISSUE THREAD

**Issue by alees24** [lowRISC/opentitan#21755] opened 2024-02-29 12:38 UTC
### Description

This issue tracks the state of block level I2C tests, broken or made less reliable by DD work for prod.

Probably failing/unreliable already:

i2c_target_stress_all_with_rand_reset

PR [#21621](https://github.com/lowRISC/opentitan/pull/21621) at this time is thought to be responsible for breaking the following:

- i2c_host_fifo_reset_fmt
- i2c_host_fifo_watermark
- i2c_target_smoke
- i2c_target_stress_rd

Others:

- i2c_intr_test : cip_base_vseq needs 'run_intr_test' changes. (PR #21804)
- cip_base_vseq also requires a change to 'clear_all_interrupts' which is still pending merge and will cause a number of other vseqs to fail, unless it or the final commit of PR #21621 is present.

**Comment by andreaskurth** [comment] 2024-03-01 13:51
`i2c_host_fifo_watermark` is another victim, I think. It passes before the merge of #21755 but fails after (seed `9596103540527566890202921826073542621372745652001006134958711591620971245237` on VCS T-2022.06-SP2). I added it to the list.

**Comment by andreaskurth** [comment] 2024-03-01 13:59
`i2c_target_stress_rd` as well: it passes before the merge of #21621 but fails after (seed `1123967404029634992796962205584092120176243998109053670291080899048047786851` on VCS T-2022.06-SP2). This test simply extends `i2c_target_smoke`, which may explain why it fails as well.

Added to the list.

**Comment by a-will** [comment] 2024-05-04 04:05
These all seem to be passing now--I fixed up several of these along the way.

We're not at 100% at this point, though:

- i2c_csr_bit_bash overflows FIFOs and triggers assertions inside the newer FIFO RTL
- i2c_host_perf has a bizarre calculation for speed that gets affected by stretching that randomly occurs
- i2c_target_unexp_stop appears to not generate correct stimulus
- i2c_target_perf generates incorrect stimulus, with SDA and SCL switching simultaneously
- i2c_target_stretch I haven't looked at

**Comment by hcallahan-lowrisc** [comment] 2024-05-13 10:30
Moving tracked effort from this issue to #23077

**Comment by moidx** [comment] 2024-06-11 21:21
Discussed moving as P1 to M5 due to RTL risk analysis performed during last issue triage.

**Comment by hcallahan-lowrisc** [comment] 2024-07-05 14:40
This PR doesn't really accurately represent the state of the I2C regressions anymore. Hence I'm going to close it.

**Closed by hcallahan-lowrisc** 2024-07-05 14:40 UTC
Labels: Component:DV, IP:i2c
