### ISSUE TITLE
[rom_ctrl] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20997] opened 2024-01-25 01:22 UTC
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by msfschaffner** [comment] 2024-02-09 02:00
Changes since ES tapeout include misc changes in docs, general reggen improvements. 
The only notable change in functionality was the removal of the S&P layer, which is already fully modeled and tested in DV.
No TODOs have been added to the code.
The currently claimed design stage D3 is hence still fulfilled.

```
$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/gpio

c721c51c13 [rtl, prim] Add 'commit' functionality to prim_count
fc8484601e [reggen,hw] Create index parameter for registers windows
de31bdf1c2 [reggen] Remove the devmode input
b6d376bc56 [dv] Fix timeout in rom_ctrl stress tests
803d9aec77 [prim, rom_ctrl] Remove S&P layer from data scrambling
f9af60328d [rom_ctrl,sival] Add a list of testable features to rom_ctrl.hjson
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
2ff1f6fbae [doc] rom_ctrl registers and interfaces now use CMDGEN
d67e35d864 [reggen] Generate constants for only the main block
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
```

**Comment by msfschaffner** [comment] 2024-02-12 22:40
@rswarbrick can you take a look at this issue and close if you agree that D2S is still fulfilled?

**Comment by rswarbrick** [comment] 2024-02-13 10:49
I've just looked through closely. Yes, I believe everything meets D2S.

I think the "D3" above was a typo? (There have been changes to the RTL and I don't have access to a CDC tool, so I can't be certain that the "Lint/CDC clean" item is satisfied)

**Comment by msfschaffner** [comment] 2024-02-13 17:06
I mentioned D3 since that is what the Hjson currently says:
https://github.com/lowRISC/opentitan/blob/81d581d6597132e0ec2201e595cc28d88bab9d0c/hw/ip/rom_ctrl/data/rom_ctrl.hjson#L20-L28

AscentLint was clean last time I checked:
![image](https://github.com/lowRISC/opentitan/assets/41358501/f079c3ad-4a82-4075-81f1-412cad819d0c)

For CDC/RDC we're still not able to sign this off at the block-level, so `No block-level flow available - waived to top-level signoff.` is still accurate.

**Comment by rswarbrick** [comment] 2024-02-14 09:24
Ah cool, that makes sense. Thanks!

**Comment by andreaskurth** [comment] 2024-03-14 08:41
PR https://github.com/lowRISC/opentitan/pull/21992 got merged after this sign-off, so I'm reopening this issue for a quick reassessment.

**Comment by msfschaffner** [comment] 2024-03-14 18:52
PR https://github.com/lowRISC/opentitan/pull/21992 switched the ROM size definition to a mechanism that is overridable from the top-level hjson, similarly how this is done for SRAM_CTRL. It does not change the functionality, nor the size used inside top_earlgrey. It did however add two configurations (32kB and 64kB) to the block-level regressions, since these are the two common sizes used by Earlgrey and Darjeeling.

I don't think this should impact the D* status, however, we should take a look at the coverage and pass rates on the DV side.
Hence, it probably makes sense to close this and reopen the V2S signoff instead.

**Comment by andreaskurth** [comment] 2024-03-31 14:26
Okay, since #21992 did not change functionality, we can keep rom_ctrl signed off at D2S. Regression results are still at V2 level as well. :+1:

**Closed by andreaskurth** 2024-03-31 14:26 UTC
Labels: Component:RTL, IP:rom_ctrl
