### ISSUE TITLE
[aes:rtl] AES produces wrong result when data is interleaved with key

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#2913] opened 2020-07-21 15:33 UTC
Hi Pirmin

I am seeing error when I interleave the data_in and key (also if I throw in IV but I am trying to go as simple as possible for debugging purposes)

I am seeing the issue on both xcelium and VCS.
to reproduce
checkout my aes_alert_dv branch
and run the aes_sanity_test with seed 1322140672

for the puposes of this problem it only produces one message of 16 bytes 
the following is fixed
data_in
key
key_len ( 256)
Mode (ecb)

the reference model produce the expected output 
the current input is
![image](https://user-images.githubusercontent.com/53917183/88074444-b5364180-cb77-11ea-9090-e7a4fdde0a28.png)

My best guess is that the DUT starts prematurely when data is received before all key is received.

**Comment by vogelpi** [comment] 2020-07-21 21:26
Hi Rasmus,

thanks for opening the issue and for providing the details. I see the problem and your guess is right: The cipher core is started based on the last write to the initial key registers. But that is one cycle too early as the key registers output the valid key one cycle later.

This is already solved on the main branch: I reworked the tracking of the IV and key registers in 29472e785947601e90d81df62072fcbfe736f0aa . Once you rebase your dev branch on #2152 the problem is solved. You don't necessarily need to do this now. My hope is that #2377 is merged later today and then we can get #2152 in and stop the rebasing on dev branches/PRs again.

Best,
Pirmin

**Comment by rasmus-madsen** [comment] 2020-07-24 09:56
@vogelpi the rebase solved some but not all issues.
I am still seeing the DUT starting operations before all key has been written.
the key register is neither all clean or all written as you can see here
![image](https://user-images.githubusercontent.com/53917183/88379848-e1360a80-cda3-11ea-9325-30243c89ab3c.png)

to recreate this issue pull my aes_alert_dv branch
and run aes_sanity_test with seed 2904956674

the test is simple.
it is running two messages with the options shown below 
length, IV, key_len, and data are fixed i.e the same for both items.
and to simplify debugging the IV is 0. 
![image](https://user-images.githubusercontent.com/53917183/88380201-66212400-cda4-11ea-895c-aa2f42de7eb0.png)

**Comment by vogelpi** [comment] 2020-07-24 16:09
Thanks @rasmus-madsen for the detailed bug report. There were two problems that I needed to fix:
1. It wasn't signaled to the status tracking of the key registers when the key was used for encryption. The module thought that once the key was written fully, it remained clean.
2. After the IV was updated internally in CTR mode, a subsequent write by software (when the module was idle again) did not make the IV dirty. This allowed for partial IV updates by software.

To conclude, these were two bugs that I would not have been able to find without proper DV. Thanks for your work Rasmus! I have pushed a fix for this in #2971 .

**Comment by rasmus-madsen** [comment] 2020-07-28 19:22
@vogelpi this issue can still be produced. when relaxing constraints further
running 
aes_stress with seed =3346499878 (vcs)
in message item 3 the DUT is configured as the following
![image](https://user-images.githubusercontent.com/53917183/88711293-44af9780-d118-11ea-9598-6c6568639d05.png)

and it from the wave you can see that it starts the operation before the last IV is written
![image](https://user-images.githubusercontent.com/53917183/88711229-28abf600-d118-11ea-83ef-5bd3f80c3560.png)

to run this test checkout my aes_alert_dv branch which has been sync'ed with master

**Comment by vogelpi** [comment] 2020-07-29 11:00
Thanks @rasmus-madsen for the detailed report. I could reproduce the behaviour.

The following is happening:
1. The test performs encryption/decryption in ECB mode. ECB mode does not need an IV but the test still provides one (there is nothing wrong with that). Since the IV is never used, it is not marked as "hot". It remains "clean" and "new".
2. The mode is switched from ECB to CTR. CTR mode needs an IV. Since the currently available IV is still "clean" and "new" the unit starts whenever data becomes available (no matter if a complete or just a partial IV is provided after the mode switch). In this particular test case, it just gets a partial IV update because the input data is available before the complete IV is updated.

The same is actually also true for the key register. 

So far, we did not specify how switches of mode (ECB, CTR, CBC), operation (ENC/DEC), and key length should be handled (we just assumed the data would be provided last when starting a new message). I see two options:
1. Whenever the configuration register is written, we declare the IV and key as **hot**. This will prevent partial updates after a mode/operation/key length switch.
2. Whenever the configuration register is written, we **clear the status tracking** for the IV and key register. Software will have to provide a complete new key and IV to start the message. This is seems the better option as it prevents someone using the previous key/IV in a less secure mode.

I will probably go with option 2. Note however that this is not equal to clearing the registers with random data. This could also be triggered upon a mode/operation/key length switch automatically. But I think it's something that should be initiated by software when handling the device over to another user only. I would be interested to also get @cdgori 's opinion here.

**Comment by rasmus-madsen** [comment] 2020-07-29 11:11
@vogelpi interesting corner case. you are probably correct in your assumption - most if not all users will probably write data last. 
But since we allow a different order option two seem like the better choice as you also point out.

**Comment by cdgori** [comment] 2020-07-29 18:07
Great corner case.  I also think option 2 is the way to go.

**Comment by vogelpi** [comment] 2020-08-03 13:51
I am closing this issue as the corresponding fix has been merged.

**Closed by vogelpi** 2020-08-03 13:51 UTC
Labels: Component:DV, Component:RTL
