### ISSUE TITLE
[hmac, rtl] Fix switching between different digest-sized streams

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#23181] opened 2024-05-17 16:32 UTC
### Description

There is currently an issue when we  switch between streams with different digest sizes, caused by the gating behavior. Creating this issue so that we can keep track of it. The previous issue #23014 is closed.

More context:
https://github.com/lowRISC/opentitan/issues/23014#issuecomment-2100595419
https://github.com/lowRISC/opentitan/issues/23014#issuecomment-2100834695

An ugly workaround would be to run a dummy operation in-between two streams to set the digest size to the correct value. 

cc: @gdessouky @martin-velay  @andreaskurth

**Comment by andreaskurth** [comment] 2024-05-20 06:15
Thanks for flagging this, @ballifatih. Will you look into fixing this together with @gdessouky or should I take a look as well?

**Comment by gdessouky** [comment] 2024-05-20 08:00
Thanks @ballifatih and @andreaskurth, we've discussed this offline and in the other original issue, I'll be pushing RTL fixes for this and exposing the Idle status https://github.com/lowRISC/opentitan/issues/22916 in the next 1-2 days. I've had a difficult PR in progress with a lot of DV fixes for synchronization in the scoreboard for this issue https://github.com/lowRISC/opentitan/issues/22578, I'll push it tonight and then prioritize these RTL changes next.

**Comment by andreaskurth** [comment] 2024-05-21 14:00
@ballifatih and @gdessouky: I may have missed or forgotten something, but is an RTL fix needed even if SW sets `CFG.sha_en` to zero before setting the digest size to the new value?

**Comment by ballifatih** [comment] 2024-05-21 14:25
After having another look, I couldn't identify the problem again. It seems to me there is no problem as long as SW follows the sequence during context saving:

* SW reads context registers
* SW deasserts sha_en
* SW clears/wipes context

and later during context restoring:
* SW writes the context registers
* SW asserts sha_en
* SW issues continue or start

Maybe I had the wrong assumption that `sha_en` comes after issuing start or continue.

Maybe a TODO for me is to try this as a simple test on top of the driver to see if I can produce this potential issue.

**Comment by gdessouky** [comment] 2024-05-21 15:22
when SW writes to the context registers and it has not asserted `sha_en`, this is when these intermediate digests are fed into the SHA-2 engine. These, however, will not get captured properly because the HMAC has not been started (`hash_start` triggered) yet with the new configuration; thus the old configuration is still preserved until HMAC is successfully started. I was now implementing a change in the RTL that captures from reg2hw irrespective of whether the HMAC has been started, for @ballifatih to test.

**Comment by andreaskurth** [comment] 2024-05-24 15:36
@gdessouky and @ballifatih please update this with your findings from the test. AFAIU no RTL problem and thus no fix required at this time

**Comment by gdessouky** [comment] 2024-05-26 07:39
I had already pushed a minor rework in the HMAC RTL (see https://github.com/lowRISC/opentitan/pull/23236/files#diff-b5d831e613a1826ac147ecfa9963fa5c285c3f243cea8f9e31f3edec5904892dR237-R250) that may have been a potential fix if there were an issue (and I think there would be an issue). This assigns to the `digest_sw` and `digest_sw_we` signals without the gating check that HMAC has been successfully started, but only configured. So at `hash_continue`, the digests written to CSRs from SW can be passed on to these signals, without waiting on HMAC to have been started. We'll be able to confirm if this resolves switching between different digest-sized streams work once we have a SAR TLT.

**Comment by andreaskurth** [comment] 2024-05-26 13:19
Thx @gdessouky, so we don't expect another RTL change, but we still wave to confirm in a TLT?

**Comment by gdessouky** [comment] 2024-06-03 07:56
In an offline discussion, @ballifatih confirmed he could run ~50 test vectors in parallel, with the SW driver, where all vectors are random SHA-2 256/348/512 vectors, and is able to switch across different digest-sized streams successfully. So we don't expect another RTL change here. I would close this issue for now, fixed by https://github.com/lowRISC/opentitan/pull/23236.

**Closed by gdessouky** 2024-06-03 07:56 UTC
Labels: Type:Bug, Component:RTL, IP:hmac
