### ISSUE TITLE
[kmac/top] Chip-level chip_csr_hw_reset failure due to fifo_empty interrupt

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#6888] opened 2021-06-08 23:00 UTC
With recent changes in CSR nodes of several IPs, we now seem to be hitting a new corner case in `kmac` in chip-level sims. In particular, it looks like the random CSR tests seem to initiate transactions into the message FIFO, and this in turn produces a `fifo_empty` interrupt - which is not expected at this point. 

Error message from VCS: 
```
Check failed obs == exp (2 [0x2] vs 0 [0x0]) Regname: chip_reg_block.kmac.intr_state
```
in the `chip_csr_hw_reset` test (see private CI from a recent PR, e.g. https://github.com/lowRISC/opentitan/pull/6870)

Is this something we can solve using exclusions?

**Comment by weicaiyang** [comment] 2021-06-09 01:05
This is caught in IP-level too. https://reports.opentitan.org/hw/ip/kmac_masked/dv/latest/results.html

in hw_reset, sequence is like this: random write CSRs -> reset -> read all CSRs for check
if the interrupt appears after reset, then it seems not quite right. @udinator WDYT?

**Comment by udinator** [comment] 2021-06-09 01:29
Hmm yes like @weicaiyang says I am seeing some infrequent failures in the IP level as well - let me dig into this, interrupts should not be firing after reset.

**Comment by udinator** [comment] 2021-06-10 02:27
Adding @rswarbrick also (since this involves rom_ctrl<->kmac things).

After some digging, I've root-caused the failure.

The various KMAC interrupts (`kmac_done`, `fifo_empty`, `kmac_err`) will rise/fall during the period just after reset when the ROM controller is initiating a hash of its memory contents - this is perfectly ok since the KMAC is currently active.

However, what is happening here is that the KMAC burst-reads a bunch of data from the ROM, rapidly incrementing the msgfifo read pointer and causing `fifo_empty` to occur - again, this is correct behavior.

As a result, once the ROM operation has finished and the "main" part of the `csr_hw_reset` test begins, a KMAC interrupt is already set, which then appears like an interrupt is somehow high right after reset - causing a comparison failure as the csr sequence clearly doesn't expect this interrupt to be high.

A possible solution is to add a read-check exclusion to the `intr_state` csr, as I think this error can technically pop up in other CSR tests.
However, this would affect IP-level testing also.

WDYT?

**Comment by rswarbrick** [comment] 2021-06-10 10:53
I'm not an expert on the details of how KMAC works, but rom_ctrl connects through one of the non-Ibex "app" interfaces. Since this isn't controlled by the CPU, I'm slightly surprised that its behaviour can trigger an interrupt being sent to the CPU. Shouldn't those be conditional on the cause coming from SW?

**Comment by udinator** [comment] 2021-06-10 17:16
sorry, I should have clarified - the interrupt lines themselves are not going high as the enable bits are all zeroed after each reset.
what is getting updated, however, are the fields of the `intr_state` CSR, and this is what is causing the mismatch failures.

**Comment by sriyerg** [comment] 2021-06-10 17:22
I dont think interrupts are actually sent (that requires `intr_enable` to be programmed, which is already write-excluded). However, the `intr_state` gets updated regardless, if the condition is met. IMO just do a read-check exclude on KMAC's `intr_state` fields and call it a day.

**Comment by msfschaffner** [comment] 2021-06-10 17:55
This solution sounds good to me as well.
Is there a straightforward way to add these exclusions? 
Afaik, these regs are autogenerated and hence there is no full associated register entry in the hjson.

**Comment by udinator** [comment] 2021-06-11 19:22
@msfschaffner yup, in `reggen/reg_block.py` we can add exclusions for the interrupt and alert registers, I am modifying the `intr_state` exclusions to exclude all checks.

**Comment by udinator** [comment] 2021-06-11 23:59
@msfschaffner the fix has been merged, can you rebase your PRs and run CI again?

**Comment by tjaychen** [comment] 2021-06-14 19:17
to @rswarbrick point, we should probably think about whether it makes sense that pure hardware triggered / response events really should be setting the interrupts though.

This might not matter for the `rom` case since it happens only at power up, but this could get kind of strange for the case kmac is used by both `otp` and software.  If the software for example statically sets up the interrupts enables, and then gets an interrupt that is actually triggered by `otp` token hashing, will that end up creating confusion for software? 

@eunchan 
@udinator

**Comment by rswarbrick** [comment] 2021-06-15 08:50
> This might not matter for the rom case since it happens only at power up, but this could get kind of strange for the case kmac is used by both otp and software. If the software for example statically sets up the interrupts enables, and then gets an interrupt that is actually triggered by otp token hashing, will that end up creating confusion for software?

Yep, that was what I was trying to get at.

**Closed** 2021-10-19 15:22 UTC
Labels: Component:DV
