### ISSUE TITLE
[regr] channel and subject for reporting regression results

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#2761] opened 2020-07-09 17:35 UTC
In organizing the reporting of regression results, we're looking for the appropriate channel and subject line for easier viewing / filtering. Suggesting the following:

1. reports go to OT silicon team only
2. subject allows for filtering, gives the following information in the subject line

`[ot-silicon][cron] OpenTitan <reporttype> Regression report <date>`

Examples:

```
[ot-silicon][cron] OpenTitan Synthesis Regression Report 2020-07-09
[ot-silicon][cron] OpenTitan Style Lint Regression Report 2020-07-08
```

Weigh in if you think more/less info should be on the subject line, and if `opentitan-silicon@` is the right channel or not.

**Comment by sriyerg** [comment] 2020-07-09 17:48
@cindychip, @msfschaffner 
All of these suggested changes SGTM.

**Comment by msfschaffner** [comment] 2020-07-09 19:24
This sounds good to me. I think our formats are mostly aligned with that. 
@cindychip, I think we only have to add `` `date +"%Y-%m-%d"` `` to the email script argument.

**Comment by msfschaffner** [comment] 2020-07-09 19:24
@lenary for visibility

**Comment by lenary** [comment] 2020-07-09 20:02
@msfschaffner Thanks!

For my needs, a unique tag like `[cron]` in the subject is good enough to filter on. I think I'm not the only person filtering these emails :)

**Comment by msfschaffner** [comment] 2020-07-09 22:16
Ok I have updated the cronjob scripts such that the regression date is appended to the email subject. 

I'll leave this issue open until we get the next batch of regression reports, and close it down tomorrow if there are no objections.

**Comment by cindychip** [comment] 2020-07-10 17:29
Sounds good, I will update the script for DV and FPV regressions.

**Comment by msfschaffner** [comment] 2020-07-10 18:28
No worries, I'll wait.

**Comment by msfschaffner** [comment] 2020-07-11 01:21
@cindychip can you close this issue once your updates are complete?

**Comment by cindychip** [comment] 2020-07-11 01:29
Sure I will do that!

**Comment by cindychip** [comment] 2020-07-13 16:35
Looks like DV, FPV, Lint, and Syn regression result all followed the proposed format. I am going to close this issue.

**Closed by cindychip** 2020-07-13 16:35 UTC
Labels: Component:Tooling, Priority:P2, Type:Question
