### ISSUE TITLE
[test-triage] chip_sw_random_sleep_all_reset wait timeout occurred

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15278] opened 2022-10-05 01:16 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
UVM_FATAL @ * us: (chip_sw_random_sleep_all_reset_vseq.sv:113) [chip_sw_random_sleep_all_reset_vseq] wait timeout occurred! has 2 failures:

0.chip_sw_pwrmgr_random_sleep_all_reset_reqs.639771430
Line 601, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_pwrmgr_random_sleep_all_reset_reqs/latest/run.log

  UVM_FATAL @ 50951.438000 us: (chip_sw_random_sleep_all_reset_vseq.sv:113) [uvm_test_top.env.virtual_sequencer.chip_sw_random_sleep_all_reset_vseq] wait timeout occurred!
  UVM_INFO @ 50951.438000 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
  
1.chip_sw_pwrmgr_random_sleep_all_reset_reqs.1797295679
Line 598, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_pwrmgr_random_sleep_all_reset_reqs/latest/run.log

  UVM_FATAL @ 43628.516000 us: (chip_sw_random_sleep_all_reset_vseq.sv:113) [uvm_test_top.env.virtual_sequencer.chip_sw_random_sleep_all_reset_vseq] wait timeout occurred!
  UVM_INFO @ 43628.516000 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

### Steps to Reproduce

- Commit hash: [67a41e3bc](https://github.com/lowrisc/opentitan/tree/67a41e3bc3ff025554a024cdb15fbf892c4752b3)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_pwrmgr_random_sleep_all_reset_reqs --fixed-seed 639771430  --build-seed 3413385032 --waves -v h

### Tests with similar or related failures

- [ ] same test, other run seed: 1797295679

**Comment by engdoreis** [comment] 2022-10-11 13:13
The test `chip_sw_random_sleep_all_reset` doesn't seem to exist, by the failure log I assume that `chip_sw_pwrmgr_random_sleep_all_reset_reqs` is the correct one.

Which has passed in 4 consecutive executions now.


Tests | latest | 2022.10.10 | 2022.10.08/1 | 2022.10.08/2 | 2022.10.06 | 2022.10.05/1 | 2022.10.05/2 | 2022.10.03/1 | 2022.10.03/2 | ... | 2022.09.30 | 2022.09.29 | 2022.09.28 | 2022.09.27 | 2022.09.26/1 | 2022.09.26/2 | 2022.09.26 | 2022.09.24 | 2022.09.23 | Suite
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chip_sw_pwrmgr_random_sleep_all_reset_reqs | 100.00 | 100.00 | 100.00 | 100.00 | 66.67 | 66.67 | 0.00 | 33.33 | 33.33 | ... | 0.00 | 0.00 | 0.00 | 33.33 | 100.00 | 100.00 | 100.00 | 100.00 | 66.67 | chip_sw_pwrmgr_random_sleep_all_reset_reqs

**Comment by engdoreis** [comment] 2022-10-24 16:31
This test is not passing consistently, so it is worth investigating


Tests | latest | 2022.10.22 | 2022.10.21 | 2022.10.17/2 | 2022.10.17/1 | 2022.10.15 | 2022.10.14 | 2022.10.12/2 | 2022.10.12/1 | 2022.10.11 | Suite
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
chip_sw_pwrmgr_random_sleep_all_reset_reqs | 66.67 | 100.00 | 33.33 | 100.00 | 66.67 | 66.67 | 33.33 | 100.00 | 100.00 | 66.67 | chip_sw_pwrmgr_random_sleep_all_reset_reqs

**Comment by johngt** [comment] 2022-10-27 08:24
As @vrozic is actively working on this, corrected status to 'In progress' and changed the organisation to lowRISC.

**Comment by vrozic** [comment] 2022-11-01 14:11
The timeout seems to be caused by the endless wait in the 'execute_reset()' task. This is sometimes caused by the hw por tests. I am working on the fix.

**Comment by johngt** [comment] 2022-11-07 15:43
@vrozic - pinging for an update on the issue? Do you have a draft PR or an update on what is currently blocking this?

**Comment by vrozic** [comment] 2022-11-07 15:56
PR #15874 should fix this problem.
I am currently testing this fix with more seeds to be sure that the problem is indeed gone.

**Comment by johngt** [comment] 2022-11-11 12:23
@vrozic - did you manage to test with more seeds? Can this issue now be closed out?

**Comment by vrozic** [comment] 2022-11-11 12:26
I've tested the fix with 30 seeds and didn't see any timeouts (previously timeouts were occurring about 20% of the time).
I think that the issue can be closed now.

**Comment by johngt** [comment] 2022-11-11 12:51
Thanks @vrozic !
Closing out.

**Closed by johngt** 2022-11-11 12:51 UTC
Labels: Component:TestTriage
