### ISSUE TITLE
[edn/dv] Assert that local escalate causes FSM error

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/opentitan#17663] opened 2023-03-23 13:14 UTC
### Description

EDN specific issue of: https://github.com/lowRISC/opentitan/issues/16269

Effort range 2-4

> estimate 4

**Comment by johngt** [comment] 2023-05-03 10:56
@vogelpi for visibility on this one. Believe that this should be done in the first sprint. Please lower priority and backlog if risk is low.

**Comment by msfschaffner** [comment] 2023-06-19 10:51
@moidx and I discussed this today and think this is low risk and can hence be postponed to the production tapeout.

We'll move it to M2.5 backlog for now.

**Comment by vogelpi** [comment] 2023-12-21 15:01
Closing as this is a duplicate of #16269 .

**Closed by vogelpi** 2023-12-21 15:01 UTC
Labels: Component:DV, Priority:P2, Subsystem:Entropy, IP:edn, Earlgrey-PROD Candidate
