### ISSUE TITLE
[test-triage] chip_rv_dm_ndm_reset_req assert failing

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#15435] opened 2022-10-12 10:48 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```
Offending '(!rst_src_ni)' has 6 failures:

Test chip_sw_lc_ctrl_kmac_reset has 3 failures.
0.chip_sw_lc_ctrl_kmac_reset.4126001754
Line 493, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_lc_ctrl_kmac_reset/latest/run.log

      Offending '(!rst_src_ni)'
  UVM_ERROR @ 2408.539809 us: (prim_sync_reqack.sv:201) [ASSERT FAILED] SyncReqAckRstSrc
  UVM_INFO @ 2408.539809 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
1.chip_sw_lc_ctrl_kmac_reset.1805505272
Line 495, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_lc_ctrl_kmac_reset/latest/run.log

      Offending '(!rst_src_ni)'
  UVM_ERROR @ 2843.112728 us: (prim_sync_reqack.sv:201) [ASSERT FAILED] SyncReqAckRstSrc
  UVM_INFO @ 2843.112728 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
... and 1 more failures.

Test chip_rv_dm_ndm_reset_req has 3 failures.
0.chip_rv_dm_ndm_reset_req.3778920470
Line 475, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_rv_dm_ndm_reset_req/latest/run.log

      Offending '(!rst_src_ni)'
  UVM_ERROR @ 3459.111856 us: (prim_sync_reqack.sv:201) [ASSERT FAILED] SyncReqAckRstSrc
  UVM_INFO @ 3459.111856 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
1.chip_rv_dm_ndm_reset_req.369530232
Line 475, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_rv_dm_ndm_reset_req/latest/run.log

      Offending '(!rst_src_ni)'
  UVM_ERROR @ 3586.547920 us: (prim_sync_reqack.sv:201) [ASSERT FAILED] SyncReqAckRstSrc
  UVM_INFO @ 3586.547920 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  ```

### Steps to Reproduce

- Commit hash d0b9668b2
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_rv_dm_ndm_reset_req --fixed-seed 3778920470 --build-seed 1745750847 --waves -v h

### Tests with similar or related failures

- [ ] chip_rv_dm_ndm_reset_req
- [ ] chip_sw_lc_ctrl_kmac_reset

Github: https://github.com/lowrisc/opentitan/tree/84fdd3bf374f168367ba7ffcb07cfa4d79c54875
 - [x] chip_sw_pwrmgr_random_sleep_all_wake_ups.3614850612
 - [x] chip_sw_pwrmgr_deep_sleep_all_wake_ups.2335872897
 - [x] chip_sw_pwrmgr_normal_sleep_all_wake_ups.3771606132

**Comment by andreaskurth** [comment] 2022-10-12 14:05
The `chip_rv_dm_ndm_reset_req` test fails (with the provided seeds and also on e79e3525c284efe83f957ba62a24cd91be94370b, which is the current head of master) because the source of the following `prim_sync_reqack_data` is reset while the destination is not:  

https://github.com/lowRISC/opentitan/blob/e79e3525c284efe83f957ba62a24cd91be94370b/hw/ip/otbn/rtl/otbn_scramble_ctrl.sv#L227-L235

According to a recently added (https://github.com/lowRISC/opentitan/pull/15100) assertion
https://github.com/lowRISC/opentitan/blob/e79e3525c284efe83f957ba62a24cd91be94370b/hw/ip/prim/rtl/prim_sync_reqack.sv#L199-L207
this is not legal, and thus the `SyncReqAckRstSrc` assertion fails.

The resets are driven by the reset manager (`top_earlgrey.u_rstmgr_aon`), which resets `rstmgr_aon_resets.rst_sys_n[rstmgr_pkg::Domain0Sel]` without simultaneously resetting `rstmgr_aon_resets.rst_lc_io_div4_n[rstmgr_pkg::Domain0Sel])`:
https://github.com/lowRISC/opentitan/blob/e79e3525c284efe83f957ba62a24cd91be94370b/hw/top_earlgrey/rtl/autogen/top_earlgrey.sv#L2310-L2312

I think the assertion is correct and the reorganization of the reset domains that is in progress (https://github.com/lowRISC/opentitan/issues/15317) should fix this. A hotfix to get these tests to pass could be to disable the assertion (set `EnRstChks` to `1'b0` for `u_otp_key_req_sync` in `otbn_scramble_ctrl`), but that would only mask the actual problem.

I have not tried `chip_sw_lc_ctrl_kmac_reset` or the other seeds, but the name of the failing assertion is the same, so I suspect the problem is the same.

**Comment by johngt** [comment] 2022-10-13 10:48
Thanks @andreaskurth for the assessment. It looks like we should keep this open until https://github.com/lowRISC/opentitan/issues/15317 is merged in and then see if this issue is resolved.
@engdoreis let's keep this open during our on-call window. If by the end of Friday the issue is not merged please de-assign @andreaskurth but keep the issue open. I'm assigning @tjaychen as the planned assignee as the person with experience in this issue.

**Comment by tjaychen** [comment] 2022-10-13 17:12
@jeoongp 
@matutem 
who will be looking after this change.

**Comment by cindychip** [comment] 2022-10-17 18:33
Adding a few more tests to this failing category (already updated in the description):
Github: https://github.com/lowrisc/opentitan/tree/84fdd3bf374f168367ba7ffcb07cfa4d79c54875
- [ ] chip_sw_pwrmgr_random_sleep_all_wake_ups.3614850612 
- [ ] chip_sw_pwrmgr_deep_sleep_all_wake_ups.2335872897
- [ ] chip_sw_pwrmgr_normal_sleep_all_wake_ups.3771606132

**Comment by tjaychen** [comment] 2022-10-17 18:34
hmmm... let me have a look at the `pwrmgr` failures. 
If those are actually going into deep sleep, there shouldn't be a domain crossing problem.  So this might be hitting a case that was not originally expected.  @cindychip i might separate those into a different issue if that's the case.

**Comment by tjaychen** [comment] 2022-10-18 15:59
The `chip_sw_pwrmgr_*` failures should be addressed by #15541

**Comment by tjaychen** [comment] 2022-10-18 16:01
@jeoongp i'm assigning this to you for now since it is related to the reset domain change.
Once that is ready, we can come back and have a look!

**Comment by jeoongp** [comment] 2022-10-18 17:54
Sounds good.

**Comment by engdoreis** [comment] 2022-10-25 08:42
All the related tests are passing:

|     | Tests                                    |   latest |   2022.10.23 |   2022.10.22 |   2022.10.21 |   2022.10.17/2 |   2022.10.17/1 |   2022.10.15 |   2022.10.14/2 |   2022.10.14/1 | 2022.10.12   | Suite                                                            |
|----:|:-----------------------------------------|---------:|-------------:|-------------:|-------------:|---------------:|---------------:|-------------:|---------------:|---------------:|:-------------|:-----------------------------------------------------------------|
| 141 | chip_sw_pwrmgr_deep_sleep_all_wake_ups   |      100 |          100 |          100 |          100 |              0 |              0 |            0 |            100 |            100 | 100.00       | chip_sw_pwrmgr_deep_sleep_all_wake_ups, chip_sw_power_sleep_load |
| 146 | chip_sw_pwrmgr_normal_sleep_all_wake_ups |      100 |          100 |          100 |          100 |              0 |              0 |            0 |            100 |            100 | 66.67        | chip_sw_pwrmgr_normal_sleep_all_wake_ups                         |
| 148 | chip_sw_pwrmgr_random_sleep_all_wake_ups |      100 |          100 |          100 |          100 |              0 |              0 |            0 |            100 |            100 | --           | chip_sw_pwrmgr_random_sleep_all_wake_ups                         |

**Comment by engdoreis** [comment] 2022-10-25 09:38
Repening because I didn't notice that there's still two test failing with the same signature:

|     | Tests                                     | latest   | 2022.10.23   | 2022.10.22   | 2022.10.21   | 2022.10.17/2   | 2022.10.17/1   | 2022.10.15   | 2022.10.14/2   | 2022.10.14/1   | 2022.10.12   | Suite                                     |
|----:|:------------------------------------------|:---------|:-------------|:-------------|:-------------|:---------------|:---------------|:-------------|:---------------|:---------------|:-------------|:------------------------------------------|
|  14 | chip_rv_dm_ndm_reset_req                  | 0.00     | 0.00         | 0.00         | 0.00         | 0.00           | 0.00           | 0.00         | 0.00           | 0.00           | 0.00         | chip_rv_dm_ndm_reset_req                  |
| 114 | chip_sw_lc_ctrl_kmac_reset                | 0.00     | 0.00         | 0.00         | 0.00         | 0.00           | 0.00           | 0.00         | 0.00           | 0.00           | 0.00         | chip_sw_lc_ctrl_kmac_reset                |

**Comment by tjaychen** [comment] 2022-11-03 04:03
should we keep this open for a bit? The test does need a bit of tweaking also.

**Comment by msfschaffner** [comment] 2022-11-03 21:49
Huh I don't remember closing this... was it maybe autoclosed via #15602?
In any case, yes let's keep it open.

**Comment by tjaychen** [comment] 2022-11-03 21:53
yeah in hindsight i think this was auto close. I'm going to quickly run the test just to see what's happening.

**Comment by tjaychen** [comment] 2022-11-09 17:15
this should now hopefully be fixed, just waiting on regression results.

**Comment by johngt** [comment] 2022-11-11 12:27
2 nightlies passed - If ok during the weekend we can close this out on Monday.

|    | Tests                                     | 2022-11-10 08:10:06   | 2022-11-09 08:04:06   | 2022-11-08 08:03:42   | 2022-11-07 08:08:10   | 2022-11-06 07:11:02   | 2022-11-05 07:11:23   | 2022-11-04 07:12:05   | 2022-11-03 07:11:23   | 2022-11-02 07:03:26   | 2022-11-01 07:10:18   | Suite                                     |
|---:|:------------------------------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:----------------------|:------------------------------------------|
| 15 | chip_rv_dm_ndm_reset_req                  | 100.00                | 100.00                | 0.00                  | 0.00                  | 0.00                  | 0.00                  | 0.00                  | --                    | --                    | --                    | chip_sw_rstmgr_sys_reset_info             |
| 16 | chip_rv_dm_ndm_reset_req                  | 100.00                | 100.00                | 0.00                  | 0.00                  | 0.00                  | 0.00                  | 0.00                  | 0.00                  | 0.00                  | 0.00                  | chip_rv_dm_ndm_reset_req                  |
| 17 | chip_rv_dm_ndm_reset_req_when_ibex_halted | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | --                    | chip_rv_dm_ndm_reset_req_when_ibex_halted |

**Closed** 2022-11-15 02:43 UTC
Labels: Component:TestTriage
