### ISSUE TITLE
execute ./meson_init.sh, encounter an error, C compiler for host version mismatch

### ISSUE THREAD

**Issue by zhajio1988** [lowRISC/opentitan#9222] opened 2021-11-15 14:48 UTC
meson.build:62:6: ERROR: Problem encountered: C compiler for host version mismatch, >=5 required.
Actually, i install a gcc-5.3.0 under my home directory, and also set PATH environment variable, when i execute "which gcc" via terminal, it return my installed gcc, not /usr/bin/gcc, but  meson.get_compiler('c', native: true) seem to be using /usr/bin/gcc.
I try to set $CC and $CXX environment variable, both can't work correctly.
Anyone can help? Thanks.

**Comment by zhajio1988** [comment] 2021-11-16 03:03
@weicaiyang 
Could you help about this issue, thanks?

**Comment by weicaiyang** [comment] 2021-11-16 06:41
@mcy @moidx @timothytrippel can you take a look at this error? Thanks

**Comment by rswarbrick** [comment] 2021-11-16 09:15
This isn't really OpenTitan specific. You're trying to tell Meson to pick a specific native compiler. Anyway, I think the problem is likely to be that Meson defaults to `cc` when picking a C compiler (which will be linked to `gcc` on your system). Is it possible that `which cc` points at `/usr/lib`?

It looks like Meson obeys the `CC` environment variable, so you could also try `CC=gcc ./meson_init.sh`.

**Comment by zhajio1988** [comment] 2021-11-16 13:43
@rswarbrick 
Thanks, 
which cc shows /usr/bin/cc
I already "export CC=gcc, export CC=absoulte path/gcc, CC=gcc", ./meson_init.sh fails too.

**Comment by rswarbrick** [comment] 2021-11-16 14:53
Oh, you're completely right. I just tried `CC=clang ./meson_init.sh` and it still picked `ccache cc` as my host compiler. I'm not sure of the exact mechanism here; it might be complicated by the fact we're also supplying a cross-compiler.

Anyway, the simplest fix would be to put a version of `cc` on your path that points at your `gcc`. Something as basic as  `D=$(dirname $(command -v gcc)); ln -s $D/gcc $D/cc` might well work.

**Comment by zhajio1988** [comment] 2021-11-17 01:38
@rswarbrick 
Amazing, I always think that Meson is looking for gcc, but I didn’t expect it to be cc. I find that cc is actually a soft link of gcc.
I make a soft link of gcc at my home gcc path as you said. It can work. Thanks.

**Comment by weicaiyang** [comment] 2021-11-17 01:48
Awesome. Thanks @rswarbrick 

If this addresses the problem, please close the issue

**Comment by zhajio1988** [comment] 2021-11-17 02:47
@weicaiyang 
Thanks, weicai

**Comment by rswarbrick** [comment] 2021-11-17 11:17
Sounds like this is working now.

**Closed by rswarbrick** 2021-11-17 11:17 UTC
