### ISSUE TITLE
[chip-test] chip_sw_alert_handler_reverse_ping_in_deep_sleep

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#14134] opened 2022-08-09 22:41 UTC
### Test point name

[chip_sw_alert_handler_reverse_ping_in_deep_sleep](https://github.com/lowRISC/opentitan/blob/b65e2705eb4ee814b46939d44f84d1adfee133c3/hw/top_earlgrey/data/chip_testplan.hjson#L1324)

### Host side component

None Required

### Contact person

@msfschaffner

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by moidx** [comment] 2022-09-13 23:07
Reopening to check regression status.

@cindychip  do you want to keep this issue open until we resolve #14887? Thanks

**Comment by cindychip** [comment] 2022-09-13 23:40
I am fine to close this once the regression passed, since we have the separate issue (#14887) to track the additional checking :)

**Comment by moidx** [comment] 2022-09-17 09:18
Increased test timeout in https://github.com/lowRISC/opentitan/pull/14929.

**Closed by moidx** 2022-09-17 09:18 UTC
Labels: Component:ChipLevelTest, Help Wanted : SW, Help Wanted : DD
