### ISSUE TITLE
[AES] hang  

### ISSUE THREAD

**Issue by e-puerto** [lowRISC/opentitan#17399] opened 2023-02-28 09:41 UTC
### Description

In the AES smoketest the reseeding rate is configured by default to PER_1.
So I modified it in order to perform a loop of 4096 encryption operation and not verify the cipher generated. then before ending I got a timeout in the wait for status (output valid bit stays at zero).
I have this behavior on master commit id "bfb2b1c0e", it appears on FPGA (cw310) and verilator.
If I change the reseeding rate to another value, the behavior arrives later.

**Comment by johngt** [comment] 2023-02-28 09:44
Tagging @vogelpi to do a quick assessment / see if this is reproducible locally. If it is then we will set priorities accordingly.

**Comment by vogelpi** [comment] 2023-02-28 10:11
Hi @e-puerto ,
thanks for reporting the issue. Question: by "not verify the cipher generated" do you mean you don't read the data output registers? Because the smoketest configures the module in automatic mode, meaning AES will at some point stall not produce further output because it doesn't overwrite previous outputs which haven't been read yet. This is indicated in the STATUS register with the `stall` bit.

If you change the reseed rate this influences this behavior in the sense that the first block will take longer to finish and the second block takes longer until it gets stalled.

**Comment by e-puerto** [comment] 2023-02-28 12:52
Hi @vogelpi, 
by "not verify the cipher generated" I mean I commend the  CHECK_ARRAYS_EQ  call In order to speed up the verilator run ;)
the loop on aes_smoketest is:
for (int idx = 0; idx < 4096; ++idx) {
  CHECK_DIF_OK(dif_aes_start(&aes, &transaction, &key, NULL));

  // "Convert" plain data byte arrays to `dif_aes_data_t`.
  dif_aes_data_t in_data_plain;
  memcpy(in_data_plain.data, kAesModesPlainText, sizeof(in_data_plain.data));

  // Load the plain text to trigger the encryption operation.
  AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusInputReady, true, TIMEOUT);
  CHECK_DIF_OK(dif_aes_load_data(&aes, in_data_plain));

  AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusOutputValid, true, TIMEOUT);

  CHECK_DIF_OK(dif_aes_read_output(&aes, &out_data));

  // Finish the ECB encryption transaction.
  CHECK_DIF_OK(dif_aes_end(&aes));
}

The influence of changing the reseed rate is to increase the number of loops before having this behavior.
If it is needed I can dump some register

**Comment by vogelpi** [comment] 2023-02-28 13:11
Thanks for the clarification. I confirm the behavior you observe is unexpected. I'll try out your code snipped and report back. It could be related to the this issue (DV for 8k reseed rate doesn't seem to be correct #17357).

If you want to speed up the test, you could change your code snippet as follows:
```c
CHECK_DIF_OK(dif_aes_start(&aes, &transaction, &key, NULL));

// "Convert" plain data byte arrays to `dif_aes_data_t`.
dif_aes_data_t in_data_plain;
memcpy(in_data_plain.data, kAesModesPlainText, sizeof(in_data_plain.data));

for (int idx = 0; idx < 4096; ++idx) {
  // Load the plain text to trigger the encryption operation.
  AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusInputReady, true, TIMEOUT);
  CHECK_DIF_OK(dif_aes_load_data(&aes, in_data_plain));

  AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusOutputValid, true, TIMEOUT);

  CHECK_DIF_OK(dif_aes_read_output(&aes, &out_data));
}
// Finish the ECB encryption transaction.
CHECK_DIF_OK(dif_aes_end(&aes));
```
Otherwise you re-configure AES for every block which is very time consuming.

**Comment by vogelpi** [comment] 2023-02-28 15:14
FYI @e-puerto , I've now simulated around 400 blocks with this code snippet and it is working fine:
```c
  // Setup ECB encryption transaction.
  dif_aes_transaction_t transaction = {
      .operation = kDifAesOperationEncrypt,
      .mode = kDifAesModeEcb,
      .key_len = kDifAesKey256,
      .key_provider = kDifAesKeySoftwareProvided,
      .mask_reseeding = kDifAesReseedPer64Block,
      .manual_operation = kDifAesManualOperationAuto,
      .reseed_on_key_change = false,
      .ctrl_aux_lock = false,
  };
  CHECK_DIF_OK(dif_aes_start(&aes, &transaction, &key, NULL));

  // "Convert" plain data byte arrays to `dif_aes_data_t`.
  dif_aes_data_t in_data_plain;
  memcpy(in_data_plain.data, kAesModesPlainText, sizeof(in_data_plain.data));

  dif_aes_data_t out_data;
  for (int idx = 0; idx < 4096; ++idx) {
    LOG_INFO("%i", idx);

    // Load the plain text to trigger the encryption operation.
    AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusInputReady, true, TIMEOUT);
    CHECK_DIF_OK(dif_aes_load_data(&aes, in_data_plain));

    // Read out the produced cipher text.
    AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusOutputValid, true, TIMEOUT);

    CHECK_DIF_OK(dif_aes_read_output(&aes, &out_data));
  }
```
I can see the reseed happening at the expected time (every 64 blocks).

Can you please check what the different functions return in your case and maybe print the return values? I suspect that the reconfiguration in `dif_aes_start()` and the clearing in `dif_aes_end()` don't like each other or something.

**Comment by e-puerto** [comment] 2023-02-28 15:27
FYI @vogelpi the following Fail.

 ```
CHECK_DIF_OK(dif_aes_start(&aes, &transaction, &key, NULL));

// "Convert" plain data byte arrays to `dif_aes_data_t`.
dif_aes_data_t in_data_plain;
memcpy(in_data_plain.data, kAesModesPlainText, sizeof(in_data_plain.data));

for (int idx = 0; idx < 4096; ++idx) {
  // Load the plain text to trigger the encryption operation.
  AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusInputReady, true, TIMEOUT);
  CHECK_DIF_OK(dif_aes_load_data(&aes, in_data_plain));

  AES_TESTUTILS_WAIT_FOR_STATUS(&aes, kDifAesStatusOutputValid, true, TIMEOUT);

  CHECK_DIF_OK(dif_aes_read_output(&aes, &out_data));
}
// Finish the ECB encryption transaction.
CHECK_DIF_OK(dif_aes_end(&aes));
```

On FPGA I use the following command to test:
`./bazelisk.sh test --test_output=streamed --cache_test_results=no //sw/device/tests:aes_smoketest_fpga_cw310_test_rom
`I can see on trace:
```
E00001 aes_smoketest.c:79] CHECK-fail: Timed out after 1000000 usec (10000000 CPU cycles) waiting for aes_testutils_get_status((&aes), (kDifAesStatusOutputValid)) == (1)
I00002 status.c:34] FAIL!
```

**Comment by vogelpi** [comment] 2023-02-28 22:28
I've tested above snippet with all three reseed rates. With the `Per8kBlock` and the `Per64Block` settings, the test passes. With the `PerBlock` setting the test fails approximately at the same time as in your case (didn't print all `idx` to speed up simulation).

That the test fails in this case is expected. The reason is that for this smoketest and because this smoketest is only doing a very limited number of blocks, the entropy distribution networks are configured in boot mode. The [boot generate command](https://docs.opentitan.org/hw/ip/edn/doc/#Reg_boot_gen_cmd) will return at most 0xFFF = 4096 blocks of 128-bit each (for a details on how to interpret the command, see [this](https://docs.opentitan.org/hw/ip/csrng/doc/#command-header)). This amounts to 524288 bits of entropy in total. When doing 3253 blocks with a reseed on every block, AES alone consumes already 520480 bits of entropy (3253 * 5*32 bits). Some more bits are being used after reset and probably also by other blocks during start up. The test simply runs out of entropy which will stall AES.

To configure the EDNs in non-boot/automatic mode, please check out e.g. the [OTBN smoketest](https://github.com/lowRISC/opentitan/blob/e80eb5029193d2bee08da635a075d75bb246b904/sw/device/tests/otbn_smoketest.c#L151).

My takeaway from this is that we should discuss whether we want to change the RTL to also set the stall bit in this case. I am not sure about DV implications of this at the moment and need to think about that.

**Comment by e-puerto** [comment] 2023-03-01 01:20
I could understand your explanation about the "boot mode vs automatic mode" even if I did not understand where the "5" came from in your formula "3253 * 5*32 bits", I was assuming that the Data_out is changed by random value after reading it, so it means 4*32 bits.
when you say "With the Per8kBlock and the Per64Block settings, the test passes" I assume you mean that the issue did not appear in this 4096 encryption operation. It looks logical that it will just need more loops before it happens because you will reseed every 64 blocks (respectively 8K blocks). Effectively if I configure to reseed every 64 blocks and increase the loop to 64*4096 I have the same behavior at idx = 167679 (that is earlier that my assumption).
Please note also that we do not have the same value if we use decrypt instead of encrypt, the behavior arrives sooner on decryption.

Even if I agree that in "boot mode" (assuming that it is the mode for the ROM) you will probably never use the AES more than 3253 encryption/decryption, from my point of view, if the entropy network could not deliver enough blocks, the AES should be busy (according to the documentation IDLE = 0 when PRNG reseeding) and the RTL should be modified accordingly.

**Comment by vogelpi** [comment] 2023-03-02 08:55
> I could understand your explanation about the "boot mode vs automatic mode" even if I did not understand where the "5" came from in your formula "3253 * 5 * 32 bits", I was assuming that the Data_out is changed by random value after reading it, so it means 4 * 32 bits.

Per Reseed for the masking PRNG, AES consumes 5 times 32 bits. Because this PRNG is based on 5 32-bit LFSRs internally.

> when you say "With the Per8kBlock and the Per64Block settings, the test passes" I assume you mean that the issue did not appear in this 4096 encryption operation.

Yes.
> It looks logical that it will just need more loops before it happens because you will reseed every 64 blocks (respectively 8K blocks). Effectively if I configure to reseed every 64 blocks and increase the loop to 64*4096 I have the same behavior at idx = 167679 (that is earlier that my assumption). 

Yes, this makes sense.

> Please note also that we do not have the same number of loop if we use decrypt instead of encrypt, the behavior arrives sooner on decryption.

This is most likely because for to get the decryption start key, the key schedule of AES first does one encryption at the very beginning of the message. So I expect the offset at which things get stuck to be 1 block. Or did you observe something different?

> Even if I agree that in "boot mode" you will probably never use the AES more than 3253 encryption/decryption (assuming that boot mode is the mode for the ROM), from my point of view, if the entropy network could not deliver enough blocks, the AES should be busy (according to the documentation IDLE = 0 when PRNG reseeding) and the RTL should be modified accordingly.

I think right now, the module should already indicate BUSY while waiting for entropy. IIRC, also other hardware blocks do not indicate if they're stalling due to waiting for entropy. So this behavior should be inline with other modules. But I need to think about this.

> By the way, I confirm that passing the EDN to "automatic mode" avoid this situation (at least the behavior did not appear with a loop of 262144 on FPGA).

Thanks for checking this out and reporting the result. Glad to know things are working as expected :-)

**Comment by vogelpi** [comment] 2023-03-06 12:16
I have now investigated the behavior and can confirm that AES, when waiting for entropy to reseed the masking PRNG due to the expired reseed counter, indeed sets the IDLE bit to low, i.e., it indicates to software that the module is busy with some operation. This can be seen in the screenshot below. 

![Screenshot from 2023-03-06 13-09-31](https://user-images.githubusercontent.com/20307557/223106610-ed278d47-d860-426d-9589-ffc335620903.png)

I also checked KMAC and OTBN which also have EDN interfaces. Both these blocks don't have a seperate status bit to indicate that the module is waiting for entropy. Instead they're just reporting to be busy. So I think no further action on this issue here is needed and I am thus closing the issue.

**Closed by vogelpi** 2023-03-06 12:16 UTC
Labels: IP:aes, TOP:earlgrey
