### ISSUE TITLE
Xcelium toggle coverage ignores X->1,0 and Z->1,0 transitions

### ISSUE THREAD

**Issue by NigelScales** [lowRISC/opentitan#10332] opened 2022-01-25 14:30 UTC
By default Xcelium will ignore transitions from X->1, X->0, Z->1 and Z->0 for it's toggle coverage collection.
This means static signals which only transition from all Zs or Xs to something are ignored.
Also dynamic signals, such as busses, which transition to/from X or Z are also ignored.

The default behaviour can be overridden by the commands:
set_toggle_includex
set_toggle_includez

Therefore I propose adding these to hw/dv/tools/xcelium/common.ccf

**Comment by rswarbrick** [comment] 2022-01-25 17:43
I'm not sure. I mean, if we only go from X to 0 (say), I'd claim the signal hasn't toggled: the X value might be modelling something with value 0 in the first place!

**Comment by sriyerg** [comment] 2022-01-25 18:43
Agreed - enabling this option will capture the transition to known value on reset assertion, which is not necessarily useful. Does VCS capture these transitions by default (I would not think so)?

Do you have an example where capturing this is useful?

**Comment by sriyerg** [comment] 2022-01-25 18:45
Hmm, I suppose we toggle the `valid` qualified payloads (such as TL) between X and value we want to send, so they will only see X->0|1 and 0|1->X.

**Comment by msfschaffner** [comment] 2022-01-25 19:24
I think in this particular case this came up while patching up the lc_ctrl DV environment, where @NigelScales is not seeing the expected coverage increase due to this issue (is that right, Nigel?).

**Comment by sriyerg** [comment] 2022-01-25 19:50
We only collect toggle coverage on DUT ports (and ports of pre-verified sub-modules). The outputs of all modules is already checked for unknown value when out of reset. The problem is only with inputs, which eventually is sourced by our testbench components (agents). Most if not all of our agents are designed to assign an X to payloads when their qualifying valid is 0. With these in mind, my vote is to enable `set_toggle_includex` switch, but not the other. `set_toggle_includez` IMO should not be needed.

**Comment by weicaiyang** [comment] 2022-01-25 21:43
> We only collect toggle coverage on DUT ports (and ports of pre-verified sub-modules). The outputs of all modules is already checked for unknown value when out of reset. The problem is only with inputs, which eventually is sourced by our testbench components (agents). Most if not all of our agents are designed to assign an X to payloads when their qualifying valid is 0. With these in mind, my vote is to enable `set_toggle_includex` switch, but not the other. `set_toggle_includez` IMO should not be needed.

Agree that we probably don't need `set_toggle_includez`. For `set_toggle_includex`, we don't assign X to valid/ready signals, which we could do during reset, but this may cause some issue when there are multiple resets/clocks. 
For example, assume `valid` is in rst/clk domain 1 and it's X as it's in reset. If domain 2 is out of reset earlier, the X on the `valid` may be propagated to domain 2.

**Comment by NigelScales** [comment] 2022-01-26 09:15
> Hmm, I suppose we toggle the `valid` qualified payloads (such as TL) between X and value we want to send, so they will only see X->0|1 and 0|1->X.

That's what I see.
Without set_toggle_includex those busses show as uncovered.

It does seem that VCS counts X->1,0 as a rising or falling edge for toggle coverage - if those busses are marked as covered.

**Comment by sriyerg** [comment] 2022-01-26 17:56
> **I think the goal should be to ensure that VCS and Xcelium work in the same way.**

Absolutely agree. All supported simulators need to be 100% aligned with each other.

**Comment by weicaiyang** [comment] 2022-01-26 18:08
> > Hmm, I suppose we toggle the `valid` qualified payloads (such as TL) between X and value we want to send, so they will only see X->0|1 and 0|1->X.
> 
> That's what I see. Without set_toggle_includex those busses show as uncovered. It does seem that VCS counts X->1,0 as rising / falling edges for toggle coverage; as those busses are marked as covered.

ohh, now I understand why we need `set_toggle_includex`.
Without `set_toggle_includex`, we need 0->1 and 1->0. With `set_toggle_includex`, we only need X->0|1 and 0|1->X. For data in TLUL, we should never see 0->1 or 1->0 as they will be always changed from X->1|0->X.

also vote to enable set_toggle_includex!

**Comment by weicaiyang** [comment] 2022-01-27 20:01
> @weicaiyang is spi_device not using Z as tristate? I thought it was at some point

some SPI pins could be driven with Z, but all the pins should have 1->0, 0->1 transition, so toggle coverage can be 100%. So `set_toggle_includez` isn't needed for SPI device.

**Comment by weicaiyang** [comment] 2022-02-07 21:31
Update from Synopsis AE. Below is how VCS handle X/Z for toggle coverage.

> X/Z->0 or X/Z->1 and vice versa by itself are not considered valid transitions and are not counted towards coverage. However 0->X/Z->1 or 1->X/Z->0 transitions are considered valid “0->1” and “1->0”  transitions respectively and are counted towards coverage.

**Comment by weicaiyang** [comment] 2022-02-07 21:35
Back to this topic, let me make a PR to add `set_toggle_includex` for Xcelium to close this issue.

**Closed** 2022-02-07 23:22 UTC
