### ISSUE TITLE
[chip-test] chip_sw_i2c_device_tx_rx

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14111] opened 2022-08-09 22:27 UTC
### Test point name

[chip_sw_i2c_device_tx_rx](https://github.com/lowRISC/opentitan/blob/07ece748876891301ac6eaba354541d4a57d39c6/hw/top_earlgrey/data/chip_testplan.hjson#L240)

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@igk8, @drewmacrae 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by drewmacrae** [comment] 2022-09-13 13:41
Why did we remove Component:ChipLevelTest @engdoreis? I was looking to pick up something Help Wanted that was SW only and unassigned so I'm going to start on this but I feel like I'm missing something (Maybe a lot)

**Comment by tjaychen** [comment] 2022-09-13 14:49
good catch, i've added the label back.

**Comment by drewmacrae** [comment] 2022-09-13 17:39
I was going to start on the software side of the work here, and it says you're the contact @martin-lueker, LMK if it's inconvenient.

**Comment by drewmacrae** [comment] 2022-09-13 17:41
>  Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
I don't see anything relevant in codesearch, I expect I'll be writing a test with a similar architecture to the i2c_host_tx_rx_test, and thought I'd start with the c components and the build rules.

**Comment by martin-lueker** [comment] 2022-09-13 17:41
Hi Drew. Actually, can we add @igk8 as the contact for this?  He would be a much better contact.  Also AFAIK, this block is not thoroughly verified at all due to resourcing issues. I think it is still at V1.  This may be "exciting".

**Comment by tjaychen** [comment] 2022-09-13 17:54
yeah Drew, I'm working on the i2c_host side, but I think the i2c_device
side is not fully verified (or at all).
It might be good to table this one for now until the DV on this has spun
up.  Because even if we have the C side, the SV side i think is mostly
undeveloped.

**Comment by drewmacrae** [comment] 2022-09-28 19:38
#15177 Should provide the C Side for this test.

**Comment by weicaiyang** [comment] 2022-10-06 18:14
I don't think I could work on this in the near term. unassigned myself, so that others may take it.

**Comment by drewmacrae** [comment] 2022-10-06 20:24
I could especially use help identifying which portions are designed for all I2C validation and which are specific to validating the I2C host.

I poked around a bit to see how/if we could do this as a self-test using two I2C modules to exercise each-other, but there's nothing we could do on the FPGA alone without custom hardware for the PMOD port to provide pullups and connect 2 pairs of pinmux pins.

**Comment by arunthomas** [comment] 2022-10-13 15:45
Unassigning Drew since the software side of this test is complete

**Comment by drewmacrae** [comment] 2022-10-17 16:37
LMK if the test needs any re-investigation/explanation.

**Comment by tjaychen** [comment] 2022-10-19 23:35
just a note the i2c host agent is not fully verified, even at block level, yet.
This is something @jdonjdon is planning to work on over the next few weeks, so you COULD try to wait for that.  Otherwise I don't think we can say for sure how much bugs might be in the agent itself.

**Comment by vrozic** [comment] 2022-10-25 08:49
I am currently working on this issue here: #15700

**Comment by tjaychen** [comment] 2022-11-09 06:38
see #15700

**Comment by tjaychen** [comment] 2022-11-11 21:40
this is now unblocked! 
Please move ahead, both the dv side changes and the rtl fixes are in.

**Comment by johngt** [comment] 2022-11-15 14:19
@vrozic - just highlighting that this is now unblocked and can be worked on.

**Comment by tjaychen** [comment] 2022-11-15 16:15
there is one more PR currently in review #16304 that helps improve the stability and function of the i2c agent.
Please sync up with @jdonjdon for more details.

**Comment by johngt** [comment] 2022-11-16 10:41
Thanks @tjaychen. @vrozic is assisting with CSRNG closeout but intends to work on I2C again this afternoon and will sync up with @jdonjdon to get the latest information to avoid any wasted effort.

**Comment by johngt** [comment] 2022-11-18 10:02
@msfschaffner / @moidx 
It looks like this will need to be worked on next week as @vrozic is familiar with this but unable to close it out today as he is OoO. I've temporarily unassigned it in case there is a resource from Google that can look at this, but will reassign to him on Monday morning.

**Comment by msfschaffner** [comment] 2022-11-18 17:49
We will likely not get to this today on our end.

**Comment by johngt** [comment] 2022-11-28 12:06
WIP branch - https://github.com/andreaskurth/opentitan/commits/chiptest_i2c
@andreaskurth / @vrozic

**Comment by vrozic** [comment] 2022-11-29 17:51
PR #15700 has been updated and it is now ready for review.
It has been tested using 10 seeds, and it passes in all cases.

**Comment by vogelpi** [comment] 2022-12-01 13:32
I am closing this issue. The corresponding test has been developed and merged with #15700 . It's run in CI and should also show up in the nightly regression tomorrow.

**Closed by vogelpi** 2022-12-01 13:32 UTC
Labels: Priority:P1, IP:i2c, Component:ChipLevelTest, Help Wanted : DV
