### ISSUE TITLE
[top_earlgrey] Debug JTAG issues on FPGA with ILA

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#18462] opened 2023-05-09 10:09 UTC
Given the problems reported in #17729, this issue tracks the effort of debugging JTAG on the CW310 with an integrated logic analyzer (ILA).

A (draft) PR that contains contributions that can be committed is here: #18401. That PR is not intended to get merged (at least not in the current state) but can be useful to reproduce the debugging setup.

**Comment by msfschaffner** [comment] 2023-05-12 20:40
I am closing this since the issue has been root caused.

See also #18554 and #17729 for context.

CC @moidx

**Closed by msfschaffner** 2023-05-12 20:40 UTC
Labels: Priority:P0, Submilestone:M2.5.1
