### ISSUE TITLE
AES DPI - VCS fixes

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#3299] opened 2020-08-30 08:26 UTC
OS: CentOS 7
Tool: VCS

AES - latest code uses DPI and I had to add the following to VCS compile to get it running:

 -CFLAGS "-std=c99 -I../../../model -I/usr/include/openssl11/ -lssl -lcrypto" \
-LDFLAGS "-lssl -lcrypto " \

I guess LDFLAGS is enough for -lssl -lcrypto (and not CFLAGS, though didn't try)

Is this known issue? 

Thanks
Srini

**Comment by rswarbrick** [comment] 2020-08-31 08:28
The main authors of this code are @vogelpi and @rasmus-madsen, who will probably know lots more about what's going on here. Can you post the exact command that you were trying to run (and needed the hacked flags)? Is it a system-level simulation, or something block-level?

**Comment by rasmus-madsen** [comment] 2020-08-31 09:15
@svenka3 can you also post the error message you are seeing?

**Comment by vogelpi** [comment] 2020-08-31 09:50
Hi Srini,
thanks for opening the issue. I am actually on vacation but since I am working on CentOS 7 as well (one of the few in the project), I thought I reply anyway. I am usually running the UVM DV for AES through the `dvsim` tool with a command like this:
```
/util/dvsim/dvsim.py hw/ip/aes/dv/aes_sim_cfg.hjson -t vcs --purge
```
Under the hood, `dvsim` then runs FuseSoC which can be used to pass such flags. We use this for example for Verilator-based simulations, see in `hw/ip/aes/model/aes_model.core`:
```
    tools:
      verilator:
        mode: cc
        verilator_options:
# linker flags
          - '-LDFLAGS "-pthread -lcrypto"'
```

But for VCS, it seems we moved to passing this flags via a different file: `hw/ip/aes/model/aes_model_sim_opts.hjson` contains:
```
  build_modes: [
    {
      name: vcs_aes_model_build_opts
      build_opts: ["-CFLAGS -I{build_dir}/src/{aes_mode_src_dir}", "-lcrypto"]
    }
```

So the bottom line is that if you run the simulation through `dvsim` the required flags should get set automatically also on CentOS 7. In case it still doesn't work, please provide the exact command you use and the error message as suggested by Rupert and Rasmus.

Best,
Pirmin

**Comment by svenka3** [comment] 2020-08-31 17:47
Thanks @vogelpi and @rasmus-madsen for timly response. To run, I read:

https://docs.opentitan.org/doc/ug/getting_started_dv/

And did:
```

cd hw/ip/aes/dv
make
```

I got error for openssl/conf.h file from gcc (My CentOS 7 laptop didn't have openssl installed to begin with).

I had to do:

```
sudo yum install openssl11-libs
sudo yum install openssl11-devel
sudo yum install epel-release
sudo yum -y install openssl-devel
```

After the above, I didn't want to recerate the fusesoc stuff, so ran VCS myself and gcc threw an error around -std=c99, hence added it myself. 

Maybe the takeaway here is the lack of openssl at my end. Please consider adding it to System Requirements page:

https://docs.opentitan.org/doc/ug/install_instructions/

Special thanks to Pirmin for taking time out during your vacation!

Regards
Srini

**Comment by svenka3** [comment] 2020-08-31 17:47
Thanks @vogelpi and @rasmus-madsen for timly response. To run, I read:

https://docs.opentitan.org/doc/ug/getting_started_dv/

And did:
```

cd hw/ip/aes/dv
make
```

I got error for openssl/conf.h file from gcc (My CentOS 7 laptop didn't have openssl installed to begin with).

I had to do:

```
sudo yum install openssl11-libs
sudo yum install openssl11-devel
sudo yum install epel-release
sudo yum -y install openssl-devel
```

After the above, I didn't want to recerate the fusesoc stuff, so ran VCS myself and gcc threw an error around -std=c99, hence added it myself. 

Maybe the takeaway here is the lack of openssl at my end. Please consider adding it to System Requirements page:

https://docs.opentitan.org/doc/ug/install_instructions/

Special thanks to Pirmin for taking time out during your vacation!

Regards
Srini

**Comment by cindychip** [comment] 2020-08-31 18:06
Hi Srini,

Thank you for reporting and debugging with this issue. I am not very familiar with CentOS 7 or AES... but one thing we should take action is to update the https://docs.opentitan.org/doc/ug/getting_started_dv/ instruction. As Pirmin mentioned, the DV flow does not support `make` anymore, instead we are using [dvsim](https://github.com/lowRISC/opentitan/tree/master/util/dvsim).

So as Pirmin mentioned, you can run AES DV with:
```
cd hw/ip/aes/dv
/util/dvsim/dvsim.py hw/ip/aes/dv/aes_sim_cfg.hjson -t vcs --purge
```

Not sure if that helps, but I will file an issue to update the getting_started_dv instruction.
Thank you again for your feedback!

Cindy

**Comment by svenka3** [comment] 2020-08-31 18:17
Fixing Getting started DV guide would certainly benefit new users. Also please consider adding the CentOS7 "yum install" steps if you feel appropriate.

Thanks for this vibrant community support, am enjoying it!

Regards
Srini

**Comment by rswarbrick** [comment] 2020-09-01 08:46
I'm not massively keen on listing installation commands for every distro, but I suppose we could include rpm/yum based commands for those poor souls on a RedHat-derived distribution :-) I definitely don't want to start giving instructions for Arch, Gentoo etc!

@imphil, @asb: What do you think?

The apt-based commands in our [install instructions](https://docs.opentitan.org/doc/ug/install_instructions/) page instal `libssl-dev`, which I think contains the relevant headers and libraries.

**Comment by imphil** [comment] 2020-09-01 10:09
Yeah, extending the documentation for RHEL/CentOS is sensible, it's the most used distribution in the hardware world.

**Comment by sriyerg** [comment] 2020-09-02 17:36
> Thanks @vogelpi and @rasmus-madsen for timly response. To run, I read:
> 
> https://docs.opentitan.org/doc/ug/getting_started_dv/
> 
> And did:
> 
> ```
> 
> cd hw/ip/aes/dv
> make
> ```
> 
> I got error for openssl/conf.h file from gcc (My CentOS 7 laptop didn't have openssl installed to begin with).
> 
> I had to do:
> 
> ```
> sudo yum install openssl11-libs
> sudo yum install openssl11-devel
> sudo yum install epel-release
> sudo yum -y install openssl-devel
> ```
> 
> After the above, I didn't want to recerate the fusesoc stuff, so ran VCS myself and gcc threw an error around -std=c99, hence added it myself.
> 
> Maybe the takeaway here is the lack of openssl at my end. Please consider adding it to System Requirements page:
> 
> https://docs.opentitan.org/doc/ug/install_instructions/
> 
> Special thanks to Pirmin for taking time out during your vacation!
> 
> Regards
> Srini

As you now by now, `make` is deprecated. Sims / regressions are to be run with `util/dvsim/dvsim.py

**Comment by sriyerg** [comment] 2020-09-22 17:11
I will prepare a fix for this soon.

**Comment by svenka3** [comment] 2020-12-29 16:29
Today I was trying to bring up OpenTitan on a different CentOS 7 laptop and was looking for the "yum install" commands, looks like the Install instructions at https://docs.opentitan.org/doc/ug/install_instructions/

Does not seem to list them explicitly for CentOS. Is this intended?

Thanks

**Comment by vogelpi** [comment] 2021-01-04 08:07
Hi Srini,
thanks for getting back to this. The install instructions state:
```
On RHEL/CentOS not all required packages are part of the base distribution; however, they can be installed easily. All required packages except for a C/C++ compiler can be obtained by enabling the EPEL repository.
```
And then there is a link to [how the EPEL repository can be enabled](https://fedoraproject.org/wiki/EPEL). On CentOS 7 this would be via:
```
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```
Since I am not to familiar with CentOS (I have access to some machines but without root access, so can't install packages), I am wondering: Does that already install those required openssl packages? They are listed in the in the [EPEL list](http://mirror.inode.at/epel/7/x86_64/Packages/o/) but I am not sure if the user still needs to explicitly install them after enabling EPEL.

**Comment by svenka3** [comment] 2021-01-04 08:16
Thanks for the response. Below are my notes from recent bring-up of OT on CentOS 7. I do recall some of the packages not being available (yum install stuff), but it worked nevertheless. 

https://github.com/svenka3/opentitan/blob/master/tmp_VW/CentOS_Install_notes.md

HTH
Srini

**Comment by vogelpi** [comment] 2021-01-20 17:53
Thanks for sharing your notes @svenka3 . I've finally managed to create a PR #4897.

@sriyerg, since you re-opened this issue: Assuming this PR is getting merged, is there anything else that needs to be done for this issue?

**Comment by sriyerg** [comment] 2021-01-20 18:38
I reopened because I had accidentally closed it :) Your PR probably fully addresses this issue, so it may be closed as long as @svenka3 is happy with it.

**Comment by vogelpi** [comment] 2021-01-21 09:13
Ah, I see. Thanks @sriyerg for letting me know :+1:

**Comment by vogelpi** [comment] 2021-01-21 13:14
I am closing this now as the corresponding PR has been merged. But feel free to reopen it Srini if necessary.

**Closed by vogelpi** 2021-01-21 13:14 UTC
Labels: Component:DV, Priority:P2, Type:Bug
