### ISSUE TITLE
[dv/ast] Provide flags to run with calibrated USB frequency

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#11264] opened 2022-03-04 22:27 UTC
The current ast model seems to come up with pre-calibration USB frequency. For most tests we expect the USB frequency to be post-calibration at nominal +- 0.25%. There are tests that perform calibration, and for those we can expect a pre-calibration frequency.

The ask is to provide some way to configure the AST with post-calibration USB frequency so the majority of tests won't need to worry about calibration.

**Comment by tjaychen** [comment] 2022-03-04 22:29
@Jacob-Levy Could you add a plugarg or something for it? Similar to the aon frequency speed-up?

**Comment by Jacob-Levy** [comment] 2022-03-04 22:34
Can those tests start with a CSR wriet to InitEn address? Or add to the init of those tests?

**Comment by tjaychen** [comment] 2022-03-04 22:35
hey Jacob, these tests (software tests), should include the ast / otp init already.
I think the issue is these are init'd to 48MHz +/- 2.5%, and for example fails our frequency measurement tests (this is a security countermeasure test).

**Comment by Jacob-Levy** [comment] 2022-03-04 22:46
The calibrated USB clock is not in spec for the OS model?

**Comment by tjaychen** [comment] 2022-03-04 22:55
it's the first case. Instead of 48MHz, we are getting 47.2MHz because the ast modeled usb drift.
@matutem has a separate test case, where for security purposes we have hardware that measures the usb frequency and we expect 48MHz. 

So we just want to be able to test under ideal circumstances whether this behaves correctly.

**Comment by Jacob-Levy** [comment] 2022-03-04 23:00
Let me check if I can diable the drift... will use plusargs if needed.

**Comment by Jacob-Levy** [comment] 2022-03-04 23:08
rand32 = $urandom_range((9'd416), -(9'd416));  // +/-416ps (+/-2% max)
I was aiming to 48MHz +/-2%. Need to check my calulations

**Comment by Jacob-Levy** [comment] 2022-03-04 23:29
48NHz - 2.5%  = 46,8MHz  & 
48MHz + 2.5% = 49.2MHz
So for ref_val=0 (no beacon) 47.2MHz is within spec. turn on the beacon and you get 48MHz.

**Comment by tjaychen** [comment] 2022-03-04 23:30
yes that's true. What i'm trying to say is that not every test will turn on the beacon because the usb overhead is very high.
So we'd like the option for some tests, to pretend like the beacon is turned on and that everything is behaving well.

There will be separate tests to check the beacon calibration.

**Comment by Jacob-Levy** [comment] 2022-03-04 23:37
OK, I will add a plusargs for becon set (ref_val=1)...

**Comment by tjaychen** [comment] 2022-03-04 23:38
thank you Jacob!

**Comment by Jacob-Levy** [comment] 2022-03-04 23:42
Yes. 
If you don't set the plusargs it will stay as it is now. In any case, it will only apply to the calibrated clock.

**Comment by Jacob-Levy** [comment] 2022-03-04 23:53
+usb_beacon_on=n   -  n  us is  from the clock calibration to  becon on.

**Comment by Jacob-Levy** [comment] 2022-03-05 10:26
@matutem  @tjaychen  Addressed by [AST] Add usb_beacon_on plusargs option to usb_osc.sv #11275

**Comment by tjaychen** [comment] 2022-03-07 18:29
> @matutem @tjaychen Addressed by [AST] Add usb_beacon_on plusargs option to usb_osc.sv #11275

thanks @Jacob-Levy , i'll let @matutem approve and merge the PR.

**Comment by matutem** [comment] 2022-03-08 18:47
@Jacob-Levy, the flag is confusing. The intent is to have two modes:
- the current mode where the usb comes up un-calibrated,
- a mode that starts up with a calibrated USB clock, to be enabled by a runtime flag.

Mentioning "beacon" is not helpful: perhaps it relates to the implementation, but it obscures the intent of the flag since most people should not need to know implementation details. A straight boolean flag named like +usb_clk_calibrated, or some such would be much simpler.

**Comment by Jacob-Levy** [comment] 2022-03-08 18:57
Not what I was asked to do... 
I was asked to bypass the USB beacon that is not available to make the USB clock accurate.
If you use +usb_beacon_on=0, the USB clock will be acurate as soon at the AST init is done. 
The AST init done a simple CSR write to offset AST(0x7c).

**Comment by matutem** [comment] 2022-03-10 00:54
Jacob, the ask is to fix this issue, and https://github.com/lowRISC/opentitan/pull/11275 you closed dealt with implementation. For simulation we always write to AST 0x7c, but that is not enough for full calibration. I thought the PR you closed was converging to some solution using +usb_clk_calibrated.

**Comment by Jacob-Levy** [comment] 2022-03-10 01:05
I added two runtime flags to address the issue, +beacon_on that bypass the USB beacon that makes the clock accurate and a new flag as you requested +usb_clk_calibrated that calibrate the clock from time 0. 
Both flags are needed and the code was tested to perform what is needed including the message.
Will you accept the code as is?

**Comment by Jacob-Levy** [comment] 2022-03-12 22:05
@sriyerg @matutem The usb_osc.sv file in dispute was remove from this PR #11368.
Will issue a separate PR for the usb_osc.sv when the current AST flag code is understood by DV.

**Comment by Jacob-Levy** [comment] 2022-03-12 22:11
Following is that latest code of the new flags:

```
integer BEACON_RDLY;
logic usb_beacon_on;
logic usb_clk_calibrated;

initial begin
  if ( !$value$plusargs("usb_beacon_on=%d", BEACON_RDLY) ) begin
    BEACON_RDLY = 0;
    usb_beacon_on = 1'b0;
  end else begin
    usb_beacon_on = 1'b1;
  end

  if ( !$value$plusargs("usb_clk_calibrated=%d", usb_clk_calibrated) ) usb_clk_calibrated = 1'b0;

end
```

**Comment by Jacob-Levy** [comment] 2022-03-12 22:23
Using 'if' for flags exist in the OS inseveral non vendor files too, e.g., gpio
```
    if ($value$plusargs("no_pullup_pulldown=%0b", no_pullup_pulldown)) begin
      if (no_pullup_pulldown == 1'b1) begin
        cfg.pullup_en   = 1'b0;
        cfg.pulldown_en = 1'b0;
      end
    end
```

**Comment by Jacob-Levy** [comment] 2022-03-12 22:39
Please coment and let me know if you accept the usb_osc.sv as is and I will  PR it.
Thanks, Jacob.

**Comment by matutem** [comment] 2022-03-15 22:06
Sorry, I got too busy and lost track of this issue.

Jacob, which PRs are open to deal with this? I know there was #11275, but it was closed. You seem to suggest there was another PR created, or that a new one should be created as described in your last comment? If so, for DV we just need boolean behavior, meaning creating a plusargs flag that calibrates the clock right away, essentially as if BEACON_RDLY was zero (if I understand BEACON_RDLY correctly). Does this make sense to you?

**Comment by Jacob-Levy** [comment] 2022-03-15 22:23
I pull the file from the previous PR  since I did not agree to Sri proposed changes.

I have simplified & renamed and left one flag that I think will work for you (see description above).

If this will work for you, I can do a quick PR of the usb_obs.sv.

**Comment by sriyerg** [comment] 2022-03-15 23:39
This is too trivial a thing to be arguing so much over about. Your latest code with a single plusarg looks good to me.

**Comment by Jacob-Levy** [comment] 2022-03-15 23:43
Will PR it, Thanks!

**Comment by Jacob-Levy** [comment] 2022-03-16 06:29
File added to PR [ast] Fix CDC and DFT issues #11439

**Closed** 2022-04-14 16:00 UTC
Labels: Priority:P1, Type:Enhancement, Component:RTL, IP:ast, Milestone:V2
