### ISSUE TITLE
[cryptotest]  //sw/device/tests/crypto/cryptotest:drbg_kat

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#22209] opened 2024-03-23 05:02 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

```shell
[2024-03-23T04:39:40.894Z INFO  harness] vendor: nist, test case: 6
[2024-03-23T04:39:40.894Z INFO  opentitanlib::test_utils::rpc] Sending: "Drbg"
[2024-03-23T04:39:40.901Z INFO  opentitanlib::test_utils::rpc] Sending: {"entropy":[162,1,5,244,225,238,117,198,137,137,54,127,78,201,156,115,245,190,4,192,94,80,9,157,75,10,210,38,42,237,23,149,178,63,213,133,143,186,150,200,177,154,0,181,103,253,18,227],"entropy_len":48,"personalization_string":[],"personalization_string_len":0,"reseed":1,"reseed_entropy":[154,146,38,164,179,128,157,42,63,159,48,213,91,159,205,31,104,159,112,109,193,130,233,235,103,37,241,17,222,48,180,243,63,142,32,65,238,189,177,38,234,98,68,13,28,193,110,23],"reseed_entropy_len":48,"reseed_additional_input":[],"reseed_additional_input_len":0,"additional_input_1":[],"additional_input_1_len":0,"additional_input_2":[],"additional_input_2_len":0,"output_len":64}
[2024-03-23T04:39:41.679Z  console]RESP_OK:{"output":[81,159,203,7,143,227,75,227,136,193,209,225,219,68,238,88,106,30,124,34,9,125,47,108,135,62,20,233,240,157,224,233,183,92,154,175,210,229,131,161,159,80,89,99,46,229,25,230,61,51,227,89,61,55,32,54,8,160,229,58,134,247,30,181],"output_len":64} CRC:321997622

[2024-03-23T04:39:41.702Z INFO  harness] Test counter: 8
[2024-03-23T04:39:41.702Z INFO  harness] vendor: nist, test case: 7
[2024-03-23T04:39:41.702Z INFO  opentitanlib::test_utils::rpc] Sending: "Drbg"
[2024-03-23T04:39:41.709Z INFO  opentitanlib::test_utils::rpc] Sending: {"entropy":[221,105,82,230,194,227,244,136,56,139,163,118,177,10,237,141,5,150,84,198,103,94,8,88,24,56,73,182,113,36,48,166,39,162,141,189,53,158,130,124,22,217,53,113,17,48,175,62],"entropy_len":48,"personalization_string":[],"personalization_string_len":0,"reseed":1,"reseed_entropy":[240,14,235,221,8,145,130,147,21,36,65,27,230,74,172,24,119,155,107,199,113,91,245,24,224,162,245,70,134,208,14,166,152,252,137,228,9,221,110,117,1,133,47,251,185,161,96,223],"reseed_entropy_len":48,"reseed_additional_input":[],"reseed_additional_input_len":0,"additional_input_1":[],"additional_input_1_len":0,"additional_input_2":[],"additional_input_2_len":0,"output_len":64}

160:Finished test test_drbg: Err(Timed Out

Stack backtrace:
   0: <T as opentitanlib::test_utils::rpc::UartRecv>::recv
   1: harness::main
   2: std::sys_common::backtrace::__rust_begin_short_backtrace
   3: std::rt::lang_start::{{closure}}
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:524:40
      std::panicking::try
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:488:19
      std::panic::catch_unwind
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:524:40
      std::panicking::try
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:488:19
      std::panic::catch_unwind
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/rt.rs:148:20
   5: main
   6: <unknown>
   7: __libc_start_main
   8: _start)
Error: Timed Out
```

### Steps to Reproduce

- GitHub Revision: 6d3cb9a1f826838a6ac2d405affb6e3fdb903022 `earlgrey_es_sival`
- Bazel terget: //sw/device/tests/crypto/cryptotest:drbg_kat_silicon_owner_prodc_rom_ext

Should be reproducible with `sival` sku as well.

### Tests with similar or related failures

- [ ] //sw/device/tests/crypto/cryptotest:drbg_kat_silicon_owner_prodc_rom_ext

**Comment by moidx** [comment] 2024-03-23 05:03
CC @jadephilipoom @milesdai

**Comment by andreaskurth** [comment] 2024-04-12 15:53
This problem occurs in silicon but not on the FPGA. It may be that we fixed it on `master`. To be seen if it can be reproduced on the sival branch.

**Comment by andreaskurth** [comment] 2024-04-26 15:58
@moidx will check this test again to determine if issue still exists. May be related to the EDN KAT failure (high entropy consumption).

**Comment by vogelpi** [comment] 2024-05-09 14:26
After including the keymgr fix (see https://github.com/lowRISC/opentitan/issues/22819#issuecomment-2095648654), the test still times out for `sival` (couldn't test `prodc`):
- `//sw/device/tests/crypto/cryptotest:drbg_kat_silicon_owner_sival_rom_ext`

See the attached log: 
[drbg_kat.txt](https://github.com/lowRISC/opentitan/files/15263519/drbg_kat.txt) Thanks @nasahlpa !

We should continue investigating this.

**Comment by h-filali** [comment] 2024-05-13 15:19
I just ran `//sw/device/tests/crypto/cryptotest:drbg_kat_fpga_cw310_test_rom`, which passes on our workstation.
I used the current master branch 5a111d3198

[test.log](https://github.com/lowRISC/opentitan/files/15296600/test.log)

**Comment by vogelpi** [comment] 2024-05-16 20:43
I've now locally defined the `fpga_cw310_sival_rom_ext` environment for this test based on the current earlgrey_es_sival branch (9ee2a4a920). It passes on FPGA.

**Comment by vogelpi** [comment] 2024-05-16 21:41
I made some further changes to the environment, e.g., reducing the reseed interval for keymgr, modifying the reseed interval and generate length for EDN0 etc.  and I now see random timeouts on FPGA for this test. The failures are not occurring for the exact same DRBG blocks but sooner or later the test fails.

Configuring extremely high reseed intervals for EDN0 (meaning EDN0 will never do a reseed from ENTROPY_SRC during the test) doesn't improve the situation. Changing the generate length for EDN0 also doesn't seem to have a notable impact. The only thing that helps is increasing the reseed interval of keymgr (reducing background EDN0 consumption).

This tells me that at least for ES:
1. We don't have an issue inside EDN (in this test, only keymgr consumes entropy from EDN0 in the background).
2. We don't have an issue with ENTROPY_SRC (in this test, the SW instance runs in fully deterministic mode and the END0 reseed interval has no obvious impact).
3. There is an issue in CSRNG when it has to arbitrate requests between different instances. In this test, its the SW instance (Instance 2) and the EDN0 instance (Instance 0). Instance 0 can be made to only trigger Generate commands whereas Instance 2 produces Instantiate, Reseed and Generate commands.

Tomorrow, I'll continue debugging this. I would like to see if:
1. This can be reproduced on master as well somehow? Because we made some changes to CSRNG in the meantime. In particular, waiting for CSRNG to become idle before checking the command ready bit and before writing commands was known to not work very well. Between software reading the idle status / the command ready bit and providing the first command part (triggering internal arbitration), another instance may issue a command. We had an issue for that actually.
2. If we can narrow down the issue to a particular CSRNG command.

FYI @moidx, @timothytrippel

**Comment by vogelpi** [comment] 2024-05-17 10:29
I turns out that when undoing the recent keymgr hardware and configuration fixes, we also have the problem on master. I've now come up with an software fix for this, see #23166 for Earlgrey PROD. I believe a slightly different fix should be feasible for ES, I'll work on that now.

**Comment by vogelpi** [comment] 2024-05-17 13:09
The fix for ES and the old CSRNG version with the incomplete SW command interface is here: https://github.com/lowRISC/opentitan/pull/23169.

I've locally modified the keymgr and EDN configuration to maximize the load onto CSRNG while running `drbg_kat` in the `fpga_cw310_sival_rom_ext` environment and with this fix in place, the test reliably passes.

**Comment by vogelpi** [comment] 2024-05-17 13:10
Once the above two PRs are merged, I'll close this issue here.

**Closed** 2024-05-17 16:00 UTC
Labels: SW:cryptolib, Component:TestTriage
