### ISSUE TITLE
[util, reggen] Auto-generate register reset values

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#1978] opened 2020-04-16 14:12 UTC
In many peripherals, we hardcode the register reset values such as:
#`define PINMUX_OUTSEL_RESET_DEFAULT 0x20820820`
These could be auto generated, however there are some difficulties:

- I think the corresponding `*.hjson` files define reset value son per field basis, which then probably would have to be accumulated into a single 32bit value (If I remember it correctly).
- It would be required to differentiate between `w1c`, `r` and `rw` type of registers when generating the defines, as default reset values as they are not always applicable for reset operations.

It would be nice to have these values autogenerated, but the question is - do you think it is worth, giving potentially non trivial implementation?

**Comment by silvestrst** [comment] 2020-04-16 14:12
@gkelly @lenary

**Comment by lenary** [comment] 2020-05-06 10:50
Duplicate of #1977

**Closed by lenary** 2020-05-06 10:50 UTC
Labels: Component:SW, Component:Tooling
