### ISSUE TITLE
Incorrect mapping of LEDS to GPIOs with Nexys Video FPGA

### ISSUE THREAD

**Issue by labbott** [lowRISC/opentitan#1546] opened 2020-02-13 19:33 UTC
The mapping of GPIOs to LEDS appears to be incorrect on the Nexys Video Artix-7. In hw/top_earlgrey/data/pins_nexysvideo.xdc I see 

```
set_property -dict { PACKAGE_PIN T14   IOSTANDARD LVCMOS25 } [get_ports { IO_GP8 }]; #IO_L15P_T2_DQS_13 Sch=led[0]
set_property -dict { PACKAGE_PIN T15   IOSTANDARD LVCMOS25 } [get_ports { IO_GP9 }]; #IO_L15N_T2_DQS_13 Sch=led[1]
set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS25 } [get_ports { IO_GP10 }]; #IO_L17P_T2_13 Sch=led[2]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS25 } [get_ports { IO_GP11 }]; #IO_L17N_T2_13 Sch=led[3]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS25 } [get_ports { IO_GP12 }]; #IO_L14N_T2_SRCC_13 Sch=led[4]
set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS25 } [get_ports { IO_GP13 }]; #IO_L16N_T2_13 Sch=led[5]
set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS25 } [get_ports { IO_GP14 }]; #IO_L16P_T2_13 Sch=led[6]
set_property -dict { PACKAGE_PIN Y13   IOSTANDARD LVCMOS25 } [get_ports { IO_GP15 }]; #IO_L5P_T0_13 Sch=led[7]
```

Which should map GPIO8->LED0 GPIO9->LED1 etc. 

When actually running the mapping is GPIO7 -> LED0, GPIO8 -> LED1.

Reproduce: It's easy to see this with the sample hello world application. If you type on the keyboard to watch the ascii on the LEDs, LED0 never lights up. This was also observed in the Tock operating system.

This was reproduced as of cb346df7417a8bea707ade8cde95a00aa68a5d44

**Comment by sjgitty** [comment] 2020-02-14 19:30
Hi @labbott thanks for reporting this. I don't myself have an Artix-7 on my
desk to confirm this. Can @imphil or @eunchan or @moidx or @msf or
@tjaychen confirm and fix?

**Comment by mdhayter** [comment] 2020-02-14 19:43
Historically I used the LEDs a bunch and with the very old hello_world did see the bits flip as expected for 'a' vs 'b', so believe the .xdc file is correct.

(I used some of the LEDs for debug info when developing the USB code, so it is possible that something bad happened when that was merged into top)

**Comment by imphil** [comment] 2020-02-20 17:21
The XDC file is more or less identical to https://github.com/Digilent/digilent-xdc/blob/master/Nexys-Video-Master.xdc, so it should be correct. So something probably goes wrong between the GPIO module, pinmux, and all of that.

I can't have a look right now, but please let us know if that's blocking for you @labbott so I can prioritize this.

**Comment by openhardwarefan** [comment] 2020-03-03 04:28
@imphil I found where the issue is caused:

In top_earlgrey.h.tpl, PINMUX_PERIPH_OUTSEL_IDX_OFFSET should be defined as 3 instead of 2 for output GPIO.

#define PINMUX_PERIPH_OUTSEL_IDX_OFFSET 3

**Comment by imphil** [comment] 2020-03-03 14:51
Good find! Would you mind opening a pull request with this change?

**Closed** 2020-03-09 08:12 UTC
Labels: Component:FPGA, Priority:P2, Type:Bug
