### ISSUE TITLE
[i2c] test failure with cdc instrumentation

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#17090] opened 2023-01-14 02:45 UTC
### Description

Some i2c tests are failing with cdc instrumentation turned on.  I dug into this a bit..
it seems like when the dv environment issues a stop, the following waveform is created:

![image](https://user-images.githubusercontent.com/1026250/212447248-5f452a4b-ba1e-459b-8bca-4584df52665e.png)

Specifically, `sda_i` is first driven 0 at exactly the same time `scl_i` transitions.  `sda_i` is then raised later to create the stop condition.

This works fine when we are using vanilla synchronizers, since both signals get the same delay and the start/stop detection always works out.

When we turn on cdc instrumentation however, they can get delayed differently.  And this can cause the device to trigger a false restart, which causes the tests to fail.

I dug around this a bit, and my interpretation of the spec is that even on the "pre-drive" prior to a `stop`, we still have to satisfy timing requirements. Ie, we cannot have `sda_i` go low so close to the clock edge, and instead need to give it some "breathing" room (data setup requirement).  I did some quick hacks in `i2c_driver` for this, and the test began to pass. 

Let me know what you guys think.
@jdonjdon 
@a-will

**Comment by jdonjdon** [comment] 2023-01-14 03:03
@tjaychen Yeh it needs abide tSU,STO, and from the waveform you show, my driver violates it

**Comment by jdonjdon** [comment] 2023-01-14 03:04
Sorry I types wrong comment. So I deleted it.

**Comment by tjaychen** [comment] 2023-01-17 18:25
@jdonjdon what did you mean by false restart in nack-stop case?

**Comment by a-will** [comment] 2023-01-17 18:45
> I dug around this a bit, and my interpretation of the spec is that even on the "pre-drive" prior to a `stop`, we still have to satisfy timing requirements. Ie, we cannot have `sda_i` go low so close to the clock edge, and instead need to give it some "breathing" room (data setup requirement). I did some quick hacks in `i2c_driver` for this, and the test began to pass.

Agreed. It's the responsibility of all chips to ensure `scl` and `sda` do not change close to each other, and even the host must continuously sample scl to check for when it actually transitions (requirement for host support of clock stretching). For a stop condition, there is an explicit setup time requirement between the `scl` rising edge and `sda` rising edge.

**Comment by GregAC** [comment] 2023-02-21 16:03
I believe this is fixed by https://github.com/lowRISC/opentitan/pull/17321 need to confirm before closing this issue.

**Comment by crteja** [comment] 2023-03-22 16:09
Estimates for M2.5
> estimate 16
> remaining 2023-03-22 1

**Comment by GregAC** [comment] 2023-04-03 17:05
Closing as the initial issue reported (CDC failures caused by incorrect behaviour from the I2C UVM driver) is fixed by #17321

**Closed by GregAC** 2023-04-03 17:05 UTC
Labels: Component:DV, Priority:P2, IP:i2c, Triaged
