### ISSUE TITLE
[flash_ctrl] Flash Bank Erase Seems To Give Errors

### ISSUE THREAD

**Issue by TimEwins** [lowRISC/opentitan#10142] opened 2022-01-18 12:20 UTC
Whilst deveoping the host_ctrl_if test, I have noticed an issue regarding Flash Bank Erase (note that Page Erase seems to be OK).

I have attempted to debug the issue, but now the same issue is being seen by @nikola-miladinovic so we think ths may be a Bug.

The test below is created to show this potential bug, other code has been commented out.

When I enable the Data Partitions for erase, and then attempt an erase (by writing to the CONTROL register) I get the following error message from the TB

xmsim: *E,ASRTST (/scratch/google/goo_opentitan/tim/host_crl_hw_if2/flash_ctrl_wrapper-sim-xcelium/default/src/lowrisc_ip_flash_ctrl_0.1/rtl/flash_mp.sv,318): (time 8238419 PS) Assertion tb.dut.u_flash_mp.BankEraseData_a has failed 
8238419 PS + 16 (Assertion output stop: tb.dut.u_flash_mp.BankEraseData_a = failed)

The reposirty branch is
https://github.com/TimEwins/opentitan/tree/host_crl_hw_if2

(please not that there is a typo in crl .. not ctl)

The command to reproduce is 
./util/dvsim/dvsim.py hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson -i host_ctrl_hw_if --tool xcelium -v h --fixed-seed 1 --max-parallel 1 --purge

**Comment by tjaychen** [comment] 2022-01-18 18:24
hi @TimEwins ,
can you make sure the [following](https://docs.opentitan.org/hw/ip/flash_ctrl/doc/index.html#Reg_mp_bank_cfg_shadowed) is set when doing bank erase? The bank erase uses a different "enable" from the normal mp controls since it applies to the entire bank.

**Comment by TimEwins** [comment] 2022-01-26 17:29
Hi @tjaychen 

I can confirm that your suggestion fixes the problem I was seeing.

I assume the person that raises the issue in the first place can close it ? Or is that not the case ?

**Comment by tjaychen** [comment] 2022-01-26 19:45
Ah we do not have strict rules, either is okay.
Since you've confirmed its behaving as expected now, I will close the issue.

**Closed by tjaychen** 2022-01-26 19:45 UTC
Labels: Priority:P1, Type:Bug, Component:RTL
