### ISSUE TITLE
[flash_ctrl] PHY CONTROLLER ARBITRATION IS NOT WORKING AS EXPECTED

### ISSUE THREAD

**Issue by nikola-miladinovic** [lowRISC/opentitan#10592] opened 2022-02-03 20:02 UTC
When parallel  host reads and controller programs
 are sent, everything what controller send is accepted without any arbitration. Operations are done on same bank and both starting on address 0 (but until controller program, addresses diverge).

**Comment by tjaychen** [comment] 2022-02-03 20:07
thanks Nikola, if you can let me know how to reproduce, I will have a look.

**Comment by nikola-miladinovic** [comment] 2022-02-03 20:12
Branch: https://github.com/nikola-miladinovic/opentitan/tree/flash_ctrl_phy_arb_issue.
Seed 1 on Xcelium ( i would say any seed is valid since test is passing)

**Comment by tjaychen** [comment] 2022-02-03 20:14
o sounds good. So just run any test and look at the waveforms when they're targeting the same bank, is that right?

**Comment by tjaychen** [comment] 2022-02-03 23:25
@nikola-miladinovic 
I ran a test and looked at the waves, this actually looks like it's working as expected to me.

![Screenshot from 2022-02-03 15-20-41](https://user-images.githubusercontent.com/1026250/152445848-cd362df0-e46b-4383-a257-187f603c74fd.png)

If you look at the above diagram, it's captured from one of the completed tests.

You'll see that the device is currently doing host reads while another controller request is going at the same time. Every time the host read completes (`host_req_rdy_o`) The arbitration count increments because the controller has "lost".

After the count gets to 4, the host request is dropped (`host_req_masked`) to ensure the controller has a chance to complete.  You then see `prog_done_o` go high, indicating the controller activity has completed, at which point the count also goes back to 0.  Now the host reads are favored again compared to the pending program, and the arbitration count starts to tick.

Let me know which part didn't seem right to you, it would be great if you show a wave also.

**Comment by nikola-miladinovic** [comment] 2022-02-04 17:47
Tim, thanks for explanation. I was confused since at Core TL Interface, I saw posted transactions from controller. Now I have updated this branch so that you can see how i manage to invoke at same address controller program and host read and also i have added check that host read data lost priority and read what was written by controller. Unfortunately, scoreboard and three tests need to be updated. I will open small PR for that (handling non blocking host reads) which would be needed to be merged first.

**Comment by tjaychen** [comment] 2022-02-04 17:58
thank you @nikola-miladinovic 
if all seems right to you, feel free to close the issue.

**Closed** 2022-02-04 17:59 UTC
