### ISSUE TITLE
meson_init.sh not working

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#12776] opened 2022-05-19 17:46 UTC
On a clean checkout running **meson_init.sh** does not complete correctly and returns with the following error (this is before trying to build and run any specific test)

```
sw/device/silicon_creator/rom_ext/meson.build:167:6: \
ERROR: Program '/projects/goo_opentitan/opentitan/build-out/sw/host/rom_ext_signer' \
not found or not executable.
```

Is there a soultion for this? I currently have to work around it by removing references to rom_ext_signer from the following:
sw/device/tests/meson.build
sw/device/silicon_owner/bare_metal/meson.build
sw/device/silicon_creator/rom_ext/meson.build

I appreciate that moving forward Bazel will be used instead but I believe that Meson is still used in the nightly regression so I assume we need it to be working at least for now and it is still the system I use to build and run tests during development. As an aside, is there an example of running a top level test using only bazel (any simple smoketest as an example)?

On an email with @timothytrippel it was suggested that there would be no need to use bazel with the meson build but I did notice in the file below it explicitly references a bazel generated file for the rom_ext_signer, I can generate this with bazel but meson does not pick it up.
sw/host/meson.build
line 22

`command: ['cp', meson.project_source_root() / 'bazel-bin/sw/host/rom_ext_image_tools/signer/rom_ext_signer', '@OUTPUT@'],`

**Comment by timothytrippel** [comment] 2022-05-20 07:55
> On a clean checkout running **meson_init.sh** does not complete correctly and returns with the following error (this is before trying to build and run any specific test)

Hmmm, that's odd, I just pulled from master and it seems to be working on my machine.

> ```
> sw/device/silicon_creator/rom_ext/meson.build:167:6: \
> ERROR: Program '/projects/goo_opentitan/opentitan/build-out/sw/host/rom_ext_signer' \
> not found or not executable.
> ```
> 
> Is there a soultion for this? I currently have to work around it by removing references to rom_ext_signer from the following: sw/device/tests/meson.build sw/device/silicon_owner/bare_metal/meson.build sw/device/silicon_creator/rom_ext/meson.build
> 
> I appreciate that moving forward Bazel will be used instead but I believe that Meson is still used in the nightly regression so I assume we need it to be working at least for now and it is still the system I use to build and run tests during development. As an aside, is there an example of running a top level test using only bazel (any simple smoketest as an example)?

Normally, we would triage and solve this issue, but I'm not sure it's worth the time in this case, since once #12761 merges (hopefully tomorrow), the nightly regressions will use Bazel only.

There are several examples I will share with you offline, but to also provide an example here, you can use the `bazel build //<bazel package>:<bazel target>` command to build any SW target. For example, to build the UART smoketest for the DV sim platform, you can use:

`bazel build //sw/device/tests:sim_dv_uart_smoketest`

Note: there was a slight cleanup in #12761, so after it merges you will use `bazel build //sw/device/tests:uart_smoketest_sim_dv` (the device/platform string will come after the test name)

Alternatively, you could also use: `bazel build --define DISABLE_VERILATOR_BUILD=true --test_tag_filters=dv //sw/device/tests:uart_smoketest` (but that is a little more verbose).

> On an email with @timothytrippel it was suggested that there would be no need to use bazel with the meson build but I did notice in the file below it explicitly references a bazel generated file for the rom_ext_signer, I can generate this with bazel but meson does not pick it up. sw/host/meson.build line 22

Oh you are right! I forgot about this hack we added to bridge the gap until we delete meson (hopefully next week, we are finishing one more task).

> `command: ['cp', meson.project_source_root() / 'bazel-bin/sw/host/rom_ext_image_tools/signer/rom_ext_signer', '@OUTPUT@'],`

Sorry for any inconvenience on this, and please let me know if you are having any Bazel issues. I'm going to close this issue, and will reopen it if #12761 does not get merged by tomorrow.

**Closed by timothytrippel** 2022-05-20 07:55 UTC
Labels: SW:Build System
