### ISSUE TITLE
[otbn] RMA causes `LOCKED` Status, intended?

### ISSUE THREAD

**Issue by ctopal** [lowRISC/opentitan#14995] opened 2022-09-19 13:18 UTC
In the case of receiving RMA request, OTBN technical specification mentions a secure wipe happening but it does not mention the end state of the module. Currently even if we don't see an error, we end up in `StatusLocked` as a result of RMA request being considered a fatal error in otbn_controller.

Is this behaviour wanted? Because as far as I understand that means OTBN will not be responsive in the case of RMA entry (unless we reset it).

@GregAC @vogelpi @andreaskurth WDYT?

`util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_escalate --reseed=1 --fixed-seed=832849013 --tool=xcelium -w` can be used to see the situation.

**Comment by vogelpi** [comment] 2022-09-22 15:59
At current master (d54b1e031) this seed doesn't result in an invalid `lc_tx_t` value for `lc_rma_req_i`. 
![Screenshot from 2022-09-22 17-49-20](https://user-images.githubusercontent.com/20307557/191793674-d2a9dc35-88ea-4443-8e45-0a9280adbac5.png)

@ctopal , can you maybe also provide the git commit at which you observed this behavior? An invalid RMA request signal should cause OTBN to abort the secure wipe and lock up immediately . The rationale is that before OTBN can become operational again or before RMA can be entered, at least one full secure wipe will be performed in any case.

To answer the original question: Yes, entering the locked state upon RMA requests is intended behavior. When returning the RMA ACK to the lifecycle controller, the RMA state is entered and the chip is then reset. I can do a PR to clarify this in the documentation.

**Comment by vogelpi** [comment] 2022-09-23 12:54
The PR clarifying the documentation has been merged already (#15086). Shall we close this @ctopal ?

**Comment by ctopal** [comment] 2022-09-23 12:59
Yes I think we can close this, I'll check the invalid `lc_txt_t` part again with the latest master and open up a new issue if it appears.

**Closed** 2022-09-23 15:42 UTC
Labels: Type:Question, Component:RTL, IP:otbn
