### ISSUE TITLE
[test-triage] Bazel cache issue

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#15145] opened 2022-09-27 08:52 UTC
### Hierarchy of regression failure

Chip Level

### Failure Description

File "/root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/private/repository_utils.bzl", line 568, column 20, in load_arbitrary_tool
          ctx.extract(
  Error in extract: java.io.IOException: Error extracting /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64/rust-1.60.0-x86_64-unknown-linux-gnu.tar.gz to /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64: Unexpected end of ZLIB input stream
  ERROR: /workspace/mnt/repo_top/sw/host/opentitantool/BUILD:10:12: //sw/host/opentitantool:opentitantool depends on @rust_linux_x86_64//:toolchain_for_x86_64-unknown-linux-gnu_impl in repository @rust_linux_x86_64 which failed to fetch. no such package '@rust_linux_x86_64//': java.io.IOException: Error extracting /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64/rust-1.60.0-x86_64-unknown-linux-gnu.tar.gz to /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64: Unexpected end of ZLIB input stream
  ERROR: Analysis of target '//sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv' failed; build aborted:
  INFO: Elapsed time: 664.144s
  INFO: 0 processes.
  FAILED: Build did NOT complete successfully (246 packages loaded, 14193 targets configured)
  FAILED: Build did NOT complete successfully (246 packages loaded, 14193 targets configured)
  make: *** [/workspace/mnt/repo_top/hw/dv/tools/dvsim/sim.mk:73: sw_build] Error 1

### Steps to Reproduce

- Commit hash where failure was observed 0c214bdb3

### Tests with similar or related failures

- [ ] chip_sw_uart_rand_baudrate
- [ ] chip_sw_all_escalation_resets
- [ ] chip_sw_example_rom

**Comment by luismarques** [comment] 2022-09-27 09:02
Question for the Bazel experts: would it be possible to check that the file in the cache has the correct hash and, if it does not, emit a message at that point (with a more sensible error message), instead of erroring out during the tarball extraction process?

Given the observed behavior, it seems like a hash check is not being performed. If it is, could there be some concurrency problem where the cache (the local copy) gets corrupted after the check?

**Comment by luismarques** [comment] 2022-09-27 09:16
@engdoreis noticed that the tests where this happens seem to have higher `reseed` values. Perhaps running the test multiple times increases the probability of this issue occurring? That would be typical behavior for a concurrency issue.

**Comment by engdoreis** [comment] 2022-09-27 10:08
I also noticed that all these tests are dv only. Given that the error is happening when trying to build opentitantool, can we just remove this dependency? Or does it really use opentitantool for, let's say, signing? 
Anyway we should fix the root cause as it can impact other cases.

**Comment by drewmacrae** [comment] 2022-09-27 12:56
@jon-flatley Do we sign //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv with OpenTitanTool?

The bazel managed dv "tests" themselves don't really run anything AFAIK, they just generate the build outputs and pass. Did this occur in a workstation or in CI somewhere?

**Comment by engdoreis** [comment] 2022-09-27 13:26
I checked that opentitantool is a dependency for the tests in `sw/device/tests/dv`, as they use the macro `opentitan_functest`  that has the default argument `test_harness = "@//sw/host/opentitantool"`, but I'm not sure why.

We haven't seen it happening in CI, It seems to happen only in the nightlies for these tests with high reseed values.

**Comment by drewmacrae** [comment] 2022-09-27 16:28
Sorry about the signing questions, looks like none of that work is being exercised to do the signing with OTT in CI or under other tools.

@timothytrippel does dvsim.py depend on output from `bazel test sw/device/tests/dsim_dv:lc_ctrl_transition_test_sim_dv`? Could/should it be changed to depend on `bazel build`...?

I'm confused about why reseeding the tests would rebuild opentitantool.

**Comment by drewmacrae** [comment] 2022-09-28 15:17
Some of the logic that controls what runs on the host to coordinate e2e tests set this as a default for the dv tests. I'll see if I can fix it

**Comment by drewmacrae** [comment] 2022-09-28 15:59
...hmm, When the binary is signed (which the rules default to doing, bazel is using OTT to do the signing of the binaries)

After fixing the test_harness dependency for things that only target dv, and then hacking out the other targets for a test, I still see:

```bazel query "somepath(sw/device/tests:uart_smoketest_sim_dv, sw/host/opentitantool)"
//sw/device/tests:uart_smoketest_sim_dv
//sw/device/tests:uart_smoketest_prog_sim_dv
//sw/device/tests:uart_smoketest_prog_sim_dv_bin_signed_test_key_0
//sw/host/opentitantool:opentitantool
```

We can avoid generating these artifacts if we don't need them for DV, @timothytrippel, can you confirm or assign this to someone who can confirm that this is the case before I go any further?

**Comment by timothytrippel** [comment] 2022-09-28 17:31
@drewmacrae yes we need those targets for dv, removing them will break all the nightly regressions as dvsim [expects](https://cs.opensource.google/opentitan/opentitan/+/master:hw/dv/tools/dvsim/sim.mk;drc=88ab6e2b78e22ea03766ef083f4b8b8e337aceb2;l=103) many targets to be built.

What do you mean by "after fixing the test_harness dependency for things that only target dv ... " ?

Sorry it took me a while to get to this, but this error looks like it may be transient, it looks like there was an error fetching the rust toolchain which is needed to build opentitantool which is needed to sign flash images which are needed to run tests with ROM in DV (which we already do). Let me dig in a little more to see if I can reproduce this.

**Comment by drewmacrae** [comment] 2022-09-28 17:47
Above there's discussion of the way we're adding OTT as a direct dependency to the *_sim_dv tests by setting it as a test_harness (which is incorrect, but also moot if we need signed flash images).

**Comment by drewmacrae** [comment] 2022-09-28 18:19
I'm curious, does the high reseed rate indicate we're building OTT more than once and eventually we just thrash the filesystem or network to the point where something blows up?

**Comment by timothytrippel** [comment] 2022-09-28 18:28
the nightly regressions are launched with dvsim, which launches separate VMs for each test. dvsim has two phases, a build phase and a run phase, each are executed on a separate VM I believe (tho @sriyerg please correct me if I am wrong). During the "build" phase, the HW design is elaborated and the sim model is built. During the "run" phase bazel is run to build SW images (if it is a SW top-level test being run) and then the sim is run. Since each test is run on a separate VM OTT is being built more than once. We currently don't have a remote cache setup in our internal infrastructure that runs the nightlies.

**Comment by timothytrippel** [comment] 2022-09-28 18:30
also, these machines are airgapped, so there is no network access ever happening.

**Comment by timothytrippel** [comment] 2022-09-28 19:59
I did some further digging, it looks like this is a transient issue. We did update our internal infrastructure yesterday a couple times that runs these tests, so lets wait until the next nightly regression results post to the dashboard. This error should disappear on its own.

Also, it looks like it only impacts two tests now (below), so I updated the list in the issue description above.
- chip_sw_uart_rand_baudrate
- chip_sw_all_escalation_resets

**Comment by luismarques** [comment] 2022-09-28 20:09
Thanks for all of the additional information. Even if this issue goes away, can we still try to diagnose it earlier in the build process, when the tarball is fetched, instead of failing when it is extracted? Also, where is it being fetched from (given the air gap)? What caused the fetching to fail?

**Comment by timothytrippel** [comment] 2022-09-29 00:35
So unfortunately there is not much we can do regarding when we detect this issue as it is internal to Bazel. The way we prep the airgapped system to do bazel builds is by running the [`util/prep-bazel-airgapped-builds.sh`](https://cs.opensource.google/opentitan/opentitan/+/master:util/prep-bazel-airgapped-build.sh;l=1?q=prep-baze&sq=&ss=opentitan%2Fopentitan) script to generate a directory that contains the bazel binary itself along with several caches, including: the [distdir](https://docs.bazel.build/versions/main/guide.html#distribution-files-directories), [repository cache](https://docs.bazel.build/versions/main/guide.html#the-repository-cache), a custom ot_python_wheels cache I developed (since Bazel had no way to cache python wheels), and the custom bitstreams cache. Then we move this to our airgapped system. Then when we run bazel on the airgapped system, when it initially tries to fetch all the external dependencies, it hits all of these caches rather than going to Internet.

The rust toolchain in particular is stored in the repository cache (which is pre-fetched/loaded by running the  [`util/prep-bazel-airgapped-builds.sh`](https://cs.opensource.google/opentitan/opentitan/+/master:util/prep-bazel-airgapped-build.sh;l=1?q=prep-baze&sq=&ss=opentitan%2Fopentitan) script). The tarball itself is what is stored though, so while Bazel on the airgapped system got a cache hit, when it went to unpack the tarball, it seems to have been corrupted. Without digging into the internals of the `ctx.extract` action in Bazel itself it is hard to know what caused the problem.

Hopefully that makes sense, lmk if you would like to chat more about this. Happy to share more details.

**Comment by engdoreis** [comment] 2022-09-29 17:18
Just an update, the error is transitory, but it happens frequently with different tests, the last execution we had these tests failing:
- chip_sw_flash_ctrl_clock_freqs
- chip_sw_clkmgr_off_peri
- chip_sw_clkmgr_external_clk_src_for_sw_fast
- chip_sw_rv_plic_smoketest

**Comment by jdonjdon** [comment] 2022-10-03 16:38
Add more test with the same failure signature

**Comment by timothytrippel** [comment] 2022-10-05 19:38
Reassigning to @drewmacrae as he will be triaging this further.

**Comment by drewmacrae** [comment] 2022-10-06 19:48
Some of the output from the sw_build phase is missing I'll put it here because it helps give context:
```
[make]: sw_build
# Loop through the list of sw_images and invoke Bazel on each.
# `sw_images` is a space-separated list of tests to be built into an image.
# Optionally, each item in the list can have additional metadata / flags using
# the delimiter ':'. The format is as follows:
# <Bazel label>:<index>:<flag1>:<flag2>
#
# If one delimiter is detected, then the full string is considered to be the
# <Bazel label>. If two delimiters are detected, then it must be <Bazel label>
# followed by <index>. The <flag> is considered optional.
#
# After the images are built, we use `bazel cquery ...` to locate the built
# software artifacts so they can be copied to the test bench run directory.
# We only copy device SW images, and do not copy host-side artifacts (like
# opentitantool) that are also dependencies of the Bazel test target that
# encode the software image targets.
set -e; \
for sw_image in //sw/device/tests/sim_dv:lc_ctrl_transition_test:1 //sw/device/lib/testing/test_rom:test_rom:0; do \
	if [[ -z $sw_image ]]; then \
		echo "ERROR: SW image \"$sw_image\" is malformed."; \
		echo "Expected format: <Bazel label>:<index>:<optional-flags>."; \
		exit 1; \
	fi; \
	prebuilt_path=`echo $sw_image | cut -d: -f 1`; \
	bazel_label="`echo $sw_image | cut -d: -f 1-2`_${sw_build_device}"; \
	bazel_target=`echo $sw_image | cut -d: -f 2`; \
	index=`echo $sw_image | cut -d: -f 3`; \
	flags=(`echo $sw_image | cut -d: -f 4- --output-delimiter " "`); \
	cd /workspace/mnt/repo_top; \
	if [[ ${flags[@]} =~ "prebuilt" ]]; then \
		echo "SW image \"$bazel_label\" is prebuilt - copying sources."; \
		cp /workspace/mnt/repo_top/${prebuilt_path} ${run_dir}/`basename ${prebuilt_path}`; \
	else \
		echo "Building SW image \"${bazel_label}\"."; \
		bazel_opts=" --define DISABLE_VERILATOR_BUILD=true"; \
		if [[ -z ${BAZEL_PYTHON_WHEELS_REPO} ]]; then \
			echo "Building \"${bazel_label}\" on network connected machine."; \
			bazel_cmd="./bazelisk.sh"; \
		else \
			echo "Building \"${bazel_label}\" on air-gapped machine."; \
			bazel_opts+=" --distdir=${BAZEL_DISTDIR} --repository_cache=${BAZEL_CACHE}"; \
			bazel_cmd="bazel"; \
		fi; \
		echo "Building with command: ${bazel_cmd} build ${bazel_opts} ${bazel_label}"; \
		${bazel_cmd} build ${bazel_opts} ${bazel_label}; \
		for dep in $(${bazel_cmd} cquery "labels(data, ${bazel_label})" --ui_event_filters=-info --noshow_progress --output=starlark); do \
			if [[ $dep != //hw* ]] && [[ $dep != //util* ]] && [[ $dep != //sw/host* ]]; then \
				for artifact in $(${bazel_cmd} cquery ${dep} --ui_event_filters=-info --noshow_progress --output=starlark --starlark:expr="\"\\n\".join([f.path for f in target.files.to_list()])"); do \
					cp -f ${artifact} ${run_dir}/$(basename ${artifact}); \
					if [[ $artifact == *.scr.vmem ]]; then \
						cp -f "$(echo ${artifact} | cut -d. -f 1).elf" \
							${run_dir}/$(basename "${artifact%.*.scr.vmem}.elf"); \
					fi; \
				done; \
			fi; \
		done; \
	fi; \
done;
Building SW image "//sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv".
Building "//sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv" on air-gapped machine.
Building with command: bazel build  --define DISABLE_VERILATOR_BUILD=true --distdir=/workspace/mnt/bazel/bazel-distdir --repository_cache=/workspace/mnt/bazel/bazel-cache //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (1 packages loaded, 0 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (12 packages loaded, 8 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (12 packages loaded, 8 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (12 packages loaded, 8 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (12 packages loaded, 8 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (12 packages loaded, 8 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (167 packages loaded, 5071 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (169 packages loaded, 5072 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (208 packages loaded, 6682 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (234 packages loaded, 11381 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (240 packages loaded, 11969 targets configured)
WARNING: Failed to copy /workspace/mnt/bazel/bazel-distdir/java_tools-v11.6.zip to repository cache: java.io.IOException: /workspace/mnt/bazel/bazel-cache/content_addressable/sha256/a7ac5922ee01e8b8fcb546ffc264ef314d0a0c679328b7fa4c432e5f54a86067 (Read-only file system)
WARNING: Failed to copy /workspace/mnt/bazel/bazel-distdir/java_tools_linux-v11.6.zip to repository cache: java.io.IOException: /workspace/mnt/bazel/bazel-cache/content_addressable/sha256/15da4f84a7d39cd179acf3035d9def638eea6ba89a0ed8f4e8a8e6e1d6c8e328 (Read-only file system)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (244 packages loaded, 12023 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (245 packages loaded, 12155 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
Analyzing: target //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv (246 packages loaded, 14193 targets configured)
INFO: Repository rust_linux_x86_64 instantiated at:
  /workspace/mnt/repo_top/WORKSPACE:50:10: in <toplevel>
  /workspace/mnt/repo_top/third_party/rust/deps.bzl:15:29: in rust_deps
  /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/repositories.bzl:133:14: in rust_register_toolchains
  /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
  /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/repositories.bzl:338:30: in rust_repository_set
Repository rule rust_toolchain_repository defined at:
  /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/repositories.bzl:205:44: in <toplevel>
INFO: Repository 'rust_linux_x86_64' used the following cache hits instead of downloading the corresponding file.
 * Hash '3a3bde7edd168df6852dd66a6685dbe9ac2f52addc3671bffc3ad14ae83ec1ce' for https://static.rust-lang.org/dist/rust-src-1.60.0.tar.gz
 * Hash 'b8a4c3959367d053825e31f90a5eb86418eb0d80cacda52bfa80b078e18150d5' for https://static.rust-lang.org/dist/rust-1.60.0-x86_64-unknown-linux-gnu.tar.gz
If the definition of 'rust_linux_x86_64' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'rust_linux_x86_64':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/repositories.bzl", line 170, column 43, in _rust_toolchain_repository_impl
		build_components = [load_rust_compiler(ctx)]
	File "/root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/private/repository_utils.bzl", line 310, column 24, in load_rust_compiler
		load_arbitrary_tool(
	File "/root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/private/repository_utils.bzl", line 568, column 20, in load_arbitrary_tool
		ctx.extract(
Error in extract: java.io.IOException: Error extracting /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64/rust-1.60.0-x86_64-unknown-linux-gnu.tar.gz to /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64: Unexpected end of ZLIB input stream
ERROR: /workspace/mnt/repo_top/WORKSPACE:50:10: fetching rust_toolchain_repository rule //external:rust_linux_x86_64: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/repositories.bzl", line 170, column 43, in _rust_toolchain_repository_impl
		build_components = [load_rust_compiler(ctx)]
	File "/root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/private/repository_utils.bzl", line 310, column 24, in load_rust_compiler
		load_arbitrary_tool(
	File "/root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rules_rust/rust/private/repository_utils.bzl", line 568, column 20, in load_arbitrary_tool
		ctx.extract(
Error in extract: java.io.IOException: Error extracting /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64/rust-1.60.0-x86_64-unknown-linux-gnu.tar.gz to /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64: Unexpected end of ZLIB input stream
ERROR: /workspace/mnt/repo_top/sw/host/opentitantool/BUILD:10:12: //sw/host/opentitantool:opentitantool depends on @rust_linux_x86_64//:toolchain_for_x86_64-unknown-linux-gnu_impl in repository @rust_linux_x86_64 which failed to fetch. no such package '@rust_linux_x86_64//': java.io.IOException: Error extracting /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64/rust-1.60.0-x86_64-unknown-linux-gnu.tar.gz to /root/.cache/bazel/_bazel_default/96f40d218badc03ed33c48f246ec2aa1/external/rust_linux_x86_64: Unexpected end of ZLIB input stream
ERROR: Analysis of target '//sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv' failed; build aborted: 
INFO: Elapsed time: 713.660s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (246 packages loaded, 14193 targets configured)
FAILED: Build did NOT complete successfully (246 packages loaded, 14193 targets configured)
make: *** [/workspace/mnt/repo_top/hw/dv/tools/dvsim/sim.mk:73: sw_build] Error 1
```

**Comment by drewmacrae** [comment] 2022-10-06 19:56
The failing bazel command is preceded by
```
Building SW image "//sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv".
Building "//sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv" on air-gapped machine.
Building with command: bazel build  --define DISABLE_VERILATOR_BUILD=true --distdir=/workspace/mnt/bazel/bazel-distdir --repository_cache=/workspace/mnt/bazel/bazel-cache //sw/device/tests/sim_dv:lc_ctrl_transition_test_sim_dv
```

**Comment by drewmacrae** [comment] 2022-10-12 15:08
I'm going to update the rust rules. There are fixes to the failing code.

**Comment by drewmacrae** [comment] 2022-10-12 15:14
@timothytrippel has beaten me to it. Has this occurred since 10/6?

**Closed** 2022-10-12 15:44 UTC
Labels: Component:TestTriage
